### ISSUE TITLE
net-snmp/net-snmp-config.h: No such file or directory 

### ISSUE THREAD

**Issue by Rajasekar0104** [prometheus/snmp_exporter#1008]
### What did you see instead? error
![snmperror](https://github.com/prometheus/snmp_exporter/assets/118898832/15f878ae-5bf0-4e98-a7c3-033de1ef2f46)

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
