### ISSUE TITLE
Missing data from snmp_exporter output in prometheus

### ISSUE THREAD

**Issue by HyperDevil** [prometheus/snmp_exporter#101]
Hi,

Using this command: curl localhost:9116/snmp?target=10.0.1.1&module=mikrotik_routeros
Template: https://github.com/prometheus/snmp_exporter/pull/76
i get this output:

HELP snmp_scrape_duration_seconds Total SNMP time scrape took (walk and processing).
TYPE snmp_scrape_duration_seconds gauge
snmp_scrape_duration_seconds 0.36220480000000005
HELP snmp_scrape_pdus_returned PDUs returned from walk.
TYPE snmp_scrape_pdus_returned gauge
snmp_scrape_pdus_returned 557
HELP snmp_scrape_walk_duration_seconds Time SNMP walk/bulkwalk took.
TYPE snmp_scrape_walk_duration_seconds gauge
snmp_scrape_walk_duration_seconds 0.35507961200000004
HELP sysUpTime 
TYPE sysUpTime untyped
sysUpTime 5.626565e+08

In Prometheus the sysUpTime value is not found, is this because the + sign is a string?

**Comment by SuperQ** [comment]
No, `5.626565e+08` looks like a proper float to me.  There may be something else going on.

**Comment by HyperDevil** [comment]
This is the prometheus config:

  - job_name: 'snmp_mikrotik'
    metrics_path: /snmp
    static_configs:
      - targets:
        - 10.0.1.1
        labels:
          alias: router
    params:
      module: [mikrotik_routeros]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116

**Comment by brian-brazil** [comment]
That all looks correct, do you have further debugging information?

**Comment by astateofmind01** [comment]
Have the same problem, any updates?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
