### ISSUE TITLE
Realtime interface usage

### ISSUE THREAD

**Issue by d-zalewski** [prometheus/snmp_exporter#102]
Hi,

Can snmp exporter be used to graph realtime network interface usage?

Thanks

Dom

**Comment by brian-brazil** [comment]
Yes, the default module includes all the standard interface stats.

**Comment by d-zalewski** [comment]
what is the highest sample frequency rate?

**Comment by brian-brazil** [comment]
Whatever you configure it to. Your switch will likely fall over before any other component.

I keep things at 10s at home.
