### ISSUE TITLE
Not getting data while hitting the URL (http://localhost:9116/snmp?module=cisco_wlc&target=MYTARGETSNMPip)

### ISSUE THREAD

**Issue by mohanprasaths** [prometheus/snmp_exporter#105]
I have my SNMP device which responds perfectly when I tried with powerSNMP tool . 

This is my snmp.yml
cisco_wlc:
  version: 3
  auth:
    username: username
    password: password
    auth_protocol: SHA
    priv_protocol: AES
  walk:
  - 1.3.6.1.2.1.2
  - 1.3.6.1.2.1.31.1.1
  - 1.3.6.1.4.1.14179.2.1.1.1.2
  - 1.3.6.1.4.1.14179.2.1.1.1.38
......etc 

When I hit URL (http://localhost:9116/snmp?module=cisco_wlc&target=IP)
Iam not getting correct data . 
![snmpscrapper](https://cloud.githubusercontent.com/assets/12637959/21740571/1952742a-d4e3-11e6-9188-25f987787b8e.PNG)

**Comment by brian-brazil** [comment]
Can you confirm it works as expected when you snmpbulkwalk with those settings?

**Comment by mohanprasaths** [comment]
Working fine . Thanks
