### ISSUE TITLE
field scale not found in type config.Metric

### ISSUE THREAD

**Issue by arcanatigris** [prometheus/snmp_exporter#1062]
### Host operating system: output of `uname -a`
Debian GNU/Linux 12 (bookworm)
Linux monitor2 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
docker: prom/snmp-exporter 0.24.1

### What did you expect to see?
snmp_exporter running with default config
https://raw.githubusercontent.com/prometheus/snmp_exporter/main/snmp.yml

### What did you see instead?
```
ts=2023-12-06T12:54:21.682Z caller=main.go:195 level=info build_context="(go=go1.21.0, platform=linux/amd64, user=root@6206907e6947, date=20230901-07:37:50, tags=netgo)"
ts=2023-12-06T12:54:21.775Z caller=main.go:202 level=error msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 23324: field scale not found in type config.Metric"
ts=2023-12-06T12:54:21.775Z caller=main.go:203 level=error msg="Possible old config file, see https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md"
```
It seems to choke on the scale setting on line 23224 of the default config, which is the only place scale is used.

**Comment by SuperQ** [comment]
This is not released yet. Will be available in v0.25.0.

**Comment by dg1sek** [comment]
I have the exact same issue on standard Ubuntu running in Virtualbox.

**Comment by SuperQ** [comment]
That is a different issue.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
