### ISSUE TITLE
snmp exporter and Octect String values

### ISSUE THREAD

**Issue by aguerra70** [prometheus/snmp_exporter#107]
Monitoring devices with OID type OctectString:
using net-snmp:
snmpget -v1 -c public 192.168.3.37 .1.3.6.1.4.1.2435.2.3.9.4.2.1.5.4.5.2.0
SNMPv2-SMI::enterprises.2435.2.3.9.4.2.1.5.4.5.2.0 = STRING: "Contrast:-     +      "

Using snnp_exporter config: 
 version: 1
   auth:
     community: public
   walk:
     - 1.3.6.1.2.1.1.3
 - 1.3.6.1.4.1.2435.2.3.9.4.2.1.5.4.5
metrics:
 - name: SysUpTime
oid: 1.3.6.1.2.1.1.3.0
 - name: Message1
oid: 1.3.6.1.4.1.2435.2.3.9.4.2.1.5.4.5.2.0

Prometheus:
Message1{instance="192.168.3.37",job="BROTHER"} = 0

Problem to  handle the OctectString values.....?

**Comment by brian-brazil** [comment]
This is something that's on the roadmap but I haven't gotten to it yet. Would you like to have a go at it?

**Comment by aguerra70** [comment]
I would like to try... but im sure to need help....

**Comment by brian-brazil** [comment]
There's 3 things to do:


    1 Add support for the exporter config to take a type
    1 If this type is octetstring, create a metric with value 1 and the string value as a label
    1 Have the generator produce these metrics

**Comment by brian-brazil** [comment]
This will be in soon.
