### ISSUE TITLE
Normalized naming scheme

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#11]
Other exporters tend to use Perl-style underscore_notation while snmp_exporter uses camlCase, e.g. `ifLinkUpDownTrapEnable` vs `node_cpu`.

Normalizing the naming scheme under One Great Scheme would be useful.

**Comment by brian-brazil** [comment]
Snake case is the standard for Prometheus, however when coming from another instrumentation system - particularly one as well established as SNMP - it's sometimes better to leave things as-is. There's also the technical problem of automatically converting from one to the other, things like `myTCPExample` are very difficult to handle correctly.

**Comment by RichiH** [comment]
I can't say I like the answer, but it makes sense to some extent.

On the other hand, interface counters are not only collectable via SNMP and
then you have two names for the same thing.

I am torn...

Richard

Sent by mobile; excuse my brevity.

**Comment by RichiH** [comment]
After some more deliberation, I still can't say that I like it, but I think you are right. Closing.
