### ISSUE TITLE
Duplicate metric errors while polling

### ISSUE THREAD

**Issue by lefthandedocto1** [prometheus/snmp_exporter#111]
I have a network device with interfaces that can be configured as a single interface(Ethernet49/1) or 4 interfaces(Ethernet49/1-4).  When I have the interface configured as a single interface some snmp tables still have 4 indexes for each interface.  The 3 extra interfaces do not exist in ifDescr so the lookup fails on the label and the value is left blank.  This causes errors due to duplicates:

* collected metric aristaEgressQueuePktsDropped label:<name:"Interface" value:"" > label:<name:"PacketType" value:"1" > label:<name:"Queue" value:"12" > untyped:<value:0 >  was collected before with the same name and label values
* collected metric aristaEgressQueuePktsDropped label:<name:"Interface" value:"" > label:<name:"PacketType" value:"0" > label:<name:"Queue" value:"7" > untyped:<value:0 >  was collected before with the same name and label values

config snippet for the above errors:

- name: aristaEgressQueuePktsDropped
  oid: 1.3.6.1.4.1.30065.3.6.1.2.1.6
  indexes:
    - labelname: Interface
      type: Integer32
    - labelname: Queue
      type: Integer32
    - labelname: PacketType
      type: Integer32
  lookups:
    - labels: [Interface]
      labelname: Interface
      oid: 1.3.6.1.2.1.2.2.1.2

snmpwalk snippet:

ifDescr:

IF-MIB::ifDescr.48 = STRING: Ethernet48
IF-MIB::ifDescr.49001 = STRING: Ethernet49/1
IF-MIB::ifDescr.50001 = STRING: Ethernet50/1

aristaEgressQueuePktsDropped:

SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.0.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.1.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.2.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.3.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.4.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.5.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.6.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.7.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.8.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.9.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.10.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.11.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.12.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.13.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.14.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.15.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49001.16.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.0.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.1.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.2.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.3.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.4.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.5.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.6.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.7.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.8.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.9.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.10.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.11.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.12.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.13.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.14.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.15.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49002.16.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.0.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.1.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.2.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.3.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.4.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.5.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.6.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.7.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.8.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.9.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.10.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.11.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.12.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.13.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.14.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.15.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49003.16.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.0.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.1.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.2.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.3.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.4.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.5.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.6.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.7.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.8.0 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.9.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.10.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.11.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.12.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.13.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.14.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.15.1 = Counter64: 0
SNMPv2-SMI::enterprises.30065.3.6.1.2.1.6.49004.16.1 = Counter64: 0

 Is there a way to have the label lookup fail back to the index rather than an empty string or some other work around? 

edit:  This is with a new build of snmp_exporter as of a couple hours ago

**Comment by brian-brazil** [comment]
If if's not unique then you can't use a lookup, try the default_ifindex module.

**Comment by lefthandedocto1** [comment]
The index is unique, it is made into a duplicate because the lookup is returning an empty string when the index does not exist in ifDescr.  

The first value for a given interface exists in ifDescr so the values for the interfaces would be:

aristaEgressQueuePktsDropped{Interface="Ethernet49/1",PacketType="1",Queue="13"}
aristaEgressQueuePktsDropped{Interface="",PacketType="1",Queue="13"}
aristaEgressQueuePktsDropped{Interface="",PacketType="1",Queue="13"}
aristaEgressQueuePktsDropped{Interface="",PacketType="1",Queue="13"}

If the lookup failed back to the index rather than an empty string it would look like:
aristaEgressQueuePktsDropped{Interface="Ethernet49/1",PacketType="1",Queue="13"}
aristaEgressQueuePktsDropped{Interface="49002",PacketType="1",Queue="13"}
aristaEgressQueuePktsDropped{Interface="49003",PacketType="1",Queue="13"}
aristaEgressQueuePktsDropped{Interface="49004",PacketType="1",Queue="13"}

**Comment by brian-brazil** [comment]
> The index is unique, it is made into a duplicate because the lookup is returning an empty string when the index does not exist in ifDescr.

That's non-unique then, you can't use it as a lookup.

**Comment by lefthandedocto1** [comment]
The index is unique in the snmp lookup, ifDescr contains incomplete information so it gets mapped to nothing.  I am suggesting this does seem like ideal behavior when a lookup fails.  We have a unique value that we are doing a lookup on and any lookup failure cause an entire scrape to fail because the lookup is making it non-unique by returning an empty string instead of the value.

**Comment by brian-brazil** [comment]
This is a case of Don't Do That Then, you need to remove the lookup.

**Comment by SuperQ** [comment]
This mib doesn't seem to have the description names in-line, and you're attempting to map in ISO names.  This is probably not going to work, but you might try something like this:

```
- name: aristaEgressQueuePktsDropped
  oid: 1.3.6.1.4.1.30065.3.6.1.2.1.6
  indexes:
    - labelname: Interface
      type: Integer32
    - labelname: Queue
      type: Integer32
    - labelname: PacketType
      type: Integer32
  lookups:
    - labels: [Interface]
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
```

Not that instead of re-writing Interface, it adds the `ifDescr` lookup as an additional label.  Unless arista is consistent when crossing different MIB trees you're going to end up with funky results.  Just trying to give you fair warning. :smile:

**Comment by lefthandedocto1** [comment]
SuperQ, The only thing consistent about snmp is it is inconsistent. This is the only case I have found so far, everything else is working fine with the lookups though. 

 Thanks for the suggestion but using a different label for one or 2 interface metrics when all the other interface labels are consistent is a hard sell to the people would be querying the data.  This would be the same thing if I just did not do a lookup, the interface index is not meaningful to a user of the switches so it would require a lookup one way or another.  

I could have sworn this was working before so I went back and looked at my previous testing config.  My testing was using a build from 12/21 and the behavior was what I would expect to see from above.  It looks like the behavior changed in PR#100 so I will just continue to use the code before that for now.

**Comment by RichiH** [comment]
This worked in the Python implementation, does not in the Go one.

This point is the one coming up most often within SNMP exporter; it's a
case of clean design vs pragmatism when faced with a legacy protocol.

Note that the Python version has way worse behaviour under load.


Richard

Sent by mobile; excuse my brevity.

**Comment by SuperQ** [comment]
@RichiH What worked in the Python one that doesn't work with Go?

**Comment by RichiH** [comment]
Python simply exposed all duplicates and Prometheus dropped all except for one.

To me, this is still the better failure than stopping to expose anything.

**Comment by SuperQ** [comment]
Ahh, I see, the golang client has different validation.  I prefer fail-fast, and to deal with the duplicate problem by never replacing labels, only add additional context labels to deal with SNMP's design.

**Comment by RichiH** [comment]
We both agree that this is the preferable solution in the end :)

Richard

Sent by mobile; excuse my brevity.

**Comment by lefthandedocto1** [comment]
Just to make sure it is clear, if I did not do the lookup there is no duplicate metric, all 4 metrics would show up with Interface=intIndex(which are unique).  I would agree returning an error is the correct way to go if there was no unique value for the metric.  In this case though the lookup is working on a unique value, the lookup is just eating that value.

If fail-fast is the way going forward I would rather see that be consistent and return an error on the failed lookup rather than potentially dumping bad data(empty labels) into Prometheus.   Currently it seems like this is being found as a side effect of a different check and does not have enough context in the error to actually troubleshoot.  I was able to find the cause of this issue because in the previous version I was using the exporter used the index as the value of the label that failed the lookup.  This made it easy to see which interfaces were failing the lookup.  Without the value that failed the lookup I need to walk all of interfaces and compare the tables manually to see which one might have been the issue. Arista has switches with 64-1,100 interfaces, I likely would have given up if I had found this on one of the bigger chassis instead of the smaller one I was testing on :)

**Comment by SuperQ** [comment]
The empty labels are not bad data, they're what's matched by the vendor lookup.  Replacing labels is always going to be dangerous, especially so when crossing OID trees.  We had the same issue with Aruba wifi controller metrics.  With the old behavior, you get silently dropped data, which is much worse.

The only safe thing to do is to never replace labels with a lookup, but add them as a new label.  This way you keep the uniqueness and the additional metadata needed to make the SNMP data useful.

**Comment by RichiH** [comment]
Caveat: Cisco will re-assign ifIndex on reload by default. That's why
relabeling is _safer_ with Cisco as perverse as that might be...

**Comment by lefthandedocto1** [comment]
Real world use of snmp there is no way not to do a lookup, ifIndex is not required to be persistent between device reboots.  interface names are the consistent data and ifIndex needs to be mapped to them for interface status.  

I think bad data is the wrong term but I explicitly configured a label with a lookup and the lookup is failing without warning.  Without that lookup the metric has potential to be wrong in prometheus when a user goes to query.  Short of looking at every metric I have no way of knowing it failed until someone complains after looking for that metric.  To be fair using the ifIndex in place of the empty string it has a similar problem but makes it easier to troubleshoot why a lookup failed.  

As is there is no way for me to collect the data I need with the latest version, but I have resolved my issue by using an older commit of the snmp_exporter.  Happy to continue the discussion but if it is not useful to the devs feel free to close the issue.

**Comment by SuperQ** [comment]
I agree, lookups are required for SNMP metrics to be useful.  With the old behavior we just had different failures. (missing labels in same metric family) :-(

This is why I suggest not doing any label replacements and only use lookups as additional labels for all use.  You get the best of both worlds.

I will mull over some other solutions, possibly mapping in the index value(s) explicitly, but I don't think the old behavior is a good solution.

**Comment by lefthandedocto1** [comment]
Just a thought for a possible solution, if there were another optional field for the lookup on what to do if a lookup fails it would make things more flexible to account for stupid SNMP inconsistencies.  

something like:

indexes:
    labelname: Index
    type: Integer32
lookups:
    labels: [Interface]
    labelname: Interface
    oid: 1.3.6.1.2.1.2.2.1.2
    default: Index

And if default is left off it would just keep the empty string.

**Comment by brian-brazil** [comment]
That doesn't help semantically, as we don't know what the index is. If the label value is the empty string then the label value is the empty string.

**Comment by SuperQ** [comment]
One thing we can do is detect if the lookup is a replacing the label, or adding a new one.  Only in the add a new one do we write the empty label.  Although this doesn't guarantee we won't have duplicates again.

**Comment by brian-brazil** [comment]
This was an incorrect config by a user, nothing for us to do here.
