### ISSUE TITLE
Go build error when trying to generate "generator" file

### ISSUE THREAD

**Issue by R4ZZB3RRY** [prometheus/snmp_exporter#1117]
Hi.  I'm tryin to build the generator file and I am getting a permission denied error.  The error happens when trying to open the generator file.

```
mitchell@mitchell-virtual-machine:~/go/src/snmp_exporter/generator$ go build
github.com/prometheus/snmp_exporter/generator: go build github.com/prometheus/snmp_exporter/generator: copying /tmp/go-build1039860546/b001/exe/a.out: open generator: permission denied

```
I've been using go build version 1.22.0 and have installed all dependencies.

### Host operating system: output of `uname -a`
Linux mitchell-virtual-machine 5.15.0-94-generic #104~20.04.1-Ubuntu SMP Tue Jan 16 13:34:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
### What did you do that produced an error?
ran go build
### What did you expect to see?
generator file
### What did you see instead?
permission denied

**Comment by SuperQ** [comment]
What do you get for: 

```
ls -ld . generator
```

**Comment by R4ZZB3RRY** [comment]
no such file or directory

**Comment by R4ZZB3RRY** [comment]
```
mitchell@mitchell-virtual-machine:~/go/src/snmp_exporter/generator$ ls -ld . generator
ls: cannot access 'generator': No such file or directory
drwxr-xr-x 3 root root 4096 Feb 17 14:43 .
```

**Comment by SuperQ** [comment]
Your checkout is owned by root, your user can not write to that.

**Comment by R4ZZB3RRY** [comment]
how do i chown the checkout?

**Comment by R4ZZB3RRY** [comment]
nevermind i figured it out.  Thanks for your help
