### ISSUE TITLE
collector doesn't use system DNS servers for address resolution

### ISSUE THREAD

**Issue by sulrich** [prometheus/snmp_exporter#112]
when using IP addresses for the targets things work fine.  however, when attempting to collect from targets using the hostname, the collector appears to always attempt to use 8.8.8.8 for resolution.

### confirm that local dns resolution works as expected
```
bert(prometheus/snmp_exporter)[master] % ping ctl-gw.xxx.yyy.net
PING ctl-gw.xxx.yyy.net (10.0.0.1) 56(84) bytes of data.
64 bytes from ctl-gw.xxx.yyy.net (10.0.0.1): icmp_seq=1 ttl=64 time=0.288 ms
64 bytes from ctl-gw.xxx.yyy.net (10.0.0.1): icmp_seq=2 ttl=64 time=0.281 ms
```

### collector logs

```
bert(prometheus/snmp_exporter)[master] % ./snmp_exporter -config.file foo.snmp.yml -log.level debug -log.format "logger:stderr"
INFO[0000] Starting snmp exporter (version=, branch=, revision=)  source=main.go:99
INFO[0000] Build context (go=go1.6.2, user=, date=)      source=main.go:100
INFO[0000] Listening on :9116                            source=main.go:114

DEBU[0015] Scraping target '10.0.0.1' with module 'default'  source=main.go:77
DEBU[0015] Walking target "10.0.0.1" subtree "1.3.6.1.2.1.1.3"  source=collector.go:70
DEBU[0015] Walk of target "10.0.0.1" subtree "1.3.6.1.2.1.1.3" completed in 971.457µs  source=collector.go:80
DEBU[0015] Walking target "10.0.0.1" subtree "1.3.6.1.2.1.2"  source=collector.go:70
DEBU[0015] Walk of target "10.0.0.1" subtree "1.3.6.1.2.1.2" completed in 131.625505ms  source=collector.go:80
DEBU[0015] Walking target "10.0.0.1" subtree "1.3.6.1.2.1.31.1.1"  source=collector.go:70
DEBU[0016] Walk of target "10.0.0.1" subtree "1.3.6.1.2.1.31.1.1" completed in 109.104921ms  source=collector.go:80
DEBU[0016] Scrape of target '10.0.0.1' with module 'default' took 0.255974 seconds  source=main.go:88
```

### curl execution 

```
bert(prometheus/snmp_exporter)[master] % curl "http://10.0.0.251:9116/snmp?target=10.0.0.1&module=default"
... 
# TYPE ifType untyped
ifType{ifDescr="enc0"} 244
ifType{ifDescr="igb0"} 6
ifType{ifDescr="igb0_vlan201"} 135
ifType{ifDescr="igb1"} 6
ifType{ifDescr="igb2"} 6
ifType{ifDescr="igb2_vlan101"} 135
ifType{ifDescr="igb3"} 6
ifType{ifDescr="igb4"} 6
ifType{ifDescr="igb5"} 6
ifType{ifDescr="lo0"} 24
ifType{ifDescr="pflog0"} 246
ifType{ifDescr="pfsync0"} 247
ifType{ifDescr="pppoe0"} 53
ifType{ifDescr="wan_stf"} 215
# HELP snmp_scrape_duration_seconds Total SNMP time scrape took (walk and processing).
# TYPE snmp_scrape_duration_seconds gauge
...
```

in short, works as expected

### collector logs

```
bert(prometheus/snmp_exporter)[master] % ./snmp_exporter -config.file foo.snmp.yml -log.level debug -log.format "logger:stderr"
INFO[0000] Starting snmp exporter (version=, branch=, revision=)  source=main.go:99
INFO[0000] Build context (go=go1.6.2, user=, date=)      source=main.go:100
INFO[0000] Listening on :9116                            source=main.go:114


DEBU[0004] Scraping target 'ctl-gw.xxx.yyy.net' with module 'default'  source=main.go:77
ERRO[0005] Error scraping target ctl-gw.xxx.yyy.net: Error connecting to target ctl-gw.xxx.yyy.net: Error establishing connection to host: dial udp: lookup ctl-gw.xxx.yyy.net on 8.8.8.8:53: no such host
  source=collector.go:125
DEBU[0005] Scrape of target 'ctl-gw.xxx.yyy.net' with module 'default' took 0.346469 seconds  source=main.go:88

```

### curl execution 

```
bert(prometheus/snmp_exporter)[master●] % curl "http://10.0.0.251:9116/snmp?target=ctl-gw.xxx.yyy.net&module=default"
An error has occurred during metrics gathering:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error connecting to target ctl-gw.xxx.yyy.net: Error establishing connection to host: dial udp: lookup ctl-gw.xxx.yyy.net on 8.8.8.8:53: no such host

```

here the collector is attempting to resolve this via 8.8.8.8 not via the internal DNS server which correctly resolves these addresses.

the python version of the collector correctly resolved the addresses for scraping.

**Comment by brian-brazil** [comment]
How is your DNS resolution configured, and how is your nsswitch-based resolution configured?

**Comment by sulrich** [comment]
## resolv.conf
```
10.0.0.251
8.8.8.8
8.8.4.4
search yyy.net
```

## nsswitch.conf
`hosts:          files mdns4_minimal [NOTFOUND=return] dns`

**Comment by brian-brazil** [comment]
I'm going to guess that 10.0.0.251 is down and that's why you're using 8.8.8.8. Mdns is likely configured differently.

**Comment by sulrich** [comment]
i don't think that's it. given that 10.0.0.251 is also the address that snmp_exporter is running on (ref curl output) and the ping output resolves correctly.  it doesn't explain why when i roll back to the python version of snmp_exporter on the same machine (10.0.0.251) it works correctly.

**Comment by brian-brazil** [comment]
Ping is not using the same code path as Go. Is 10.0.0.251 running a resolver that the exporter can successfully use? What does tcpdump say?

**Comment by SuperQ** [comment]
It also depends on the behavior of the pure-go DNS resolver.  It may not respect the order of `nameserver` entries in `resolv.conf`. 

The nsswitch.conf line looks like Ubuntu default.

**Comment by SuperQ** [comment]
I did some testing and it looks like the `snmp_exporter` does correctly use the `resolv.conf` ordering.  Brian is probably correct that the resolver on `10.0.0.251` isn't functioning correctly.

Either way, having a mix of public and private nameservers in `/etc/resolv.conf` is never going to work properly.  Every server in the list must function identically or you're going to have a bad time.  There are many resolver implementations out there that don't follow the default strict ordering rules.

**Comment by sulrich** [comment]
so ... 

a couple of quick observations. 

looks like `snmp_exporter` only binds to a single interface.  offhand, i don't know whether this is a modifiable behavior.  the `-h` output doesn't seem to indicate that it is.


**snmp_exporter bindings**
```
bert(/home/sulrich)% netstat -an | grep ':9116'
tcp6       0      0 :::9116                 :::*                    LISTEN
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52044        TIME_WAIT
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52038        TIME_WAIT
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52042        TIME_WAIT
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52018        TIME_WAIT
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52048        TIME_WAIT
```


for comparison, bind grabs all available interfaces (as i have it configured).

**dns server bindings**
```
bert(prometheus/snmp_exporter)[master] % netstat -an | grep ':53'
tcp        0      0 172.17.0.1:53           0.0.0.0:*               LISTEN
tcp        0      0 10.0.0.251:53           0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN
tcp6       0      0 :::53485                :::*                    LISTEN
tcp6       0      0 :::53                   :::*                    LISTEN
udp        0      0 0.0.0.0:5353            0.0.0.0:*
udp        0      0 172.17.0.1:53           0.0.0.0:*
udp        0      0 10.0.0.251:53           0.0.0.0:*
udp        0      0 127.0.0.1:53            0.0.0.0:*
udp6       0      0 :::53                   :::*
```

**tcpdump execution**

when i run tcpdump it looks like `snmp_exporter` doesn't do a local (`10.0.0.251`) query to DNS it instead queries `8.8.8.8` immediately.  this is reasonable behavior, particularly given that it doesn't also listen on all intfs.  the python implementation by comparison seems to `bind(2)` more pervasively.

**python snmp_exporter bindings**
```
bert(prometheus/snmp_exporter)[master] % netstat -an | grep ':9116'
tcp        0      0 0.0.0.0:9116            0.0.0.0:*               LISTEN
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52744        TIME_WAIT
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52754        TIME_WAIT
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52748        TIME_WAIT
tcp6       0      0 10.0.0.251:9116         172.17.0.2:52750        TIME_WAIT
```

**resolution**

this is trivially worked around by putting `127.0.0.1` at the top of my `resolv.conf` to get the behavior i'm after. though the go behavior here is something that i should acquaint myself here.

i don't know if this change in behavior is worth mentioning in the docs somewhere or not.

thanks!

**Comment by SuperQ** [comment]
Interesting, thanks for the report.  I'm not sure there's much we can do about it, the default bind is for all interfaces, so it should work correctly.  If I have time I'll try and do some more debugging.

**Comment by brian-brazil** [comment]
I don't see how which ports we listen on has to do with outbound UDP packets.

**Comment by sulrich** [comment]
i suspect that in this case it's not the ports, it's the interfaces.  `snmp_exporter` only binds to the interface addressed `10.0.0.251` for INET.  while the python implementation `LISTEN`s on all addresses/interfaces. 

my theory here is that the go behavior is to never send traffic to its own interface and since i have the primary resolver in `resolv.conf` on the same address it doesn't send to to this address and goes to the next dns server in the list.

**Comment by brian-brazil** [comment]
That doesn't mesh with my understanding of Unix sockets. Unless you explicitly coded the behaviour your described in the application (which we didn't), what addresses you listen to has nothing to do with what client addresses you use for sockets (which will typically be chosen by the kernel).

**Comment by sulrich** [comment]
i agree. my comments re: `LISTEN` were largely observational and what cued me to the behavior and my resolution. 

that said, my tcpdump (across all interfaces on the host) shows the `10.0.0.251` (src+dst) connections from `curl` to `snmp_exporter` immediately followed by a DNS query to `8.8.8.8`.  there was no attempt to query `10.0.0.251`. all packets are in order and my capture filter expression is/was for ports 9116 and 53 only.

when i put `127.0.0.1` into my `resolv.conf` and re-ran the `curl` it worked as expected *and* for some reason it issued the DNS query with `127.0.0.1` as the src and the dst addresses.  this worked.  this is closer to the operation that i would have expected.

as an aside, there is an slight difference between the `LISTEN` behavior of the go vs the python implementations, which may be a hint towards the root cause of this behavior.  the go implementation shows a `tcp6` listener (iirc, this indicates an AF_INET6 type socket which, is capable of handling IPv4 and IPv6 connections) while the python implementation is a vanilla `tcp` listener.  i wonder if this triggers different `socket(2)` behaviors under the hood for the DNS resolution?
