### ISSUE TITLE
Build instructions in `README.md` do not work

### ISSUE THREAD

**Issue by mpalmer** [prometheus/snmp_exporter#114]
The instructions provided for installation do not work for me:

    $ go get -d
    $ go build
    ./collector.go:58: cannot use &snmp (type *"github.com/soniah/gosnmp".GoSNMP) as type *"github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp".GoSNMP in argument to config.ConfigureSNMP

On the other hand, running `make build` *does* work.  Perhaps the README just needs to be updated to deprecate using `go build` directly?  Or is `go build` definitely supposed to work?

**Comment by brian-brazil** [comment]
Is your GOPATH configured correctly?

**Comment by mpalmer** [comment]
Define "correctly"...  The same setting for GOPATH works Just Fine for running `make build`, it's only `go build` that has problems.

**Comment by brian-brazil** [comment]
Do you have a working Go build environment with at least Go 1.6?

**Comment by neotkm** [comment]
Same problem
go version go1.6.4 linux/amd64 / go version go1.7.4 
go build
# _/root/snmp_exporter
./collector.go:58: cannot use &snmp (type *"github.com/soniah/gosnmp".GoSNMP) as type *"github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp".GoSNMP in argument to config.ConfigureSNMP

**Comment by mpalmer** [comment]
Yes, I have a working Go build environment with at least Go 1.6, because **`make build` works just fine**.

**Comment by brian-brazil** [comment]
make build working does not mean that you have a working Go environment, as it's not doing a simple go build. The error you're getting indicates your GOPATH is not setup correctly.

**Comment by mpalmer** [comment]
We're back to the definition of "correctly".  I don't know what you consider to be a "correct" GOPATH setup.  It seems to work fine for building other stuff.

**Comment by brian-brazil** [comment]
https://golang.org/doc/code.html#GOPATH is one guide

**Comment by carpenike** [comment]
Builds fine for me in Docker...

Dockerfile
`FROM golang
MAINTAINER Ryan Holt <ryan@ryanholt.net>
RUN go get github.com/prometheus/snmp_exporter
RUN go install github.com/prometheus/snmp_exporter
EXPOSE 9116
VOLUME [ "/config" ]
ENTRYPOINT [ "/go/bin/snmp_exporter" ]
CMD [ "-config.file=/config/snmp.yml" ]`

**Comment by jlauenercern** [comment]
Had the same issue. Had it fixed by building SNMP exporter directly from the gopath:
cd $GOPATH/src/github.com/prometheus/snmp_exporter
go build

**Comment by lucevers** [comment]
Have the same issue, I'm using gvm and go version go1.7.5

**Comment by brian-brazil** [comment]
There's no indication there's any issues here beyond incorrectly setup Go build environments, so closing for now.
