### ISSUE TITLE
Problem in snmp.yml: field scale not found in type config.Metric

### ISSUE THREAD

**Issue by realwuffi** [prometheus/snmp_exporter#1170]
Sometimes I have to add new modules to the SNMP exporter.
I do that by starting off with the snmp.yml provided here.

As soon as I start the SNMP Exporter (or Grafana Agent / Alloy with SNMP exporter built in)
I get the following error message

> ts=2024-03-22T20:48:05.3578471Z caller=manager.go:261 level=error msg="failed to initialize integration. it will not run or be scraped" 
integration=snmp err="failed to load snmp config from file C:/Users/admin/Desktop/snmp.yml: yaml: unmarshal errors:\n  
\nline 30297: field scale not found in type config.Metric"

https://github.com/prometheus/snmp_exporter/blob/5f907e691aa59ec2545aa72a350da11f34058246/snmp.yml#L30297

It seem slike the scale property is not supported. And also this line is the only occurence.

After I remove that line it do not get that issue any longer.

**Comment by bastischubert** [comment]
Hi @realwuffi 
which version of the snmp generator did you use, and also which version of the snmp_exporter? do the versions generator and exporter match? 
for reference: the scale field was added in October 2023 (https://github.com/prometheus/snmp_exporter/pull/1026)

**Comment by realwuffi** [comment]
Hey @bastischubert ,
thanks for reaching out. I think I have found the problem:
Grafana Agent / Alloy is still using version 0.23 of the SNMP Exporter, so it fails when it reads that new scale field.
When I run version 0.25 of the snmp_exporter everything works fine.
