### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by buroa** [prometheus/snmp_exporter#1172]
Can we please cut a release? It's been months and there are a few features I'd like to have.

**Comment by RichiH** [comment]
@bastischubert do you have cycles to test?

**Comment by bastischubert** [comment]
Will spend some time today on 🐈ching up with the latest changes

**Comment by SuperQ** [comment]
I have two pending PRs that I would like to include.

* https://github.com/prometheus/snmp_exporter/pull/1157
* https://github.com/prometheus/snmp_exporter/pull/1167

**Comment by ptodev** [comment]
I would also appreciate if there is a new release please. The PR which I need is #1163 :)

**Comment by SuperQ** [comment]
https://github.com/prometheus/snmp_exporter/releases/tag/v0.26.0

**Comment by buroa** [comment]
Greatly appreciate the team getting a release out, thanks so much! 🤍
