### ISSUE TITLE
SNMP v3 support

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#12]
If scraping over third-party links, the ability to encrypt and properly authenticate SNMP would be great.

**Comment by SuperQ** [comment]
I've got a patch in progress for v1 and v3 support: https://github.com/SuperQ/snmp_exporter

**Comment by jcollie** [comment]
Like #8, I believe that this can be closed now.

**Comment by brian-brazil** [comment]
Yip, thanks.
