### ISSUE TITLE
SNMP exporter config generator docker container

### ISSUE THREAD

**Issue by ninoabbate** [prometheus/snmp_exporter#120]
Hello all,
I built a docker container for the config generator, you can find it here: https://github.com/ninoabbate/docker-secg
Hope you will find it useful too.

**Comment by brian-brazil** [comment]
Thanks for sharing. That depends on your local system, and doesn't include mibs so it's of limited use. I'm not sure what the legal status would be on including the mibs.

**Comment by ninoabbate** [comment]
I've just realized that the A10 mibs couldn't be included, so I've removed them.
The container must be used only for generating the configuration, so it is a one time run only.

**Comment by ninoabbate** [comment]
Ok, I've updated the repo adding the Palo Alto firewall MIBs, which can be downloaded for free from here: https://www.paloaltonetworks.com/documentation/misc/snmp-mibs.html

To test the generator, just clone my repo [docker-secg](https://github.com/ninoabbate/docker-secg) and then run the container:
```
$  docker run -it -v "$PWD/mibs:/root/.snmp/mibs" \
    -v "$PWD/generator.yml:/snmp_exporter/generator/generator.yml" \
    -v "$PWD/snmp.yml:/snmp_exporter/generator/snmp.yml" aabbate/secg
```

**Comment by brian-brazil** [comment]
Thinking on this, what we could do in this repo is provide a docker image with a working generator and document the volume mounts to pull in the MIBs etc.

**Comment by ninoabbate** [comment]
@brian-brazil I will add the needed documentation about volume mounts, etc.. 👍

**Comment by ninoabbate** [comment]
@brian-brazil I did a rework on this container, it uses the same tag used by snmp-exporter, also I documented the volumes to mount, please take a look if you have one free minute. 
Suggestions are welcomed.

**Comment by brian-brazil** [comment]
At a first glance I'd suggest arranging the paths so that the volume mounts are much more concise.

I'd also advise making the commands other than 'generate' accessible, they're handy for debugging.

**Comment by brian-brazil** [comment]
There is one now.
