### ISSUE TITLE
Building generator on FreeBSD

### ISSUE THREAD

**Issue by aduitsis** [prometheus/snmp_exporter#122]
Hello,

To build and install the generator component under FreeBSD, I had to change the cgo flags in the start of generator/net_snmp.go, like that:

```
#cgo LDFLAGS: -lnetsnmp -L/usr/local/lib
#cgo CFLAGS: -I/usr/local/include
```
In FreeBSD, third party software (ie packages) is always installed under the prefix /usr/local. So that little tweak is required to have the C compiler under cgo to search these paths for headers and libraries.

Regarding the name of the shared library, Debian and other Linux distros provide libsnmp.so, whereas in FreeBSD only the "normal" libnetsnmp.so is provided by the package net-snmp. I would speculate libsnmp.so is provided for compatibility(?). In my humble opinion, the -lsnmp flag could probably be changed to -lnetsnmp without serious problem. Obviously I can provide a pull request for this exceedingly simple change. 

The inclusion of -L and -I to search under /usr/local/lib can be provided via -CGO_CFLAGS and -CGO_LDFLAGS, so one trying to build under FreeBSD wouldn't have to patch the sources. But even putting the two paths in the flags inside the source wouldn't hurt even if the directories do not exist.

Many thanks for your attention,

**Comment by brian-brazil** [comment]
I'm open to a PR that makes things work on FreeBSD as long as it doesn't break Linux.

**Comment by aduitsis** [comment]
Fair enough, I'll see what I can do.
