### ISSUE TITLE
snmp-exporter times out and gives up after 10 seconds during scrape, snmpbulkwalk of the same tree works fine

### ISSUE THREAD

**Issue by eriksejr** [prometheus/snmp_exporter#1240]
I have a host that uses AgentX with snmpd to collect data from the application. There's a very large number of OIDs here to collect, around 500 or so per walk and its rather slow to respond with each response with max-repetitions of 10 takes roughly 500 milliseconds. This host has a problem where snmp-exporter appears to just give up for no apparent reason, even though the host is responding within the timeout period specified (or the default of 5 seconds). An snmpbulkwalk of the same host/tree with the same number of max_repetitions (10) completes successfully with no errors/timeouts or unusual time intervals between responses. The issue can be seen here in this packet capture screenshot:

![image](https://github.com/user-attachments/assets/209ffea6-91ec-4634-bb8a-879c135f6ae1)

The exporter always gives up at the same point - exactly 10 seconds into the scrape. In the larger capture you can see that the scrape always restarts 50 seconds later (the interval is set to 60 seconds). So it appears there's a 10-second timeout somewhere in the code that can't be controlled or configured anywhere and any scrape that takes longer then 10 seconds will fail in this manner.

`ts=2024-08-30T15:25:52.790Z caller=main.go:212 level=info msg="Starting snmp_exporter" version="(version=, branch=, revision=unknown)" concurrency=1 debug_snmp=false ts=2024-08-30T15:25:52.790Z caller=main.go:213 level=info build_context="(go=go1.21.12, platform=freebsd/amd64, user=, date=, tags=unknown)" 
ts=2024-08-30T15:25:53.000Z caller=tls_config.go:313 level=info msg="Listening on" address=[::]:9116 
ts=2024-08-30T15:25:53.003Z caller=tls_config.go:349 level=info msg="TLS is enabled." http2=true address=[::]:9116 
ts=2024-08-30T15:26:04.223Z caller=collector.go:367 level=info auth=xxxx target=xxxx source_address= worker=0 module=xxx msg="Error scraping target" err="scrape canceled after 301.889065ms (possible timeout) walking target xxxx"
ts=2024-08-30T15:26:59.177Z caller=collector.go:367 level=info auth=xxxx target=xxxx source_address= worker=0 module=xxxx msg="Error scraping target" err="scrape canceled after 1.207017261s (possible timeout) walking target xxxx"`

Debug Logs:
`ts=2024-08-30T16:25:54.201Z caller=collector.go:456 level=debug auth=auth target=target.domain source_address= worker=0 module=moduleName msg="Starting scrape"
ts=2024-08-30T16:25:54.201Z caller=collector.go:476 level=debug auth=auth target=target.domain source_address= msg="Sent module to worker" module=moduleName
ts=2024-08-30T16:25:54.201Z caller=gosnmp.go:103 level=debug auth=auth target=target.domain source_address= worker=0 msg="Walking subtree" oid=1.3.6.1.4.1.31674.1.3.18.1.4.1.3.3.1.10
ts=2024-08-30T16:25:59.029Z caller=gosnmp.go:119 level=debug auth=auth target=target.domain source_address= worker=0 msg="Walk of subtree completed" oid=1.3.6.1.4.1.31674.1.3.18.1.4.1.3.3.1.10 duration_seconds=4.827800612s
ts=2024-08-30T16:25:59.029Z caller=gosnmp.go:103 level=debug auth=auth target=target.domain source_address= worker=0 msg="Walking subtree" oid=1.3.6.1.4.1.31674.1.3.18.1.4.1.3.3.1.100
ts=2024-08-30T16:26:03.859Z caller=gosnmp.go:119 level=debug auth=auth target=target.domain source_address= worker=0 msg="Walk of subtree completed" oid=1.3.6.1.4.1.31674.1.3.18.1.4.1.3.3.1.100 duration_seconds=4.829902776s
ts=2024-08-30T16:26:03.859Z caller=gosnmp.go:103 level=debug auth=auth target=target.domain source_address= worker=0 msg="Walking subtree" oid=1.3.6.1.4.1.31674.1.3.18.1.4.1.3.3.1.110
ts=2024-08-30T16:26:04.463Z caller=collector.go:367 level=info auth=auth target=target.domain source_address= worker=0 module=moduleName msg="Error scraping target" err="scrape canceled after 603.359071ms (possible timeout) walking target target.domain"
ts=2024-08-30T16:26:04.463Z caller=collector.go:460 level=debug auth=auth target=target.domain source_address= worker=0 module=moduleName msg="Finished scrape" duration_seconds=10.261429181`

In this log we can see:
Subtree 1 finished in 4.828 seconds
Subtree 2 finished in 4.83 seconds
Subtree 3 aborted after 0.63 seconds

4.828 + 4.83 + 0.63 = 10.288 which is not a co-incidence I'm sure. 

### Host operating system: output of `uname -a`
FreeBSD 14.1-RELEASE FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC amd64

### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter, version  (branch: , revision: unknown)
  build user:
  build date:
  go version:       go1.21.12
  platform:         freebsd/amd64
  tags:             unknown

### What device/snmpwalk OID are you using?
The OID can be seen in the screenshot. The device is a Home Subscriber Server as part of an LTE EPC core.

### If this is a new device, please link to the MIB(s).
Sorry I'm not sure that I'm permitted to do that.

### What did you do that produced an error?
Basic scrape of a large number of OIDs

### What did you expect to see?
A complete scrape of all OIDs specified

### What did you see instead?
A timeout message prior to the scrape being completed.

**Comment by SuperQ** [comment]
The default Prometheus scrape timeout is 10 seconds.

**Comment by eriksejr** [comment]
Thanks @SuperQ that was the issue, I kept looking at the exporter, but it was prometheus timing out. Still after playing with it some more this host is just too slow to scrape all the information I want at the interval I want it at. I'm going to need to make some compromises.

**Comment by SuperQ** [comment]
Yes, that does seem excessively slow.

If you have any control over the application it's likely worth your time to convert it to Prometheus native metrics. Prometheus uses HTTP for collection, which is much more suited to bulk data than SNMP over UDP is. The SNMP protocol is very latency sensitive as it has none of the bulk windowing that TCP does.

**Comment by remchuk** [comment]
> The default Prometheus scrape timeout is 10 seconds.

What does the Prometheus has to do with the snmp_exporter?
I face a similar problem that after 10 responses it timesout, but I don't have a prometheus running, just the snmp_exporter

**Comment by eriksejr** [comment]
> > The default Prometheus scrape timeout is 10 seconds.
> 
> What does the Prometheus has to do with the snmp_exporter? I face a similar problem that after 10 responses it timesout, but I don't have a prometheus running, just the snmp_exporter

Since there's no interval defined in the exporter config, I believe that the exporter does not begin a scrape of the data for the target until a HTTP(s) request is made for that data. Once the request is made, the scrape begins and the requestor (be it Prometheus or something else) needs to wait for completion before getting a response to the request with the results. I assume (again I didn't test this with a capture) that once Prometheus times out it closes/cancels the HTTP(s) connection to the exporter which causes the exporter to terminate any scrape that was still in progress as a result of the now terminated request.

So in my case the scrape would always end after 10 seconds, once prometheus gave up waiting for a response from the exporter.

**Comment by eriksejr** [comment]
> Yes, that does seem excessively slow.
> 
> If you have any control over the application it's likely worth your time to convert it to Prometheus native metrics. Prometheus uses HTTP for collection, which is much more suited to bulk data than SNMP over UDP is. The SNMP protocol is very latency sensitive as it has none of the bulk windowing that TCP does.

I don't have access to the application I'm afraid, but I forwarded a request to the vendor to take a look at both the slow SNMP response time and options to export the metrics via HTTP.
