### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by wenshi01** [prometheus/snmp_exporter#1248]
Compile and run the file independently on Windows, go 1.21.13 version. The error is as shown in the figure

![image](https://github.com/user-attachments/assets/ebd35036-0bdb-4060-b18d-67ba7765481c)

**Comment by bastischubert** [comment]
not very familiar with windows os, but have you tried `make exporter` instead?

**Comment by wenshi01** [comment]
I haven't tested it. My Linux environment is a LAN environment and cannot connect to the Internet.

**Comment by bastischubert** [comment]
Hi @wenshi01 ,
closing this as. 
Unless you need the HEAD version of snmp exporter that you need to build yourself, please use a windows/linux build from our releases (https://github.com/prometheus/snmp_exporter/releases/tag/v0.26.0)
