### ISSUE TITLE
make error from generator 

### ISSUE THREAD

**Issue by bettswang** [prometheus/snmp_exporter#1264]
### Host operating system: output of `uname -a`
`Linux instance-20231226-1057 5.15.0-1063-oracle #69~20.04.1-Ubuntu SMP Sat Jun 29 02:21:46 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
### snmp_exporter version: output of `snmp_exporter -version`

```
snmp_exporter, version 0.26.0 (branch: main, revision: cf2862117122ed86870b86c256d75cdde996a091)
  build user:       root@instance-20231226-1057
  build date:       20241011-09:47:03
  go version:       go1.23.2
  platform:         linux/amd64
  tags:             unknown
```

### What did you do that produced an error?
```
cd snmp_exporter/generator
make mibs
```
### What did you expect to see?
`no error`
### What did you see instead?
```
caution: filename not matched:  SOPHOS-XG-MIB20.txt
make: *** [Makefile:303: mibs/.sophos_xg] Error 11
```
```
cat -n Makefile
……
303         @unzip -j -d $(MIBDIR) $(TMP) SOPHOS-XG-MIB20.txt
……
```
When delete "SOPHOS-XG-MIB20.txt", it works fine. Is this a bug?

**Comment by RuParker** [comment]
I agree. Just found the same issue. 
There appears to be a path required in the Makefile for expanding the Sophos entry from the downloaded sophos zip file (which is correct).
 @unzip -j -d $(MIBDIR) $(TMP) SOPHOS-XG-MIB20.txt
requires to be:
 @unzip -j -d $(MIBDIR) $(TMP) sophos-xg-mib/SOPHOS-XG-MIB20.txt
After editing the Makefile, the 'make' functions as expected.

**Comment by SuperQ** [comment]
@RuParker Want to open a PR to fix it?

**Comment by SuperQ** [comment]
Fixed in https://github.com/prometheus/snmp_exporter/pull/1266

**Comment by RuParker** [comment]
Hi @SuperQ , Many thanks.
