### ISSUE TITLE
make: *** [Makefile:89 : generator] Error 127

### ISSUE THREAD

**Issue by Phi2ca** [prometheus/snmp_exporter#1272]
hi

I have a prometheus server running debian 12

I followed the installation and configuration tutorial here, but also this one https://colby.gg/posts/2023-10-17-monitoring-synology/

And every time I try to use the generator and especially the make command, I get the same error:

`root@Matrix:~/snmp_exporter/generator# make generate
go build
make: go: Aucun fichier ou dossier de ce type
make: *** [Makefile:89 : generator] Erreur 127`

I'm not a developer at all, so I don't understand what's going on and where the error comes from.

Thank you in advance for your help

**Comment by bastischubert** [comment]
looks your system is missing go
See https://go.dev/doc/install for instructions how to install on linux

**Comment by Phi2ca** [comment]
Hello

I didn't know go, so indeed I couldn't find it.

That solved my problem, thank you
