### ISSUE TITLE
Default configuration seems to be invalid / too old

### ISSUE THREAD

**Issue by zLvkas** [prometheus/snmp_exporter#1273]
### docker-compose file
https://just-paste.it/91Ck9O1J7D

### What did you expect to see?
The system boots up properly.
### What did you see instead?
An error that says the configuration is outdated. I used the default configuration from the repository: https://raw.githubusercontent.com/prometheus/snmp_exporter/refs/heads/main/snmp.yml)

The error is:
https://just-paste.it/kBiGYCeZ0z

**Comment by bastischubert** [comment]
Hey @zLvkas , you're using the latest (HEAD) version of the snmp.yml vs the 0.26.0 release docker image.
Please use either the latest snmp exporter version, or a config that matches with 0.26.0 (see https://github.com/prometheus/snmp_exporter/releases/tag/v0.26.0 they all include a valid configuration)
