### ISSUE TITLE
snmpget instead of walk & static config (labeling)

### ISSUE THREAD

**Issue by tvc-dps** [prometheus/snmp_exporter#128]
Hello I am new here

I have idea collecting stats data from my equipment via snmp. (eg. network equipment very similar)
Equipment have a lot of fake/logical interfaces that i do not want pooling collect data.
Another problem I desperate need have at least two labels assigned to collected data similar as with switches (ifDescr + ifAlias), problem that ifAlias is not unique.
My idea is to generate list with oids that should be pooled and statically assign necessary labels. So not walk through all indexes, but specify exact oid with text labels in config file.
Can it be done with snmp_exporter?
If it is possible can you please provide configuration example?

Thanks in advance

**Comment by brian-brazil** [comment]
This is not possible with the snmp exporter, we ultimately work off the MIB and not manually assigned labels.

> Another problem I desperate need have at least two labels assigned to collected data similar as with switches (ifDescr + ifAlias), problem that ifAlias is not unique.

If it's not unique, then it doesn't belong as a label. There's an pending PR that'll improve string handling that you can take advantage of.

**Comment by SuperQ** [comment]
A configuration example that allows mapping of multiple description labels is here:

https://github.com/SuperQ/tools/blob/master/snmp_exporter/default.yml
