### ISSUE TITLE
Write log to separate file

### ISSUE THREAD

**Issue by hunterelectros** [prometheus/snmp_exporter#1309]
Hello! Is it possible to set write log to separate log-file, instead syslog? Or, if this option is already present, please show me how we may use it.

**Comment by bastischubert** [comment]
Hi @hunterelectros ,

`snmp_exporter` logs to stdout/stderr. How do you operate/install `snmp_exporter`?

**Comment by hunterelectros** [comment]
That's right. Now we can see the log in our separate file. Thanks for the leading question)

**Comment by bastischubert** [comment]
@hunterelectros if you don't mind, i'm just gonna close the issue as fixed ;)
