### ISSUE TITLE
generate mibs snmp.yml file have datetime_pattern error 

### ISSUE THREAD

**Issue by HassanNetops** [prometheus/snmp_exporter#1324]
My snmp-exporter docker is in restarting state and when i checked the logs its complaining about datetime_pattern in snmp.yml file. Below are the logs. 

root@grafana:/opt/docker/snmp-exporter/config# grep -n "datetime_pattern" snmp.yml
37897:      datetime_pattern: '%a %b %d %H:%M:%S %Y'
38303:      datetime_pattern: '%b %d %Y'
38319:      datetime_pattern: '%b %d %Y'
38335:      datetime_pattern: '%b %d %Y'
38351:      datetime_pattern: '%b %d %Y'
38367:      datetime_pattern: '%b %d %Y'
38383:      datetime_pattern: '%b %d %Y'
38399:      datetime_pattern: '%b %d %Y'
38415:      datetime_pattern: '%b %d %Y'
38431:      datetime_pattern: '%b %d %Y'

`ts=2024-12-30T15:16:05.449Z caller=main.go:212 level=info msg="Starting snmp_exporter" version="(version=0.26.0, branch=HEAD, revision=44f8732988e726bad3f13d5779f1da7705178642)" concurrency=1 debug_snmp=false
ts=2024-12-30T15:16:05.450Z caller=main.go:213 level=info build_context="(go=go1.22.3, platform=linux/amd64, user=root@90ba0aabb239, date=20240511-11:16:35, tags=unknown)"
ts=2024-12-30T15:16:05.610Z caller=main.go:220 level=error msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 37897: field datetime_pattern not found in type config.Metric\n  line 38303: field datetime_pattern not found in type config.Metric\n  line 38319: field datetime_pattern not found in type config.Metric\n  line 38335: field datetime_pattern not found in type config.Metric\n  line 38351: field datetime_pattern not found in type config.Metric\n  line 38367: field datetime_pattern not found in type config.Metric\n  line 38383: field datetime_pattern not found in type config.Metric\n  line 38399: field datetime_pattern not found in type config.Metric\n  line 38415: field datetime_pattern not found in type config.Metric\n  line 38431: field datetime_pattern not found in type config.Metric"
ts=2024-12-30T15:16:05.610Z caller=main.go:221 level=error msg="Possible old config file, see https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md"`

**Comment by SuperQ** [comment]
/duplicate https://github.com/prometheus/snmp_exporter/issues/1281
