### ISSUE TITLE
Understanding lookups

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/snmp_exporter#134]
I'm not sure I completely understand how lookups in the generator file work.

With a Cisco NX9000 switch, there are metrics in the SNMP output such as this:
```
cpmProcessAverageUSecs{cpmCPUTotalIndex="1",cpmProcessPID="94"} 3
```
(cpu time per process)
and then a process name table which can be scraped as this:
```
cpmProcessName{cpmCPUTotalIndex="1",cpmProcessName="scsi_eh_1",cpmProcessPID="94"} 1
```

But I'm not clear on how to do a mapping which will get `cpmProcessName` added as a label.

Is this possible currently?

**Comment by wrouesnel** [comment]
Hm, looking into this it looks like the problem is I can't do a multidimensional lookup? Because the actual oid I would need to look under is first indexed by cpmCPUTotalIndex (appends a `.1` to the oid) and then the PID.

**Comment by SuperQ** [comment]
Yes, multi-loookup mapping isn't supported yet.

**Comment by brian-brazil** [comment]
That is something the exporter supports, but its yet to be added to the generator as I was waiting for a use case to appear to clarify the semantics. This is not a valid use case for it though, as process names aren't unique.

You should join these together in PromQL, see https://www.robustperception.io/exposing-the-software-version-to-prometheus/
