### ISSUE TITLE
Non-Numeric types as values

### ISSUE THREAD

**Issue by jstoja** [prometheus/snmp_exporter#138]
Hello,

I don't know if I'm missing something or that it's not implemented but I get a many values from our generated MIB file with `OctetString` that I had to replace with `DisplayString` to get some values, but it appears in the label and not for the actual value.

I got a confirmation on the README of the generator that this is a known behavior, but I'm currently looking for way to integrate these values into prometheus. Is it possible yet?

**Comment by brian-brazil** [comment]
This is how it works, Prometheus uses only float64s so we have to put strings in labels.

It's unwise to switch an OctectString to a DisplayString, as that can break the output.

**Comment by jstoja** [comment]
Oh right ! I didn't know that. That explains the #98 .

What do you mean by:
> It's unwise to switch an OctectString to a DisplayString, as that can break the output.

?
Fetched values that are in hex seem useless if it's not converted.

**Comment by brian-brazil** [comment]
If we don't know how they're encoded, we can't convert them to much else.

**Comment by jstoja** [comment]
Ok, thank you for your quick answers!
