### ISSUE TITLE
System load when using snmp_exporter

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#14]
On a self-contained prometheus machine scraping half a dozen node_exporters, and pinging ~150 hosts via blackbox_exporter, load is at 0.03 to 0.14.

Adding 27 snmp targets via snmp_exporter running on the same machine which are scraped every minute increases load to 1.5. Querying the dataset every minute or so will increase load further to around 2.

VM specs:
* 6 cores of Intel(R) Xeon(R) CPU L5640  @ 2.27GHz
* 6 GiB RAM
* random, reasonably fast spindle disks

With four cores and 2 GiB of RAM, and with snmp_exporter being scraped, the system started swapping about 1.5 GiB and load went to ~8; quitting the main prometheus process via ctrl-c took about three minutes.

**Comment by brian-brazil** [comment]
Load is not a very useful statistic on modern systems. Can you indicate how much CPU the snmp exporter was using (keep in mind it's forking for every request), and how many OIDs were being processed?

**Comment by RichiH** [comment]
CPU usage was 70-80% over four cores. At that point, no other process of interest showed up and waiting etc were all around 0%.

snmp_oids_walked cummulates to around 120k over 27 targets.

**Comment by brian-brazil** [comment]
Based on the numbers I'm seeing, I'd expect that to be using ~.4 of a core with the code at HEAD.

The problem is likely that you're swapping. The default prometheus settings can easily use 1-2GB of RAM. Try adding more RAM, or tuning down Prometheus.

**Comment by RichiH** [comment]
I started swapping way after I pegged the CPUs.

Now, I am not swapping any more as I tripled the RAM of the test machine.

**Comment by brian-brazil** [comment]
How many rules do you have, and what is the cpu usage?

**Comment by brian-brazil** [comment]
Could you try out the `trie` branch? That should cut a good chunk of CPU, 50% for me with the default 34 rules.

**Comment by RichiH** [comment]
Will do in two days when I have time to look at things in peace and quiet ;)

I run the standard rules, plus the three rules for CPU power I pasted to you, and one rule which tries to read out uptime, but does nothing as it's not converting the string into float, yet.

**Comment by brian-brazil** [comment]
sysUpTimeInstance is a Timeticks, it should be a number already.

38 rules shouldn't be producing that much load, there must be something else going on on that machine.

**Comment by RichiH** [comment]
* Before `trie`: System load between 1.0 and 1.16
* Running `trie`: System load between 0.31 and 0.52

**Comment by RichiH** [comment]
As to sysUpTimeInstance, sadly IOS returns:

    % snmpget -v 2c -c foo bar 1.3.6.1.2.1.1.3.0
    DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1328688782) 153 days, 18:48:07.82

so I need to cut that out

**Comment by RichiH** [comment]
I can't give you better and/or longer-running load stats due to /me fat-fingering right into https://github.com/prometheus/prometheus/issues/1275

**Comment by RichiH** [comment]
Also due to the above, all numbers above, except for the initial 0.03 to 0.14, were for snmp_exporter being scraped, only.

Load with the blackbox, node, and snmp exporters is around 0.4 now, with in between 0.35 and 0.86.

**Comment by SqiSch** [comment]
@RichiH: 
The high CPU load when using the snmp_exporter is caused by pySNMP lib. http://stackoverflow.com/questions/22089477/how-to-avoid-high-cpu-usage-with-pysnmp
I have very good results using easysnmp/netsnmp in our fork:  
https://github.com/lovoo/snmp_exporter/tree/feature/add_features_increase_perf
Just try some changes from our fork. I also started to write an extended snmp_exporter which can handle mibs.

**Comment by brian-brazil** [comment]
@RichiH Can you provide CPU usage numbers please? Load is not useful.You can get these from the node exporter.

@SqiSch We can't use easysnmp, as it requires a too recent version of netsmmp that it's not reasonable to expect our users to have available. We're going to be using netsnmp directly.

**Comment by RichiH** [comment]
To sync the current situation in here:

* At ~190 targets polled every 60 seconds, the exporter is working as expected even though there's notable system load.
* At 264 targets polled every 60 seconds, the exporter is dropping arbitrary scrapes thus losing data.

@brian-brazil is aware and stated he will need to find some quality time to dig down. A potential rewrite of the export in Go depends on a rewrite of client_golang.

**Comment by RichiH** [comment]
https://github.com/prometheus/snmp_exporter/issues/53 will hopefully solve this issue.

**Comment by brian-brazil** [comment]
I believe that did resolve it.
