### ISSUE TITLE
Use BigIP F5 SNMP for LTM Metrics

### ISSUE THREAD

**Issue by Smuggla** [prometheus/snmp_exporter#142]
Hey Gang,

We are trying to use this SNMP exporter to get metrics from our Big IP LTMs.

The generator seems to be using the MIBs from LibreMS successfully but does not pull any of the LTM configuration.

We have already tried using the BigIP Exporter that uses the BigIP's slow API, but that exporter causes a 10% increase in CPU load.

We were hoping to use the SNMP exporter to get the metrics instead of the API.

Multi valued oids also look to not be supported.

The main oid is 1.3.6.1.4.1.3375 for LTM metrics.

Has anyone had a similar use case?

I have attached a hardcoded yml for the metrics we are trying to export.

[f5_ltm_snmp.txt](https://github.com/prometheus/snmp_exporter/files/894575/f5_ltm_snmp.txt)

Thanks for all your work!

**Comment by brian-brazil** [comment]
If you have the right MIB and it's correctly formed, then the generator should just work.

> Multi valued oids also look to not be supported.

Can you give an example? As far as I'm aware, an OID can only have one value.

**Comment by Smuggla** [comment]
I think we figured it out... Gonna have to spin up the config artisanally... But the generator doesn't like the LTM MIBs

generator dump
```
$ ./generator dump | grep sysStatClientCurConns
INFO[0000] Loading MIBs from $HOME/.snmp/mibs:/usr/share/snmp/mibs  source="net_snmp.go:72"
WARN[0000] NetSNMP reported 1 parse errors               source="main.go:78"
1.3.6.1.4.1.3375.2.1.1.2.1.8 sysStatClientCurConns GAUGE [] The current connections from client-side to the system.
1.3.6.1.4.1.3375.2.1.1.2.1.65 sysStatClientCurConns5s GAUGE [] The average current connections from client-side to the system in the last five seconds.
1.3.6.1.4.1.3375.2.1.1.2.1.79 sysStatClientCurConns1m GAUGE [] The average current connections from client-side to the system in the last one minute.
1.3.6.1.4.1.3375.2.1.1.2.1.93 sysStatClientCurConns5m GAUGE [] The average current connections from client-side to the system in the last five minutes.
```
snmp.yml
```
$ grep sysStatClientCurConns snmp.yml | wc -l
       0
```

generator dump
```
$ ./generator dump | grep ltmPoolEntry
INFO[0000] Loading MIBs from $HOME/.snmp/mibs:/usr/share/snmp/mibs  source="net_snmp.go:72"
WARN[0000] NetSNMP reported 1 parse errors               source="main.go:78"
1.3.6.1.4.1.3375.2.2.5.1.2.1 ltmPoolEntry OTHER [ltmPoolName] Columns in the ltmPool Table
```
snmp.yml
```
$ grep ltmPoolEntry snmp.yml | wc -l
       0
```

**Comment by brian-brazil** [comment]
Did you specify those OIDs in the generator.yml? Looks like it's parsing fine to me given the dump.

**Comment by Smuggla** [comment]
I guess that it's not clear in the documentation what the generator does.

Based on how we read it it was:

generator + empty template to fill (config.yml) + MIBs = snmp.yml

Thanks!

**Comment by brian-brazil** [comment]
Take a look at https://github.com/prometheus/snmp_exporter/blob/master/generator/generator.yml

**Comment by krizzo** [comment]
@Smuggla Having F5 metrics in the default would be nice. Are you planning on doing a PR to the project?

**Comment by cr41gc** [comment]
I created a PR (https://github.com/prometheus/snmp_exporter/pull/155) that adds F5 LTM support. @Smuggla, not sure if you figured this out on your own or not.

**Comment by SqiSch** [comment]
Can anyone explain me please how i can generate a working config for the table 
ltmHttpProfileStatTable. I cannot find a correct Index OID for the HttpProfileStatTable or maybe i misunderstand the config generation with the new_index and old_index. 
http://www.oidview.com/mibs/3375/F5-BIGIP-LOCAL-MIB.html

**Comment by cr41gc** [comment]
Have you tried using the ltmHttpProfileStat OID (1.3.6.1.4.1.3375.2.2.6.7.6) ?
