### ISSUE TITLE
Understanig the Basics

### ISSUE THREAD

**Issue by iGlaedr** [prometheus/snmp_exporter#144]
Hi

I'm new in the theam of monitoring. I understand the concept of SNMP but I don't understand how to Monitor Multipel Devices (SNMP targets). Is this eaven Possible ?
For Starting I'm trying to monitor tow ports of a "Zyxel GS1920-48" (192.168.1.2) Switch and one Port of a "GS1900-10HP" (192.168.1.4) Switch. I want to get Current Speed and if the Port Status it is UP or Down.

thank you in advance
best regarts
iGlaedr

**Comment by brian-brazil** [comment]
See https://www.robustperception.io/snmp-monitoring-with-prometheus/

**Comment by iGlaedr** [comment]
Hi 

I've seen this page but it didn' help me.
Must I create a snmp.1.yml to monitor a second switch and must I add somting i though the "scrape_configs"

thank for your support
best regarts
iGlaedr

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users

**Comment by iGlaedr** [comment]
Is the "metrics_path: /snmp"  the file " snmp.yml" ?
Can you send me an other example (other names instad of SNMP) of a job ?
Please
