### ISSUE TITLE
Complete walkthrough anywhere?

### ISSUE THREAD

**Issue by Xaelias** [prometheus/snmp_exporter#148]
Hi guys!

I don't consider myself as being stupid, or not a minimum knowledgeable in the IT department.
But I have no idea how to start getting this thing running for my NAS.

Short story, I have a synology NAS running prometheus/grafana, and I'm collecting data from a couple sources already. And I wanted to add the SNMP data from the NAS itself and... I honestly don't understand what's expected of me here.

Is there a walkthrough for a use-case at least remotely similar to mine?

Thanks guys

**Comment by SuperQ** [comment]
You don't need SNMP to get data from a Synology NAS.  What you're looking for is the [node_exporter](https://github.com/prometheus/node_exporter).

**Comment by Xaelias** [comment]
Well the NAS does offer an SNMP endpoint. And things like this: https://github.com/nlamirault/syno_exporter would let me think that SNMP is rather the way to go. That's actually why I came here in the first place :-)

**Comment by RichiH** [comment]
As (probably still) the largest user of snmp_exporter world-wide, I can say that you want to avoid it where reasonably possible.

**Comment by Xaelias** [comment]
Ah! Merci pour le conseil :-)
Ok je vais voir comment faire marcher node_exporter sur le NAS du coup.

**Comment by dakky** [comment]
the node_exporter seems NOT to work on synology NAS (maybe limited to older models):

```
./node_exporter 
FATAL: kernel too old
Aborted
```  

In my case it's a DS411.

```
uname -a
Linux hive 2.6.32.12 #15217 Fri Nov 3 04:40:48 CST 2017 armv5tel GNU/Linux synology_88f6282_411
```

**Comment by edasque** [comment]
@dakky Which one did you get?

I used https://github.com/prometheus/node_exporter/releases/download/v0.15.2/node_exporter-0.15.2.linux-386.tar.gz on a DSM 6.x 1815

```
uname -a
Linux my_synology 3.10.102 #15217 SMP Fri Nov 10 20:09:05 CST 2017 x86_64 GNU/Linux synology_avoton_1815+
```

**Comment by dakky** [comment]
hmmm i also tried the most recent node exporter.

But as u can see:
You are running a much newer synology station:
Kernel: 2.6 vs 3.0
Arch: ARM vs x68_64
