### ISSUE TITLE
How to load the MIB files

### ISSUE THREAD

**Issue by gurivi** [prometheus/snmp_exporter#151]
Hi,
I am new to Prometheus. I have downloaded the prometheus and snmp_exporter packages and i have added OIDs in snmp.yml. From the UI, <ip>:9090 i can see the graph and other tabs.
How can i check the Mib tree structure and walk through the Mib tree using prometheus.

**Comment by SuperQ** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
