### ISSUE TITLE
[Discussion] Caching values for a short time

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#153]
I am fully aware of how contentious this topic will be.

We observed cases of different Prometheus servers scraping specific targets which take a long time to answer which leads to increased waits and the Prometheus servers synchronizing their scrape timing. This, combined with common scrape intervals, leads to bad load behaviour.

The obvious answer is to cache values for a short time, let's say ~1-10 seconds. This for two scrapes hitting at the same-ish time to not congest the target.

If this is too controversial, we can solve this with Varnish, but as others will run into the same behaviour, polishing (and applying varnish to) the proverbial turd within the exporter seems like the better option to me.

**Comment by brian-brazil** [comment]
The core problem here is the performance of some devices. Caching creates artifacts in graphs and oddness in alerts doesn't really get around that, and the general guideline is only to consider caching if a scrape takes over a minute.

I don't see any scope for caching in the SNMP exporter.

> the Prometheus servers synchronizing their scrape timing

That's not how that works, the phase of scraped isn't affected by the duration of scrapes. https://github.com/prometheus/prometheus/issues/1546 is what you want.

**Comment by RichiH** [comment]
We agree on the core problem.

But as that's a real-world problem for us which will not go away any time soon, barring https://github.com/prometheus/prometheus/issues/1546 being solved, caching is the only viable workaround for said core problem.

**Comment by brian-brazil** [comment]
Thinking a bit, would a feature to throttle the frequency of requests handle this? For example allowing a 1ms wait between snmp requests.

**Comment by RichiH** [comment]
From our testing, legacy devices are busy and unhappy in the region of seconds, not ms.

**Comment by brian-brazil** [comment]
I don't mean throttling requests to the snmp exporter, I mean throttling requests from the snmp exporter.

**Comment by RichiH** [comment]
I would gladly test that.

I will be on the road most of next week, though.

**Comment by brian-brazil** [comment]
It'd need to be implemented down in the snmp library we use, so it's unlikely to happen in the immediate future. You could add a time.Sleep down in that code and see if it helps, as I think that'd be a much better solution than caching.

**Comment by RichiH** [comment]
FTR, we played with timeouts, wait times, etc on our end.

The unfortunate solution we are now running with is caching.

**Comment by brian-brazil** [comment]
Okay, sounds like there's nothing we can do on the snmp exporter side then if your devices can't handle 2 scrapes worth of load inside a scrape interval.

**Comment by brian-brazil** [comment]
Incidentally, the recommendation here would be to increase your scrape interval or decrease the amount of work you're doing per scrape.
