### ISSUE TITLE
s/walk/bulkget/ in the config and docs

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#156]
Networking people tend to stumble over the walk section being called walk when it's a bulkget in reality; allowing this section to be called bulkget or get would be the obvious solution.

walk would still need to be supported, of course.

**Comment by RichiH** [comment]
Hmm, or just `oids:`

**Comment by SuperQ** [comment]
`oids` or maybe `walk_oids`?

**Comment by brian-brazil** [comment]
It could be a bulkget or a getnext. "snmpwalk" is well known though.

**Comment by SuperQ** [comment]
@RichiH Are you talking about the `walk` key in the config?

**Comment by RichiH** [comment]
@SuperQ Yes, I am.

@brian-brazil Too well known for the sanity of network people when I explain the config syntax, which is why I am proposing this.

**Comment by RichiH** [comment]
This change is minor, just needs some deprecation notices. Regex handling has a chance to increase usage, so if possible, I would love to get this in beforehand.

**Comment by brian-brazil** [comment]
I don't think what you propose makes things clearer, in fact I think it'd increase confusion.

**Comment by RichiH** [comment]
I have lost count about how often people asked me "why are you walking the devices, this is way too much load".

Within the context of people using SNMP on a daily basis, `walk` is a red flag for "this will kill my devices".

**Comment by brian-brazil** [comment]
I'm thinking of this from a graph theory perspective, where walking is what we're doing. How we're doing it is an implementation detail.

I don't see any other suggestions though that are correct (oids could just be a get, walk_oids has the same issue and still mentions walk, bulkget is incorrect, getnext is incorrect, bulkwalk is incorrect).

Maybe this is something to clear up in the readme?

**Comment by RichiH** [comment]
`oids` is generic and names what is fetched, `lookups` are actions based on that.

While `walk` is well-defined graph theory, it's also well-defined within SNMP and, in the context of this exporter, SNMP is the most specific match.

**Comment by brian-brazil** [comment]
oids aren't fetched here though, they're walked (getbulk supports doing both a fetch via getnext and the usual walk in the same request).

**Comment by brian-brazil** [comment]
The readme now makes it clear what we're doing, hopefully that'll clear up most confusion around this.

**Comment by RichiH** [comment]
Arguably, having docs stating that the config stanza is wrong for historical reasons is worse than migrating to a correct name without needing docs to explain history.

**Comment by brian-brazil** [comment]
The config stanza is correct, it's people misinterpreting it that's the issue. I also note that no other correct name has been proposed.

**Comment by RichiH** [comment]
I maintain that https://github.com/prometheus/snmp_exporter/issues/156#issuecomment-315388377 addresses both of your points.
