### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by iGlaedr** [prometheus/snmp_exporter#160]
Hi

I have a simple problem. The Dockerhub "prom/snmp_exporter" is empty.
Can some one pleas put it back up on there ?

Thanks
iGlaedr

**Comment by broxio** [comment]
should be prom/snmp-exporter

**Comment by iGlaedr** [comment]
No i can't find it 
<img width="1918" alt="bildschirmfoto 2017-05-17 um 17 15 09" src="https://cloud.githubusercontent.com/assets/25317853/26161599/aa1c5a32-3b24-11e7-8301-fa5fbd099679.png">

**Comment by iGlaedr** [comment]
status ?

**Comment by jcollie** [comment]
Try: quay.io:

https://quay.io/repository/prometheus/snmp-exporter

**Comment by iGlaedr** [comment]
thanks
