### ISSUE TITLE
Support DISPLAY-HINT attributes

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#163]
Moving https://github.com/prometheus/blackbox_exporter/issues/153 over to here.

https://tools.ietf.org/html/rfc2579#section-3.1 specifies how OCTET STRING entries can be displayed.

**Comment by brian-brazil** [comment]
Are there particular OIDs you want to capture?

To get good metrics out we need some care, as for example date times (which are 2d-1d-1d,1d:1d:1d.1d,1a1d:1d) should be converted to a unix timestamp.

**Comment by brian-brazil** [comment]
We're covering the main ones. If there's particular ones you want, please open an individual issue for them.
