### ISSUE TITLE
Use tc_index to get text convention

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/snmp_exporter#164]
Currently we rely on the display hint for things like DisplayString, however some MIBs depend on RFC1213-MIB which is too old to have a hint. The tc_index can be used to get the original text convention (SYNTAX) in the MIB, so we can still set the right type for such things.

**Comment by fwclements** [comment]
Before I go and post a specific question about textual conventions I'll ask here.  I'm running into two, but I'm sure there's loads more, Cisco MIBs that use their own textual conventions for some value.

Example 1:
  CISCO-CEF-MIB
    cefFIBSummaryTable uses cefFIBIpVersion which is syntax of CefIpVersion

Example 2:
   CISCO-AAA-SERVER-MIB
     casConfigTable uses casProtocol which is syntax of CiscoAAAProtocol

Looking at what I'm getting from Example 1: 
# HELP cefFIBSummaryFwdPrefixes 
# TYPE cefFIBSummaryFwdPrefixes gauge
cefFIBSummaryFwdPrefixes{cefFIBIpVersion="1",entPhysicalName="cpu R0/0"} 646115
cefFIBSummaryFwdPrefixes{cefFIBIpVersion="2",entPhysicalName="cpu R0/0"} 10

It would be nice if the cefFIBIpVersion labels would map to their respective values (1=ipv4, 2=ipv6).

Is this related to #164 or am I doing something wrong in the generator.yml file by needing to do some type of lookup?

**Comment by brian-brazil** [comment]
That's something else again, enum support. Both of those are being used as values, so we'd be looking at  adding some information to the HELP.

**Comment by fwclements** [comment]
@brian-brazil when you say "something else again" do you mean that it's another potential future feature of snmp_exporter/generator or that it's some configuration that I would need to do in order to get that information into the HELP?

**Comment by brian-brazil** [comment]
It's another potential feature, but it's of limited use.

**Comment by fwclements** [comment]
Ok thanks

**Comment by brian-brazil** [comment]
snIfOpticalMonitoringTxPower in FOUNDRY-SN-SWITCH-GROUP-MIB is another variant of this, where DisplayString has its size changed. May also be a case of #163
