### ISSUE TITLE
Where is the config.yml to include the snmp v3 authentication

### ISSUE THREAD

**Issue by xbblq7n** [prometheus/snmp_exporter#168]
Hi,
I have deployed snmp exporter and able to scrape the snmp v2 devices which used the community string "public" in prometheus.
But in order to scrape the snmp v3 devices i have to pass the authentication values to the config.
But this config file is missing in the binary which i downloaded.
The binary only has the snmp.yml and does not have the config.yml to add below details.

default:
  version: 3
  auth:
    username: SomeUser
    password: TotallySecret
    auth_protocol: SHA
    priv_protocol: AES
    security_level: SomethingReadOnly
    priv_password: SomeOtherSecret
  walk:
    - ...
  metrics:
    - ...

Does adding a config.yml in the same location as snmp.yml will make this work.
Thanks in advance.

**Comment by brian-brazil** [comment]
I'm not sure where you got config.yml from, snmp.yml is the file you want.

**Comment by xbblq7n** [comment]
Hi Brian,
Thanks for you reply.
so adding the authentication parameter in each modules within snmp.yml will make this work right.
similar to this.

_apcups:
  version: 3
  auth:
    username: SomeUser
    password: TotallySecret
    auth_protocol: SHA
    priv_protocol: AES
    security_level: SomethingReadOnly
    priv_password: SomeOtherSecret
  walk:
  - 1.3.6.1.2.1.1.3
  - 1.3.6.1.2.1.2
  - 1.3.6.1.4.1.318.1.1.1.12
  - 1.3.6.1.4.1.318.1.1.1.2
  - 1.3.6.1.4.1.318.1.1.1.3
  - 1.3.6.1.4.1.318.1.1.1.4
  - 1.3.6.1.4.1.318.1.1.1.7.2
  - 1.3.6.1.4.1.318.1.1.1.8.1
  - 1.3.6.1.4.1.318.1.1.10.2.3.2
  metrics:
  - name: sysUpTime_



i have misunderstood this line in the readme to be a separate config file. 
" The default configuration is to use SNMPv2 with the community public. **This can be changed in the yaml config**. NOTE: Version 2 implies SNMP version 2c."
