### ISSUE TITLE
invalid memory address or nil pointer dereference Error

### ISSUE THREAD

**Issue by xbblq7n** [prometheus/snmp_exporter#169]
Hi,

I am getting invalid memory address error when using snmp v3 authentication.
The exporter was working fine with snmpv2 devices with default_if_index module.
Below is the error, yml config , snmpbulwalk command output from the box.

![image](https://cloud.githubusercontent.com/assets/24911089/26814137/c1729f9e-4aa0-11e7-9f01-48a3297d54ad.png)

![image](https://cloud.githubusercontent.com/assets/24911089/26814024/e247b2b4-4a9f-11e7-8198-90da4248db78.png)

![image](https://cloud.githubusercontent.com/assets/24911089/26814159/0026aa14-4aa1-11e7-9426-af8977ca01f6.png)

**Comment by SuperQ** [comment]
Can you run the exporter with `-log.level=deubg` and attach a text copy (not a screenshot) of the output?

**Comment by RichiH** [comment]
@SuperQ was minimally faster, so my only remaining point: Please change your login credentials and take care to blank/remove _everything_, ideally making even the length of the strings invisible to anyone you send this to.

**Comment by xbblq7n** [comment]
@SuperQ  and @RichiH  thanks for your reply.
Here is the text with the output.
[snmpexporter output.txt](https://github.com/prometheus/snmp_exporter/files/1054105/snmpexporter.output.txt)

**Comment by SuperQ** [comment]
I traced the error, it looks like it's coming from the upstream SNMP code.  I will have to see if there are any related upstream issues filed/fixed.

**Comment by xbblq7n** [comment]
Thanks @SuperQ for your time.
Will wait for the resolution.
Hope i can get the snmp metrics scraped soon.

**Comment by SuperQ** [comment]
There's nothing specific upstream that I can find after a quick glance through the changes.  However it looks like the v3 auth has been refactored since we released the last snmp_exporter.  I propose we update the vendoring and test again.

**Comment by xbblq7n** [comment]
okay

**Comment by SuperQ** [comment]
If possible, can you build a version of the snmp_exporter from master?

**Comment by xbblq7n** [comment]
Never done them before.
i will give a try to build from master.

**Comment by SuperQ** [comment]
If you have a Golang compiler/build env setup, it should be as easy as `go get github.com/prometheus/snmp_exporter` and the binary will end up in the `bin` dir of your build env.

**Comment by xbblq7n** [comment]
No i have not setup Golang 
I am off on wed will be back on Thursday to check this.
Meanwhile, is the docker version of the image from dockerhub uses a different buid?
https://hub.docker.com/r/prom/snmp-exporter/
If this image is a latest build can i try with this.
Thanks for your help @SuperQ

**Comment by SuperQ** [comment]
Here is a `snmp_exporter` test binary built for Linux x86-64.

[snmp_exporter.gz](https://github.com/prometheus/snmp_exporter/files/1054661/snmp_exporter.gz)

**Comment by xbblq7n** [comment]
Thanks @SuperQ 
Iam now able to scrape the metrics using snmpv3 auth using the new binary you have provided.

![image](https://cloud.githubusercontent.com/assets/24911089/26827194/ca2561b0-4ad9-11e7-8c61-e9e0d08490fa.png)

Thanks again :)

**Comment by SuperQ** [comment]
Great!  We'll have to make a new official release that contains the updated vendor code.

**Comment by SuperQ** [comment]
FYI, I've made an official release of the new version.

**Comment by tricycleHack** [comment]
Hi,

the problem seems to be back:

Using version 0.12.0 with docker image.
SNMPv3 with authPriv mode

```
Configured everything in configs accordingly:
version: 3
max_repetitions: 25
retries: 3
timeout: 20s
auth: 
security_level: authPriv
username: user
password: safePassword
auth_protocol: SHA
priv_protocol: AES
priv_password: privatePassword
```

snmpwalk is working with the device, so the problem is not on the side of the device for sure. From log.level=debug returns:

```
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=debug msg="Scraping target '192.168.1.1:161' with module 'if_mib'" source="main.go:86"
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=debug msg="Walking target \"192.168.1.1:161\" subtree \"1.3.6.1.2.1.1.3\"" source="collector.go:125"
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=info msg="Error scraping target 192.168.1.1:161: Error walking target 192.168.178.6: recover: runtime error: invalid memory address or nil pointer dereference" source="collector.go:180"
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=debug msg="Scrape of target '192.168.1.1:161' with module 'if_mib' took 60.002449 seconds" source="main.go:97"
```
