### ISSUE TITLE
Timeout definition for snmp_exporter

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#17]
While I can set a timeout for the scraping of the exporter, I can't set a timeout for when the snmp_exporter stops trying, internally. I can't seem to find an option within the exporter codebase, either.

Unless I am missing something, an option to have snmp_exporter jobs kill themselves after X time would be appreciated.

**Comment by brian-brazil** [comment]
There's no such option currently, but I'd be happy to accept a PR.

**Comment by brian-brazil** [comment]
There's an option now, however it's not of too much use. The upstream library needs improvements in the timeout department, preferably by using contexts.

**Comment by brian-brazil** [comment]
The other option is to use the raw BulkGet calls that the library exposes, which would probably be simpler.

**Comment by SuperQ** [comment]
We can how handle this like we do in the blackbox_exporter[0] and get the timeout from `X-Prometheus-Scrape-Timeout-Seconds` headers.

[0]: https://github.com/prometheus/blackbox_exporter/blob/master/main.go#L74-L86

**Comment by brian-brazil** [comment]
The underlying snmp library needs better timeout handling first.

**Comment by brian-brazil** [comment]
https://github.com/soniah/gosnmp/pull/203 will permit us to do this.
