### ISSUE TITLE
Reduce severity of logging messages when target is down

### ISSUE THREAD

**Issue by cubranic** [prometheus/snmp_exporter#174]
### Host operating system
```
Linux cndhn 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### snmp_exporter version
```
snmp_exporter, version 0.3.0 (branch: master, revision: 6f8aa8a24d720b36991f29ffb179b2896e92090b)
  build user:       root@07f1e81a0104
  build date:       20170315-16:01:54
  go version:       go1.7.5
```

### What did you do that produced an error?

When a number of devices are turned off (say during a power outage, or for routine maintenance), the logs on the host where snmp_exporter is run fill up with error messages like this one:
```
Jun 12 08:36:37 cndhn snmp_exporter: time="2017-06-12T08:36:37-04:00" level=error msg="Error scraping target cn2cx: Error walking target cn2cx: Request timeout (after 3 retries)" source="collector.go:126"
```

I'd like to reduce the level of spamming this is causing in my logs. Right now, it seems like my only option is to run with `-log.level fatal`. Could perhaps these messages be logged with a lower severity level?

**Comment by SuperQ** [comment]
That message probably could be reduced to a warning, as the timeout isn't the exporter's "problem".

**Comment by brian-brazil** [comment]
It's debug really, but info until we've got good diagnostics.

**Comment by cubranic** [comment]
Thanks!
