### ISSUE TITLE
Walk only part of a table

### ISSUE THREAD

**Issue by cchance27** [prometheus/snmp_exporter#176]
When scraping ifHCInOctets as an example the device returns the index 1001 - 1048 for instance but it also returns alot of virtual interfaces such as ifIndex 100010051. 

I've seen past issues opened but couldn't find reference to any solution unless i'm missing it i saw some people requesting even to be able to do "range" walks such as 1.3.6.1.1.x~y but i don't think thats something the tool implements currently but would be handy to rain in runaway oid tables.

is their a way to have snmp_exporter only return the 4 digit oids or only the first X number of oid's?

**Comment by brian-brazil** [comment]
Your only option currently is to hand alter the walk to the specific oids you want, but it's not going to be particularly efficient with the current implementation.

**Comment by SuperQ** [comment]
It doesn't fix the walk, but you can drop excess metrics using `metric_relabel_configs` in the Prometheus server config file.

**Comment by brian-brazil** [comment]
I should ask, what's the problem with returning these interfaces?

**Comment by RichiH** [comment]
Many of them are empty or bogus, yet returned. Virtual interfaces are...
Interesting in most networking machines.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by brian-brazil** [comment]
I'm interested in if this is merely an annoyance (in which case metric_relabel_configs is acceptable), or a performance concern (in which case we need to see if we can do something about it).

**Comment by cchance27** [comment]
Using relabel to drop them will help with db size but pulling down several hundred or thousand even virtual interface is a LOT of extra load on the switches not to mention network load especially when only maybe 48 of each walk are needed but the walk runs away to several hundred each time for every device

**Comment by SuperQ** [comment]
@cchance27 I don't know about the SNMP side of the protocol, but Prometheus uses compressed protocol buffers when talking to the `snmp_exporter`.  A single scrape, even on the order of thousands, will be on the order of 10s of kB.  Network load is really not a concern from that side.  10,000 devices at 50kB/min is under 70mbps.

**Comment by RichiH** [comment]
@brian-brazil load is roughly linear for the amount of interfaces scraped. Given that we run hardware with hundreds of ports and thousands of virtual interfaces, this adds up in load.

A further problem is that some virtual interfaces return sane values on _some_ OIDs, but that set can change between hardware, and sometimes even between software, revisions.

**Comment by brian-brazil** [comment]
#131 covers this.

**Comment by cchance27** [comment]
Ok so is this a feature thats just not going to happen? As you said 131 covers this, but 131 you marked as a feature-request and then closed it ?

**Comment by brian-brazil** [comment]
#131 is still open. This would be fairly complex to implement, I wouldn't expect it anytime soon.
