### ISSUE TITLE
timeout snmp

### ISSUE THREAD

**Issue by ridhoyp** [prometheus/snmp_exporter#177]
Hi 

I want to get cisco switch interface statistic, its snmp not using public community string, how to change it on snmp.yml :

default:
  version: 2
  auth:
    community: tes35nmp
  walk:

but it still timeout, i dont know where to change it, please help

ubuntu : 14.0.4, 
snmp_exporter : snmp_exporter-0.4.0.linux-amd64
Regards,
RidhoYP

**Comment by RichiH** [comment]
Can you snmpbulkget from that machine with that snmp secret?

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by ridhoyp** [comment]
Hi ,

yea can, is my config is correct? iam new, and wat to try promethus with it snmp-export, because i already use graphite, librenms + influx still have such a large data in bits/sec metrics on grafana

Regards,
RidhoYP

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users
