### ISSUE TITLE
CPU load expectations 1k targets and ~30 metrics per target

### ISSUE THREAD

**Issue by vitaly-m** [prometheus/snmp_exporter#181]
Hello @brian-brazil,

What CPU utilization you are expect for one exporter and 1000 targets with ~30 metrics per target? On my machine I have 40-50% CPU load of Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz, I think it is too high and it increase very fast, for example this machine can't handle 2000 targets with 60s request period.

What kind information can help to solve this performance problem (I think this is problem)?

**Comment by SuperQ** [comment]
@RichiH You have more experience with large numbers of targets.

Also, next time, please use our [community](https://prometheus.io/community/) for help requests.

**Comment by vitaly-m** [comment]
I think it is related to snmp_exporter only, and it is a performance bug, that is why I created an issue here. @SuperQ, next time I will use the [community](https://prometheus.io/community/), thank you

**Comment by SuperQ** [comment]
The easiest way to find out what's going on inside the snmp_exporter is to use [pprof](https://blog.golang.org/profiling-go-programs).

For example:
```
go tool pprof http://localhost:9116/debug/pprof/profile
```

Then you can run the `web` command at the `(pprof)` prompt and see what's up.

**Comment by vitaly-m** [comment]
OK, I'll try, the result of top command:
``` (pprof) top
16.36s of 20.06s total (81.56%)
Dropped 325 nodes (cum <= 0.10s)
Showing top 10 nodes out of 117 (cum >= 0.15s)
      flat  flat%   sum%        cum   cum%
    14.32s 71.39% 71.39%     14.38s 71.68%  syscall.Syscall
     0.47s  2.34% 73.73%      1.41s  7.03%  runtime.mallocgc
     0.31s  1.55% 75.27%      0.31s  1.55%  runtime.memclrNoHeapPointers
     0.29s  1.45% 76.72%      0.29s  1.45%  runtime.futex
     0.26s  1.30% 78.02%      0.36s  1.79%  runtime.scanobject
     0.17s  0.85% 78.86%      0.24s  1.20%  strconv.ParseInt
     0.15s  0.75% 79.61%      0.48s  2.39%  strings.genSplit
     0.14s   0.7% 80.31%      0.14s   0.7%  runtime.epollwait
     0.13s  0.65% 80.96%      0.13s  0.65%  runtime.memmove
     0.12s   0.6% 81.56%      0.15s  0.75%  runtime.heapBitsSetType
```

**Comment by SuperQ** [comment]
Interesting.  Is that for a 30s sample?  It looks like you're using about 50% of one core, not 50% of all your cores.  With your current quad-core CPU, you should be able to handle 8000 targets.

Where did you get the "50% CPU load" number?

**Comment by vitaly-m** [comment]
I have snmp_exporter inside VM with one core:
```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
stepping        : 3
cpu MHz         : 3292.376
cache size      : 6144 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm
bogomips        : 6584.75
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:


```

**Comment by RichiH** [comment]
* 16 cores Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
* ~1 million PDUs scraped every 120 seconds from ~1k devices
* This binary is from September 2016

![snmp_exporter](https://user-images.githubusercontent.com/754723/27528656-abff7482-5a51-11e7-9da6-ce9d20924b67.png)

**Comment by SuperQ** [comment]
Thanks @RichiH.  Looks to be about the same.  Your trace shows a lot of time spent parsing yaml, this should be fixed with the SIGHUP change.  There is also some extra time spent in GC, so there may be some places where we could improve efficiency by reducing memory allocations.

**Comment by brian-brazil** [comment]
We can see how the allocations look after the SIGHUP change to see if there's low hanging fruit. I would hope for a bit more than 10k PDU/s/core.

**Comment by vitaly-m** [comment]
The result of 30s prof test after configuration update changes:
![30sload](https://user-images.githubusercontent.com/574929/27823247-1f1e7318-60b1-11e7-8930-da71aa8bc3dd.png)

In my case I have this output for top command:
```
$ top
top - 04:59:26 up 1 day,  1:39,  2 users,  load average: 0.48, 0.24, 0.13
Tasks:  92 total,   1 running,  91 sleeping,   0 stopped,   0 zombie
%Cpu(s):  7.0 us, 25.5 sy,  0.0 ni, 59.3 id,  0.0 wa,  0.0 hi,  8.2 si,  0.0 st
KiB Mem :  1883788 total,   810168 free,   297440 used,   776180 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  1362320 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
16137 netcrk    20   0   21016  13196   3664 S 43.7  0.7   1:03.44 snmp_exporter
16151 netcrk    20   0  213852 170736  12024 S  1.7  9.1   0:04.04 prometheus

```
And I think that CPU load is too high.

**Comment by brian-brazil** [comment]
75% of the time is spent in syscalls, any improvements we make are going to be pretty small.

**Comment by SuperQ** [comment]
Yes, that looks pretty good.  Most of the time is being spent outside the snmp exporter handling network traffic.  Given that the profile shows 7.96s out of the 30s (26.5%) of a single core.  That seems pretty efficient to me.

**Comment by vitaly-m** [comment]
Am I understand correctly that in any case this is code base of gosnmp and the problem should be discussed there? Or maybe snmp_exporter can optimize snmp request calls?

**Comment by brian-brazil** [comment]
Most of the time is spent in Linux, and I think it's a safe bet that those code paths are already optimised to hell and back.

**Comment by vitaly-m** [comment]
I understand, but maybe the requests are not optimized, for example snmp_exporter send 30k requests in my case instead of 1000, for example using getbulk. I think that the walk command is not the best solution if we have predefined set of OIDs.

What do you think?

**Comment by SuperQ** [comment]
We already use `BulkWalkAll()` which is implemented by the upstream library as a GetBulk.

**Comment by vitaly-m** [comment]
I see `GetNext()` calls in the graph... Does it mean that the implementation doesn't use `GetBulk()`?

**Comment by brian-brazil** [comment]
That'll only be the case if you've explicitly configured SNMP v1.

**Comment by vitaly-m** [comment]
Hm, OK, in my case it is true. I will try to retest it with v2.

**Comment by SuperQ** [comment]
Any luck with better performance with v2?

**Comment by vitaly-m** [comment]
Not tested yet, I will try to do it next week.

**Comment by vitaly-m** [comment]
I think the problem can be closed with 1000 targets and 19 metrics per target I have only ~15% CPU load on the same machine ![snmpv2](https://user-images.githubusercontent.com/574929/28008200-3e1fea3c-655f-11e7-9922-332b6290a4af.png)

**Comment by SuperQ** [comment]
Yes, it looks much better with v2.  50% of the time is still being spent in syscall netowork overhead, but I don't think that can be avoided due to the chatty nature of SNMP.

It does look like there are some cases where we could do a better job with memory allocation, but this looks pretty good.
