### ISSUE TITLE
[FR] /config page

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#182]
As per https://github.com/prometheus/snmp_exporter/pull/179 there should be a /config page.

**Comment by RichiH** [comment]
Arguably, this should be linked from the main page.

**Comment by brian-brazil** [comment]
I was thinking more that the modules would be listed on the main page, and you could view each module's config individually. I think that'd be more readable than all the config on one page (or at least as readable as a format not intended for human consumption gets.)

**Comment by vitaly-m** [comment]
I think that the API should look like:
`/config GET`
`/config/{module} GET`
Because we may need to view all configuration or only part of it.

**Comment by brian-brazil** [comment]
Fixed by #199 

We're keeping with one big dump for now.
