### ISSUE TITLE
Validate metric names and make them valid when possible

### ISSUE THREAD

**Issue by pcfens** [prometheus/snmp_exporter#184]
Some MIB files produce metric names that have dashes in them (like digital-sen1-1).

Should the snmp_exporter convert dashes to underscores to make these into valid metric names?

In this case, the problem metric is coming off of an older AVTECH TemPageR device. I'm currently building snmp_exporter from source (aa8c078) on a Linux machine.

**Comment by brian-brazil** [comment]
It should convert anything invalid to underscores on the generator side. I wasn't aware there were SNMP objects with such names.
