### ISSUE TITLE
"integer divide by zero" issue

### ISSUE THREAD

**Issue by eskornev** [prometheus/snmp_exporter#185]
Hello!
Have a trouble with scraping my device, receive next error:
error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error walking target X.X.X.X: recover: runtime error: integer divide by zero

my config:

```
default:
  version: 3
  auth:
    username: user
    password: pass
    auth_protocol: MD5
    security_level: authNoPriv
  walk:
    # List of OID subtrees to walk.
    - 1.3.6.1.4.1.35265.1.29.31.1.0
  metrics:
    - name: channels_used
      oid: 1.3.6.1.4.1.35265.1.29.31.1.0.0
      type:  gauge
```

application log:

```
DEBU[0025] Walking target "X.X.X.X" subtree "1.3.6.1.4.1.35265.1.29.31.1.0"  source="collector.go:71"
ERRO[0025] Error scraping target X.X.X.X: Error walking target X.X.X.X: recover: runtime error: integer divide by zero  source="collector.go:126"
```

tcpdump:

```
12:25:06.441261 IP (tos 0x0, ttl 64, id 40838, offset 0, flags [DF], proto UDP (17), length 92)
    192.168.182.30.60371 > X.X.X.X.161:  { SNMPv3 { F=r } { USM B=0 T=0 U="" } { ScopedPDU E= C="" { GetRequest(14) R=-1138337590  } } } 
12:25:06.470267 IP (tos 0x0, ttl 53, id 0, offset 0, flags [DF], proto UDP (17), length 137)
    X.X.X.X.161 > 192.168.182.30.60371:  { SNMPv3 { F= } { USM B=87 T=67234 U="" } { ScopedPDU E=_80_00_1f_88_80_48_41_a5_e5_4c_2d_d4_c5 C="" { Report(31) R=-1138337590  .1.3.6.1.6.3.15.1.1.4.0=25 } } }
```

result of snmpwalk from my machine:
iso.3.6.1.4.1.35265.1.29.31.1.0.0 = Counter32: 30
iso.3.6.1.4.1.35265.1.29.31.1.1.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.2.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.3.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.4.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.5.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.6.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.7.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.8.0 = Counter32: 0
iso.3.6.1.4.1.35265.1.29.31.1.9.0 = Counter32: 0

**Comment by brian-brazil** [comment]
Your config doesn't look right, that trailing .0 shouldn't be there.

I'd suggest using the generator to generate your config (as it appears incorrect in other ways too), and seeing if it works.

**Comment by eskornev** [comment]
Thanks Brian, I'll try.

**Comment by RichiH** [comment]
Notwithstanding the trailing .0, the error message could arguably be improved.

**Comment by brian-brazil** [comment]
We have no idea yet what this error is coming from, nowhere relevant in our code uses `recover` that could cause this particular message.

**Comment by brian-brazil** [comment]
I'm not sure I'm going to be able to debug this one from the information given, I've a suspicion this issue is down in a core Golang library somewhere.

Would you be able to narrow this down to a line of code in the exporter or our snmp library?

**Comment by LordGorgul** [comment]
Has anyone found a solution yet? I'm struggling with the exact same problem right now.

**Comment by SuperQ** [comment]
@LordGorgul Would you please attach the snmp.yml config you are using?

**Comment by LordGorgul** [comment]
@SuperQ Here it is:
`default:
  version: 3
  auth:
    username: XXXX
  walk:`
I don't have the password for the user I'm using but it should work without one (snmpwalk and snmpbulkwalk work just fine without a password). I already tried adding the auth_protocol and security_level but that didn't do anything.

**Comment by RichiH** [comment]
You need to include the walk & metrics sections.

If you don't have those, snmp_exporter can not function; that being said it should still not divide by zero.

**Comment by brian-brazil** [comment]
Can ye tell us which types of devices you're probing? Is this only happening with SNMPv3?

**Comment by LordGorgul** [comment]
@RichiH I do have the walk and metrics sections I just didn't include them in the comment because I thought it would be unnecessary (I haven't made any changes to the standard snmp.yml except for the version and auth part)

**Comment by LordGorgul** [comment]
@brian-brazil I'm probing a SAN switch (Brocade DCX 8510-8)
This happens when I change the version to SNMPv2:
`default:
  version: 2
  auth:
    community: XXXX
`

`INFO[0000] Starting snmp exporter (version=0.4.0, branch=master, revision=0a00acbf61971015b6475441d741ce59ad2ba26d)  source="main.go:99"
INFO[0000] Build context (go=go1.8.3, user=root@ea8b44ce07e1, date=20170606-13:39:44)  source="main.go:100"
INFO[0000] Listening on :9116                            source="main.go:143"
DEBU[0065] Walking target "XXXX" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
ERRO[0065] Error scraping target XXXX: Error walking target XXXX: Request timeout (after 3 retries)  source="collector.go:126"
`

and version 1:
`default:
  version: 1
  auth:
    community: XXXX
`

`INFO[0000] Starting snmp exporter (version=0.4.0, branch=master, revision=0a00acbf61971015b6475441d741ce59ad2ba26d)  source="main.go:99"
INFO[0000] Build context (go=go1.8.3, user=root@ea8b44ce07e1, date=20170606-13:39:44)  source="main.go:100"
INFO[0000] Listening on :9116                            source="main.go:143"
DEBU[0068] Walking target "XXXX" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
ERRO[0068] Error scraping target XXXX: Error walking target XXXX: Request timeout (after 3 retries)  source="collector.go:126"
`

The debug message appears multiple times I just cut it out for the sake of readability

**Comment by brian-brazil** [comment]
I'd by default suspect that's a auth issue, does that community string work with snmpwalk/snmpbulkwalk?

I see one bug upstream fixed around SNMPv3, but it presents as a timeout rather than a divide by 0.

**Comment by LordGorgul** [comment]
`snmpwalk -v2c -c XXXX XXXX
Timeout: No Response from XXXX`
`
snmpwalk -v1 -c XXXX XXXX
Timeout: No Response from XXXX
`
It could be possible that SNMPv2 & 1 are disabled because we normally only use v3

**Comment by LordGorgul** [comment]
So i've just tried to generate a new config with the generator and then the following happend:
`./generator generate
INFO[0000] Loading MIBs from $HOME/.snmp/mibs:/usr/share/snmp/mibs  source="net_snmp.go:83"
WARN[0000] NetSNMP reported 1 parse errors               source="main.go:78"
INFO[0000] Generating config for module default          source="main.go:29"
INFO[0000] Generated 42 metrics for module default       source="main.go:36"
INFO[0000] Generating config for module default_ifname   source="main.go:29"
INFO[0000] Generated 42 metrics for module default_ifname  source="main.go:36"
INFO[0000] Generating config for module cisco_wlc        source="main.go:29"
FATA[0000] Cannot find oid '1.3.6.1.4.1.14179.2.1.1.1.38' to walk  source="tree.go:143"
`
Is this a known problem? Could this have anything to do with the snmp_exporter not working?

**Comment by brian-brazil** [comment]
That's a missing MIB, you'll need to find it and add it.

**Comment by LordGorgul** [comment]
Okay I deleted the missing MIBs from the generator.yml (because I don't need them, I just need the default) and generated a new snmp.yml
I again added the config (SNMPv3 with username) but I still get the same error:

`ERRO[0001] Error scraping target XXXX: Error walking target XXXX: recover: runtime error: integer divide by zero  source="collector.go:126"`

**Comment by brian-brazil** [comment]
Does anyone have one of these boxes available publicly for debugging?

**Comment by arthepsy** [comment]
I just got the same issue, debugged and resolved it. With current code base, You have to set `priv_password` to something, even if it's not being used, therefore, @eskornev, here's the fast fix (_add this to configuration_):
`priv_password: none`

**Longer story**:
Full error message is: 
```
Error walking target X: recover: runtime error: integer divide by zero  source="collector.go:126"
```

which corresponds to https://github.com/prometheus/snmp_exporter/blob/v0.6.0/collector.go#L126:
```
124	pdus, err := ScrapeTarget(c.target, c.module)
125	if err != nil {
126		log.Infof("Error scraping target %s: %s", c.target, err)
```

and https://github.com/prometheus/snmp_exporter/blob/v0.6.0/collector.go#L76
```
76			pdus, err = snmp.BulkWalkAll(subtree)
77		}
78		if err != nil {
79			return nil, fmt.Errorf("Error walking target %s: %s", snmp.Target, err)
```

So this happens in external library [snmp](github.com/soniah/gosnmp) by using [recover](https://golang.org/pkg/builtin/#recover) function. **Let's debug this**.

First, find all the places where `recover` is being used:
```
$ cd ~/go/src/github.com/prometheus/snmp_exporter
$ grep -A1 -nrH 'recover(' vendor/github.com/soniah/gosnmp/
vendor/github.com/soniah/gosnmp/v3.go:65:               if e := recover(); e != nil {
vendor/github.com/soniah/gosnmp/v3.go-66-                      fmt.Printf("recover: %v\n", e)
--
vendor/github.com/soniah/gosnmp/marshal.go:254:         if e := recover(); e != nil {
vendor/github.com/soniah/gosnmp/marshal.go-255-                        err = fmt.Errorf("recover: %v", e)
```
Using [delve](https://github.com/derekparker/delve) debugger, set breakpoints in those places and run the `snmp_exporter`:
```
$ ~/go/bin/dlv exec ./snmp_exporter
Type 'help' for list of commands.
(dlv) b /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/v3.go:66
Breakpoint 1 set at 0x7aa9e8 for github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp.(*SnmpPacket).authenticate.func1() /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/v3.go:66
(dlv) b /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/marshal.go:255
Breakpoint 2 set at 0x7aa908 for github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp.(*GoSNMP).send.func1() /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/marshal.go:255
(dlv) c
INFO[0000] Starting snmp exporter (version=0.6.0, branch=HEAD, revision=4388d6815791d6d616098f899110c9dca354028c)  source="main.go:125"
INFO[0000] Build context (go=go1.8.3, user=root@fd9cde4d0842, date=20170822-11:04:46)  source="main.go:126"
INFO[0000] Listening on :9116                            source="main.go:205"
```

Now, when error is triggered, it hits breakpoint:
```
> github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp.(*GoSNMP).send.func1() /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/marshal.go:255 (hits goroutine(12):1 total:1) (PC: 0x7aa908)
   250: //
   251: // all sends wait for the return packet, except for SNMPv2Trap
   252: func (x *GoSNMP) send(packetOut *SnmpPacket, wait bool) (result *SnmpPacket, err error) {
   253:         defer func() {
   254:                 if e := recover(); e != nil {
=> 255:                         err = fmt.Errorf("recover: %v", e)
   256:                 }
   257:         }()
   258:
   259:         if x.Conn == nil {
   260:                 return nil, fmt.Errorf("&GoSNMP.Conn is missing. Provide a connection or use Connect()")
```
And backtrace gives enough information about the culprit:
```
(dlv) bt
 0  0x00000000007aa908 in github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp.(*GoSNMP).send.func1
    at /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/marshal.go:255
 1  0x00000000004571b8 in runtime.call32
    at /usr/local/go/src/runtime/asm_amd64.s:514
 2  0x000000000042a79f in runtime.gopanic
    at /usr/local/go/src/runtime/panic.go:489
 3  0x00000000004294fe in runtime.panicdivide
    at /usr/local/go/src/runtime/panic.go:42
 4  0x00000000007a574e in github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp.md5HMAC
    at /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/v3_usm.go:192
(..)
```
Which corresponds to https://github.com/prometheus/snmp_exporter/blob/v0.6.0/vendor/github.com/soniah/gosnmp/v3_usm.go#L192:
```
   186  func md5HMAC(password string, engineID string) []byte {
   187          comp := md5.New()
   188          var pi int // password index
   189          for i := 0; i < 1048576; i += 64 {
   190                  var chunk []byte
   191                  for e := 0; e < 64; e++ {
   192                          chunk = append(chunk, password[pi%len(password)])
   193                          pi++
   194                  }
   195                  comp.Write(chunk)
   196          }
```

Long story short, here's the reason and output of hitting breakpoint in culprit line:
```
b /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/v3_usm.go:192
(dlv) c
> github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp.md5HMAC() /go/src/github.com/prometheus/snmp_exporter/vendor/github.com/soniah/gosnmp/v3_usm.go:192 (hits goroutine(34):2 total:2) (PC: 0x7a5639)
   187:         comp := md5.New()
   188:         var pi int // password index
   189:         for i := 0; i < 1048576; i += 64 {
   190:                 var chunk []byte
   191:                 for e := 0; e < 64; e++ {
=> 192:                         chunk = append(chunk, password[pi%len(password)])
   193:                         pi++
   194:                 }
   195:                 comp.Write(chunk)
   196:         }
   197:         compressed := comp.Sum(nil)
(dlv) print password
""
(dlv) print pi%len(password)
Command failed: runtime error: integer divide by zero
```

**Comment by brian-brazil** [comment]
Thanks for the detailed debugging @arthepsy! Would you like to send a PR upstream to fix this?

**Comment by arthepsy** [comment]
@brian-brazil sure; but as `snmp_exporter` depends on upstream and one will have to wait for fix to be merged, isn't it worth to also include workaround here?

**Comment by brian-brazil** [comment]
It can be worked around by users, so I don't there's a need for a temporary hack on our end.
