### ISSUE TITLE
FR: Custom community string

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#19]
For various policy and compartmentalization reasons, we need to use different community strings for some targets. Being able to specify them in prometheus.yml and passing them onto the exporter would be a lot easier than spawning an arbitrary number of snmp exporters.

**Comment by brian-brazil** [comment]
This was added in #7

**Comment by RichiH** [comment]
Unless I am mistaken, that's one community per exporter, not one community per target.

**Comment by brian-brazil** [comment]
The snmp exporter only currently supports one configuration, which supports setting the community. At some point it'll support multiple configurations similar to the blackbox exporter.

There's no plans to pass in paramaters beyond which configuration to use, especially not secrets.
