### ISSUE TITLE
Negative value for ifHCOutUcastPkts

### ISSUE THREAD

**Issue by sirtux** [prometheus/snmp_exporter#191]
Hi,

I have the snmp_exporter running against a Juniper MX (Junos 17.1) with the default snmp.yaml and I'm getting a negative value for ifHCOutUcastPkts:

# HELP ifHCOutUcastPkts 
# TYPE ifHCOutUcastPkts counter
ifHCOutUcastPkts{ifDescr="ae0"} -1.241915e+06

I verified on the router that the value is indeed not negative:

teichhorn@DE-ES-001-03-10-01-re0> show snmp mib get 1.3.6.1.2.1.31.1.1.1.11.629
ifHCOutUcastPkts.629 = 18446744073708309388

I am not sure if this is a problem handling 64bit values, 
or howto debug this further - running the exporter with log level debug doesn't give any hints to what is happening behind the curtains.

If you need any help from my side, please don't hesitate to ask.

Thanks,
Tom

**Comment by brian-brazil** [comment]
That sounds like a bug on our side, that'd be of type Counter64 which cannot be negative.

Incidentally, I find it very likely that your device is buggy to be able to produce such a large number.

**Comment by sirtux** [comment]
Hi Brian, 

you are correct as this is a known bug (I got confirmation 5 minutes ago) that such a huge number is reported, but still in the valid range. 

I plan to upgrade my routers to a fixed release on monday, I assume we can test this with some mockup or shall I try to retain the old release for further testing?

**Comment by brian-brazil** [comment]
I don't think there's any need to retain the old release. We'll need to mock it somehow anyway for unittesting.

**Comment by RichiH** [comment]
Could we run into a bug of the 2^53 mitigation here? SNMP exporter mangles
that data before exposing.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by brian-brazil** [comment]
No, we'd just lose precision if that were the case. Most likely this is being stored in an int64 rather than a uint64 somewhere.

**Comment by sirtux** [comment]
I did some testing with the soniah/gosnmp itself and its example code:

tom@jumper:~/gopath/src/github.com/soniah/gosnmp$ ./example
0: oid: .1.3.6.1.2.1.31.1.1.1.11.629 number: 18446744073708268813

So it seems the library handles it correctly.

**Comment by brian-brazil** [comment]
That saves me time, thanks.
