### ISSUE TITLE
I don't know how to write generator.yml file, can you tell me

### ISSUE THREAD

**Issue by huangfupeng** [prometheus/snmp_exporter#194]
I don't know how to write generator.yml  file, can you tell me
Does the generator.yml get in the device manufacturer's documentation？

**Comment by SuperQ** [comment]
The SNMP exporter is documented in the [README](https://github.com/prometheus/snmp_exporter/blob/master/generator/README.md).

There is also a good [tutorial](http://devopstarter.info/snmp-exporter-generator-tutorial/).

In addition, usage questions are best asked via our [community](https://prometheus.io/community/).

**Comment by huangfupeng** [comment]
ok! thank you !
