### ISSUE TITLE
Implement multiple configurations similar to blackbox_exporter

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#20]
Different devices are able to return different metrics. While implementing https://github.com/prometheus/snmp_exporter/issues/19 would already reduce the number of required exporters significantly, a way to pass a custom capability/model label from `prometheus.yml` which is then mapped to a preconfigured OID set in snmp_exporter would allow to reduce the number of running exporters once again.

**Comment by brian-brazil** [comment]
This will be covered by multiple configurations when that's implemented.

**Comment by RichiH** [comment]
Might make sense to keep it open as a marker, but I am ambivalent.

**Comment by brian-brazil** [comment]
Fixed by #21
