### ISSUE TITLE
[Feature Request] Handle `OID not increasing:`

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#208]
I am currently hitting https://gist.github.com/RichiH/51c49e0c2abe6c38367e3a7f9051adb6 .

The vendor thinks this is OK: http://kb.fortinet.com/kb/documentLink.do?externalID=FD39616

And snmp_exporter tells me: error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error walking fqdn: OID not increasing: .1.3.6.1.2.1.2.2.1.1.13

This is not a problem with snmp_exporter, but it exists in the real world. Is there a way to work around this?

**Comment by brian-brazil** [comment]
As far as I'm aware this is out of spec for SNMP. I don't think it's possible to do anything about it, as we can't know what the next oid is.

**Comment by RichiH** [comment]
The manual way is "cut one off, increase the lower by one", i.e.

`1.3.6.1.2.1.2.2.1.1.13` -> `1.3.6.1.2.1.2.2.1.2`

but I can understand if that's out of scope and closed.

**Comment by brian-brazil** [comment]
We don't know that there isn't a .14. This is a request for upstream in any case, as we just use that library.
