### ISSUE TITLE
prometheus failed to read snmp_exporter generated content

### ISSUE THREAD

**Issue by qubic** [prometheus/snmp_exporter#211]
SNMP target is Windows7.
Prometheus show error: invalid label value "Bluetooth \xc9豸(RFCOMM Э\xd2\xe9 TDI)\x00"

I have checked the output of snmp_exporter , it's encoding is gb2312, the actual content is: 

> ifAdminStatus{ifDescr="Bluetooth 设备(RFCOMM 协议 TDI) "} 2

**Comment by brian-brazil** [comment]
This is a bug in Windows 7, ifDescr must be ASCII as it is a DisplayString.

**Comment by brian-brazil** [comment]
This is now caught by the exporter.
