### ISSUE TITLE
snmp_exporter - community password with numbers

### ISSUE THREAD

**Issue by mowatten** [prometheus/snmp_exporter#213]
Hi,

I have a snmp community password with numbers in it, and that won't work with the snmp_exporter. Is this something that can be fixed?

### Host operating system: output of `uname -a`
Linux prometheus 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter, version 0.4.0 (branch: master, revision: 0a00acbf61971015b6475441d741ce59ad2ba26d)
  build user:       root@ea8b44ce07e1
  build date:       20170606-13:39:44
  go version:       go1.8.3
### What device/snmpwalk OID are you using?
default

**Comment by brian-brazil** [comment]
Can you give the general form of the community string? Does it start with a number for example?

**Comment by mowatten** [comment]
Yes, it starts with a number and ending with some random text.

Example: 9afasaceafa

**Comment by brian-brazil** [comment]
Try putting it in quotes, this is a yaml issue.
