### ISSUE TITLE
hex instead of text

### ISSUE THREAD

**Issue by cchance27** [prometheus/snmp_exporter#216]
I'm trying to set the value of a label to the sysName but for some reason it appears to be showing as a hex value in the output instead of the normal text. 

The mib shows it as an octetstring, but i've tried defining as octetstring and displaystring but always it outputs as Name="0xFFFFFFFFFFFFFFFFFF" for example 

my metric config is basically just repeats of 

 metrics:
   - name: rxByte
     oid: 1.3.6.1.2.1.31.1.1.1.6.1
     type: counter
     indexes:
       - labelname: Name
         type: OctetString
     lookups:
       - labels: [Name]
         labelname: Name
         oid: 1.3.6.1.2.1.1.5

**Comment by brian-brazil** [comment]
Only configurations generated by the generator are supported, if you use that it'll produce a good config.
