### ISSUE TITLE
All modules use the community string of the final module

### ISSUE THREAD

**Issue by andrewd-sterling** [prometheus/snmp_exporter#220]
snmp_exporter uses the community string of the final snmp.yml module for *all* modules.
### Host operating system: output of `uname -a`
CentOS Linux release 7.3.1611 (Core)
3.10.0-514.26.2.el7.x86_64

### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter, version 0.5.0 (branch: master, revision: 4a6cefde688765abba45f8110c219e8e512da3f1)
  build user:       root@localhost
  build date:       20170815-23:37:12
  go version:       go1.8.3

### What did you do that produced an error?
I have multiple communities, but only the last module works. Everything else times out. To reproduce, try making two modules the first of which has the *wrong* community:
generator.yml
```YAML
modules:
  default:
    walk:
      - sysORTable
    version: 2
    auth:
      community: wrongcommunity
  default2:
    walk:
      - sysORTable
    version: 2
    auth:
      community: public
```
Run snmp_exporter with the generated snmp.yml, and query the same device with both modules. You'd expect the first module to fail, and the second to succeed. Instead they both succeed. If you reverse the correct/incorrect communities, now they will both fail.

```
$ curl -sw '' 'http://localhost:9116/snmp?module=default&target=192.168.0.100' | egrep '^snmp_scrape_pdus_returned'
DEBU[0223] Scraping target '192.168.0.100' with module 'default'  source="main.go:73"
DEBU[0223] Walking target "192.168.0.100" subtree "1.3.6.1.2.1.1.9"  source="collector.go:71"
DEBU[0223] Walk of target "192.168.0.100" subtree "1.3.6.1.2.1.1.9" completed in 3.43896ms  source="collector.go:81"
DEBU[0223] Scrape of target '192.168.0.100' with module 'default' took 0.004030 seconds  source="main.go:84"
snmp_scrape_pdus_returned 24
$ curl -sw '' 'http://localhost:9116/snmp?module=default2&target=192.168.0.100' | egrep '^snmp_scrape_pdus_returned'
DEBU[0229] Scraping target '192.168.0.100' with module 'default2'  source="main.go:73"
DEBU[0229] Walking target "192.168.0.100" subtree "1.3.6.1.2.1.1.9"  source="collector.go:71"
DEBU[0229] Walk of target '192.168.0.100" subtree "1.3.6.1.2.1.1.9" completed in 3.525606ms  source="collector.go:81"
DEBU[0229] Scrape of target '192.168.0.100' with module 'default2' took 0.004137 seconds  source="main.go:84"
snmp_scrape_pdus_returned 24
```

**Comment by brian-brazil** [comment]
Does the generated snmp.yml appear correct?

**Comment by andrewd-sterling** [comment]
The generated snmp.yml is currently suffering from #219, so all the communities are literally `<secret>`. When I correct that manually, I get the behavior here.

**Comment by andrewd-sterling** [comment]
Confirmed fixed on master, thank you!
