### ISSUE TITLE
main.go:120:14: cannot use kingpin.CommandLine (type *kingpin.Application) as type *flag.FlagSet in argument to "github.com/prometheus/common/log".AddFlags

### ISSUE THREAD

**Issue by nim-nim** [prometheus/snmp_exporter#230]
+ GOPATH=/builddir/build/BUILD/snmp_exporter-0.6.0/_build:/usr/share/gocode
+ go build
# _/builddir/build/BUILD/snmp_exporter-0.6.0
./main.go:120:14: cannot use kingpin.CommandLine (type *kingpin.Application) as type *flag.FlagSet in argument to "github.com/prometheus/common/log".AddFlags

Installed:
  go-compilers-golang-compiler.x86_64 1-14.fc27                                                                                                   
  golang.x86_64 1.9-1.fc28                                                                                                                        
  golang-github-alecthomas-template-devel.noarch 0-0.9.gita0175ee.fc28.llt                                                                        
  golang-github-alecthomas-units-devel.noarch 0-0.7.git2efee85.fc28.llt                                                                           
  golang-github-prometheus-client-devel.noarch 0.9.0-0.5.git353b8c3.fc28.llt                                                                      
  golang-github-prometheus-common-devel.noarch 0-0.9.git195bde7.fc27                                                                              
  golang-github-soniah-gosnmp-devel.noarch 1.10-0.11.git80f670d.fc28.llt                                                                          
  golang-gopkg-alecthomas-kingpin2-devel.noarch 2.2.5-4.fc28.llt                                                                                  
  golang-gopkg-yaml-devel-v2.noarch 1-18.fc27                                                                                                     
  net-snmp-devel.x86_64 1:5.7.3-27.fc28                                                                                                           
  elfutils-devel.x86_64 0.170-1.fc27                                                                                                              
  elfutils-libelf-devel.x86_64 0.170-1.fc27                                                                                                       
  golang-bin.x86_64 1.9-1.fc28                                                                                                                    
  golang-bitbucket-kardianos-osext-devel.noarch 0-0.18.git9b883c5.fc27                                                                            
  golang-bitbucket-ww-goautoneg-devel.noarch 0-0.13.git75cd24fc2f2c.fc27                                                                          
  golang-github-Sirupsen-logrus-devel.noarch 0.8.4-9.fc27                                                                                         
  golang-github-beorn7-perks-devel.noarch 0-0.12.git4c0e845.fc27                                                                                  
  golang-github-bugsnag-bugsnag-go-devel.noarch 1.0.4-8.fc27                                                                                      
  golang-github-bugsnag-panicwrap-devel.noarch 1.1.0-0.6.gitaceac81.fc27                                                                          
  golang-github-davecgh-go-spew-devel.noarch 1.1.1-0.2.gita476722.fc28.mllt                                                                       
  golang-github-julienschmidt-httprouter-devel.noarch 1.1-8.fc27                                                                                  
  golang-github-matttproud-protobuf-extensions-devel.noarch 1.0.0-5.fc28.llt                                                                      
  golang-github-pmezard-go-difflib-devel.noarch 0-0.9.git792786c.fc28                                                                             
  golang-github-prometheus-client-model-devel.noarch 0.0.3-0.6.git6f38060.fc28.llt                                                                
  golang-github-prometheus-procfs-devel.noarch 0-0.19.gitfcdb11c.fc27                                                                             
  golang-github-stretchr-objx-devel.noarch 0-0.12.git1a9d0bb.fc28                                                                                 
  golang-github-stretchr-testify-devel.noarch 1.1.4-1.fc28.mllt                                                                                   
  golang-golangorg-net-devel.noarch 0-0.40.git1c05540.fc28                                                                                        
  golang-golangorg-text-devel.noarch 0-0.21.git3bd178b.fc28                                                                                       
  golang-googlecode-goprotobuf-devel.noarch 0-0.30.git24f28ae.fc28                                                                                
  golang-src.noarch 1.9-1.fc28

**Comment by brian-brazil** [comment]
This appears to be a Debian specific problem, as you are not following our build instructions. I'd suggest taking it up with them.

**Comment by nim-nim** [comment]
It's not Debian, it's Fedora, but the problem is probably in the maze of unversionned prometheus repositories, since kingpin does actually provide actual releases and the build is using the latest one.

And anyway the snmp exporter requires building against the system libs, That's why the build uses the system infra.

**Comment by brian-brazil** [comment]
> And anyway the snmp exporter requires building against the system libs, That's why the build uses the system infra.

This is due to your setup, not the snmp exporter itself.

**Comment by nim-nim** [comment]
Actually, it builds fine in the golang 1.8 environment, but not in the golang 1.9 one (with the same versions of prometheus repositories and kingpin), so it looks like golang 1.9 is more picky about this code than golang 1.8
