### ISSUE TITLE
time="2017-09-27T19:18:25Z" level=fatal msg="Unknown index type string" source="collector.go:390"

### ISSUE THREAD

**Issue by Mrcortez34** [prometheus/snmp_exporter#232]
https://github.com/prometheus/snmp_exporter/blob/c5c5164ffcab5c814b93ec077af303a87d52b10d/collector.go#L390

When I updated to the latest V0.6.0 I get this issues (time="2017-09-27T19:18:25Z" level=fatal msg="Unknown index type string" source="collector.go:390"). But it works just fine with V0.2.0

Prometheus is running on Coreos v4.12.14 and being managed by K8s 1.6

Has this error been encountered before?

**Comment by brian-brazil** [comment]
Can you try this with the latest generator and exporter? Several breaking changes have happened since then.

**Comment by Mrcortez34** [comment]
Latest Generator & exporter?

**Comment by Mrcortez34** [comment]
To my knowledge everything is up to date other than snmp_exporter which only works on 0.2.0

**Comment by brian-brazil** [comment]
Can you share your generator config?

**Comment by Mrcortez34** [comment]
`apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter
data:
  snmp.yml: |-
    default:
      walk:
      - 1.3.6.1.2.1.1.3
      - 1.3.6.1.2.1.2
      - 1.3.6.1.2.1.31.1.1
      metrics:
      - name: sysUpTime
        oid: 1.3.6.1.2.1.1.3
        type: gauge
      - name: ifNumber
        oid: 1.3.6.1.2.1.2.1
        type: gauge
      - name: ifIndex
        oid: 1.3.6.1.2.1.2.2.1.1
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: string
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifType
        oid: 1.3.6.1.2.1.2.2.1.3
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifMtu
        oid: 1.3.6.1.2.1.2.2.1.4
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifSpeed
        oid: 1.3.6.1.2.1.2.2.1.5
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifAdminStatus
        oid: 1.3.6.1.2.1.2.2.1.7
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOperStatus
        oid: 1.3.6.1.2.1.2.2.1.8
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifLastChange
        oid: 1.3.6.1.2.1.2.2.1.9
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInOctets
        oid: 1.3.6.1.2.1.2.2.1.10
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.11
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInNUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.12
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInDiscards
        oid: 1.3.6.1.2.1.2.2.1.13
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInErrors
        oid: 1.3.6.1.2.1.2.2.1.14
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInUnknownProtos
        oid: 1.3.6.1.2.1.2.2.1.15
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutOctets
        oid: 1.3.6.1.2.1.2.2.1.16
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.17
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutNUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.18
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutDiscards
        oid: 1.3.6.1.2.1.2.2.1.19
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutErrors
        oid: 1.3.6.1.2.1.2.2.1.20
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutQLen
        oid: 1.3.6.1.2.1.2.2.1.21
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifName
        oid: 1.3.6.1.2.1.31.1.1.1.1
        type: string
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.2
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifInBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.3
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.4
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifOutBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.5
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCInOctets
        oid: 1.3.6.1.2.1.31.1.1.1.6
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCInUcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.7
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCInMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.8
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCInBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.9
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCOutOctets
        oid: 1.3.6.1.2.1.31.1.1.1.10
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCOutUcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.11
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCOutMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.12
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHCOutBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.13
        type: counter
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifLinkUpDownTrapEnable
        oid: 1.3.6.1.2.1.31.1.1.1.14
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifHighSpeed
        oid: 1.3.6.1.2.1.31.1.1.1.15
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifPromiscuousMode
        oid: 1.3.6.1.2.1.31.1.1.1.16
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifConnectorPresent
        oid: 1.3.6.1.2.1.31.1.1.1.17
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifAlias
        oid: 1.3.6.1.2.1.31.1.1.1.18
        type: string
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
      - name: ifCounterDiscontinuityTime
        oid: 1.3.6.1.2.1.31.1.1.1.19
        type: gauge
        indexes:
        - labelname: ifDescr
          type: Integer
        lookups:
        - labels:
          - ifDescr
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
    default_ifindex:
      walk:
      - 1.3.6.1.2.1.1.3
      - 1.3.6.1.2.1.2
      - 1.3.6.1.2.1.31.1.1
      metrics:
      - name: sysUpTime
        oid: 1.3.6.1.2.1.1.3
        type: gauge
      - name: ifNumber
        oid: 1.3.6.1.2.1.2.1
        type: gauge
      - name: ifIndex
        oid: 1.3.6.1.2.1.2.2.1.1
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: string
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifType
        oid: 1.3.6.1.2.1.2.2.1.3
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifMtu
        oid: 1.3.6.1.2.1.2.2.1.4
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifSpeed
        oid: 1.3.6.1.2.1.2.2.1.5
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifAdminStatus
        oid: 1.3.6.1.2.1.2.2.1.7
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOperStatus
        oid: 1.3.6.1.2.1.2.2.1.8
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifLastChange
        oid: 1.3.6.1.2.1.2.2.1.9
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInOctets
        oid: 1.3.6.1.2.1.2.2.1.10
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.11
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInNUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.12
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInDiscards
        oid: 1.3.6.1.2.1.2.2.1.13
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInErrors
        oid: 1.3.6.1.2.1.2.2.1.14
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInUnknownProtos
        oid: 1.3.6.1.2.1.2.2.1.15
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutOctets
        oid: 1.3.6.1.2.1.2.2.1.16
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.17
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutNUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.18
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutDiscards
        oid: 1.3.6.1.2.1.2.2.1.19
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutErrors
        oid: 1.3.6.1.2.1.2.2.1.20
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutQLen
        oid: 1.3.6.1.2.1.2.2.1.21
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifName
        oid: 1.3.6.1.2.1.31.1.1.1.1
        type: string
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.2
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifInBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.3
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.4
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifOutBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.5
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCInOctets
        oid: 1.3.6.1.2.1.31.1.1.1.6
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCInUcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.7
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCInMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.8
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCInBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.9
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCOutOctets
        oid: 1.3.6.1.2.1.31.1.1.1.10
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCOutUcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.11
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCOutMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.12
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHCOutBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.13
        type: counter
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifLinkUpDownTrapEnable
        oid: 1.3.6.1.2.1.31.1.1.1.14
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifHighSpeed
        oid: 1.3.6.1.2.1.31.1.1.1.15
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifPromiscuousMode
        oid: 1.3.6.1.2.1.31.1.1.1.16
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifConnectorPresent
        oid: 1.3.6.1.2.1.31.1.1.1.17
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifAlias
        oid: 1.3.6.1.2.1.31.1.1.1.18
        type: string
        indexes:
        - labelname: ifIndex
          type: Integer
      - name: ifCounterDiscontinuityTime
        oid: 1.3.6.1.2.1.31.1.1.1.19
        type: gauge
        indexes:
        - labelname: ifIndex
          type: Integer
    default_ifname:
      walk:
      - 1.3.6.1.2.1.1.3
      - 1.3.6.1.2.1.2
      - 1.3.6.1.2.1.31.1.1
      metrics:
      - name: sysUpTime
        oid: 1.3.6.1.2.1.1.3
        type: gauge
      - name: ifNumber
        oid: 1.3.6.1.2.1.2.1
        type: gauge
      - name: ifIndex
        oid: 1.3.6.1.2.1.2.2.1.1
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: string
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifType
        oid: 1.3.6.1.2.1.2.2.1.3
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifMtu
        oid: 1.3.6.1.2.1.2.2.1.4
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifSpeed
        oid: 1.3.6.1.2.1.2.2.1.5
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifAdminStatus
        oid: 1.3.6.1.2.1.2.2.1.7
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOperStatus
        oid: 1.3.6.1.2.1.2.2.1.8
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifLastChange
        oid: 1.3.6.1.2.1.2.2.1.9
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInOctets
        oid: 1.3.6.1.2.1.2.2.1.10
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.11
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInNUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.12
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInDiscards
        oid: 1.3.6.1.2.1.2.2.1.13
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInErrors
        oid: 1.3.6.1.2.1.2.2.1.14
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInUnknownProtos
        oid: 1.3.6.1.2.1.2.2.1.15
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutOctets
        oid: 1.3.6.1.2.1.2.2.1.16
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.17
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutNUcastPkts
        oid: 1.3.6.1.2.1.2.2.1.18
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutDiscards
        oid: 1.3.6.1.2.1.2.2.1.19
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutErrors
        oid: 1.3.6.1.2.1.2.2.1.20
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutQLen
        oid: 1.3.6.1.2.1.2.2.1.21
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifName
        oid: 1.3.6.1.2.1.31.1.1.1.1
        type: string
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.2
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifInBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.3
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.4
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifOutBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.5
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCInOctets
        oid: 1.3.6.1.2.1.31.1.1.1.6
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCInUcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.7
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCInMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.8
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCInBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.9
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCOutOctets
        oid: 1.3.6.1.2.1.31.1.1.1.10
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCOutUcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.11
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCOutMulticastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.12
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHCOutBroadcastPkts
        oid: 1.3.6.1.2.1.31.1.1.1.13
        type: counter
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifLinkUpDownTrapEnable
        oid: 1.3.6.1.2.1.31.1.1.1.14
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifHighSpeed
        oid: 1.3.6.1.2.1.31.1.1.1.15
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifPromiscuousMode
        oid: 1.3.6.1.2.1.31.1.1.1.16
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifConnectorPresent
        oid: 1.3.6.1.2.1.31.1.1.1.17
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifAlias
        oid: 1.3.6.1.2.1.31.1.1.1.18
        type: string
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1
      - name: ifCounterDiscontinuityTime
        oid: 1.3.6.1.2.1.31.1.1.1.19
        type: gauge
        indexes:
        - labelname: ifName
          type: Integer
        lookups:
        - labels:
          - ifName
          labelname: ifName
          oid: 1.3.6.1.2.1.31.1.1.1.1`

**Comment by brian-brazil** [comment]
That was not produced a recent generator.

**Comment by Mrcortez34** [comment]
That is the file that I have at the moment. So I should up date that file then?

**Comment by Mrcortez34** [comment]
thank you for than information. I will update the file and let you know if that has resolved the issue.

**Comment by Mrcortez34** [comment]
Brian,

After I updated that file I was able to update the version and no issues. Thank you for your help.
