### ISSUE TITLE
support  net-snmp extending ?

### ISSUE THREAD

**Issue by or0or1** [prometheus/snmp_exporter#236]
my snmp configure  file has so  much net-snmp extending configuration, such as  the describe of the article.

https://docs-old.fedoraproject.org/en-US/Fedora/26/html/System_Administrators_Guide/sect-System_Monitoring_Tools-Net-SNMP-Extending.html

snmp-exporter support  it?  if support, any example ? thank you very much.

**Comment by SuperQ** [comment]
GitHub issues should only be used for feature requests and bug reports. For general discussions and support, please refer to our [community](https://prometheus.io/community/).
