### ISSUE TITLE
Need a way to configure listening interface

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus/snmp_exporter#24]
While there is a way to configure the listening port, there is currently now way to define on which interface the http server listen. It defaults to listening on all interfaces.

My usual config is to run the snmp_exporter on the same machine than promotheus, and I don't want to expose the running service all over the network, so I'd like to make it listen on 127.0.0.1 only.

**Comment by paurullan** [comment]
I know this is not your answer but as a workaround I would recommend you to deploy the prometheus+snmp_exporter under something like docker-compose. That way you would be able to hide the exporter and make it accessible to prometheus.

I hope the maintainer answers your question.

**Comment by brian-brazil** [comment]
This will come with #53
