### ISSUE TITLE
FluidFS OctetString not displayed correctly

### ISSUE THREAD

**Issue by arivano** [prometheus/snmp_exporter#240]
[snmp.yml.txt](https://github.com/prometheus/snmp_exporter/files/1430029/snmp.yml.txt)
Linux 3.10.0-514.26.2.el7.x86_64
snmp_exporter version 0.7.0
snmp.yml created by generator using FluidFS-MIB.txt (provided by vendor). snmp.yml attached.

snmpwalk output:
snmpwalk -Os -c public -v 2c 172.xxx.xxx.xxx 1.3.6.1.4.1.674.11000.2000.200.1.38.1
enterprises.674.11000.2000.200.1.38.1 = STRING: "364875083.09"

Prometheus output:
\# HELP nASPoolTotalCapacityMB Total NAS pool capacity (in MBs) - 1.3.6.1.4.1.674.11000.2000.200.1.38.1
\
[snmp.yml.txt](https://github.com/prometheus/snmp_exporter/files/1430037/snmp.yml.txt)
\# TYPE nASPoolTotalCapacityMB gauge
nASPoolTotalCapacityMB{nASPoolTotalCapacityMB="0x3336343837353038332E3039"} 1

MIB attached for reference.

Using the MIB in iReasoning returns expected results.
[FluidFS-MIB.txt](https://github.com/prometheus/snmp_exporter/files/1430017/FluidFS-MIB.txt)

**Comment by brian-brazil** [comment]
This rendering is correct, that's an OctetString of unknown character encoding so we can't do anything with it other than render it as a hexstring.

This is an incorrect use of SNMP by the vendor - it follows the letter of the spec but not the spirit. The vendor should also have selected DisplayString to indicate it was ASCII, rather than a binary string. Or even better used an actual number rather than a string.

Look at the regex_extracts feature.

**Comment by arivano** [comment]
I tried with the regex_extracts yesterday without any success and couldn't find any good examples to copy that matched this use case.
Are you able to provide some pointers on how we could workaround the vendor's misteps?

**Comment by brian-brazil** [comment]
Try changing the mib to use a DisplayString

**Comment by arivano** [comment]
I added:
            DisplayString
                    FROM RFC1213-MIB;
To the MIB and changed the SYNTAX to Display string and now I get the correct string in Prometheus but it charts as a 1, presumably because it's a string?
# HELP nASPoolTotalCapacityMB Total NAS pool capacity (in MBs) - 1.3.6.1.4.1.674.11000.2000.200.1.38.1
# TYPE nASPoolTotalCapacityMB gauge
nASPoolTotalCapacityMB{nASPoolTotalCapacityMB="364875083.09"} 1

Is this where regex_extracts can help?

**Comment by brian-brazil** [comment]
Yes, regex_extracts helps from this point.

**Comment by arivano** [comment]
Not an issue then, but are you able to provide some guidance on how to use regex_extracts in this use case?

**Comment by arivano** [comment]
Perfect, regex_extracts now gives usable data. Thks!

**Comment by SuperQ** [comment]
@arivano Maybe file an upstream issue with Dell to fix the MIB.

**Comment by maozi07** [comment]
@arivano I face the same problem can you give some example,how to solve the problem,THX

**Comment by SuperQ** [comment]
@maozi07 
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by maozi07** [comment]
OK! thank you
