### ISSUE TITLE
Lookups question - IfDescr instead of ifIndex

### ISSUE THREAD

**Issue by zarkoc** [prometheus/snmp_exporter#242]
Hi All,

Im trying to set the ifDescr instead of ifIndex to be the index. But it seems that when I that hange that the exporter is looking at the value of the IfDescr instead of the Label of IfDescr.

The error is that I get when i configure the lookup, and try to use that module:
`collected metric ifOutNUcastPkts label:<name:"ifDescr" value:"" > counter:<value:0 >  was collected before with the same name and label values`

When I use a module without the lookup configured (so the ifIndex is used by default) this is how the ifDescr looks like:

```
#HELP ifDescr 
#TYPE ifDescr gauge
ifDescr{ifDescr="1 Gigabit - Level",ifIndex="1"} 1
```
So the value is "1" for all of the ifDescr, by the label name is unique for each of them.

Am I doing something wrong?

Thanks,
Zarko

**Comment by brian-brazil** [comment]
If you're getting that error then ifDescr is not unique, and thus can't be used as a lookup.

**Comment by zarkoc** [comment]
Hi Brian,

Just to see if I understand correctly, so the issue is not that the value of ifDescr is equal 1, but that the label ifDescr is same?

tx
Zarko

**Comment by brian-brazil** [comment]
Yes.
