### ISSUE TITLE
Unable to specify community in generator

### ISSUE THREAD

**Issue by AnalogGodOfBandwidth** [prometheus/snmp_exporter#253]
### Host operating system: output of `uname -a`
uname -a
Linux localhost.localdomain 4.13.13-300.fc27.x86_64 #1 SMP Wed Nov 15 15:47:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Fedora release 27

### snmp_exporter version: output of `snmp_exporter -version`

commit 885c82591460f550702022ab2a2379fbb71a9667

### Config

generator.yml

```
modules:
  auth:
    community: mrtg
  # Default IF-MIB interfaces table with ifIndex.
  if_mib:
    walk: [sysUpTime, interfaces, ifXTable]
  # Interfaces if ifAlias is unique.
  if_mib_ifalias:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        new_index: ifAlias
  # Interfaces if ifDescr is unique.
  if_mib_ifdescr:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        new_index: ifDescr
  # Interfaces if ifName is unique.
  if_mib_ifname:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        new_index: 1.3.6.1.2.1.31.1.1.1.1 # ifName
```
### What did you do that produced an error?

./generator generate --log.level="debug"

### What did you expect to see?
INFO[0001] Config written to snmp.yml                    source="main.go:57"
### What did you see instead?
```
./generator generate --log.level="debug"
INFO[0000] Loading MIBs from $HOME/.snmp/mibs:/usr/share/snmp/mibs  source="net_snmp.go:109"
WARN[0001] NetSNMP reported 527 parse errors             source="main.go:72"
WARN[0001] Can't find augmenting oid tokenRingMLStatsEntry for tokenRingMLStats2Entry  source="tree.go:58"
WARN[0001] Can't find augmenting oid tokenRingPStatsEntry for tokenRingPStats2Entry  source="tree.go:58"
WARN[0001] Can't find augmenting oid rptrPortEntry for ciscoRptrPortEntry  source="tree.go:58"
FATA[0001] Error parsing yml config: unknown fields in module: community  source="main.go:25"
```

**Comment by brian-brazil** [comment]
That's creating a module called auth, check your indentation.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
