### ISSUE TITLE
OCTET STRING didn't get converted into STRING

### ISSUE THREAD

**Issue by smallgreenhorse** [prometheus/snmp_exporter#254]
### snmp_exporter version: output of `snmp_exporter -version`

./snmp_exporter --version
snmp_exporter, version 0.8.0 (branch: HEAD, revision: 17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)
  build user:       root@57f813d2791a
  build date:       20171120-12:36:57
  go version:       go1.9.2

### What device/snmpwalk OID are you using?
snL4RealServerStatisticName and other which have syntax set to L4ServerName

### If this is a new device, please link to the MIB(s).
FOUNDRY-SN-SW-L4-SWITCH-GROUP-MIB

### What did you expect to see?
I was expecting to see:

snL4RealServerStatisticName{snL4RealServerStatisticName="smtp-2", snL4RealServerStatisticRealIP="10.65.240.102"} 1

that would match what snmpwalk returns :

FOUNDRY-SN-SW-L4-SWITCH-GROUP-MIB::snL4RealServerStatisticName.10.65.240.102 = STRING: "smtp02"

### What did you see instead?

But the snL4RealServerStatisticName didn't get converted into string :

snL4RealServerStatisticName{snL4RealServerStatisticName="0x736D74703032",snL4RealServerStatisticRealIP="10.65.240.102"} 1

**Comment by brian-brazil** [comment]
This is correct, it's an `OCTET STRING {1..32}` - which is to say an arbitrary binary string. If that's actually an ASCII or UTF-8 string, then the MIB needs to specify that.

**Comment by smallgreenhorse** [comment]
Is there a way to make snmp-exporter convert it to a STRING like snmpwalk does ?

**Comment by brian-brazil** [comment]
Not at the moment, I'd suggest asking your vendor to fix their mib.

**Comment by FoxBoxsnet** [comment]
In my case, I changed the following code and it worked

Source of the file: [Netdisco / Mibs / [7ee5e0] /foundry/FOUNDRY-SN-SW-L4-SWITCH-GROUP-MIB.mib](https://sourceforge.net/p/netdisco/mibs/ci/7ee5e0cb01666ae755f1a7e95fa156556819bc67/tree/foundry/FOUNDRY-SN-SW-L4-SWITCH-GROUP-MIB.mib)


[FOUNDRY-SN-SW-L4-SWITCH-GROUP-MIB.patch.txt](https://github.com/prometheus/snmp_exporter/files/1638601/FOUNDRY-SN-SW-L4-SWITCH-GROUP-MIB.patch.txt)
