### ISSUE TITLE
Authentication failed during snmpv3 authNoPriv getBulk operation

### ISSUE THREAD

**Issue by albertdabrowski** [prometheus/snmp_exporter#257]
I'm trying to poll juniper router. Everything works fine in SNMPv1 or v3 in noAuthNoPriv mode.
The problem occurs in authNoPriv or authPriv with failed message
`Error walking target 192.168.233.30: Incoming packet is not authentic, discarding source="collector.go:126"`
It seems problem occurs during security negotiation. Checked how it works on wireshark
1) Client: Get-Request
2) Agent: Report with 
`Result: Error 1.3.6.1.6.3.15.1.1.4.0
authoritativeEngineId=xxxxxvalue, authoritativeEngineBoot=0, authoritativeEngineTime=0`
3) Client: GetBulkRequest specific oid with authoritativeEngineId set
4) Agent: Report with 
`Result: Error 1.3.6.1.6.3.15.1.1.2.0
authoritativeEngineId=xxxxxvalue, authoritativeEngineBoot=1, authoritativeEngineTime=0` 
5) Client:  Send again GetBulkRequest with `authoritativeEngineBoot=0, authoritativeEngineTime=0`
6) Repeats steps 4/5 so cannot complete it
In case of `snmpbulkget` the difference is that in step 5 client set authoritativeEngineTime to 1 and authoritativeEngineBoot to 0. Then negotiation completes and values are received.

I am doing these tests with simulation toolkit which seems to have EngineBoot set to 1. 

Is this upstream problem of gosnmp or I'm doing something incorrect. For me seems that gosnmp has problem with handling properly `usmStatsNotInTimeWindows` error (`1.3.6.1.6.3.15.1.1.2.0`). Anyway if this is normal handshake procedure then it should not work for anybody or all devices return engineBoot set to 0. Any hints?

### Host operating system: output of `uname -a`
`Ubuntu 14, net-snmp v. 5.7.2`

### snmp_exporter version: output of `snmp_exporter -version`
`snmp_exporter, version 0.8.0 (branch: HEAD, revision: 17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)
  build user:       root@57f813d2791a
  build date:       20171120-12:36:57
  go version:       go1.9.2`

**Comment by brian-brazil** [comment]
That sounds like something for upstream.

**Comment by wanrui** [comment]
you resolved this problems?
s1. use snmpwalk like ` snmpwalk -v3 -l authPriv -u xxx -a MD5 -A "xxxxxx" -x DES -X "xxxxxxxxx" 1.2.3.4` have some correct data return 

s2. use snmp_exporter like below ,it's not work 
 
```
if_mib:
  version: 3
  auth:
    username: xxx 
    password: xxxxxx
    auth_protocol: MD5
    priv_protocol: DES
    security_level: authPriv
    priv_password: xxxxxxxxx
  get:
    - 1.3.6.1.2.1.1.3
  metrics:
    - name: sysUpTime
      oid: 1.3.6.1.2.1.1.3
      type: gauge
```
we have something error  debug log on snmp_exporter

```
Incoming packet is not authentic, discarding
```
use tcpdump to scrap the info like that 

![image](https://user-images.githubusercontent.com/12728608/50008047-e3dc5580-ffed-11e8-8b5c-65c9efab0c05.png)

when to snmp_exporter to test authentic ,find that 
```
snmp.msgAuthenticationParameters 00:00:00:00:00:00:00:00:00:00:00:00
```
is not correct

**Comment by adrianschneider94** [comment]
Hi there!

I have the same problem. Package not authentic with authNoPriv and authPriv. Works with other software.

Did any of you resolve this?

**Comment by 6forcs** [comment]
我也有同样的问题
