### ISSUE TITLE
invalid UTF-8 label value

### ISSUE THREAD

**Issue by HyperDevil** [prometheus/snmp_exporter#259]
uname: 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
Target: Mikrotik Cloudcore router
MIB: http://download2.mikrotik.com/Mikrotik.mib
snmp_exporter version: 0.8.0 AMD64
Error message:
```
invalid UTF-8 label value
prometheus[420]: level=warn ts=2018-01-12T13:57:23.022072428Z caller=scrape.go:673 component="target manager" scrape_pool=snmp-mikrotik target="http://127.0.0.1:9116/snmp?module=mikrotikExperimentalModule&target=10.0.2.1" msg="append failed" err="invalid UTF-8 label value"
```

Generator config:
```
 mikrotikExperimentalModule:
    walk: [sysUpTime, interfaces, mtxrHealth, mtxrSystem, mtxrInterfaceStats, mtxrWireless, mtxrDHCP, mtxrOptical, mikrotik, mtXMetaInfo, mtXRouterOsGroups]
```

snmp.yml file:
https://pastebin.com/sauds104

**Comment by brian-brazil** [comment]
This is probably your device claiming that a string is DisplayString or SnmpAdminString but it not actually being ASCII/UTF-8. I'd suggest confirming this, and filing a bug with your vendor.

**Comment by HyperDevil** [comment]
Is there any way to find out which string?

**Comment by brian-brazil** [comment]
I'd suggest bisecting the metrics in the snmp.yml to narrow it down.

**Comment by HyperDevil** [comment]
The strange thing is that the output directly via curl from snmp_exporter works fine.
Is there any way in can grep or awk the output from snmp_exporter to find the culprit?

**Comment by brian-brazil** [comment]
Curl wouldn't be doing UTF-8 validation. I doubt grep or awk have the features required, I usually spot these sort of things by hand.

**Comment by HyperDevil** [comment]
You can close the issue.
