### ISSUE TITLE
Documentation needs an example with no hardcoded IP

### ISSUE THREAD

**Issue by jpds** [prometheus/snmp_exporter#260]
I have `snmp-exporter` running as a container within my Kubernetes cluster. I've tried adding my scrape target for the SNMP endpoints, however the documentation in the `README.md` in this repo only has an example of running the SNMP exporter with a static IP.

How does one use the exporter within Kubernetes reliably re: pod IP addresses and service discovery?

**Comment by SuperQ** [comment]
This is a Kubernetes issue, you need to declare a Kubernetes service for the exporter and use the service name in the prometheus config.

**Comment by SuperQ** [comment]
I thought this over a bit, and you're right, the documentation is not clear enough.  See #261.
