### ISSUE TITLE
Cross-Indexed SNMP lookups (IETF ENTITY-MIB)

### ISSUE THREAD

**Issue by cron2** [prometheus/snmp_exporter#262]
@richih asked me to bring this here, so I'm doing it.  Possibly related to #227, but maybe a different twist of madness.

We have Cisco ASR9000 routers that are fairly inconvenient to monitor wrt environmental values, namely "temperature", "power draw", "incoming power feeds".  First you have to read an IETF standard table (ENTITY-MIB) to find "what is in this box?", then use the table index from there to read values and scaling factor.

It's explained better than I could in this posting from Cisco, with examples:

https://supportforums.cisco.com/t5/service-providers-documents/asr9000-monitoring-power-supply-information-via-snmp/ta-p/3109984

so... what's the best way to get these values into Prometheus in a meaningful way?

**Comment by brian-brazil** [comment]
Can you provide sample snmpwalk output for the relevant objects?

**Comment by cron2** [comment]
Hi,

here's examples for temperature (3 indexes picked out of 200 lines in ENTITY-MIB)

ENTITY-MIB::entPhysicalDescr.2217939 = STRING: Transceiver Temperature Sensor
ENTITY-MIB::entPhysicalDescr.6762374 = STRING: Hot Temperature SensorHotspot1
ENTITY-MIB::entPhysicalDescr.29683569 = STRING: Inlet Temperature SensorInlet1

ENTITY-MIB::entPhysicalVendorType.2217939 = OID: CISCO-ENTITY-VENDORTYPE-OID-MIB::cevSensorTransceiverTemp
ENTITY-MIB::entPhysicalVendorType.6762374 = OID: CISCO-ENTITY-VENDORTYPE-OID-MIB::cevSensor.54
ENTITY-MIB::entPhysicalVendorType.29683569 = OID: CISCO-ENTITY-VENDORTYPE-OID-MIB::cevSensorModuleInletTemp

ENTITY-MIB::entPhysicalName.2217939 = STRING: temperature 0/0/2/3
ENTITY-MIB::entPhysicalName.6762374 = STRING: temperature 0/0/CPU0
ENTITY-MIB::entPhysicalName.29683569 = STRING: temperature 0/RSP0/CPU0

so with that, you know what you're dealing with, and then you go to CISCO-ENTITY-SENSOR-MIB tables with the corresponding index for the values:

CISCO-ENTITY-SENSOR-MIB::entSensorType.2217939 = INTEGER: celsius(8)
CISCO-ENTITY-SENSOR-MIB::entSensorScale.2217939 = INTEGER: units(9)
CISCO-ENTITY-SENSOR-MIB::entSensorPrecision.2217939 = INTEGER: 1
CISCO-ENTITY-SENSOR-MIB::entSensorValue.2217939 = INTEGER: 252
CISCO-ENTITY-SENSOR-MIB::entSensorStatus.2217939 = INTEGER: ok(1)
CISCO-ENTITY-SENSOR-MIB::entSensorValueTimeStamp.2217939 = Timeticks: (0) 0:00:00.00
CISCO-ENTITY-SENSOR-MIB::entSensorValueUpdateRate.2217939 = INTEGER: 30 seconds
CISCO-ENTITY-SENSOR-MIB::entSensorMeasuredEntity.2217939 = INTEGER: 10906792

CISCO-ENTITY-SENSOR-MIB::entSensorType.6762374 = INTEGER: celsius(8)
CISCO-ENTITY-SENSOR-MIB::entSensorScale.6762374 = INTEGER: units(9)
CISCO-ENTITY-SENSOR-MIB::entSensorPrecision.6762374 = INTEGER: 1
CISCO-ENTITY-SENSOR-MIB::entSensorValue.6762374 = INTEGER: 348
CISCO-ENTITY-SENSOR-MIB::entSensorStatus.6762374 = INTEGER: ok(1)
CISCO-ENTITY-SENSOR-MIB::entSensorValueTimeStamp.6762374 = Timeticks: (0) 0:00:00.00
CISCO-ENTITY-SENSOR-MIB::entSensorValueUpdateRate.6762374 = INTEGER: 0 seconds
CISCO-ENTITY-SENSOR-MIB::entSensorMeasuredEntity.6762374 = INTEGER: 18788073

CISCO-ENTITY-SENSOR-MIB::entSensorType.29683569 = INTEGER: celsius(8)
CISCO-ENTITY-SENSOR-MIB::entSensorScale.29683569 = INTEGER: units(9)
CISCO-ENTITY-SENSOR-MIB::entSensorPrecision.29683569 = INTEGER: 1
CISCO-ENTITY-SENSOR-MIB::entSensorValue.29683569 = INTEGER: 250
CISCO-ENTITY-SENSOR-MIB::entSensorStatus.29683569 = INTEGER: ok(1)
CISCO-ENTITY-SENSOR-MIB::entSensorValueTimeStamp.29683569 = Timeticks: (0) 0:00:00.00
CISCO-ENTITY-SENSOR-MIB::entSensorValueUpdateRate.29683569 = INTEGER: 0 seconds
CISCO-ENTITY-SENSOR-MIB::entSensorMeasuredEntity.29683569 = INTEGER: 52690955

**Comment by brian-brazil** [comment]
From a quick look at the MIBs that should just work currently, the the tables share an index.

**Comment by LukeSiX** [comment]
- 1.3.6.1.2.1.47.1.1.1.1.2 #entPhysicalDescr
    - 1.3.6.1.2.1.47.1.1.1.1.7 #entPhysicalName
    - 1.3.6.1.2.1.47.1.1.1.1.13 #entPhysicalModelName
    - 1.3.6.1.4.1.9.9.91.1.1.1.1.1 #entSensorType
    - 1.3.6.1.4.1.9.9.91.1.1.1.1.2 #entSensorScale
    - 1.3.6.1.4.1.9.9.91.1.1.1.1.3 #entSensorPrecision
    - 1.3.6.1.4.1.9.9.91.1.1.1.1.4 #entSensorValue
    - 1.3.6.1.4.1.9.9.91.1.1.1.1.5 #entSensorStatus

----

    - name: entSensorValue
      oid: 1.3.6.1.4.1.9.9.91.1.1.1.1.4
      indexes:
        - labelname: entPhysicalIndex
          type: Integer32
      lookups:
        - labels: [entPhysicalIndex]
          labelname: entPhysicalDescr
          oid: 1.3.6.1.2.1.47.1.1.1.1.2
        - labels: [entPhysicalIndex]
          labelname: entPhysicalName
          oid: 1.3.6.1.2.1.47.1.1.1.1.7
        - labels: [entPhysicalIndex]
          labelname: entPhysicalModelName
          oid: 1.3.6.1.2.1.47.1.1.1.1.13
        - labels: [entPhysicalIndex]
          labelname: entPhysicalType
          oid: 1.3.6.1.4.1.9.9.91.1.1.1.1.1
        - labels: [entPhysicalIndex]
          labelname: entSensorScale
          oid: 1.3.6.1.4.1.9.9.91.1.1.1.1.2
        - labels: [entPhysicalIndex]
          labelname: entSensorPrecision
          oid: 1.3.6.1.4.1.9.9.91.1.1.1.1.3

    - name: entSensorStatus
      oid: 1.3.6.1.4.1.9.9.91.1.1.1.1.5
      indexes:
        - labelname: entPhysicalIndex
          type: Integer32
      lookups:
        - labels: [entPhysicalIndex]
          labelname: entPhysicalDescr
          oid: 1.3.6.1.2.1.47.1.1.1.1.2
        - labels: [entPhysicalIndex]
          labelname: entPhysicalName
          oid: 1.3.6.1.2.1.47.1.1.1.1.7
        - labels: [entPhysicalIndex]
          labelname: entPhysicalModelName
          oid: 1.3.6.1.2.1.47.1.1.1.1.13
        - labels: [entPhysicalIndex]
          labelname: entPhysicalType
          oid: 1.3.6.1.4.1.9.9.91.1.1.1.1.1
        - labels: [entPhysicalIndex]
          labelname: entSensorScale
          oid: 1.3.6.1.4.1.9.9.91.1.1.1.1.2

**Comment by RichiH** [comment]
This is possible with current snmp_exporter.

**Comment by RajKiranS** [comment]
Hello,

Here is a snippet from snmp.yml that's edited by hand which is working for me.

temp_arista:
  walk:
  - 1.3.6.1.2.1.47.1.1.1.1.2
  - 1.3.6.1.2.1.99.1.1.1.4
  metrics:
  - name: entPhySensorValue
    oid: 1.3.6.1.2.1.99.1.1.1.4
    type: gauge
    help: The most recent measurement obtained by the agent for this sensor - 1.3.6.1.2.1.99.1.1.1.4
    indexes:
    - labelname: entPhysicalIndex
      type: Integer32
    lookups:
    **- labels: [entPhysicalIndex]
      labelname: entPhysicalDescr**
      oid: 1.3.6.1.2.1.47.1.1.1.1.2
      type: DisplayString

My question is, how do I specify it in generator.yml so that I obtain the above.

**Comment by SuperQ** [comment]
@RajKiranS This can already be handled with the generator, as long as you apply [this patch](https://github.com/SuperQ/tools/blob/master/snmp_exporter/tree.go.patch).  I made a quick [example generator.yml](https://github.com/SuperQ/tools/tree/master/snmp_exporter/arista).

**Comment by RajKiranS** [comment]
Thanks a lot, @SuperQ . That is what I wanted.
