### ISSUE TITLE
Running binaries produces results, running as docker image - "No connection could be made because the target machine actively refused it"

### ISSUE THREAD

**Issue by kaytrance** [prometheus/snmp_exporter#267]
This may be a bug, I am not really sure.

So if I download binaries and run just them 

```
./snmp_exporter --config.file="mysnmp.yml" --log.level="debug" --web.listen-address=":9110"
```

prometheus can scrape metrics just fine. However if I run, basically, the same but as docker container, every target fails with the following error in prometheus:
```
Get http://<snmp_exporter_location>:9110/snmp?module=if_mib&target=<targer_url>: dial tcp <snmp_exporter_location_ip>:9110: connectex: No connection could be made because the target machine actively refused it.
```

and in condole:

```
INFO[0025] Error scraping target <target_host>: Error connecting to target <target_host>: Error establishing connection to host: dial udp: lookup<target_host> on <target_ip>:53: read udp 172.17.0.2:35959-><target_ip>:53: i/o timeout
  source="collector.go:126"
```

Here's the command I use to launch exporter:

```
docker run --rm -it -v `pwd`/mysnmp.yml:/etc/snmp_exporter/mysnmp.yml -p 9110:9110 --name snmp-exporter prom/snmp-exporter --log.level="debug" --config.file="/etc/snmp_exporter/mysnmp.yml" --web.listen-address=":9110"
```

**Comment by brian-brazil** [comment]
Sounds like a firewall.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by kaytrance** [comment]
maybe I have to expose/forward some udp ports when running snmp_exporter via docker?
