### ISSUE TITLE
Auth problem with generator and snmp v3

### ISSUE THREAD

**Issue by barciella** [prometheus/snmp_exporter#269]
### Host operating system: output of `uname -a`
Linux ip-10-0-193-31 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter, version 0.8.0 (branch: HEAD, revision: 17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)
  build user:       root@57f813d2791a
  build date:       20171120-12:36:57
  go version:       go1.9.2

### What device/snmpwalk OID are you using?
Cisco. 

When I generate using the template and generator it will put my auth info at the bottom of the snmp.yml file like this:

version: 3
  max_repetitions: 25
  retries: 3
  timeout: 100s
  auth:
    community: public
    security_level: AuthPriv
    username: "myuser"
    password: "mypass"
    auth_protocol: SHA
    priv_protocol: DES
    priv_password: "mypass""

And I get a timeout when I try to connect to scrape.

If I paste the auth etc bellow if_mib like this:

if_mib:
  version: 3
  max_repetitions: 25
  retries: 3
  timeout: 100s
  auth:
    community: public
    security_level: AuthPriv
    username: "myuser"
    password: "mypass"
    auth_protocol: SHA
    priv_protocol: DES
    priv_password: "mypass""

It targets the cisco switch but the result is:

HELP snmp_scrape_duration_seconds Total SNMP time scrape took (walk and processing).
TYPE snmp_scrape_duration_seconds gauge
snmp_scrape_duration_seconds 0.179921859
HELP snmp_scrape_pdus_returned PDUs returned from walk.
TYPE snmp_scrape_pdus_returned gauge
snmp_scrape_pdus_returned 0
HELP snmp_scrape_walk_duration_seconds Time SNMP walk/bulkwalk took.
TYPE snmp_scrape_walk_duration_seconds gauge
snmp_scrape_walk_duration_seconds 0.179806379

I am not sure what I am doing wrong. snmpbulkwalk works without issues. Even for specific OID.

snmpbulkwalk -v3 -l authPriv -u "myuser" -a SHA -A "mypass"  -x DES -X "mypass" 172.19.195.201 1.3.6.1.2.1.31.1.1.1.15

**Comment by brian-brazil** [comment]
That's not a timeout, the device returned nothing.

**Comment by barciella** [comment]
How odd. The timeout happens when I use the snmp.yml with the auth at the bottom of the file:

./snmp_exporter --log.level=debug
INFO[0000] Starting snmp exporter (version=0.8.0, branch=HEAD, revision=17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)  source="main.go:125"
INFO[0000] Build context (go=go1.9.2, user=root@57f813d2791a, date=20171120-12:36:57)  source="main.go:126"
INFO[0000] Listening on :9116                            source="main.go:205"
DEBU[0003] Scraping target '172.19.195.221' with module 'if_mib'  source="main.go:73"
DEBU[0003] Walking target "172.19.195.221" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0005] Scraping target '172.19.195.201' with module 'if_mib'  source="main.go:73"
DEBU[0005] Walking target "172.19.195.201" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0015] Scraping target '172.19.195.201' with module 'if_mib'  source="main.go:73"
DEBU[0015] Walking target "172.19.195.201" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0025] Scraping target '172.19.195.201' with module 'if_mib'  source="main.go:73"
DEBU[0025] Walking target "172.19.195.201" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0035] Scraping target '172.19.195.201' with module 'if_mib'  source="main.go:73"
DEBU[0035] Walking target "172.19.195.201" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0045] Scraping target '172.19.195.201' with module 'if_mib'  source="main.go:73"
DEBU[0045] Walking target "172.19.195.201" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0055] Scraping target '172.19.195.201' with module 'if_mib'  source="main.go:73"
DEBU[0055] Walking target "172.19.195.201" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
INFO[0063] Error scraping target 172.19.195.221: Error walking target 172.19.195.221: Request timeout (after 3 retries)  source="collector.go:126"
DEBU[0063] Scrape of target '172.19.195.221' with module 'if_mib' took 60.001294 seconds  source="main.go:84"
DEBU[0065] Scraping target '172.19.195.201' with module 'if_mib'  source="main.go:73"
DEBU[0065] Walking target "172.19.195.201" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
INFO[0065] Error scraping target 172.19.195.201: Error walking target 172.19.195.201: Request timeout (after 3 retries)  source="collector.go:126"
DEBU[0065] Scrape of target '172.19.195.201' with module 'if_mib' took 60.001248 seconds  source="main.go:84"


Should I have the snmp v3 auth config under all the if_mib modules?

**Comment by barciella** [comment]
By the way. If I configure my switch with a public community without credentials it works as expected. My issue is with the snmp v3 credentials.

**Comment by brian-brazil** [comment]
You'll have to tcpdump to figure out what the difference is.

**Comment by barciella** [comment]
Hah the main problem was: security_level: AuthPriv. It is supposed to be authPriv.

And I had to put the code inside the if_mib module. Outside it doesn't work.
