### ISSUE TITLE
SNMP Secret

### ISSUE THREAD

**Issue by alythemonk** [prometheus/snmp_exporter#27]
Hey Team,

Is there a way to specify a secret to the snmp_exporter ? I want to monitor a bunch of Cisco switches and they won't talk to the exporter if the secret is not provided ... Thanks.

Cheers,

ASD.

**Comment by brian-brazil** [comment]
You can specify the `community` in the module in your snmp.yml. The default is "public".

**Comment by alythemonk** [comment]
Thanks ! This worked, do you happen to know if there is a way to import mibs into snmp.yml ? I see the current context is using OIDs

**Comment by brian-brazil** [comment]
Currently it has to be done by hand. MIB parsing libraries in python are kinda non-existent unfortunately.
