### ISSUE TITLE
Question regarding SMART attributes via SNMP of a Synology NAS.

### ISSUE THREAD

**Issue by PatrickSchuster** [prometheus/snmp_exporter#271]
### Host operating system:
Inside a docker container. Dockerfile of version v0.8.0 (quay.io/prometheus/busybox:latest)

### snmp_exporter version:
Version v0.8.0

### What device/snmpwalk OID are you using?
A Synology NAS: RS814RP+

### If this is a new device, please link to the MIB(s).
I found the MIBs here: https://global.download.synology.com/download/Document/MIBGuide/Synology_MIB_File.zip

Hi,

thank you for working on such a great and very useful tool.

Currently, I face some difficulties trying to monitor a Synology NAS. I have successfully exported several SNMP statistics and displayed them properly using Grafana, however I have some difficulties with S.M.A.R.T.

I'm trying to retrieve the following S.M.A.R.T. attributes of the built in HDDs:

* Reallocated_Sector_Ct
* Reported_Uncorrect
* Command_Timeout
* Current_Pending_Sector
* Uncorrectable Sector Count

I want them in a format similar to the attached screenshot, where you can see the diskSMARTable. using a MIB browser on a Mac. 
However, I am only interested in the diskSMARTInfoDeviceName (e.g. /dev/sda), the diskSMARTAttrName (e.g. Reallocated_Sector_Ct) and the diskSMARTAttrRaw value (e.g. 0).
![mib_browser](https://user-images.githubusercontent.com/3827255/36851491-9fa2bc4a-1d69-11e8-9044-978c422083f9.png)

I think that this can be configured inside the generator.yml but I am not sure how to do so.

The next issue I am dealing with is that the string values diskSMARTInfoDeviceName and diskSMARTAttrName are hex encoded. I would like to have plain strings (like it can be seen in the MIB browser). Could anybody tell me how I can convert these?
E.g. 0x5265616C6C6F63617465645F536563746F725F4374 is the hex representation of Reallocated_Sector_Ct (see the following screenshot for a sample Prometheus output)
![prometheus_reallocated_sector_ct](https://user-images.githubusercontent.com/3827255/36851819-7cf60764-1d6a-11e8-9d33-41e86531f9db.PNG)

In the end, I want to display these S.M.A.R.T. attributes in Grafana as well, but I have trouble since I can't get the attributes in my desired format.

Any guides are greatly appreciated. Thank you!

**Comment by brian-brazil** [comment]
> Could anybody tell me how I can convert these?

It sounds like your vendor has put in the MIB that these are arbitrary binary strings or OCTET STRING so we don't know how to decode them, and hex is the only safe option. You'll need to ask your vendor if these should actually be a DisplayString or SnmpAdminString, as we can't presume that.

The rest is a matter of selecting the oids you want in the generator.yml.

**Comment by PatrickSchuster** [comment]
> The rest is a matter of selecting the oids you want in the generator.yml.

Could you give me an example on how to do this? 
I can't seem to do this using generator.yml. Instead, I tried to change snmp.yml like so:

```
- name: diskSMARTTable
    oid: 1.3.6.1.4.1.6574.5.1.1.3
    type: DisplayString
    help: disk SMART table
    indexes:
    - labelname: devIndex
      type: gauge
    lookups:
    - labels:
      - devName
      labelname: devName
      oid: 1.3.6.1.4.1.6574.5.1.1.2
      type: DisplayString
    - labels:
      - rawVal
      labelname: rawVal
      oid: 1.3.6.1.4.1.6574.5.1.1.8
      type: DisplayString
```
Which results in this:
```
...
diskSMARTTable{devIndex="21",devName="",diskSMARTTable="Raw_Read_Error_Rate",rawVal=""} 1
diskSMARTTable{devIndex="22",devName="",diskSMARTTable="Spin_Up_Time",rawVal=""} 1
diskSMARTTable{devIndex="23",devName="",diskSMARTTable="Start_Stop_Count",rawVal=""} 1
diskSMARTTable{devIndex="24",devName="",diskSMARTTable="Reallocated_Sector_Ct",rawVal=""} 1
diskSMARTTable{devIndex="25",devName="",diskSMARTTable="Seek_Error_Rate",rawVal=""} 1
diskSMARTTable{devIndex="26",devName="",diskSMARTTable="Power_On_Hours",rawVal=""} 1
diskSMARTTable{devIndex="27",devName="",diskSMARTTable="Spin_Retry_Count",rawVal=""} 1
diskSMARTTable{devIndex="28",devName="",diskSMARTTable="Calibration_Retry_Count",rawVal=""} 1
diskSMARTTable{devIndex="29",devName="",diskSMARTTable="Power_Cycle_Count",rawVal=""} 1
diskSMARTTable{devIndex="3",devName="",diskSMARTTable="Start_Stop_Count",rawVal=""} 1
diskSMARTTable{devIndex="30",devName="",diskSMARTTable="Power-Off_Retract_Count",rawVal=""} 1
...
```
Albeit close to what I want, I'm still not able retrieve a device name (devName) and the raw value (rawVal) belonging to the given devIndex.

I realize that changing the snmp.yml is probably not the way to go since it will be generated, but so far that's the best I've got.

Thank you!

**Comment by brian-brazil** [comment]
> I realize that changing the snmp.yml is probably not the way to go since it will be generated, but so far that's the best I've got.

You need to use the generator. Hand-writing snmp.yml is only possible for those with deep knowledge of both SNMP and the snmp exporter.

**Comment by PatrickSchuster** [comment]
> You need to use the generator.

Okay. I can access these attributes individually using my current generator.yml:
Here's an example to emphasize my point. I have to manually do the following to find out which devices currently report a value for "Reallocated_Sector_Ct" (0x5265616C6C6F63617465645F536563746F725F4374):
1. Query diskSMARTAttrName{diskSMARTAttrName="0x5265616C6C6F63617465645F536563746F725F4374"}
-> This will tell me that indices diskSMARTInfoIndex="24", "4", "41" and "61" for which such an attribute exists.
2. Query diskSMARTInfoDevName{diskSMARTInfoIndex="24"}
-> This will tell me that the device "0x2F6465762F736462" (/dev/sdb) maps to this index.
3. Query diskSMARTAttrRaw{diskSMARTInfoIndex="24"}
-> This will reveal the value I am interested in (in this case 0, which tells me that Reallocated_Sector_Ct is not problematic).

Is that a valid approach or is there some way of doing that in the generator.yml. So far, I couldn't find an example for doing something like that.

Thank you!

**Comment by SuperQ** [comment]
What you probably want is detailed in https://github.com/prometheus/snmp_exporter/issues/186.  I wrote a hack patch in https://github.com/prometheus/snmp_exporter/pull/263, it works but I haven't had the time to clean it up.
