### ISSUE TITLE
The system cannot place a conversion string, causing the value to not be obtained

### ISSUE THREAD

**Issue by xilu0** [prometheus/snmp_exporter#274]
hi,
  The value returned by my device is a string that is recorded as a label, where I can handle the string as a number?Please tell me where I can finally handle it, thank you very much.
`[root@test prometheus]# snmpwalk -v 2c -c sangfor 192.168.8.1  1.3.6.1.4.1.35047.1.6
SNMPv2-SMI::enterprises.35047.1.6.1.0 = STRING: "4.32"
SNMPv2-SMI::enterprises.35047.1.6.2.0 = STRING: "4.62"
SNMPv2-SMI::enterprises.35047.1.6.3.0 = STRING: "4.48"`

**Comment by SuperQ** [comment]
Github issues are reserved for bugs and feature requests.  Please use our [community]()
