### ISSUE TITLE
See what we can do about InetAddress

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/snmp_exporter#290]
To understand it you need an InetAddressType, which is in another object. Our model is that each object is independent so making that work might not be practical.

**Comment by RichiH** [comment]
Somewhat hamfisted, but IPv4 vs IPv6 can be done based on size. That's far from clean, though.

**Comment by brian-brazil** [comment]
That doesn't work, as they could also be DNS names of that length.

**Comment by sgissi** [comment]
Can't these be forcibly overridden by the user (e.g. like we can parse floats out of strings in some cases)?

**Comment by brian-brazil** [comment]
Nope, they can vary from table instance to table instance.

**Comment by RichiH** [comment]
Valid domain names and fqdns can not end on [.:]\d+

For now that is

Sent by mobile; please excuse my brevity.

**Comment by brian-brazil** [comment]
That doesn't help us. The data is binary, so a valid IP can also be a DNS name.

**Comment by brian-brazil** [comment]
Per https://tools.ietf.org/html/rfc2851#section-3 the Type is required to be just before the InetAddress, which should make this a bit more plausible.
