### ISSUE TITLE
Problem compiling the generator.

### ISSUE THREAD

**Issue by albertocastro63** [prometheus/snmp_exporter#295]
### Host operating system: output of `uname -a`

Linux prometheus-v01 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.10.0 (branch: HEAD, revision: 5c997da9e9ee79dc6c72641f02d204f4eafc14b3)
  build user:       root@922afdf4a276
  build date:       20180509-11:49:31
  go version:       go1.10.2

### What did you do that produced an error?

I was following the instructions to compile the snmp configuration generator:

```
sudo apt-get install build-essential libsnmp-dev snmp-mibs-downloader  # Debian-based distros
go get github.com/prometheus/snmp_exporter/generator
cd ${GOPATH-$HOME/go}/src/github.com/prometheus/snmp_exporter/generator
go build
```
After I executed:
```
go get github.com/prometheus/snmp_exporter/generator
```
I got an error.

### What did you expect to see?

Not sure, probably nothing, in other words the command succeeded.

### What did you see instead?

The following error:
```
# github.com/prometheus/snmp_exporter/generator
src/github.com/prometheus/snmp_exporter/generator/tree.go:247: undefined: sort.Slice
```

**Comment by brian-brazil** [comment]
You need a newer version of Go.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by albertocastro63** [comment]
Thank you very much and in the future I will send the request to the right place. All the best, Alberto
