### ISSUE TITLE
Is there support for community string?

### ISSUE THREAD

**Issue by chngtrn** [prometheus/snmp_exporter#306]
Hi. We leverage community string on our smpd services. Is there support for community string? If yes, could you please provide example?

Thanks.

**Comment by SuperQ** [comment]
You can include the community string in the config file. See the [documentation](https://github.com/prometheus/snmp_exporter/tree/master/generator#file-format).

For usage questions/help, please use our [community](https://prometheus.io/community/).  There are many more people there that can help.  GitHub issues are reserved for bug reports and feature requests.

**Comment by chngtrn** [comment]
Thanks.
