### ISSUE TITLE
[Discussion] Indexed community strings per module?

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#309]
CC @cron2

We are seeing more and more situations where we need to ingest network data from customer devices; devices on which the customers have full config access. Obviously, those customers have different community strings, and sharing community strings across different customers is not an option.

Given the network security layers we are dealing with and that a lot of IPs have been grandfathered in, running multiple exporter instances is icky at best.

Our current approach is to have different community strings in different modules and then relabel those customer-specific module names into the commonly defined ones. This kludgy at best.

Having community strings on the wire between Prometheus & snmp_exporter is also a no-go.

All this being considered, I am wondering if an optional index for communities would be a viable approach; community strings would still live in the config and only a changed index position would be on the wire.

**Comment by SuperQ** [comment]
I've suggested the idea that we have an `auth` param separate from the `module` param. to have an index of auth options separate from the actual modules. But @brian-brazil and I looked over how much complication it would add to the config parsing and decided it wasn't worth it.

There are some workarounds that can make things easier. The first component is to use YAML templates to deduplicate the walk/metrics sections.

This was previously discussed in https://github.com/prometheus/snmp_exporter/issues/221#issuecomment-328270980

**Comment by brian-brazil** [comment]
As Ben says, this is something that has been looked at previously and doesn't make sense overall. In exchange for a tiny improvement to a complex scenario, all simpler scenario get harder. Multiple modules as you're currently doing is the recommended way to handle this.
