### ISSUE TITLE
Change Timeout for SNMP_Exporter?

### ISSUE THREAD

**Issue by indgirl6** [prometheus/snmp_exporter#310]
### Host operating system: output of `uname -a`
RedHat Linux 6
### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.11.0 (branch: HEAD, revision: e4591716c29459cb2a12b1bed129af519ad91d23)
  build user:       root@80735d30559d
  build date:       20180530-10:24:52
  go version:       go1.10.2

### What device/snmpwalk OID are you using?
CISCO UCS
# Cicso UCS
  cisco_ucs:
    walk:
      - interfaces
      - ifXTable
      - 1.3.6.1.4.1.9.9.719.1.16  #CISCO-UNIFIED-COMPUTING-ETHER-MIB
      - 1.3.6.1.4.1.9.9.719.1.3   #CISCO-UNIFIED-COMPUTING-ADAPTOR-MIB
      - 1.3.6.1.4.1.9.9.719.1.20  #CISCO-UNIFIED-COMPUTING-FC-MIB
      - 1.3.6.1.4.1.9.9.719.1.9   #CISCO-UNIFIED-COMPUTING-COMPUTE-MIB
      - 1.3.6.1.4.1.9.9.719.1.41  #CISCO-UNIFIED-COMPUTING-PROCESSOR-MIB
      - 1.3.6.1.4.1.9.9.719.1.30  #CISCO-UNIFIED-COMPUTING-MEMORY-MIB
      - 1.3.6.1.4.1.9.9.719.1.46  #CISCO-UNIFIED-COMPUTING-SW-MIB

### What did you do that produced an error?
run snmp_exporter
### What did you expect to see?
expect to see metrics 
### What did you see instead?
log file shows the following:
time="2018-06-22T17:20:36-04:00" level=info msg="Starting snmp exporter (version=0.11.0, branch=HEAD, revision=e4591716c29459cb2a12b1bed129af519ad91d23)" source="main.go:138"
time="2018-06-22T17:20:36-04:00" level=info msg="Build context (go=go1.10.2, user=root@80735d30559d, date=20180530-10:24:52)" source="main.go:139"
time="2018-06-22T17:20:36-04:00" level=info msg="Listening on :9116" source="main.go:218"
time="2018-06-22T17:20:46-04:00" level=debug msg="Scraping target '172.16.148.20' with module 'if_mib'" source="main.go:86"
time="2018-06-22T17:20:46-04:00" level=debug msg="Getting 1 OIDs from target \"172.16.148.20\"" source="collector.go:94"
time="2018-06-22T17:21:01-04:00" level=debug msg="Scraping target '172.16.148.20' with module 'if_mib'" source="main.go:86"
time="2018-06-22T17:21:01-04:00" level=debug msg="Getting 1 OIDs from target \"172.16.148.20\"" source="collector.go:94"
time="2018-06-22T17:21:16-04:00" level=debug msg="Scraping target '172.16.148.20' with module 'if_mib'" source="main.go:86"
time="2018-06-22T17:21:16-04:00" level=debug msg="Getting 1 OIDs from target \"172.16.148.20\"" source="collector.go:94"
time="2018-06-22T17:21:31-04:00" level=debug msg="Scraping target '172.16.148.20' with module 'if_mib'" source="main.go:86"
time="2018-06-22T17:21:31-04:00" level=debug msg="Getting 1 OIDs from target \"172.16.148.20\"" source="collector.go:94"
time="2018-06-22T17:21:46-04:00" level=debug msg="Scraping target '172.16.148.20' with module 'if_mib'" source="main.go:86"
time="2018-06-22T17:21:46-04:00" level=debug msg="Getting 1 OIDs from target \"172.16.148.20\"" source="collector.go:94"
time="2018-06-22T17:21:46-04:00" level=info msg="Error scraping target 172.16.148.20: Error getting target 172.16.148.20: Request timeout (after 3 retries)" source="collector.go:179"
time="2018-06-22T17:21:46-04:00" level=debug msg="Scrape of target '172.16.148.20' with module 'if_mib' took 60.001094 seconds" source="main.go:97"
time="2018-06-22T17:22:01-04:00" level=debug msg="Scraping target '172.16.148.20' with module 'if_mib'" source="main.go:86"
time="2018-06-22T17:22:01-04:00" level=debug msg="Getting 1 OIDs from target \"172.16.148.20\"" source="collector.go:94"
time="2018-06-22T17:22:01-04:00" level=info msg="Error scraping target 172.16.148.20: Error getting target 172.16.148.20: Request timeout (after 3 retries)" source="collector.go:179"
time="2018-06-22T17:22:01-04:00" level=debug msg="Scrape of target '172.16.148.20' with module 'if_mib' took 60.000821 seconds" source="main.go:97"
time="2018-06-22T17:22:16-04:00" level=debug msg="Scraping target '172.16.148.20' with module 'if_mib'" source="main.go:86"
time="2018-06-22T17:22:16-04:00" level=debug msg="Getting 1 OIDs from target \"172.16.148.20\"" source="collector.go:94"
time="2018-06-22T17:22:16-04:00" level=info msg="Error scraping target 172.16.148.20: Error getting target 172.16.148.20: Request timeout (after 3 retries)" source="collector.go:179"
time="2018-06-22T17:22:16-04:00" level=debug msg="Scrape of target '172.16.148.20' with module 'if_mib' took 60.001244 seconds" source="main.go:97"

snmpwalk for the device works fine, but the exporter seems to be timing out while scraping. Is there a way to change  / increase the time out value?

**Comment by tvc-dps** [comment]
We have pretty same problems 
1. with devices with enormous number of metrics (1000 interfaces - multi linecards switches), and
2. with devices located remotely and respond with latency > 50ms
scraping timing out

**Comment by Cougar** [comment]
You can try to use smaller `max_repetitions` than default 25. I had the problem that the reply with 25 entries (strings) didn't fit to one UDP packet and lost somewhere (not sure if it lost in transit because of MTU or device even didn't send it). Anyway lower max_repetitions (10 in my case) fixed that.

**Comment by SuperQ** [comment]
@Cougar I wonder if we could make the retry mechanism in the exporter attempt to backoff the size if a request is lost.
