### ISSUE TITLE
Support getting only a subset of indexes from SNMP table

### ISSUE THREAD

**Issue by veksh** [prometheus/snmp_exporter#311]
It would be nice to be able to get only a part of a large SNMP table, both for performance and convenience reasons. Most obvious use case would be `IF-MIB:ifTable` and `ifXTable`: for a stacked Juniper EX 4*48 switch full table is about 420 entries, and usually monitoring 2 of them (uplinks) is enough. One poll with full ifTable is about 20 s (with significant CPU load), while getting stats on uplink allows to trim this time down to 0.5s. 

Another reason to poll only a subset of interfaces is convenient labels: with interfaces named by `ifAlias` (manually entered description like "uplink-1 ge1/2/1") graphs in Grafana are way easier to read than with `ifDescr` labels (usually physical addresses like "ge-1/2/3").

Currently I have to create a custom module for each device, like

``` yaml
cisco-router-4500
  walk:
    - sysUpTime
    # - ifTable
    # ifTable is  1.3.6.1.2.1.2.2.1.<id>.<ifIndex>
    # - ifIndex: 1
    # - ifDescr: 2
    # - ifSpeed: 5
    # ...
    # - ifOutErrors: 20

    - 1.3.6.1.2.1.2.2.1.1.33
    - 1.3.6.1.2.1.2.2.1.2.33
    - 1.3.6.1.2.1.2.2.1.5.33
    # etc
    - 1.3.6.1.2.1.2.2.1.19.33
    - 1.3.6.1.2.1.2.2.1.20.33
    - 1.3.6.1.2.1.2.2.1.1.45
    - 1.3.6.1.2.1.2.2.1.2.45
```

One obvious way to specify subset is like

``` yaml
- ifTable:
  entries: [1, 2, 5, 7, ..., 20]
  indexes: [33, 45, 46, 49]
```

or slightly better

``` yaml
- ifXTable:
  entries: [ifDescr, ifSpeed, ifInOctets, ...]
  ifIndex: [33, 45, 46, 49]
```

Ideal (but hard to implement) solution would be to specify those restrictions
- per host, as most swithes/routers of same model are different only in that regard 
  (requires passing some additional parameters to snmp_exporter while polling)
- and filtered by value of key-equivalent attribute like ifDescr (that must be decoded to numeric indexes on snmp_exporter startup/reload)

**Comment by SuperQ** [comment]
Walks don't know anything about the labels themselves, so doing walks based on strings isn't going to be easy to implement.

We've talked about more automatic limiting the index range in the walk/bulkwalk, but the current solution is to list all OIDs indexes you wish to pull.

**Comment by brian-brazil** [comment]
Yes, as Ben says you need to list all the OIDs you want. Anything more intelligent is unlikely to happen as that's getting into more complex policy questions which are out of scope. At that stage you need to auto-generate the config.

**Comment by veksh** [comment]
> At that stage you need to auto-generate the config

Yes, that's what I'm doing now (templated it with Ansible), but why not allow entries + indexes in generator config? Simple 

```
- ifTable:
  entries: [1, 2, 5, 7, ..., 20]
  indexes: [33, 45, 46, 49]
```

would be quite enough for most cases and will be easy to implement (I'll try to make it into PR if you wish); skipping `entries` would be a little harder but still possible.

**Comment by brian-brazil** [comment]
That would be a breaking change for all existing users, and the proposed semantics would be fairly complex. I think this is best handled by configuration management for the users who need it, especially when non-trivial table indexes are considered.

**Comment by veksh** [comment]
> That would be a breaking change for all existing users

Not necessary: could have those children only for some entries while keeping compatibility (and testing for the presence of children at run-time).

But yes, it looks pretty ugly and cannot be fixed w/o some pre-processing.
