### ISSUE TITLE
Print log warning on startup when default config is not defined

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#317]
As per https://github.com/prometheus/snmp_exporter/issues/314 we are currently letting users run into a run-time error if they expect a default config to work.

While it can be argued that this is in the scope of a user-defined setup, it's still not a good operational experience.

**Comment by RichiH** [comment]
As an aside, the run-time message via HTTP could be improved, as well.

**Comment by brian-brazil** [comment]
I don't understand what you're proposing. The default config does work.

**Comment by RichiH** [comment]
If the user removes/renames the default config, it's not immediately obvious to them what goes wrong.

This is made worse by the fact that the default module is not called "default" but "if_mib".

**Comment by brian-brazil** [comment]
I continue to not understand what you're proposing. We already log and exist if the file doesn't exist, or return an appropriate http error if the user requests a non-existent module.

**Comment by brian-brazil** [comment]
Okay, now I understand you. That's an valid configuration, and the prometheus.yml snippet is explicit in specifying the module. Nor would this have helped in #314, where the user requested a specific module name.

**Comment by sgissi** [comment]
Sorry for resurrecting this old issue. Warning on the default "if_mib" not being in the config is not particularly helpful, as it is probably happens in most real scenarios. Maybe in a future release we should rename it to "default" or something more reasonable but is a breaking change.

For me, the whole issue here boils down to snmp_exporter logs not showing that the module requested wasn't found (default or otherwise).

@RichiH PR welcome to add the log and close this issue or would you prefer a different approach?

**Comment by RichiH** [comment]
Personally, I would be happy with a "The default module, called 'if_mib', is not defined, please [...]" or something.

**Comment by SuperQ** [comment]
I was going to make a flag for the default module. The other option is we can drop the default handling of the collector, making it required that you specify a module. This would be less confusing.

**Comment by RichiH** [comment]
That would also work, though it would be a breaking change.

**Comment by sgissi** [comment]
> Personally, I would be happy with a "The default module, called 'if_mib', is not defined, please [...]" or something.

Looking back at the original issue, the config had a commented line saying `module: [default]`. If the line was not commented, the error would be equally difficult to find. To me, logging the error during the scrape would make it explicit that the module name doesn't exist and what the default is also.

> I was going to make a flag for the default module. The other option is we can drop the default handling of the collector, making it required that you specify a module. This would be less confusing.

Dropping the default is probably the most reasonable thing to do, but it is a breaking change. If we agree on dropping it, I think we need to deprecate it first somehow. In any case, I strongly believe that we should not only return an HTTP error but also alert the user why scrape failed.

**Comment by brian-brazil** [comment]
I don't think we should start spamming the logs if a Prometheus starts sending scrapes for non-existent modules. The existing error makes it pretty clear what's going on.

**Comment by brian-brazil** [comment]
I think our current behaviour here is fine, we've got appropriate errors we should have and don't have warnings for what are valid configurations.
