### ISSUE TITLE
Header blurb for snmp.yml

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#326]
Generator should put a warning stanza about this config being autogenerated at the top of snmp.yml

**Comment by sgissi** [comment]
@RichiH @brian-brazil Something along the lines of: "# WARNING: This file was auto-generated using snmp_exporter generator, do not edit."? It is a trivial change, I can submit a PR.

**Comment by brian-brazil** [comment]
Yeah, something like that. A PR would be great.
