### ISSUE TITLE
fatal error: net-snmp/net-snmp-config.h: No such file or directory

### ISSUE THREAD

**Issue by ykfq** [prometheus/snmp_exporter#345]
I encountered the error below when generating `snmp.yml`
  ```
  go/src/github.com/prometheus/snmp_exporter/generator/net_snmp.go:19:38: fatal error: net-snmp/net-snmp-config.h: No such file or directory
   #include <net-snmp/net-snmp-config.h>
  ```
  
It is because I need to install the `net-snmp-devel` module, so the Building step in the README of generator should be like this:
  ```
  sudo yum install gcc gcc-g++ make net-snmp net-snmp-utils net-snmp-libs net-snmp-devel
  ```

**Comment by wbh1** [comment]
I experienced the same issue today on RHEL7 and just submitted a PR for it.

**Comment by RichiH** [comment]
Fixed with https://github.com/prometheus/snmp_exporter/pull/347
