### ISSUE TITLE
Error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by tricycleHack** [prometheus/snmp_exporter#346]
Hi,

the problem from #169 seems to be back:

Using version 0.12.0 with docker image.
SNMPv3 with authPriv mode

```
Configured everything in configs accordingly:
version: 3
max_repetitions: 25
retries: 3
timeout: 20s
auth: 
security_level: authPriv
username: user
password: safePassword
auth_protocol: SHA
priv_protocol: AES
priv_password: privatePassword
```

snmpwalk is working with the device, so the problem is not on the side of the device for sure. From log.level=debug returns:

```
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=debug msg="Scraping target '192.168.1.1:161' with module 'if_mib'" source="main.go:86"
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=debug msg="Walking target \"192.168.1.1:161\" subtree \"1.3.6.1.2.1.1.3\"" source="collector.go:125"
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=info msg="Error scraping target 192.168.1.1:161: Error walking target 192.168.1.1:161: recover: runtime error: invalid memory address or nil pointer dereference" source="collector.go:180"
snmp-exporter_1         | time="2018-10-24T13:30:17Z" level=debug msg="Scrape of target '192.168.1.1:161' with module 'if_mib' took 60.002449 seconds" source="main.go:97"
```

**Comment by brian-brazil** [comment]
Hmm, can you tweak the exporter to print the full stack trace?

**Comment by brian-brazil** [comment]
Can you build a version without the `recover` in vendor/github.com/soniah/gosnmp/v3.go?

**Comment by tricycleHack** [comment]
You mean building up snmp-exporter without recover, right? In that case apart from recover what else should i use/not use for this build?

**Comment by brian-brazil** [comment]
That's all that matters, as that's what's hiding the error.

**Comment by brian-brazil** [comment]
Did you manage to get the full trace?

**Comment by brian-brazil** [comment]
Yes please. It's likely an upstream bug.

**Comment by brian-brazil** [comment]
Did you ever get that trace?

**Comment by SuperQ** [comment]
There were several upstream SNMPv3 bug fixes since this was posted. I'm going to close this. If it turns out to there are still problems, feel free to re-open or file a new issue.
