### ISSUE TITLE
Option to mask counters to 53 bits?

### ISSUE THREAD

**Issue by candlerb** [prometheus/snmp_exporter#350]
Prometheus stores float64 (double) values, which have a [53-bit mantissa](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).

For counters which exceed 2<sup>53</sup>, this means there is a loss of precision when taking the difference between adjacent samples to calculate rates.

A link running at 100Gbps could reach 2<sup>53</sup> bytes in 8.3 days.  After this, the accuracy will degrade, eventually to the point where counters are rounded to the nearest 2<sup>11</sup> bytes.

This is arguably a minor issue - but it could be avoided entirely if there were an option to truncate SNMP counter values to 53 bits by ANDing them with `0x001f_ffff_ffff_ffff`.  Such counters would then wrap more frequently, but maintain full accuracy.

Such masking must not be applied to gauges of course, so it would have to be a per-OID option.

**Comment by SuperQ** [comment]
Thanks for opening this issue. I've talked with people about doing this, I think it's a good idea. The simple method would be to do `value % 2^53`.

The question is, should we do this automatically for counters? Should it be a configuration option for the generator? Should it be per-OID or per module?

I could imagine something like this:
```yaml
overrides:
  ifHCInOctets:
    wrap_large_values: true
  ifHCOutOctets:
    wrap_large_values: true
```

**Comment by SuperQ** [comment]
Another question, for users that care about the current value of the counter, how/if do we expose the number of wraps applied to the value? Do we have a metric like `ifHCInOctets_wraps{...} 0`

**Comment by RichiH** [comment]
I thought this was done already with counter resets. I know Brian and me
talked about this after the Prometheus dev summit 2016 in Berlin.


Sent by mobile; please excuse my brevity.

**Comment by RichiH** [comment]
LGTM.

**Comment by RichiH** [comment]
Maybe with one or two sentences in the docs to make this obvious.
