### ISSUE TITLE
Unknown module spelling error

### ISSUE THREAD

**Issue by coretemp** [prometheus/snmp_exporter#354]
https://github.com/prometheus/snmp_exporter/blob/c778920c5aab6856e4de440c8825d089df384bcc/main.go#L82

Additionally, I don't have the `if_mib` module on my system, whatever that means. Please write an error message that has context with it and preferably link to some URL.

**Comment by Dean-Coakley** [comment]
Fixed in: https://github.com/prometheus/snmp_exporter/pull/359
