### ISSUE TITLE
[Feature Request] configuration dry-run for snmp_exporter

### ISSUE THREAD

**Issue by k0ste** [prometheus/snmp_exporter#355]
**What did you do?**

At this time is impossible check `snmp_exporter` configuration.

See related issue https://github.com/prometheus/prometheus/issues/4293

**What did you expect to see?**

Startup failed -> non zero exit-code.
This is important for automation tools and `systemd`.

**Comment by SuperQ** [comment]
The generator should never produce an invalid configuration. Do you have an example of an invalid configuration coming from the generator?

**Comment by k0ste** [comment]
@SuperQ, how I can use generator if my `snmp_exporter` configuration saved in git and deployed via Ansible?

**Comment by SuperQ** [comment]
I store the `generator.yml` in git, and have a script to generate the snmp.yml which is then deployed by ansible. Because the generator doesn't parse things like the community strings, I can even include ansible template values for handling secretes.

See: https://github.com/FOSDEM/infrastructure/blob/master/ansible/playbooks/templates/snmp_exporter/generator.yml

**Comment by SuperQ** [comment]
You should not be editing the snmp.yml manually, this is explicitly not supported. This stated [in the documentation](https://github.com/prometheus/snmp_exporter#configuration). The file is meant to be generated, exactly to avoid this kind of problem.

**Comment by k0ste** [comment]
@SuperQ, generator is a MIB -> yaml, right?

**Comment by SuperQ** [comment]
The generator takes a list of walks/auth configuration, your MIBs, and produces the snmp.yml configuration. Including all the help information, correct types, etc.

**Comment by k0ste** [comment]
@SuperQ, I don't have a MIBs'. Also, to reduce the load on the device, my configuration contains only the necessary OID.

**Comment by SuperQ** [comment]
If you only include necessary OIDs, the generator will not add extras except for the case of lookups.

Note, that walking a tree, and only including some metrics does not reduce the load on the device. Only on Prometheus. This is also supported, via `ignore` in the generator.yml.

```yaml
     overrides: # Allows for per-module overrides of bits of MIBs
       metricName:
         ignore: true
```

**Comment by sgissi** [comment]
@k0ste SNMP without MIBs can be quite non-standard, if it is a device from a vendor, it should provide MIBs, if it is your own SNMP agent, writing the MIB isn't too hard. With that said, snmp-exporter should exit with non-zero code if it fails to parse the configuration and the dry-run method is a good sanity check that isn't hard to implement.

@SuperQ, I can take that one if nobody else is doing working on it.

**Comment by k0ste** [comment]
@sgissi, I tested your patch and this is exactly what I meant.
