### ISSUE TITLE
Community String not working

### ISSUE THREAD

**Issue by nexusguy59** [prometheus/snmp_exporter#357]
Here is the version I am using.

snmp_exporter, version 0.13.0 (branch: HEAD, revision: 84cab6d72f4c70e6239e1efa4f7ea9cba2b7acc8)
  build user:       root@b26f44b735fe
  build date:       20180912-11:01:50
  go version:       go1.10.3

So in version 0.11.0 The community string worked fine, and now it is not working no matter what I do.
```
  auth:   <- 3 spaces from left
      # Community string is used with SNMP v1 and v2. Defaults to "public".
      community: <stringhere>
```

./generator generate

FATA[0007] Error parsing yml config: yaml: unmarshal errors:
line 4: field community not found in type main.ModuleConfig  source="main.go:44"

Please help and let me know what I am doing wrong.

Thanks,
Michael

**Comment by SuperQ** [comment]
You likely have an indenting problem, please see the [docs](https://github.com/prometheus/snmp_exporter/tree/master/generator#file-format) on how to write a generator config.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by nexusguy59** [comment]
I thought that's what it was so I will take another look thanks.

On Nov 25, 2018 5:07 AM, "Ben Kochie" <notifications@github.com> wrote:

You likely have an indenting problem, please see the docs
<https://github.com/prometheus/snmp_exporter/tree/master/generator#file-format>
on how to write a generator config.

For usage questions/help, please use our community
<https://prometheus.io/community/>. On the mailing list, more people are
available to potentially respond to your question, and the whole community
can benefit from the answers provided.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prometheus/snmp_exporter/issues/357#issuecomment-441428955>,
or mute the thread
