### ISSUE TITLE
ADP PDU only gets interface info

### ISSUE THREAD

**Issue by qrpike** [prometheus/snmp_exporter#375]
### What device/snmpwalk OID are you using?
I am using an ADP PDU AP86XX

I can get the network interface information, however I cannot get the power usage and any other stats other than net inferface details. 

I found this article: https://www.apc.com/us/en/faqs/FA156179/ however, I'm not sure how to configure the generator. Any help would be greatly appreciated.

Thanks,

**Comment by daenney** [comment]
Look in `generator.yml` for `apcups`. There's a `walk` block there with names and OIDs to walk. As you can see the `1.3.6.1.4.1.318.1.1.26.x.y.z....` etc listed in the article you linked aren't covered, so none of the OIDs for the Rack PDU 2G projects are getting fetched.

While you're at it, also update the `Makefile` to fetch `428` of the APC MIB would be nice.
