### ISSUE TITLE
Add enum integer mapping support

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#377]
## Feature proposal

Some OIDs are INTEGER, but instead of a range like `INTEGER (0..60000)`, they are an enum mapping to strings.

Example from AIRESPACE-WIRELESS-MIB:
```
bsnAPIfType OBJECT-TYPE
    SYNTAX          INTEGER  {
                        dot11b(1),
                        dot11a(2),
                        uwb(4)
                    }
    MAX-ACCESS      read-only
    STATUS          current
    DESCRIPTION
        "The type of this interface. dot11b also implies 802.11b/g." 
    ::= { bsnAPIfEntry 2 }
```

It would be useful to have the generator/exporter support mapping these values into labels so that they can be used in a PromQL join.

There are two modes here, "info" and "stateset".

```
overrides:
   bsnAPIfType:
     enum: (info|stateset)
```

The end result would look like this:

info:
```
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="0",bsnAPIfType="dot11b"} 1
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="1",bsnAPIfType="dot11a"} 1
```
stateset:
```
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="0",bsnAPIfType="dot11b"} 1
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="0",bsnAPIfType="dot11a"} 0
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="0",bsnAPIfType="uwb"} 0
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="1",bsnAPIfType="dot11b"} 0
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="1",bsnAPIfType="dot11a"} 1
bsnAPIfType{bsnAPDot3MacAddress="XX",bsnAPIfSlotId="1",bsnAPIfType="uwb"} 0
```

The only difficulty for stateset, is if the MIB is invalid and there are states that exist on the device, but are (missing from the MIB)[https://quickview.cloudapps.cisco.com/quickview/bug/CSCvb04932].

**Comment by brian-brazil** [comment]
We can get the enum mapping from the MIB, the user would need to indicate if whey want it as an info or a stateset. Type override would seem a good way to do this.

**Comment by SuperQ** [comment]
Good point on info/stateset. I'll update the description.

**Comment by brian-brazil** [comment]
For unknown states, we'd use the number I think - adding in an enum state while it's present.

**Comment by RichiH** [comment]
That is a reasonable trade-off.

The WLC is also a prime example for why we need mixins for it once multi
index is merged. This thing is horribly horrible.

Sent by mobile; please excuse my brevity.
