### ISSUE TITLE
snmp_exporter does not print enumerator identifiers when scraping an object with an enumeration

### ISSUE THREAD

**Issue by xcross-ibm** [prometheus/snmp_exporter#391]
### Host operating system: output of `uname -a`
Linux imbroglio 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.15.0 (branch: HEAD, revision: 92a3da4467f8bc6759cf197e7442b8c43e890b13)
  build user:       root@8c3a7c03d455
  build date:       20190212-13:40:02
  go version:       go1.11.5

### What device/snmpwalk OID are you using?
DataPower/dpStatusMIB
### If this is a new device, please link to the MIB(s).
[drConfigMIB.txt](https://github.com/prometheus/snmp_exporter/files/3010163/drConfigMIB.txt)
[drStatusMIB.txt](https://github.com/prometheus/snmp_exporter/files/3010164/drStatusMIB.txt)
[generator.yml.gz](https://github.com/prometheus/snmp_exporter/files/3010177/generator.yml.gz)
[snmp.yml.gz](https://github.com/prometheus/snmp_exporter/files/3010178/snmp.yml.gz)

### What did you do that produced an error?
Use snmp_exporter to scrape my device MIB for an object that includes an enumeration. 
### What did you expect to see?
Expect to see both the enumeration ID as well as the value. When I walk the MIB directly I see this:

        $ snmpwalk -Os -v 2c -c public -m ./drConfigMIB.txt:./drStatusMIB.txt localhost:1161 dpStatusSystemUsage2TableTaskName
        dpStatusSystemUsage2TableTaskName.1.main = INTEGER: main(1)
        dpStatusSystemUsage2TableTaskName.3.quotaEnforcement = INTEGER: quotaEnforcement(17)

### What did you see instead?
The snmp_exporter output does not include the enumerator ID, just the value. 

        # HELP dpStatusSystemUsage2TableTaskName The name of the task or component. - 1.3.6.1.4.1.14685.3.1.265.1.2
        # TYPE dpStatusSystemUsage2TableTaskName gauge
        dpStatusSystemUsage2TableTaskName{dpStatusSystemUsage2TableTaskID="1",dpStatusSystemUsage2TableTaskName="1"} 1
        dpStatusSystemUsage2TableTaskName{dpStatusSystemUsage2TableTaskID="3",dpStatusSystemUsage2TableTaskName="17"} 17

A previous version of `generator` did not emit the enumeration into `snmp.yml` but the current version does. I've attached my MIBs and `generator` input and output files.

The snmp.yml includes the enumeration:

          - name: dpStatusSystemUsage2TableTaskName
            oid: 1.3.6.1.4.1.14685.3.1.265.1.2
            type: gauge
            help: The name of the task or component. - 1.3.6.1.4.1.14685.3.1.265.1.2
            indexes:
            - labelname: dpStatusSystemUsage2TableTaskID
              type: gauge
            - labelname: dpStatusSystemUsage2TableTaskName
              type: gauge
            enum_values:
              1: main
              <snip>
              17: quotaEnforcement

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by xcross-ibm** [comment]
@brian-brazil Thanks, I will. But can you give me a clue? My first take was I this is a bug, that `snmp_exporter` loses the enumerator id info. Are you saying user error?

**Comment by SuperQ** [comment]
There are 3 ways to use enumeration. This is documented in the generator. There is not enough information in MIB files to determine a correct mapping. You must use an override to decide which way of the two string mapping types to use.

See: https://github.com/prometheus/snmp_exporter/blob/master/generator/README.md#enumasinfo-and-enumasstateset

**Comment by xcross-ibm** [comment]
Hey @SuperQ thanks. I confess I didn't look at your new doc and was using a year old snapshot of generator. RTFM! I posted a question on the mail list.
