### ISSUE TITLE
Support chained lookups

### ISSUE THREAD

**Issue by tarko** [prometheus/snmp_exporter#405]
Hey,

Given the following metrics (coming straight from CISCO-CLASS-BASED-QOS-MIB):

```
ifIndex{ifName="Fa4"} 5

cbQosIfIndex{cbQosPolicyIndex="82"} 5

cbQosCMDropPkt64{cbQosObjectsIndex="1472497",cbQosPolicyIndex="82"} 116235
cbQosCMDropPkt64{cbQosObjectsIndex="14967793",cbQosPolicyIndex="82"} 116235
cbQosCMDropPkt64{cbQosObjectsIndex="5207969",cbQosPolicyIndex="82"} 0
cbQosCMDropPkt64{cbQosObjectsIndex="8687729",cbQosPolicyIndex="82"} 0

cbQosConfigIndex{cbQosObjectsIndex="1472497",cbQosPolicyIndex="82"} 1593
cbQosConfigIndex{cbQosObjectsIndex="14967793",cbQosPolicyIndex="82"} 1593
cbQosConfigIndex{cbQosObjectsIndex="5207969",cbQosPolicyIndex="82"} 296545
cbQosConfigIndex{cbQosObjectsIndex="8687729",cbQosPolicyIndex="82"} 18785

cbQosCMName{cbQosCMName="CS6",cbQosConfigIndex="296545"} 1
cbQosCMName{cbQosCMName="EF",cbQosConfigIndex="18785"} 1
cbQosCMName{cbQosCMName="class-default",cbQosConfigIndex="1593"} 1
```

and wanting to get cbQosCMDropPkt64 for specific ifName with cbQosCMName label added, it is pretty straightforward to go from ifIndex -> cbQosIfIndex -> cbQosCMDropPkt64 so one ends up with:

```
cbQosCMDropPkt64{cbQosObjectsIndex="1472497",cbQosPolicyIndex="82"}
cbQosCMDropPkt64{cbQosObjectsIndex="14967793",cbQosPolicyIndex="82"}
cbQosCMDropPkt64{cbQosObjectsIndex="5207969",cbQosPolicyIndex="82"}
cbQosCMDropPkt64{cbQosObjectsIndex="8687729",cbQosPolicyIndex="82"}
```

Getting the cbQosCMName is a problematic bit as this would require joining cbQosObjectsIndex value (for example 1593) with cbQosConfigIndex label on cbQosCMName metric.

To my best knowledge it's not doable with prometheus query language itself nor with snmp_exporter lookups (edit: this is incorrect, it is doable with PromQL using `count_values` operator)

Is this something that would be considered in snmp_exporter in some form?

**Comment by brian-brazil** [comment]
I think you want to add a lookup on the two ifIndexes, if it's not there already.

**Comment by tarko** [comment]
Which kind of lookup do you have in mind? Ifindexes themselves are not an issue, they can be looked up using:

```
cbQosCMDropPkt64{instance="blah"} and
ignoring(cbQosObjectsIndex) (cbQosIfIndex{instance="blah"} == on (instance) group_left(ifIndex) ifIndex{instance="blah", ifName="Fa4"})
```
It's the cbQosCMName I cannot wrap my head around. cbQosConfigIndex value must be used to look up correct cbQosCMName and to make matters worse multiple cbQosConfigIndex can reference to single cbQosCMName. There is also no supporting oid like cbQosCMNameIndex that would have cbQosConfigIndex as table index and as value (like ifTable.ifIndex) so value to value match cannot also be used.

**Comment by tarko** [comment]
@SuperQ and @RichiH , do you perhaps also have a view on this?

**Comment by SuperQ** [comment]
I think [this is another example](https://www.reddit.com/r/PrometheusMonitoring/comments/dmnvc6/snmp_exporter_assistance_with_source_index_lookups/) of a lookup based on a value.

CISCO-PROCESS-MIB contains a table, `cpmCPUTotalTable`. There is a `cpmCPUTotalPhysicalIndex` who's value is the lookup into `entPhysicalName`.

**Comment by brian-brazil** [comment]
This sounds like it was a usage question, so closing off.

**Comment by tarko** [comment]
Well I don't think you can accomplish such lookup with PromQL right now. @SuperQ has hit the same problem to my best knowledge.

**Comment by brian-brazil** [comment]
It's definitely possible with PromQL, but I'm now a little unsure of the status in this exporter. Can you share all the metrics for one example in all relevant tables?

**Comment by brian-brazil** [comment]
Taking a deeper look this is a chained lookup that should work like:

Add lookup [cbQosObjectsIndex, cbQosPolicyIndex] -> cbQosConfigIndex giving:
`cbQosCMDropPkt64{cbQosObjectsIndex="8687729",cbQosPolicyIndex="82",cbQosConfigIndex="18785"} 0`
Add lookup [cbQosConfigIndex] -> cbQosCMName giving:
`cbQosCMDropPkt64{cbQosObjectsIndex="8687729",cbQosPolicyIndex="82",cbQosConfigIndex="18785",cbQosCMName="EF"} 0`

The exporter can handle this, however the generator won't spot that the lookup can be applied with cbQosConfigIndex as a source though.

**Comment by tarko** [comment]
> It's definitely possible with PromQL

Can you throw us a bone here, how to do it with PromQL? (I'll be sharing the metrics in separate reply).

**Comment by tarko** [comment]
> Can you share all the metrics for one example in all relevant tables?

Sure: [snmp.txt](https://github.com/prometheus/snmp_exporter/files/3921158/snmp.txt)

**Comment by brian-brazil** [comment]
I think it's:
```
  rate(cbQosCMDropPkt64{instance="$device"}[5m])
* ignoring(cbQosObjectsIndex) group_left(ifName)
  (cbQosIfIndex == ignoring (ifName, cbQosIfIndex) group_left(ifName) ifIndex)
* ignoring(cbQosCMNamae) group_left(cbQosCMName)
  (
      count_values("cbQosConfigIndex", cbQosConfigIndex)
    * ignoring(cbQosObjectsIndex, cbQosCMName) on group_left(cbQosCMName)
      cbQosCMName
  )
```

**Comment by tarko** [comment]
Thanks, `count_values` is a great tip (dunno how I have missed it until now) and it indeed allows us to convert value to label in this instance (I'll edit the original post to reflect that). Took some time to wrap my head around why it drops all labels and this is what I ended up with:

```
(
rate(cbQosCMDropPkt64{instance="$device"}[5m])
and ignoring(cbQosObjectsIndex) (cbQosIfIndex{instance="$device"} == on (instance) group_left(ifIndex) ifIndex{instance="$device", ifName="$ifname"})
and ignoring(cbQosObjectsIndex) (cbQosPolicyDirection{instance="$device"} == 2)
)
* ignoring(cbQosConfigIndex) group_left(cbQosConfigIndex) (count_values("cbQosConfigIndex", cbQosConfigIndex{instance="$device"}) without ())
* on(cbQosConfigIndex) group_left(cbQosCMName) cbQosCMName{instance="$device"}
```

CISCO-CLASS-BASED-QOS-MIB is one of the saddest MIBs I've seen over the years. It originates from year 2000 so NMS landscape was totally different back then. Query above is not really readable to random reader so I'd say it would be still better to do it in the exporter with chained lookups.

**Comment by hreidar** [comment]
Hi @tarko, would you be so kind as to share your snmp.yml which generates the result in the snmp.txt you posted here?

**Comment by tarko** [comment]
@hreidar there is no point to post snmp.yml which will be super long. You need generator.yml and this is what we use for Cisco IOS devices right now (please note that we do not collect whole if(X)Table to save TSDB space): https://gist.github.com/tarko/47dc7fa972711cf17976e0c35e14c3c3

**Comment by hreidar** [comment]
thank you @tarko

**Comment by hreidar** [comment]
Hi, @tarko, I'm trying to do similar things but I'm not getting anything from Prometheus using the query you provided here above. My understanding is that you're "instance" label is used to identify a device so I modified the query a bit as I'm using the "node" label for that purpose. Here are some ot the metrics:

```
ifIndex{ifIndex="95",ifName="Gi4/40",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 95

cbQosIfIndex{cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 95

cbQosCMDropPkt64{cbQosObjectsIndex="131072",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 1700
cbQosCMDropPkt64{cbQosObjectsIndex="196608",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 1826
cbQosCMDropPkt64{cbQosObjectsIndex="262144",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 11
cbQosCMDropPkt64{cbQosObjectsIndex="65536",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 0

cbQosConfigIndex{cbQosObjectsIndex="131072",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 3.59449529e+08
cbQosConfigIndex{cbQosObjectsIndex="196608",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 3.5804184e+08
cbQosConfigIndex{cbQosObjectsIndex="262144",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 1593
cbQosConfigIndex{cbQosObjectsIndex="65536",cbQosPolicyIndex="1522",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 2.81639407e+08

cbQosCMName{cbQosCMName="class-default",cbQosConfigIndex="1593",instance="app2:9118",job="cisco-snmp",node="EAC1109-Beykiskogar13-A"} 1
```

and here is the query that returns no data:

```
(
rate(cbQosCMDropPkt64{node="EAC1109-Beykiskogar13-A"}[5m])
and ignoring(cbQosObjectsIndex) (cbQosIfIndex{node="EAC1109-Beykiskogar13-A"} == on (node) group_left(ifIndex) ifIndex{node="EAC1109-Beykiskogar13-A", ifName="Gi4/40"})
and ignoring(cbQosObjectsIndex) (cbQosPolicyDirection{node="EAC1109-Beykiskogar13-A"} == 2)
)
* ignoring(cbQosConfigIndex) group_left(cbQosConfigIndex) (count_values("cbQosConfigIndex", cbQosConfigIndex{node="EAC1109-Beykiskogar13-A"}) without ())
* on(cbQosConfigIndex) group_left(cbQosCMName) cbQosCMName{node="EAC1109-Beykiskogar13-A"}
```
Is there something that I'm missing?

**Comment by tarko** [comment]
You have additional labels that I do not have, you have to ignore/use those on the matches. ifIndex has extra `ifIndex` label, all others have `node` that you should not really have, you should put that into `instance`.

**Comment by hreidar** [comment]
Hi, I did change the configuration so that the device name goes to the instance label. The ifIndex is generated from the generator.yml file you kindly provided.(https://gist.github.com/tarko/47dc7fa972711cf17976e0c35e14c3c3)

````
  - name: ifIndex
    oid: 1.3.6.1.2.1.2.2.1.1
    type: gauge
    help: A unique value, greater than zero, for each interface - 1.3.6.1.2.1.2.2.1.1
    indexes:
    - labelname: ifIndex
      type: gauge
    lookups:
    - labels:
      - ifIndex
      labelname: ifName
      oid: 1.3.6.1.2.1.31.1.1.1.1
      type: DisplayString
````

**Comment by tarko** [comment]
I drop ifIndex label on all ifTable metrics during ingest to workaround devices where ifName is not unique. I have to keep ifIndex label in snmp_exporter as snmp_exporter is not happy if there are duplicate metrics and whole scrape will fail. By keeping the label I can drop it during ingest - obviously the duplicate metrics will not make it into TSDB but I don't care as they are irrelevant interfaces anyway.

**Comment by hreidar** [comment]
Hi, sorry for my noob questions, I'm trying to drop the ifIndex label without any luck. I've tried both of these:

```
metric_relabel_configs:
      - regex: 'ifIndex'
        action: labeldrop
```
and
```
metric_relabel_configs:
   - target_label: ifIndex
     replacement: ''
```

would you be so kind to share your method?

**Comment by tarko** [comment]
This is getting pretty far from the original issue. It'll be my last reply:

```    
metric_relabel_configs:
      - regex: "ifIndex"
        action: labeldrop
```

**Comment by hreidar** [comment]
Yes I know, thanks for your help.

**Comment by brian-brazil** [comment]
With #489 merged, is this all working now?

**Comment by tarko** [comment]
Unfortunately no, but this might be some other issue, this is the config I'm testing with:

```
  - name: cbQosCMDropPkt64
    oid: 1.3.6.1.4.1.9.9.166.1.15.1.1.14
    type: counter
    indexes:
    - labelname: cbQosPolicyIndex
      type: gauge
    - labelname: cbQosObjectsIndex
      type: gauge
    lookups:
    - labels:
      - cbQosObjectsIndex
      - cbQosPolicyIndex
      labelname: cbQosConfigIndex
      oid: 1.3.6.1.4.1.9.9.166.1.5.1.1.2
      type: gauge
    - labels:
      - cbQosConfigIndex
      labelname: cbQosCMName
      oid: 1.3.6.1.4.1.9.9.166.1.7.1.1.1
      type: DisplayString

  - name: cbQosConfigIndex
    oid: 1.3.6.1.4.1.9.9.166.1.5.1.1.2
    type: gauge
    indexes:
    - labelname: cbQosPolicyIndex
      type: gauge
    - labelname: cbQosObjectsIndex
      type: gauge
    lookups:
    - labels:
      - cbQosObjectsIndex
      - cbQosPolicyIndex
      labelname: cbQosConfigIndex
      oid: 1.3.6.1.4.1.9.9.166.1.5.1.1.2
      type: gauge
```

And this is the result, interestingly the single lookup doesn't succeed on cbQosConfigIndex itself except for single value so recursive lookup couldn't work either:

```
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="",cbQosObjectsIndex="14844913",cbQosPolicyIndex="18"} 0
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="",cbQosObjectsIndex="3853409",cbQosPolicyIndex="18"} 0
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="",cbQosObjectsIndex="6790561",cbQosPolicyIndex="18"} 0
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="",cbQosObjectsIndex="723537",cbQosPolicyIndex="18"} 0

cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="11669987",cbQosPolicyIndex="18"} 9.745795e+06
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="12233635",cbQosPolicyIndex="18"} 2.385763e+06
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="13431872",cbQosPolicyIndex="18"} 493104
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="13497762",cbQosPolicyIndex="18"} 1594
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="14844913",cbQosPolicyIndex="18"} 1593
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="15548995",cbQosPolicyIndex="18"} 4.299683e+06
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="15549011",cbQosPolicyIndex="18"} 4.299699e+06
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="3853409",cbQosPolicyIndex="18"} 1593
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="5603762",cbQosPolicyIndex="18"} 1594
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="5776802",cbQosPolicyIndex="18"} 4.323234e+06
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="654323",cbQosPolicyIndex="18"} 3.352419e+06
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="6790561",cbQosPolicyIndex="18"} 18785
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="723537",cbQosPolicyIndex="18"} 296545
cbQosConfigIndex{cbQosConfigIndex="",cbQosObjectsIndex="8478386",cbQosPolicyIndex="18"} 9.824962e+06
cbQosConfigIndex{cbQosConfigIndex="13281264",cbQosObjectsIndex="18",cbQosPolicyIndex="18"} 1.3281264e+07

```

**Comment by brian-brazil** [comment]
Was that config hand generated? Those values for cbQosConfigIndex also don't look like the previous ones shared.

**Comment by tarko** [comment]
The recursive part was hand generated as the generator refuses to do it (just adds the lookup to cbQosCMName as cbQosConfigIndex is originally index there), [cbQosObjectsIndex, cbQosPolicyIndex] to cbQosConfigIndex is exactly as from generator, the generator config is following:

```
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifName
      - source_indexes: [cbQosObjectsIndex, cbQosPolicyIndex]
        lookup: cbQosConfigIndex
      - source_indexes: [cbQosConfigIndex]
        lookup: cbQosCMName
```

As for the values it's hard to reproduce with exact label values as they are dynamic over time. But the logic is the same as originally reported plus the first lookup for some reason succeeds for `cbQosConfigIndex="13281264"`

**Comment by brian-brazil** [comment]
I'm having a little trouble getting my head around all of this. Can you share an snmpwalk of just the relevant lines for one output time series?

**Comment by tarko** [comment]
You are not the only one, look at the query that pulls it all together :) This MIB has pretty bad datamodel.

```
cbQosCMDropPkt64[18][723537] = Counter64: 0
cbQosCMDropPkt64[18][3853409] = Counter64: 0
cbQosCMDropPkt64[18][6790561] = Counter64: 0
cbQosCMDropPkt64[18][14844913] = Counter64: 0

cbQosConfigIndex[18][18] = Gauge32: 13281264
cbQosConfigIndex[18][654323] = Gauge32: 3352419
cbQosConfigIndex[18][723537] = Gauge32: 296545
cbQosConfigIndex[18][3853409] = Gauge32: 1593
cbQosConfigIndex[18][5603762] = Gauge32: 1594
cbQosConfigIndex[18][5776802] = Gauge32: 4323234
cbQosConfigIndex[18][6790561] = Gauge32: 18785
cbQosConfigIndex[18][8478386] = Gauge32: 9824962
cbQosConfigIndex[18][11669987] = Gauge32: 9745795
cbQosConfigIndex[18][12233635] = Gauge32: 2385763
cbQosConfigIndex[18][13431872] = Gauge32: 493104
cbQosConfigIndex[18][13497762] = Gauge32: 1594
cbQosConfigIndex[18][14844913] = Gauge32: 1593
cbQosConfigIndex[18][15548995] = Gauge32: 4299683
cbQosConfigIndex[18][15549011] = Gauge32: 4299699

cbQosCMName[1593] = STRING: class-default
cbQosCMName[18785] = STRING: EF
cbQosCMName[296545] = STRING: CS6
```

To pull it all together, [18][723537] refers to 296545 which then refers to "CS6"

**Comment by brian-brazil** [comment]
The `labels` in your lookup is the wrong way around, order matters.

**Comment by tarko** [comment]
Indeed, also explains ofc why it worked for `cbQosObjectsIndex="18",cbQosPolicyIndex="18"`. So that takes care of that problem.

Recursive cbQosCMName lookup doesn't work tho after manually adding second lookup:

```
    - labels:
      - cbQosConfigIndex
      labelname: cbQosCMName
      oid: 1.3.6.1.4.1.9.9.166.1.7.1.1.1
      type: DisplayString
```

Output being:
```
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="1593",cbQosObjectsIndex="14844913",cbQosPolicyIndex="18"} 0
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="1593",cbQosObjectsIndex="3853409",cbQosPolicyIndex="18"} 0
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="18785",cbQosObjectsIndex="6790561",cbQosPolicyIndex="18"} 0
cbQosCMDropPkt64{cbQosCMName="",cbQosConfigIndex="296545",cbQosObjectsIndex="723537",cbQosPolicyIndex="18"} 0
```

**Comment by brian-brazil** [comment]
Hmm, are you sure you built from master?

**Comment by tarko** [comment]
Yup, `go get -u -x github.com/prometheus/snmp_exporter` and same for generator. Manually looking at src indicates it's up2date with github master and ofc:

```
~/go/bin/snmp_exporter 
level=info ts=2020-05-04T11:06:16.408Z caller=main.go:149 msg="Starting snmp_exporter" version="(version=, branch=, revision=)"
level=info ts=2020-05-04T11:06:16.408Z caller=main.go:150 build_context="(go=go1.14, user=, date=)"
```

**Comment by brian-brazil** [comment]
Can you add some debug lines to the code to see what's going wrong?

**Comment by tarko** [comment]
Yes, I was about to already but have to work on some other stuff now. I'll get back here with results and hopefully a fix as well.

**Comment by tarko** [comment]
Dug into `indexesToLabels` and this is what is happening:

```
metric: &config.Metric{Name:"cbQosCMDropPkt64", Oid:"1.3.6.1.4.1.9.9.166.1.15.1.1.14", Type:"counter", Help:"The 64 bits counter of dropped pkts per class as the result of all features that can produce drops (e.g., police, random detect, etc.). - 1.3.6.1.4.1.9.9.166.1.15.1.1.14", Indexes:[]*config.Index{(*config.Index)(0xc002d1a4e0), (*config.Index)(0xc002d1a510)}, Lookups:[]*config.Lookup{(*config.Lookup)(0xc002cf4a00), (*config.Lookup)(0xc002cf4a50)}, RegexpExtracts:map[string][]config.RegexpExtract(nil), EnumValues:map[int]string(nil)}

labels: map[string]string{"cbQosObjectsIndex":"3853409", "cbQosPolicyIndex":"18"}

labelOids: map[string][]int{"cbQosObjectsIndex":[]int{3853409}, "cbQosPolicyIndex":[]int{18}}


lookup: &config.Lookup{Labels:[]string{"cbQosPolicyIndex", "cbQosObjectsIndex"}, Labelname:"cbQosConfigIndex", Oid:"1.3.6.1.4.1.9.9.166.1.5.1.1.2", Type:"gauge"}

lookup oid: "1.3.6.1.4.1.9.9.166.1.5.1.1.2.18.3853409"

looked up pdu: gosnmp.SnmpPDU{Name:".1.3.6.1.4.1.9.9.166.1.5.1.1.2.18.3853409", Type:0x42, Value:0x639, Logger:(*log.Logger)(0xc0008b5770)}

post lookup labels: map[string]string{"cbQosConfigIndex":"1593", "cbQosObjectsIndex":"3853409", "cbQosPolicyIndex":"18"}

post lookup labelOids: map[string][]int{"cbQosObjectsIndex":[]int{3853409}, "cbQosPolicyIndex":[]int{18}}


lookup: &config.Lookup{Labels:[]string{"cbQosConfigIndex"}, Labelname:"cbQosCMName", Oid:"1.3.6.1.4.1.9.9.166.1.7.1.1.1", Type:"DisplayString"}

lookup oid: "1.3.6.1.4.1.9.9.166.1.7.1.1.1."

```

In this case, the if statement added in #489 is never true and first lookup OID is never added to labelOids (labels are populated tho) hence the second lookup could never succeed.

If I try to manually call `pdu.Value.(int)` I'm greeted with  `panic: interface conversion: interface {} is uint, not int`

This looks correct because cbQosConfigIndex is actually Unsigned32 but labelOids map is array of signed ints (64bit tho).

Not really sure how to fix this correctly as SNMP PDU can be Unsigned64 and it will obviously not fit into signed 64bit int without loosing data.

**Comment by brian-brazil** [comment]
What I'd suggest is using something like gosnmp.ToBigInt(pdu.Value).Int64() as we do in getPduValue.

I wouldn't worry about a value being more than 32 bits, if that actually comes up we can deal with it then.

**Comment by tarko** [comment]
labelOids needs int not int64 so I had to do `int(gosnmp.ToBigInt(pdu.Value).Int64())`. After this is hacked to code then indeed, chained lookups work as expected.

**Comment by brian-brazil** [comment]
Can you send a PR?

**Comment by tarko** [comment]
#527

**Comment by brian-brazil** [comment]
Great, so this should be fixed then.
