### ISSUE TITLE
Walking and retrieving OIDs finished in zero

### ISSUE THREAD

**Issue by paurullan** [prometheus/snmp_exporter#41]
In the `collector.walk:oid` function there is a conditional to manipulate zeros on oids that says:

```python
def walk_oid(session, oid):
       # [...]
        if v.iid == '0':
          yield v.tag[1:], v.val
        else:
          yield last_oid, v.val
```

We have a Mikrotik switch that has a oids finished in zero:
```
cpu-frequency: .1.3.6.1.4.1.14988.1.1.3.14.0
```

And this function will completely broke the crawling for that item, ignoring the parsed result and not showing in the prometheus-ready endpoint.

The simple fix was to remove the conditional but this was at the expense of almost a full day of investigation.

Is there any reason I cannot grasp why this is implemented in this way?

**Comment by brian-brazil** [comment]
I presume the 0 was in the iid in that case, which is what the conditional is looking for - removing trailing 0s from non-table OIDs as some switches add them.

**Comment by paurullan** [comment]
@brian-brazil yes, the full OID ended in zero. My question is, why would the `walk_oid` function ignore it?

**Comment by brian-brazil** [comment]
Because it's not part of the OID.

**Comment by paurullan** [comment]
@brian-brazil OK, thank you.
I will talk with the router support people to ask for another OID number.

**Comment by brian-brazil** [comment]
The snmp_exporter should be handling this anyway. What's the actual problem you're seeing?

**Comment by paurullan** [comment]
The `cpu-frequency` metric has a `.1.3.6.1.4.1.14988.1.1.3.14.0`, finished in zero, and it is not collected by the exporter. I can see all the other specified metrics but this one is ignored because of that «if».

**Comment by brian-brazil** [comment]
Are you using a snmp_exporter built from head? It should have the fix for this.

**Comment by paurullan** [comment]
No, this was used with version 0.0.5.

**Comment by brian-brazil** [comment]
You might want to try out head then. Once the v1/v3 support is in I'm planning on doing a release.

**Comment by brian-brazil** [comment]
Is this still an issue with the latest version?

**Comment by brian-brazil** [comment]
Presuming handled with the Go rewrite.
