### ISSUE TITLE
probe_success style metric

### ISSUE THREAD

**Issue by jpds** [prometheus/snmp_exporter#411]
The `blackbox_exporter` exposes a `probe_success` metric for its probes, it would be useful if `snmp_exporter` had a similar metric too.

**Comment by brian-brazil** [comment]
There's no need as the scrape will fail if there's an SNMP problem.

**Comment by jpds** [comment]
How do I expose that to a monitoring end-user? Currently I use `up` and `probe_success` combined in a grafana dashboard, however, the `up`-metrics for snmp-exporter are constant as prometheus naturally sees it as available at all times.

**Comment by SuperQ** [comment]
That just means it's working reliably. :smile: If SNMP `/probe` was failing, `up` would be 0.

**Comment by jpds** [comment]
> That just means it's working reliably. smile If SNMP /probe was failing, up would be 0.

Yep, realized that and rechecked my targets! :)
