### ISSUE TITLE
Custom Listen Port

### ISSUE THREAD

**Issue by davidlesicnik** [prometheus/snmp_exporter#417]
### Host operating system: output of `uname -a`
Linux monitor 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.15.0 (branch: HEAD, revision: 92a3da4467f8bc6759cf197e7442b8c43e890b13)
  build user:       root@8c3a7c03d455
  build date:       20190212-13:40:02
  go version:       go1.11.5

### What did you do that produced an error?
Added --web.listen-address=":9990" to run snmp_exporter on port 9990 (I already have something running on 9116)

### What did you expect to see?
I expected to see the snmp_exporter web page to work when going to [ip]:9990

### What did you see instead?
systemd service crashes with journalctl spitting out 
level=fatal msg="listen tcp: address tcp/9990\": unknown port" source="main.go:227"

**Comment by SuperQ** [comment]
I'm not able to reproduce this. Can you share your whole unit file?

```console
$ ./snmp_exporter --web.listen-address=":9990"
INFO[0000] Starting snmp exporter (version=0.15.0, branch=HEAD, revision=92a3da4467f8bc6759cf197e7442b8c43e890b13)  source="main.go:139"
INFO[0000] Build context (go=go1.11.5, user=root@8c3a7c03d455, date=20190212-13:40:02)  source="main.go:140"
INFO[0000] Listening on :9990                            source="main.go:226"
```

**Comment by davidlesicnik** [comment]
snmp_exporter.service:
`[Unit]
Description=SNMP Exporter
After=network.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/snmp_exporter --config.file=/monitor/snmp_exporter/snmp.yml --web.listen-address=":9990"

[Install]
WantedBy=multi-user.target`

Setup is night identical to another one I have (I recreated my whole prometheus setup recently), except for the --web.listen-address.
And if I remove --web.listen-address from the unit file (to keep the default 9116 port) it works fine.

**Comment by jwsomis** [comment]
I have this same issue on the node_exporter.

**Comment by SuperQ** [comment]
Weird, seems like a systemd parsing issue. Thanks for reporting a fix.
