### ISSUE TITLE
Configuring Generator.yml

### ISSUE THREAD

**Issue by nexusguy59** [prometheus/snmp_exporter#423]
Hello Guys,

I am trying to configure the generator.yml so I can generate a snmp.yml for my devices on the snmp_exporter. However I am putting the OIDs and the names for metrics in the file and it is giving me an error,

cfadmin@cfsnmp:~/go/src/github.com/prometheus/snmp_exporter/generator$ ./generator generate          INFO[0000] Loading MIBs from $HOME/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp  source="net_snmp.go:141"
WARN[0000] NetSNMP reported 10 parse error(s)            source="main.go:104"
FATA[0000] Error parsing yml config: yaml: line 48: did not find expected key  source="main.go:44"

So do I have to put the mibs in all of the above locations? I have them in the /home/cfadmin/.snmp/mibs.

I am new to this snmp exporter so I am hoping some has a real example generator.yml I could look at.

Thanks Guys,
Michael

**Comment by SuperQ** [comment]
The error is from your `generator.yml` file, not a problem with the MIBs files.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by nexusguy59** [comment]
Yeah I figured that, do you know where I can get a good example to follow?

Thanks

**Comment by nexusguy59** [comment]
Thank you sir, I will take the initiative look those over.
