### ISSUE TITLE
How to combine hwIpAdEntIfIndex,hwIpAdEntAddr, IfAlias and IfDescription informations

### ISSUE THREAD

**Issue by umutcokbilir** [prometheus/snmp_exporter#426]
Hi There,

I've tried to run the following configuration:

  - name: hwIpAdEntAddr
    oid: 1.3.6.1.4.1.2011.5.25.41.1.2.1.1.1
    type: DisplayString
    indexes:
    - labelname: hwIpAdEntIfIndex
      type: gauge
  - name: hwIpAdEntIfIndex
    oid: 1.3.6.1.4.1.2011.5.25.41.1.2.1.1.2
    type: DisplayString
    indexes:
    - labelname: ifIndex
      type: gauge
    lookups:
    - labels:
      - ifIndex
      labelname: ifAlias
      oid: 1.3.6.1.2.1.31.1.1.1.18
      type: DisplayString

I want to combine IP addresses and descriptions But it didn't work.
Here is the result; it's giving same description where I made mistake?
Please help me

# TYPE hwIpAdEntIfIndex gauge
hwIpAdEntIfIndex{hwIpAdEntIfIndex="1",ifAlias="",ifIndex="127"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="106",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="107",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="108",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="109",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="111",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="112",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="114",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="115",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="35",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="36",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="37",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="38",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="4",ifAlias="",ifIndex="192"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="49",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="51",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="55",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="61",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="63",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="65",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="66",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="67",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="68",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="69",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="70",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="84",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="85",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="86",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="87",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="88",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
hwIpAdEntIfIndex{hwIpAdEntIfIndex="89",ifAlias="FTTS_H7332_REZERVE",ifIndex="10"} 1
# HELP ifIndex A unique value, greater than zero, for each interface - 1.3.6.1.2.1.2.2.1.1
# TYPE ifIndex gauge
ifIndex{ifAlias="ATN_K6649.0.1.3@01V000007992@||1000-1000||_NNI_ASY",ifDescr="GigabitEthernet0/2/0",ifIndex="6",ifName="GigabitEthernet0/2/0"} 6
ifIndex{ifAlias="BTS_1548",ifDescr="GigabitEthernet0/2/3.2647",ifIndex="52",ifName="GigabitEthernet0/2/3.2647"} 52
ifIndex{ifAlias="BTS_A1295",ifDescr="GigabitEthernet0/2/3.2130",ifIndex="62",ifName="GigabitEthernet0/2/3.2130"} 62
ifIndex{ifAlias="BTS_A1482",ifDescr="GigabitEthernet0/2/3.2685",ifIndex="64",ifName="GigabitEthernet0/2/3.2685"} 64
ifIndex{ifAlias="BTS_B1059",ifDescr="GigabitEthernet0/2/3.2144",ifIndex="50",ifName="GigabitEthernet0/2/3.2144"} 50
ifIndex{ifAlias="BTS_E3323",ifDescr="GigabitEthernet0/2/3.2138",ifIndex="60",ifName="GigabitEthernet0/2/3.2138"} 60
ifIndex{ifAlias="BTS_H7332",ifDescr="GigabitEthernet0/2/4.2860",ifIndex="116",ifName="GigabitEthernet0/2/4.2860"} 116
ifIndex{ifAlias="BTS_H7337",ifDescr="GigabitEthernet0/2/3.2086",ifIndex="113",ifName="GigabitEthernet0/2/3.2086"} 113
ifIndex{ifAlias="BTS_K6648",ifDescr="GigabitEthernet0/2/3.2597",ifIndex="54",ifName="GigabitEthernet0/2/3.2597"} 54
ifIndex{ifAlias="BTS_M3904",ifDescr="GigabitEthernet0/2/3.2593",ifIndex="48",ifName="GigabitEthernet0/2/3.2593"} 48
ifIndex{ifAlias="DCN loopback interface",ifDescr="LoopBack1023",ifIndex="5",ifName="LoopBack1023"} 5

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by umutcokbilir** [comment]
Hi Brian,
Please also help me.
