### ISSUE TITLE
generator: 

### ISSUE THREAD

**Issue by Carmezim** [prometheus/snmp_exporter#431]
Hey - I've been having an issue with the generator. I have setup one that works for a similar MIB, but for some reason when I set up a very similar one for the same vendor the generator fails the walk. I double checked the OIDs and they seem to be correct.

### Host operating system: output of `uname -a`
Darwin (MacOS Mojave) Darwin Kernel Version 19.0.0

### snmp_exporter version: output of `snmp_exporter -version`

Latest

### What device/snmpwalk OID are you using?
Device: Microhard-BulletPlusAC-CAT9

OIDs:
```
- 1.3.6.1.2.1.1.3 # UPTIME
- 1.3.6.1.4.1.21703.9000.5.4.6.0 # CORE 
- 1.3.6.1.4.1.21703.9000.5.4.5.0 # RSSI
- 1.3.6.1.4.1.21703.9000.5.4.16.0 # RSRQ
- 1.3.6.1.4.1.21703.9000.5.4.17.0 # RSRP
- 1.3.6.1.4.1.21703.9000.5.4.20.0 # ECIO
```

### If this is a new device, please link to the MIB(s).
MIB: https://file.io/TM6YU9

### What did you do that produced an error?
1. Installed the generator per instructions:
2. Added the target MIB file to `/mibs` directory
3. Configured `generator.yml` accordingly with proper OIDs
4. Ran the generator both locally and through Docker

### What did you expect to see?
Successful walk on the MIB's OIDs.

Example:
```
INFO[0000] Loading MIBs from mibs                        source="net_snmp.go:141"
WARN[0000] NetSNMP reported 7 parse error(s)             source="main.go:104"
INFO[0000] Generating config for module bullet_plus_gps  source="main.go:49"
INFO[0000] Generated 6 metrics for module bullet_plus_gps  source="main.go:60"
INFO[0000] Config written to /opt/snmp.yml               source="main.go:85"
```
### What did you see instead?
Example:
```
INFO[0000] Loading MIBs from $HOME/.snmp/mibs:/usr/local/share/snmp/mibs:/usr/share/snmp/mibs  source="net_snmp.go:141"
INFO[0000] Generating config for module bullet_plus_ac_cat9  source="main.go:49"
FATA[0000] Cannot find oid '1.3.6.1.4.1.21703.9000.5.4.16.0' to walk  source="tree.go:290"
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Carmezim** [comment]
@brian-brazil Hey Brian, firstly thanks for your work and for sharing with us. DId we rule out the possibility of a big on the generator?

Thanks

**Comment by brian-brazil** [comment]
This appears to be incorrect usage, either that or you've a very weird MIB. If it turns out to be a bug, we can reopen.

**Comment by Carmezim** [comment]
@brian-brazil I see. I tried without the trailing 0 btw and unfortunately had the same result. The MIB could be a possibility however for a another very similar (and equally validated) the generator worked :(

Thanks and if you think of any other possibility please let me know!

**Comment by RichiH** [comment]
Did you tcpdump the two devices and look at it in Wireshark?

Sent by mobile; please excuse my brevity.

**Comment by ainiml** [comment]
I solved my issue by using the OID name aliases from the MIB files instead

The prometheus generator doesn't like the OID's from `smidump`

see, https://github.com/TheShellLand/docker-smidump/blob/master/mibs/generator.yml
