### ISSUE TITLE
scarpe the data metrics is missing

### ISSUE THREAD

**Issue by vipsql** [prometheus/snmp_exporter#441]
### Host operating system: output of `uname -a`
Centos6.9

### snmp_exporter version: output of `snmp_exporter -version`
version: 0.15.0
generator: 0.15.0

### What device/snmpwalk OID are you using?
routeros
- 1.3.6.1.2.1.17.1.1
      - 1.3.6.1.2.1.17.2.1
      - 1.3.6.1.2.1.17.2.2
      - 1.3.6.1.2.1.17.4.3.1.1
      - 1.3.6.1.2.1.17.4.3.1.2
      - 1.3.6.1.2.1.17.4.3.1.3
      - 1.3.6.1.2.1.2.2.1.1
      - 1.3.6.1.2.1.2.2.1.10
      - 1.3.6.1.2.1.2.2.1.11
      - 1.3.6.1.2.1.2.2.1.12
      - 1.3.6.1.2.1.2.2.1.13
      - 1.3.6.1.2.1.2.2.1.14
      - 1.3.6.1.2.1.2.2.1.15
      - 1.3.6.1.2.1.2.2.1.16
      - 1.3.6.1.2.1.2.2.1.17
      - 1.3.6.1.2.1.2.2.1.18
      - 1.3.6.1.2.1.2.2.1.19
      - 1.3.6.1.2.1.2.2.1.2
      - 1.3.6.1.2.1.2.2.1.20
      - 1.3.6.1.2.1.2.2.1.21
      - 1.3.6.1.2.1.2.2.1.3
      - 1.3.6.1.2.1.2.2.1.4
      - 1.3.6.1.2.1.2.2.1.5
      - 1.3.6.1.2.1.2.2.1.6
      - 1.3.6.1.2.1.2.2.1.7
      - 1.3.6.1.2.1.2.2.1.8
      - 1.3.6.1.2.1.2.2.1.9
      - 1.3.6.1.2.1.25.1.1
      - 1.3.6.1.2.1.25.2.2
      - 1.3.6.1.2.1.25.2.3.1.1
      - 1.3.6.1.2.1.25.2.3.1.3
      - 1.3.6.1.2.1.25.2.3.1.4
      - 1.3.6.1.2.1.25.2.3.1.5
      - 1.3.6.1.2.1.25.2.3.1.6
      - 1.3.6.1.2.1.25.2.3.1.7
      - 1.3.6.1.2.1.25.3.2.1.1
      - 1.3.6.1.2.1.25.3.2.1.3
      - 1.3.6.1.2.1.25.3.2.1.5
      - 1.3.6.1.2.1.25.3.2.1.6
      - 1.3.6.1.2.1.25.3.3.1.2
      - 1.3.6.1.2.1.31.1.1.1.1
      - 1.3.6.1.2.1.31.1.1.1.10
      - 1.3.6.1.2.1.31.1.1.1.11
      - 1.3.6.1.2.1.31.1.1.1.12
      - 1.3.6.1.2.1.31.1.1.1.13
      - 1.3.6.1.2.1.31.1.1.1.15
      - 1.3.6.1.2.1.31.1.1.1.2
      - 1.3.6.1.2.1.31.1.1.1.3
      - 1.3.6.1.2.1.31.1.1.1.4
      - 1.3.6.1.2.1.31.1.1.1.5

### What did you do that produced an error?
![image](https://user-images.githubusercontent.com/13550799/61882795-c3815b80-af2b-11e9-8707-e0ccf18c3c00.png)
![image](https://user-images.githubusercontent.com/13550799/61882828-d4ca6800-af2b-11e9-809b-396d8d6e6972.png)
![image](https://user-images.githubusercontent.com/13550799/61882910-f7f51780-af2b-11e9-96b0-54cf9c27fdb7.png)

### What did you expect to see?
first i used snmpwalk to explore the snmp_data,it can see ether device indexID
and i used the snmp_exporter to get the metrics,the deivice indexID is missing

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
