### ISSUE TITLE
Allow overriding name

### ISSUE THREAD

**Issue by MarkLyck** [prometheus/snmp_exporter#442]
When you're building 1 system to handle the same metrics from many different devices, it's really frustrating that there's no way to normalize the metric names with the generator.

when you run the generator on multiple MIBs you'll get output names like:
`cypWlsUptime`
`sysUpTime`
`cfTmpUptime`

etc. Depending on whatever the vendor decided to name the OID. (I want to normalize the output names of these to `sh_probe_uptime`)

After *A LOT* of digging I kind of found a way to alter the name with regex_extracts like so:

```
overrides:
      sysUpTime:
        regex_extracts:
          _uptime:
            - regex: '(.*)'
              value: '$1'
```

But instead of replacing the name... This just adds a postfix to whatever name is already there...

So a long with this, I had to write a bash script with a perl regex to change **all** the names of the snmp.yml output to be `sh_probe`

For the first test. This was a success. The only metric outputted was `sh_probe_uptime`. Just what I wanted it to be called (for all devices).

However... After adding other metrics to our scraping like RSSI, RSRQ, ECIO, etc. snmp_exporter stopped working and starts complaining about duplicate names and "wrong" help messages.

so the already hacky method of normalizing a name didn't work...

I'm now finding myself having to create a loop with a regex to find the name, and then find the first word after `regex_extracts` (5 to 7 lines down) in the same block. Change the name to `sh_probe` + postfix ....

All this hassle to just change the output name of a metric!

It would be really really helpful if there was a better way to just override the name of a metric from the generator without having to write custom scripts that manipulates the output after snmp generator does it's thing."

To clarify I want e.g. `cypWlsUptime` & `sysUpTime` to both be outputed as `sh_probe_uptime` and define the output name in the generator.yml (likely overrides section)

**Comment by brian-brazil** [comment]
We purposefully use the object name from the MIB, with no way to override it, as that is the name of the metric. sysUpTime is sysUpTime, and they're almost all unique.

It sounds like you want to handle this on the PromQL end.

**Comment by MarkLyck** [comment]
Unfortunately that won't work for our needs.

(well for one we don't use PromQL, we use a postgres adapter).

But secondly, the generator.yml file is the **only** 100% reliable place where we know what metric it is.

I don't want to build a system that's relying on some random vendor in China putting `RSSI` in the metric oid name to "map" it to `sh_probe_rssi`

This absolutely should be done in the generator step. (at least for our purposes) I assume most others might not care about the oid name, but we need it to be consistent for different devices.

**Comment by brian-brazil** [comment]
Your use case is a fair bit outside standard SNMP/Prometheus usage, and also clashes with the meaning of metrics names in Prometheus. I'd suggest handling this elsewhere, such as metric_relabel_configs.
