### ISSUE TITLE
timeout when walking LLDP oid

### ISSUE THREAD

**Issue by visualcjy** [prometheus/snmp_exporter#448]
### What device/snmpwalk OID are you using?
when walking som Huawei switch's OID 1.0.8802.1.1.2.1.4.1.1.9，it will timeout. but the others is correct.
### What did you do that produced an error?
DEBU[0020] Walking target "192.168.52.240" subtree "1.0.8802.1.1.2.1.4.1.1.7"  source="collector.go:156"
DEBU[0020] Walk of target "192.168.52.240" subtree "1.0.8802.1.1.2.1.4.1.1.7" completed in 210.145534ms  source="collector.go:166"
DEBU[0020] Walking target "192.168.52.240" subtree "1.0.8802.1.1.2.1.4.1.1.9"  source="collector.go:156"
INFO[0080] Error scraping target 192.168.52.240: error walking target 192.168.52.240: Request timeout (after 3 retries)  source="collector.go:211"
DEBU[0080] Scrape of target '192.168.52.240' with module 'lldp' took 60.457660 seconds  source="main.go:98"
### What did you expect to see?
but if i snmpwalk , it's OK.
snmpwalk -v3 -l authpriv -u ops -a sha -A "abc" -x aes -X "abc" 192.168.52.240 1.0.8802.1.1.2.1.4.1.1.9
iso.0.8802.1.1.2.1.4.1.1.9.253088189.43.1 = STRING: "CU_S5720_DW"
iso.0.8802.1.1.2.1.4.1.1.9.253088189.47.1 = STRING: "CU_USG6600_M"
iso.0.8802.1.1.2.1.4.1.1.9.253088189.52.1 = STRING: "CU_CE6855_C"
### What did you see instead?
    
   is the 253088189 oid is too big to index ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by visualcjy** [comment]
it's gosnmp lib problem. After I update the  vendor/github.com/soniah/gosnmp/ files , the problem sloved.

**Comment by SuperQ** [comment]
@visualcjy What version of the snmp_exporter did you experience the problem with?

**Comment by SuperQ** [comment]
Created https://github.com/prometheus/snmp_exporter/pull/462 to bump to the latest gosnmp.

**Comment by jpmondet** [comment]
Exact same issue here with last release `version 0.22.0` (also tried 0.19.0 to 0.21.0)
