### ISSUE TITLE
Feature request: Additional flags

### ISSUE THREAD

**Issue by udf2457** [prometheus/snmp_exporter#450]
Hi,

Would be good to have a few more flags, paricularly the ability to override locations for `snmp.yml`, `generator.yml` and `mibs/`

**Comment by brian-brazil** [comment]
The mibs location is up to netsnmp. Why do you want to have different paths for the generator files?

**Comment by udf2457** [comment]
Different paths because I might not be calling `generator` from the directory. Also there could be use-cases where `generator` output needs to go somewhere else first before rolling out (e.g. generating alternative configs for test ?)

**Comment by tarko** [comment]
You can manipulate netsnmp paths with env variables like `export MIBDIRS=+/home/tarko/.snmp/alcatel-7750:/home/tarko/.snmp/JuniperMibs` before you execute generator

**Comment by SuperQ** [comment]
I think having flags for the input/output file locations is reasonable, just like having the same flag(s) for the config itself.

**Comment by SuperQ** [comment]
Fixed in #1028
