### ISSUE TITLE
Feature request: Syslog logging

### ISSUE THREAD

**Issue by udf2457** [prometheus/snmp_exporter#451]
For the purposes of consistency (and to assist those of us who may be writing automated sysadmin tools), it would be nice if **all** Prometheus "official" products had a syslog logging option ?

At the moment it is a bit hit and miss, for example `blackbox_exporter` does not have it, `generator` does not have it, but `node_exporter` does and as does `prometheus` itself.

The ability for all tools to log to syslog would mean all outputs could be collected by centralised logging systems.

**Comment by brian-brazil** [comment]
Prometheus doesn't do syslog. You're free to hook up the log output however you like, rather than us having to code up every possibility inside every exporter.

**Comment by udf2457** [comment]
Its not every possibility. Syslog is an inherently popular tool, and as I said, you should really be consistent with options in the toolset.

**Comment by brian-brazil** [comment]
Our standard is to do only stderr, anything not doing that is out of date.

**Comment by SuperQ** [comment]
We recently updated the logging library to go-kit. This uses stderr logging. For syslog you can use standard tools like systemd or bsdutils logger.
