### ISSUE TITLE
Please fulfill DockerHub project

### ISSUE THREAD

**Issue by nbluis** [prometheus/snmp_exporter#455]
Hi.

There is the project repository in dockerhub but it does not have any README information or release tags.

https://hub.docker.com/r/prom/snmp_exporter

Apparently it's official (as it is in the prom repository) but without tags or README it's hard to use in productive environments.

It would be amazing if we had a README and the tags available.

**Comment by brian-brazil** [comment]
https://hub.docker.com/r/prom/snmp-exporter is the right one, I've deleted the incorrect one.
