### ISSUE TITLE
Authentication error SNMPv3 using prometheus

### ISSUE THREAD

**Issue by imtiazahmed156** [prometheus/snmp_exporter#458]
ails: An error has occurred during metrics gathering:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error walking target 192.168.100.1: Incoming packet is not authentic, discarding

$ sudo tcpdump -i ens3 -v | grep "192.168.100.1"
(parallel in other terminal)
$ snmpwalk -v 3 -u iithcore -l authNoPriv -a MD5 -A IITH*1234 192.168.100.1

   monitor2.iith.ac.in.38612 > 192.168.100.1.snmp:  { SNMPv3 { F=ar } { USM B=1 T=623924 **U="iithcore"** } { ScopedPDU E=_2c_be_1c_80_a1 C="" { GetNextRequest(30) R=534815630  interfaces.ifTable.ifEntry.ifIndex.55 } } } 
    192.168.100.1.snmp > monitor2.iith.ac.in.38612:  { SNMPv3 { F=a } { USM B=1 T=623924 U="iithcore" } { ScopedPDU E=_2c_be_1c_80_a1 C="" { GetResponse(31) R=534815630  interfaces.ifTable.ifEntry.ifIndex.56=56 } } } 
    monitor2.iith.ac.in.38612 > 192.168.100.1.snmp:  { SNMPv3 { F=ar } { USM B=1 T=623924 U="iithcore" } { ScopedPDU E=_2c_be_1c_80_a1 C="" { GetNextRequest(30) R=534815631  interfaces.ifTable.ifEntry.ifIndex.56 } } } 
    192.168.100.1.snmp > monitor2.iith.ac.in.38612:  { SNMPv3 { F=a } { USM B=1 T=623924 U="iithcore" } { ScopedPDU E=_2c_be_1c_80_a1 C="" { GetResponse(31) R=534815631  interfaces.ifTable.ifEntry.ifIndex.57=57 } } }

$ **with Prometheus and snmp_exporter TCP Dump result**

monitor2.iith.ac.in.37467 > 192.168.100.1.snmp:  { SNMPv3 { F=r } { USM B=0 T=0 **U=""** } { ScopedPDU E= C="" { GetRequest(14) R=193338631  } } } 
    192.168.100.1.snmp > monitor2.iith.ac.in.37467:  { SNMPv3 { F= } { USM B=1 T=623951 U="" } { ScopedPDU E=_2c_be_1c_80_a1 C="" { Report(30) R=0  S:snmpUsmMIB.usmMIBObjects.usmStats.usmStatsUnknownEngineIDs.0=42830 } } }

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
