### ISSUE TITLE
multi-modules prometheus snmp job configuration.

### ISSUE THREAD

**Issue by mjtrangoni** [prometheus/snmp_exporter#47]
I would like to ask you for an advice/recommendation on configuring different modules at the same Prometheus job. Is it possible? 
Somethings like this prometheus.yml
...
  - job_name: 'snmp'

    static_configs:
      - targets: ['sw1.localdomain', 'sw2.localdomain']
    params:
      module: [procurve]

    static_configs:
      - targets: ['fcsw1.localdomain', 'fcsw2.localdomain']
    params:
      module: [brocade]

    static_configs:
      - targets: ['ibsw1.localdomain', 'ibsw2.localdomain']
    params:
      module: [mellanox]

    relabel_configs:
....

**Comment by brian-brazil** [comment]
You could do something with relabelling, but when working with different types of devices I'd recommend multiple scrape configs search with their own job name.
