### ISSUE TITLE
Generator is exits without clear error message

### ISSUE THREAD

**Issue by HearttBreaker** [prometheus/snmp_exporter#476]
Hi,
I'm trying to generate snmp.yml as instructed. But when I use the generator, I get the following logs:

./generator generate
level=info ts=2020-01-22T16:54:00.052Z caller=net_snmp.go:142 msg="Loading MIBs" from=$HOME/.snmp/mibs:/usr/share/snmp/mibs
level=warn ts=2020-01-22T16:54:03.608Z caller=main.go:120 msg="NetSNMP reported parse error(s)" errors=767
level=warn ts=2020-01-22T16:54:04.534Z caller=tree.go:83 msg="Can't find augmenting node" augments=tokenRingMLStatsEntry node=tokenRingMLStats2Entry
level=warn ts=2020-01-22T16:54:04.534Z caller=tree.go:83 msg="Can't find augmenting node" augments=tokenRingPStatsEntry node=tokenRingPStats2Entry
level=warn ts=2020-01-22T16:54:04.535Z caller=tree.go:83 msg="Can't find augmenting node" augments=dot1agCfmMepEntry node=mefSoamPmMepEntry
level=warn ts=2020-01-22T16:54:04.537Z caller=tree.go:83 msg="Can't find augmenting node" augments=rptrPortEntry node=ciscoRptrPortEntry
level=info ts=2020-01-22T16:54:04.558Z caller=main.go:52 msg="Generating config for module" module=module_name
Killed

Mibs are loaded in to /root/Projects/Proj1/src/github.com/prometheus/snmp_exporter/generator/mibs. generator.yml is configured to receive SNMP v3.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
