### ISSUE TITLE
snmprec files that are linked to modules in generator.yml

### ISSUE THREAD

**Issue by Gmapoub** [prometheus/snmp_exporter#478]
I've tried on #prometheus on freenode without success ("Cannot send to nick/channel") and I'm less and less a google friend to use (https://groups.google.com/forum/#!forum/prometheus-users)

It could be nice to add .snmprec files that can be used with modules from https://github.com/prometheus/snmp_exporter/blob/master/generator/generator.yml

Thanks

**Comment by brian-brazil** [comment]
What's snmprec?

**Comment by Gmapoub** [comment]
Thanks for the quick answer.
http://snmplabs.com/snmpsim/building-simulation-data.html
It is a snapshot of an existing SNMP agent

Or an equivalent

**Comment by brian-brazil** [comment]
What would the benefit of that be? We don't even have access to most of these devices to generate such a thing.

If you want to test your own devices, that's something you can do yourself.

**Comment by Gmapoub** [comment]
Hum, so, if I don't have access to a [synology](https://github.com/prometheus/snmp_exporter/blob/master/generator/generator.yml#L160), how could I test if this [# Use OID to avoid conflict with Netscaler NS-ROOT-MIB.](https://github.com/prometheus/snmp_exporter/blob/master/generator/generator.yml#L192) 
is the same problem with another kind of agent ?

So the module, you are presented [here](https://github.com/prometheus/snmp_exporter/blob/master/generator/generator.yml) are not already tested? (I'm pretty sure it is, but it's good to know)

Thanks for your time.

**Comment by brian-brazil** [comment]
> is the same problem with another kind of agent ?

I don't see how that would help you. Such an issue is entirely in the generator.

> And another point, how could you test snmp_exporter if you do not have access to the SNMP agent ?

We've got extensive unittests. 

> So the module, you are presented here are not already tested?

It presumably works for whoever submitted it. SNMP is fun, part of that is that devices regularly violate both the specs and their own docs. The only real way to test is actual hardware.

**Comment by Gmapoub** [comment]
> > is the same problem with another kind of agent ?
> 
> I don't see how that would help you. Such an issue is entirely in the generator.
> 
OK

> > And another point, how could you test snmp_exporter if you do not have access to the SNMP agent ?
> 
> We've got extensive unittests.
>
Cool !

> > So the module, you are presented here are not already tested?
> 
> It presumably works for whoever submitted it. SNMP is fun, part of that is that devices regularly violate both the specs and their own docs. The only real way to test is actual hardware.
Yes your are right about irregularity ;) and records (like snmprec) from that hardware are fun to used mostly due to latency, constancy, modifications, tests, etc..

Anyway thanks for your answers and time
