### ISSUE TITLE
cisco_v2 download fails

### ISSUE THREAD

**Issue by wakarim** [prometheus/snmp_exporter#480]
Hi,

I have cloned the snmp_exporter repository and followed all the instructions given

However when I go to make mibs, the first 4 download, and the make gets stuck on cisco_v2. I get the following error:
```
administrator@aisgrovcs02:~/go/src/github.com/prometheus/snmp_exporter/generator$ make mibs
mkdir: created directory 'mibs'
>> Downloading apc-powernet-mib
>> Downloading ARISTA-ENTITY-SENSOR-MIB
>> Downloading ARISTA-SMI-MIB
>> Downloading ARISTA-SW-IP-FORWARDING-MIB
>> Downloading cisco_v2
Makefile:121: recipe for target 'mibs/.cisco_v2' failed
make: *** [mibs/.cisco_v2] Error 7
```

Is this an error with the link or is there something I'm missing?

**Comment by brian-brazil** [comment]
Works for me, though it has always been one of the biggest and thus slowest ones.

**Comment by wakarim** [comment]
Still not working here. But could just be my network.
Thanks

**Comment by brian-brazil** [comment]
I'm going to close for now, as it looks to be on your end.

**Comment by AntoineThebaud** [comment]
Hello,

I encounter the same error

**Comment by prijks** [comment]
The issue is most likely that the URL for the cisco_v2 MIB is FTP. Your firewall probably blocks FTP. It would be nice if the cisco_v2 MIB was available via http(s) instead of FTP, since FTP is a bit of a nightmare protocol. I worked around this by downloading it locally and changing the cisco_v2 URL in the Makefile.

**Comment by jeromystewart** [comment]
Same issue here

**Comment by gnanasalten** [comment]
If you are running behind proxy, set proxy for ftp also
