### ISSUE TITLE
exporter produces a 500 without metrics when the target cannot be resolved.

### ISSUE THREAD

**Issue by ykuksenko** [prometheus/snmp_exporter#484]
The primary issue is that when a host cannot be resolved by DNS snmp_exporter produces no metrics and a 500. This seems to be inconsistent with all the other exporters that produce a value even if the target is missing or unresolvable.

The secondary issue is that there seems to be no `-version` flag in this docker build (not sure if that is intentional).

### Host operating system: output of `uname -a`
Podman container in Fedora 31:
`Linux f31 5.4.17-200.fc31.x86_64 #1 SMP Sat Feb 1 19:00:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
### snmp_exporter version: output of `snmp_exporter -version`
This docker image build has no `-version` command when trying to run that and `--help` doesn't list `-version` either. Though the docker image is tagged with `v0.17.0`
The image digest is: `sha256:4d81a08b3f44166b8145561d7988ce6a152333e5a19742e7fe4a55ccb3a15129`

### What did you do that produced an error?
scrape a target that doesn't resolve in dns.

### What did you expect to see?
I expected the scrape to return some valid metrics. At least the following two:
```
up 1
probe_success 0
```
### What did you see instead?
```
/ # curl 'http://snmp-exporter.dns.podman:9116/snmp?module=woot&target=switch.example.org'
An error has occurred while serving metrics:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: error connecting to target switch.example.org: error establishing connection to host: dial udp: lookup switch.example.org on 10.89.0.1:53: no such host
```

**Comment by brian-brazil** [comment]
Different exporters work in different ways, this is not the blackbox exporter and has different design considerations. This is working as expected.

**Comment by ykuksenko** [comment]
Fair enough. Feel free to close this issue unless you want to keep this open for the missing `-version` option.
Thank you.

**Comment by bck01215** [comment]
Can this be revisited?` up` implies that the exporter is working/not working while `probe_success` implies that their is an issue with the connections.  As is, there is not a good way to determine if the snmp_exporter is at fault or if the target is down. 

If all targets go down, is there a network outage or has the snmp_exporter just failed?
