### ISSUE TITLE
Snmpwalk error

### ISSUE THREAD

**Issue by Daly123456** [prometheus/snmp_exporter#506]
’am monitoring my fortigate 200D using snmp_exporter i got problem wh:
-snmp_exporter status is working but snmpwalk -c public -v2c x.x.x.x.x show Timeout no response
-then i got that error :
snmp_exporter[7974]: level=info ts=2020-04-22T12:06:47.755Z caller=collector.go:216 module=if_mib target=172.16.0.240 msg=“Error scraping target” err=“error getting target 172.16.0.240: context canceled”
Some help please!

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
