### ISSUE TITLE
SNMP Exporter Timeout

### ISSUE THREAD

**Issue by fresaelens** [prometheus/snmp_exporter#507]
### Host operating system: output of `uname -a`

Linux hostname 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
0.17.0

### What device/snmpwalk OID are you using?
We are walking lots of different devices/manufacturers (Mikrotik devices, Huawei switches, Ruckus wireless switches, Ruckus Wireless APs, Huawei APs, etcetera)

### What did you do that produced an error?

We are using curl to execute the query ourselves.

curl 'http://127.0.0.1:9116/snmp?target=10.1.32.110&module=mikrotik'
curl 'http://127.0.0.1:9116/snmp?target=10.1.32.110&module=huawei_switch'

### What did you expect to see?

We expect to see SNMP results. Most of the time, the queries succeed and we get back the data. Now and then (there's no correlation as to when it succeeds or fails), the SNMP query times out. Actually after taking packet captures, we see that the query is reaching the device, the device answers, but the response gets lost somewhere along the way. (These queries/replies are being sent over VPN tunnels over the public Internet.)

Due to the connectionless nature of UDP, we expect the SNMP exporter to send another query (after timeout interval of 10s, retries this 3 times; default values). 

### What did you see instead?

However, as you can see below, the snmp exporter doesn't send another query for 60 seconds:

<img width="1440" alt="Screenshot 2020-04-24 at 14 40 41" src="https://user-images.githubusercontent.com/7249189/80214888-e1572a80-863b-11ea-9b87-b96b9842f0f6.png">

**Comment by brian-brazil** [comment]
With the defaults it should be retrying after 3.3s, are you sure you've not changed those settings?

**Comment by fresaelens** [comment]
Hi,

I haven't changed any settings.

Would it be helpful if I include the generate.yml and/or snmp.yml files?

**Comment by brian-brazil** [comment]
I don't think that'd help in this case, I'd have to dig through the upstream code again. Can you try an explicit lower timeout?

**Comment by fresaelens** [comment]
Hi,

I noticed when I don’t explicitly define the retries and timeout variables, the requests only get retransmitted after 60 seconds (as described in the original post). 

When I explicitly define the variables to the following: retries=3, timeout=15; then the requests are retransmitted after 45 seconds. 

When I explicitly define the variables to the following: retries=3, timeout=10; then the requests are retransmitted after 30 seconds.

**Comment by brian-brazil** [comment]
Ah, looks like the docs are wrong the default timeout is actually 20s, and the upstream docs are incorrect in terms of how the retries and timeout interact.

**Comment by burakkalafat** [comment]
hi biran Community defaults to raritan_public in snmp.yml. I want to call it with another community. is it possible ?

**Comment by burakkalafat** [comment]
hi brian Community defaults to raritan_public in snmp.yml. I want to call it with another community. is it possible ?
