### ISSUE TITLE
Missing 7z dependency from readme

### ISSUE THREAD

**Issue by impala454** [prometheus/snmp_exporter#516]
Just a quick note that on Ubuntu 18.04 building the generator, `7z` was missing so I had to also install `p7zip-full` (just `p7zip` was not enough).

### Host operating system: output of `uname -a`
```Linux <redacted> 5.3.0-7648-generic #41~1586790036~18.04~600aeb5~dev-Ubuntu SMP Mon Apr 13 17:49:24  x86_64 x86_64 x86_64 GNU/Linux```
### snmp_exporter version: output of `snmp_exporter -version`
N/A

### What device/snmpwalk OID are you using?
Nothing yet, just installing the generator as per the readme.
### If this is a new device, please link to the MIB(s).
Defaults
### What did you do that produced an error?
```make mibs```
### What did you expect to see?
Successful build.
### What did you see instead?
```
make: 7z: Command not found                                                                                                                
Makefile:236: recipe for target 'mibs/IPD-MIB_Q419V9.mib' failed                                                                                   
make: *** [mibs/IPD-MIB_Q419V9.mib] Error 127
```

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by impala454** [comment]
#518
