### ISSUE TITLE
Missing SNMP metrics from Synology device

### ISSUE THREAD

**Issue by taintedkernel** [prometheus/snmp_exporter#519]
### Host operating system: output of `uname -a`
Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
Tried master and 0.17.0

### What device/snmpwalk OID are you using?
Synology RS1219+

### If this is a new device, please link to the MIB(s).
Standard Synology MIBs

### What did you do that produced an error?
No error, just an incomplete set of metrics

### What did you expect to see?
All Synology metrics listed per their MIB Guide https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf

### What did you see instead?
Only interface metrics were being exposed, eg: ifAdminStatus, ifConnectorPresent, ifHCInOctets, ifInBroadcastPkts, ifSpeed, etc

If I run snmpwalk with some of the OIDs listed in the guide (eg: 1.3.6.1.4.1.2021, 1.3.6.1.4.1.6574) I am able to retrieve data successfully; but snmp exporter does not emit these.

I have tried editing the generator.yml and specifying a few extra OIDs under the `walk` config param, but no luck.  I've also tried using my own generated smnp.yml and the one supplied in the repo, same results on both.

`level=debug ts=2020-05-11T23:03:44.079Z caller=main.go:99 module=if_mib target=192.168.2.12 msg="Starting scrape"
level=debug ts=2020-05-11T23:03:44.079Z caller=collector.go:129 module=if_mib target=192.168.2.12 msg="Getting OIDs" oids=1
level=debug ts=2020-05-11T23:03:44.079Z caller=collector.go:135 module=if_mib target=192.168.2.12 msg="Get of OIDs completed" oids=1 duration_seconds=354.679µs
level=debug ts=2020-05-11T23:03:44.079Z caller=collector.go:159 module=if_mib target=192.168.2.12 msg="Walking subtree" oid=1.3.6.1.2.1.2
level=debug ts=2020-05-11T23:03:44.086Z caller=collector.go:169 module=if_mib target=192.168.2.12 msg="Walk of subtree completed" oid=1.3.6.1.2.1.2 duration_seconds=6.26548ms
level=debug ts=2020-05-11T23:03:44.086Z caller=collector.go:159 module=if_mib target=192.168.2.12 msg="Walking subtree" oid=1.3.6.1.2.1.31.1.1
level=debug ts=2020-05-11T23:03:44.093Z caller=collector.go:169 module=if_mib target=192.168.2.12 msg="Walk of subtree completed" oid=1.3.6.1.2.1.31.1.1 duration_seconds=7.111382ms
level=debug ts=2020-05-11T23:03:44.098Z caller=main.go:110 module=if_mib target=192.168.2.12 msg="Finished scrape" duration_seconds=0.019271954
`

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by taintedkernel** [comment]
Understood, thanks for the suggestion.

I actually just figured it out.  I was missing the URL paramater `module=synology` to the exporter (in addition to target)

**Comment by rogierlommers** [comment]
@taintedkernel do you mind providing me with an example of how you run the snmp_exporter? I also want to use this exporter to monitor my Synology. But I would like to know how to configure DSM to expose snmp, how to run the exporter, etc.

**Comment by taintedkernel** [comment]
@rogierlommers Sorry for the delay, life has me otherwise distracted recently and just catching up.

In terms of usage, I run it as a container in my microk8s cluster and at the time hacked together a basic manifest.  But I'm planning to move to the official Helm chart when I can carve out more time.

With DSM, it's a simple setting in the control panel to enable SNMP.  Just using v2 here, since everything is internal.
