### ISSUE TITLE
generator populating OID types differently than net-snmp

### ISSUE THREAD

**Issue by maemigh** [prometheus/snmp_exporter#520]
### Host operating system: output of `uname -a`
Linux tesla 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
./snmp_exporter -version
snmp_exporter: error: unknown short flag '-v', try --help

### What device/snmpwalk OID are you using?
Dell iDRAC 8

### If this is a new device, please link to the MIB(s).
iDRAC-SMIv2.mib [link](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverId=PNHK2)

### What did you do that produced an error?
Generator sets type of StringType OIDs as OctetString

### What did you expect to see?
DisplayString
snmpget shows the value properly
ex:
`IDRAC-MIB-SMIv2::systemOSName.0 = STRING: "VMware ESXi"`
This seems to happen for all string values

### What did you see instead?
generator sets the type as OctetString and output appears as gauge
```
# HELP systemOSName This attribute defines the name of the operating system that the host is running. - 1.3.6.1.4.1.674.10892.5.1.3.6
# TYPE systemOSName gauge
systemOSName{systemOSName="0x564D776172652045535869"} 1
```

**Comment by brian-brazil** [comment]
StringType is an OCTET STRING, this behaviour is correct. If the vendor wanted it to be treated as ASCII, they should have specified that in the MIB.

**Comment by maemigh** [comment]
Perhaps I have the details wrong. Nevertheless, behavior doesn't appear to be following that of net-snmp

**Comment by brian-brazil** [comment]
Net-snmp appears to use a heuristic rather than what the MIB says, we follow the MIB - as it wouldn't be correct to do anything else. The MIB says it's a binary string, so we handle it as a binary string.

**Comment by brian-brazil** [comment]
Closing, as there's no bug here. We're doing exactly what the MIB tells us to.
