### ISSUE TITLE
Error: ...source="collector.go:211"

### ISSUE THREAD

**Issue by subin8848** [prometheus/snmp_exporter#525]
### Host operating system: output of `uname -a`
Linux snmp-exporter-prometheus-snmp-exporter-56c85fff97-dnvmr 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 12 20:32:56 UTC 2020 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.14.0 

### What device/snmpwalk OID are you using?
Cisco Router (module: if_mib)

### If this is a new device, please link to the MIB(s).
No
### What did you do that produced an error?
Error received from curl:

An error has occurred during metrics gathering:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error getting target 1.2.3.4: Request timeout (after 3 retries)

evel=info msg="Error scraping target 1.2.3.4: Error getting target 1.2.3.4: Request timeout (after 3 retries)" source="collector.go:211"

I can ping 1.2.3.4 from container and snmp walk is working from the server.

### What did you expect to see?
snmp parameters in reply

### What did you see instead?
Error messages

**Comment by SuperQ** [comment]
This is likely an authentication issue.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by subin8848** [comment]
Thanks for the info. The default community-string seems to be 'public'. If I put this community in the router, it works but I want a different community string. Can you suggest how can I add new community-string? I could not modify the snmp.yaml to append 'auth: /n community: string' in that file.
