### ISSUE TITLE
Reimplement in Go

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#53]
Sponsored by SpaceNet :p

**Comment by RichiH** [comment]
Possible low-hanging fruit for this port:

* https://github.com/prometheus/snmp_exporter/issues/54
* https://github.com/prometheus/snmp_exporter/issues/16
* https://github.com/prometheus/snmp_exporter/issues/17

**Comment by SuperQ** [comment]
Looks like this is done :-)
