### ISSUE TITLE
Ability to override community string for select devices?

### ISSUE THREAD

**Issue by hartfordfive** [prometheus/snmp_exporter#532]
I have a situation where i'm scraping snmp metrics from hundreds of devices, and unfortunately a very small subset of them have a different community string due to the fact the vendor doesn't support specific characters in them.  So far, I can't see that there's any way to override a different community string for just a few devices.  If this isn't the case, could this feature potentially be added?  Would be quite useful to have this ability as it's a shame to have to run an additional snmp_exporter process just to scrape metrics of a few devices.

**Comment by brian-brazil** [comment]
You can do with by having a different module with a different community string for those devices.

**Comment by houston88** [comment]
This means that the snmp.yml file will get very large with mostly repeating sections. The only difference will be the community string in my use case. Would be cool if could specify per target somehow...

**Comment by brian-brazil** [comment]
That's a matter for configuration management, and overall this is not something that's likely to be added.
