### ISSUE TITLE
cannot find oid xxx to walk

### ISSUE THREAD

**Issue by 496268931** [prometheus/snmp_exporter#534]
### What did you see instead?

Hello, I have some oids that need to be collected by snmp, but after writing in generator.yml, the snmp.yml is generated with an error "level=error ts=2020-06-22T08:14:55.325Z caller=main.go :130 msg="Error generating config netsnmp" err="cannot find oid '1.3.6.1.4.1.41475.3.1.11.11' to walk""

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ainiml** [comment]
Getting the same thing with opengear MIB files, here http://ftp.opengear.com/download/snmp/mibs/

**Comment by ainiml** [comment]
solved it, `smidump` doesn't generate OID's the way prometheus generator wants them. 

solution: use oid name aliases instead

see, https://github.com/TheShellLand/docker-smidump/blob/master/mibs/generator.yml

**Comment by brian-brazil** [comment]
It looks like your tool wasn't producing the full OIDs, see http://oidref.com/1.3.6.1.4.1.25049.2.10.10.1.1.1 for example.

**Comment by ainiml** [comment]
> It looks like your tool wasn't producing the full OIDs, see http://oidref.com/1.3.6.1.4.1.25049.2.10.10.1.1.1 for example.

What tool do you guys use for generating the OIDs?

**Comment by SuperQ** [comment]
The snmp_exporter includes the [generator](https://github.com/prometheus/snmp_exporter/tree/master/generator).

**Comment by ainiml** [comment]
> The snmp_exporter includes the [generator](https://github.com/prometheus/snmp_exporter/tree/master/generator).

Does it have an option to export the OIDs and descriptions

I made a list of all the OIDs and descriptions, so you can just comment out what you don't want from the generator config

**Comment by darox** [comment]
We have a few extreme switches that I want to monitor, but I'm facing similar issues. If I walk the switch, I can clearly see:
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1035388100) 119 days, 20:04:41.00

But when I try to generate the snmp.yml file:
level=error ts=2020-12-11T12:54:38.000Z caller=main.go:130 msg="Error generating config netsnmp" err="cannot find oid 'sysUpTimeInstance' to walk"

Although DISMAN-EVENT-MIB is in mibs folder. 

What's the  point?

**Comment by 496268931** [comment]
> We have a few extreme switches that I want to monitor, but I'm facing similar issues. If I walk the switch, I can clearly see:
> DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1035388100) 119 days, 20:04:41.00
> 
> But when I try to generate the snmp.yml file:
> level=error ts=2020-12-11T12:54:38.000Z caller=main.go:130 msg="Error generating config netsnmp" err="cannot find oid 'sysUpTimeInstance' to walk"
> 
> Although DISMAN-EVENT-MIB is in mibs folder.
> 
> What's the point?


According to my experience, Go program is not necessarily required to produce configuration files that snmp_exporter can recognize. As long as you can know all the OIDs, and then generate them according to the correct configuration file format. Below is what I generated with java code




if_mib:
  auth: {community: public}
  get: [1.3.6.1.4.1.41475.3.1.134.134.23.0, 1.3.6.1.4.1.41475.3.1.136.136.33.0]
  metrics:
  - help: 设备名称：PDU_IT2_B ，点名称：电流报警值 ，单位： ， 点值描述： ,oid：1.3.6.1.4.1.41475.3.1.134.134.23.0
    name: NAME1
    oid: 1.3.6.1.4.1.41475.3.1.134.134.23.0
    type: DisplayString
    regex_extracts: &id001
      ? ''
      : - {regex: '^(?:^(?:(.*))$)$', value: $1}
  - help: 设备名称：PDU_IT3_B ，点名称：有功功率 ，单位：kw ， 点值描述： ,oid：1.3.6.1.4.1.41475.3.1.136.136.33.0
    name: NAME2
    oid: 1.3.6.1.4.1.41475.3.1.136.136.33.0
    type: DisplayString
    regex_extracts: *id001
  version: 2

**Comment by tangcfrank** [comment]
main.go:130 msg="Error generating config netsnmp" err="cannot find oid 'sysUpTimeInstance' to walk"

**Comment by tangcfrank** [comment]
How to solve it
main.go:130 msg="Error generating config netsnmp" err="cannot find oid 'sysUpTimeInstance' to walk"
