### ISSUE TITLE
[RFE] Autoload MIBs based on qualified names in config file

### ISSUE THREAD

**Issue by yrro** [prometheus/snmp_exporter#535]
With Net-SNMP I'm used to _not_ having to load all available MIB files (and dealing with the log message spew caused by errors in vendor supplied files, grr)... but rather using qualified variable names to trigger on-demanding MIB loading:

```
$ snmptranslate -m : -Dparse-file -On QCT-RACK-MIB::temperatureStatusOverall 
registered debug token parse-file, 1
parse-file: Parsing file:  /home/phe.gov.uk/sam.morris/.snmp/mibs/QCT-RACK-MIB.txt...
parse-file: Parsing file:  /usr/share/snmp/mibs/ietf/SNMPv2-SMI...
parse-file: End of file (/usr/share/snmp/mibs/ietf/SNMPv2-SMI)
parse-file: End of file (/home/phe.gov.uk/sam.morris/.snmp/mibs/QCT-RACK-MIB.txt)
.1.3.6.1.4.1.7244.1.2.1.2.5
```

You can see Net-SNMP is only loading the requested MIB plus its dependencies. All the other junk MIBs littering my `MIBDIRS` are ignored. :)

So, it would be nice if variable names in `generator.yml` could be qualified with a module name to trigger MIB loading on demand in the same manner, like this:

```
modules:
  qct_rack_mib:
    walk:
      - QCT-RACK-MIB::temperatureStatusOverall
```

That way you don't have to force loading `ALL` mibs in the generator.

**Comment by brian-brazil** [comment]
We should be hiding the parse errors just giving a line count, if that's not the case that's a bug.

I don't believe that'll work, as that MIB presumably depends on many others. If you want to limit the MIBs that are parsed, you can provide them in a separate directory and point the generator to them. 

What you propose would also be a breaking change to all users of this exporter, for the sake of making a number in a log line smaller which doesn't seem like the right choice to me before even considering the complexity it'd add.

**Comment by brian-brazil** [comment]
Closing per above.
