### ISSUE TITLE
Golang version mismatch in CI config yamls

### ISSUE THREAD

**Issue by gbrener** [prometheus/snmp_exporter#536]
Hi guys, this is a minor issue. Wanted to point out that the Go version was bumped to 1.14 in https://github.com/prometheus/snmp_exporter/blob/master/.promu.yml, but it was not updated in the other CI configuration yaml files.

**Comment by brian-brazil** [comment]
Hmm, #513 seems to have not left anything out. What was missed?

**Comment by gbrener** [comment]
https://github.com/prometheus/snmp_exporter/blob/master/.travis.yml#L8

**Comment by brian-brazil** [comment]
We no longer need Travis, would you like to send a PR to remove that?
