### ISSUE TITLE
 The collected oid values ​​are all 0

### ISSUE THREAD

**Issue by 496268931** [prometheus/snmp_exporter#537]
The version of snmp_exporter is the latest version on git

The first picture is my snmp.yml file, the current oid has 20 child nodes, but after executing the collector, it is found that the value collected by each node is 0

![image](https://user-images.githubusercontent.com/31230459/85504300-520bca80-b61e-11ea-828d-43494b3d63b5.png)
![image](https://user-images.githubusercontent.com/31230459/85504321-60f27d00-b61e-11ea-936d-9d6f8bf1ccc3.png)

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
