### ISSUE TITLE
Modulus for interface counters

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#54]
As per our talks during/after PromCon, float64 loses precision in todays interface counters for 10G or quicker. Introducing modulus and thus artificially resetting will solve that until int64/float128 are a thing.

**Comment by sgissi** [comment]
@RichiH @SuperQ I believe this fixed by #351, correct?

**Comment by SuperQ** [comment]
@sgissi Yes, thanks, that's the fix.
