### ISSUE TITLE
snmp_exporter: collection and query

### ISSUE THREAD

**Issue by 496268931** [prometheus/snmp_exporter#540]
1. The snmp_exporter uses the get method for each id, but why the collected values ​​are all in the labels in braces, marked with one.
2. After collecting, I am on the server side of prometheus, why can't I query the data. See figures 2, 3
![image](https://user-images.githubusercontent.com/31230459/85916475-9946c500-b883-11ea-8781-3c1a66ac1eb5.png)
![image](https://user-images.githubusercontent.com/31230459/85916487-bda2a180-b883-11ea-97cf-36e13d34b6bc.png)
![image](https://user-images.githubusercontent.com/31230459/85916507-f0e53080-b883-11ea-913f-63de41351154.png)

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
