### ISSUE TITLE
Module parameter is not taken into account

### ISSUE THREAD

**Issue by darox** [prometheus/snmp_exporter#545]
### Host operating system: output of `uname -a`
 3.10.0-514.71.1.el7.x86_64 #1 SMP Mon Nov 25 09:21:51 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
0.18.0

### What did you do that produced an error?
I renamed the module from if_mib to correlator.

`curl http://8.9.9.3:9116/snmp?target=1.2.3.4&module=correlator`

### What did you expect to see?
Metrics are returned correctly when module name was changed from if_mib to correlator.

### What did you see instead?

`Unknown module 'if_mib'`

**Comment by SuperQ** [comment]
If that's your literal curl command, you have to quote the URL to avoid shell escaping.

```
curl 'http://8.9.9.3:9116/snmp?target=1.2.3.4&module=correlator'
```

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
