### ISSUE TITLE
snmp_exporter issue with oid type integer and string

### ISSUE THREAD

**Issue by mo254** [prometheus/snmp_exporter#548]
Hey

after using another oid with the type STRING on my snmp.yml, the snmp give me an error, i am using snmp on my supermicro server with the motherboard x10SLD

error: level=info ts=2020-07-17T18:42:16.293Z caller=main.go:243 msg="Listening on address" address=:9116
panic: Unknown index type INTEGER

my snmp.yml look like this:

supermicro:
  version: 2
  auth:
    community: public
  walk:
    - 1.3.6.1.4.1.21317.1.3.1.13.11
  metrics:
    - name: Vcpu
      oid:  1.3.6.1.4.1.21317.1.3.1.13.11
      type: INTEGER

**Comment by brian-brazil** [comment]
Can you share your generator.yml?

**Comment by mo254** [comment]
hey Brian, i am not using generator.yml
The only thing what i am using is prometheus.yml
Thank you

**Comment by brian-brazil** [comment]
That is not supported, you snmp.yml is intended to be generated by the generator. Hand-written configs are entirely at your own risk.

**Comment by mo254** [comment]
I want to became the power consumption from my server ( supermicro X10sld) and i have enabled the snmp on my server but the problem which i have when i use the type string or integer i became the error

**Comment by mo254** [comment]
Okey, so if i use generator.yml i will receive the Power consumption of my server?

**Comment by brian-brazil** [comment]
That's a usage question, and it makes more sense to ask questions like that on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
