### ISSUE TITLE
Exporter not able to load valis snmp.yml file generated using the generator 

### ISSUE THREAD

**Issue by zeshahid** [prometheus/snmp_exporter#549]
### Host operating system: output of `uname -a`
 3.10.0-1062.21.1.el7.x86_64 #1 SMP Wed Mar 25 10:20:14 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter-0.18.0
### What device/snmpwalk OID are you using?
F5:
  walk:
  - 1.3.6.1.4.1.3375.2.1.7.1
  get:
  - 1.3.6.1.2.1.1.3.0
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
    help: The time (in hundredths of a second) since the network management portion
      of the system was last re-initialized. - 1.3.6.1.2.1.1.3
  - name: sysHostMemoryTotal
    oid: 1.3.6.1.4.1.3375.2.1.7.1.1
    type: counter
    help: The total host memory in bytes - 1.3.6.1.4.1.3375.2.1.7.1.1
  - name: sysHostMemoryUsed
    oid: 1.3.6.1.4.1.3375.2.1.7.1.2
    type: counter
    help: The host memory in bytes currently in use - 1.3.6.1.4.1.3375.2.1.7.1.2
  - name: sysHostMemoryTotalKb
    oid: 1.3.6.1.4.1.3375.2.1.7.1.3
    type: gauge
    help: The total host memory in Kilobytes - 1.3.6.1.4.1.3375.2.1.7.1.3
  - name: sysHostMemoryUsedKb
    oid: 1.3.6.1.4.1.3375.2.1.7.1.4
    type: gauge
    help: The host memory in Kilobytes currently in use - 1.3.6.1.4.1.3375.2.1.7.1.4

### What did you do that produced an error?
stop and  start the service with new yml file
### What did you expect to see?
service is not starting up, however, when I run below it works fine 

******************
 ./snmp_exporter
level=info ts=2020-07-29T10:21:13.118Z caller=main.go:149 msg="Starting snmp_exporter" version="(version=0.18.0, branch=HEAD, revision=9a2ff257dd2e8cdb2a4c88b18df668e2008c2cd6)"
level=info ts=2020-07-29T10:21:13.118Z caller=main.go:150 build_context="(go=go1.14.3, user=root@84ec61d89273, date=20200526-08:27:09)"
level=info ts=2020-07-29T10:21:13.119Z caller=main.go:243 msg="Listening on address" address=:9116

*****************
### Main issue is below and I even tried with dry run it's same 

Jul 29 14:46:57 prisbprodcmpnms snmp_exporter[4759]: level=info ts=2020-07-29T09:46:57.398Z caller=main.go:149 msg="Starting snmp_exporter" version="(version=0.18.0, br
Jul 29 14:46:57 prisbprodcmpnms snmp_exporter[4759]: level=info ts=2020-07-29T09:46:57.398Z caller=main.go:150 build_context="(go=go1.14.3, user=root@84ec61d89273, date
Jul 29 14:46:57 prisbprodcmpnms snmp_exporter[4759]: level=error ts=2020-07-29T09:46:57.398Z caller=main.go:156 msg="Error parsing config file" err="open snmp.yml: no s
Jul 29 14:46:57 prisbprodcmpnms systemd[1]: snmp_exporter.service: main process exited, code=exited, status=1/FAILURE
Jul 29 14:46:57 prisbprodcmpnms systemd[1]: Unit snmp_exporter.service entered failed state.
Jul 29 14:46:57 prisbprodcmpnms systemd[1]: snmp_exporter.service failed.
Jul 29 14:46:57 prisbprodcmpnms systemd[1]: snmp_exporter.service holdoff time over, scheduling restart.
Jul 29 14:46:57 prisbprodcmpnms systemd[1]: Stopped node_exporter.
-- Subject: Unit snmp_exporter.service has finished shutting down

###with dry run 

/usr/local/snmp_exporter/snmp_exporter --config.file="/usr/local/snmp_exporter/snmp_exporter/snmp.yml" --dry-run
level=info ts=2020-07-29T10:24:35.521Z caller=main.go:149 msg="Starting snmp_exporter" version="(version=0.18.0, branch=HEAD, revision=9a2ff257dd2e8cdb2a4c88b18df668e2008c2cd6)"
level=info ts=2020-07-29T10:24:35.521Z caller=main.go:150 build_context="(go=go1.14.3, user=root@84ec61d89273, date=20200526-08:27:09)"
level=error ts=2020-07-29T10:24:35.521Z caller=main.go:156 msg="Error parsing config file" err="open /usr/local/snmp_exporter/snmp_exporter/snmp.yml: not a directory"

**Comment by brian-brazil** [comment]
This looks like an issue with how you're pointing to the config file, rather than the exporter itself. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by zeshahid** [comment]
Thanks, let me share this in the mailing list as well, however it was working and stopped working when I restarted the service. so don't know what I'm doing incorrect
