### ISSUE TITLE
"collected metric was collected before with the same name and label values" is label_value size limited?

### ISSUE THREAD

**Issue by flourme** [prometheus/snmp_exporter#551]
Hi all, i'm not sure i can open a issue for this behaviour but you will tell me :). I'm a simple network engineer so i'm sorry if my understanding of the snmp_exporter code is really limited.

### Host operating system: output of `uname -a`

Linux sys-d063323c.ctrl.cs 4.0.1-1-ARCH #1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.8.0 (branch: HEAD, revision: 17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)
  build user:       root@57f813d2791a
  build date:       20171120-12:36:57
  go version:       go1.9.2

### What device/snmpwalk OID are you using?

ltmVirtualServStatClientCurConns | 1.3.6.1.4.1.3375.2.2.10.2.3.1.12 from F5-BIGIP-LOCAL-MIB

### If this is a new device, please link to the MIB(s).

No it's a standart F5 LTM 

http://www.oidview.com/mibs/3375/F5-BIGIP-LOCAL-MIB.html

### What did you do that produced an error?

When i check the /metrics output from snmp_exporter for that target i can see this error.

```
collected metric "ltmVirtualServStatClientCurConns" { label:<name:"ltmVirtualServStatName" value:"/Common/ref-si-silo-cs-pdct-rp2web2app.private.sfr.com.app/vip-ref-si-silo-cs-pdct-rp2web2app.pri" > counter:<value:0 > } was collected before with the same name and label values
```

I should have two different metrics with two different "ltmVirtualServStatName" label value below:

```
/Common/ref-si-silo-cs-pdct-rp2web2app.private.sfr.com.app/vip-ref-si-silo-cs-pdct-rp2web2app.private.sfr.com_HTTP_extra
/Common/ref-si-silo-cs-pdct-rp2web2app.private.sfr.com.app/vip-ref-si-silo-cs-pdct-rp2web2app.private.sfr.com_HTTP_intra
```

but it seems that the "ltmVirtualServStatName" label_value is limited to "/Common/ref-si-silo-cs-pdct-rp2web2app.private.sfr.com.app/vip-ref-si-silo-cs-pdct-rp2web2app.pri" in the /metric output so the snmp_exporter is seeing the same metric two times and drop the error.

### What did you expect to see?

I have another F5 LTM in the cluster with the same configuration (but another version) and i can get two different metrics

```
ltmVirtualServStatClientCurConns{ltmVirtualServStatName="/Common/ref-si-silo-cs-pdct-rp2web2app.private.sfr.com.app/vip-ref-si-silo-cs-pdct-rp2web2a780a7faf"} 0
ltmVirtualServStatClientCurConns{ltmVirtualServStatName="/Common/ref-si-silo-cs-pdct-rp2web2app.private.sfr.com.app/vip-ref-si-silo-cs-pdct-rp2web2ac8889aed"} 0
```

This time it seems that the snmp_exporter is putting a random string at the end of the label ltmVirtualServStatName to make it unique

Do you have any idea why this is happening when the MIB used is the same on both devices?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
