### ISSUE TITLE
[RFE] IP protocol preference

### ISSUE THREAD

**Issue by M0NsTeRRR** [prometheus/snmp_exporter#552]
Hello,

I came across a problem today regarding Unifi devices that does not support Unifi OID in IPv6

```
snmpbulkwalk -v 2c -c <community> <IPv6> 1.3.6.1.2.1.2.2.1.7
iso.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.2 = INTEGER: 1
```

```
snmpbulkwalk -v 2c -c <community> <IPv6> 1.3.6.1.4.1.41112.1.6
iso.3.6.1.4.1.41112.1.6 = No Such Object available on this agent at this OID
```

```
snmpbulkwalk -v 2c -c <community> <IPv4> 1.3.6.1.4.1.41112.1.6
iso.3.6.1.4.1.24681.1.2.1.0 = STRING: "17.40 %"
iso.3.6.1.4.1.24681.1.2.9.1.1.1 = INTEGER: 1
iso.3.6.1.4.1.24681.1.2.9.1.2.1 = STRING: "eth0"
iso.3.6.1.4.1.24681.1.2.9.1.3.1 = Counter32: 325418
[...]
```

It would be possible to add an option for some devices like on blackbox-exporter to choose preferred IP protocol, to use hostname in targets ?

https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#http_probe
```
# The IP protocol of the HTTP probe (ip4, ip6).
[ preferred_ip_protocol: <string> | default = "ip6" ]
[ ip_protocol_fallback: <boolean> | default = true ]
```

Best regards,

PS : The exporter works like a charm, thanks for this amazing job :)

**Comment by SuperQ** [comment]
That's a pretty unfortunate device bug. For sure, it would be good to file a ticket with Ubiquity.

As a workaround, you can manipulate the IP / hostname in the Prometheus relabel configs. Not ideal, but it works. What service discovery method are you using?

**Comment by M0NsTeRRR** [comment]
Sure, but also some devices has dual stack but there are not fully compatible. For example I've an old QNAP TS-219P II that doesn't support SNMP in ipv6, at the moment I use the IPv4 as the target but It would be better if we get an option to force IPv4.

I don't use discovery method for the moment only static config

**Comment by brian-brazil** [comment]
I don't think that exporters should have configuration at this level, the SNMP exporter doesn't know that IP exists. If you want to use a specific address, then pass in that address.

**Comment by SuperQ** [comment]
In your example, if the QNAP doesn't support v6, and there is no AAAA DNS record, the snmp_exporter will work just fine.

Exposing AAAA DNS records to devices that don't support v6 doesn't seem like a Prometheus problem.

The Ubiquiti device having partial/broken support is a very weird edge case. IMO, I would disable v6 on the device until it's fixed.

**Comment by M0NsTeRRR** [comment]
> 
> 
> I don't think that exporters should have configuration at this level, the SNMP exporter doesn't know that IP exists. If you want to use a specific address, then pass in that address.

Blackbox-exporter is supporting this type of feature what's the difference ?

> 
> 
> In your example, if the QNAP doesn't support v6, and there is no AAAA DNS record, the snmp_exporter will work just fine.
> 
> Exposing AAAA DNS records to devices that don't support v6 doesn't seem like a Prometheus problem.
> 
> The Ubiquiti device having partial/broken support is a very weird edge case. IMO, I would disable v6 on the device until it's fixed.

He is not fully compatible, I can share files etc... via IPv6 but the SNMP server doesn't support IPv6

**Comment by brian-brazil** [comment]
> Blackbox-exporter is supporting this type of feature what's the difference ?

The blackbox exporter is designed to allow testing both v4 and v6 connectivity as an explicit feature. No whitebox exporter should need that.

> Exposing AAAA DNS records to devices that don't support v6 doesn't seem like a Prometheus problem.

Agreed.

**Comment by SuperQ** [comment]
Like I said above, these IPv4/IPv6 problems can be solved at the Prometheus discover time. You can send the correct address to the `__address__` meta-label, and the hostname to `instance`.

See: https://www.robustperception.io/controlling-the-instance-label

**Comment by M0NsTeRRR** [comment]
> 
> 
> Like I said above, these IPv4/IPv6 problems can be solved at the Prometheus discover time. You can send the correct address to the `__param_target` meta-label, and the hostname to `instance`.
> 
> Similar to: https://www.robustperception.io/controlling-the-instance-label

Sure or I can put the IP in target file but as you said it's not ideal but it works.

**Comment by brian-brazil** [comment]
Closing as this is a device bug, or an error in your DNS zone entry, depending on how you see it.
