### ISSUE TITLE
Support RFC 3430

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#555]
While it's not common, some devices do support [RFC 3430](https://tools.ietf.org/html/rfc3430), SNMP over TCP. The upstream gosnmp library supports this, so it should be an easy thing to add.

**Comment by Andy1616** [comment]
++ for that feature request

**Comment by hhromic** [comment]
Today I realised that we might need this feature and I am willing to implement it, if there is still interest for it.

Indeed the gosnmp library supports setting `tcp` for `Transport` here:
https://github.com/gosnmp/gosnmp/blob/33df32e33fbd043727a4a117a0ef6f2183607113/gosnmp.go#L57-L58

Given that this is pretty much settable together with `Target`, I propose to add a new optional request query parameter `transport` to the `/snmp` scrape endpoint that, when provided, allows to set the underlying `Transport` attribute in gosnmp. If not provided, then `Transport` would be left untouched and will default to the current `udp` default. Therefore, making it 100% backwards compatible. What do you think of this implementation proposal?

**Comment by SuperQ** [comment]
Not something for a query parameter, but should be part of the `auths`.

**Comment by hhromic** [comment]
Hi @SuperQ , thanks for replying!
I'm not very familiar yet with the upcoming auth split, however from what I saw in the [migration guide](https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md), I'm not sure how the connection transport is related to authentication configuration?

Transport (and `host:port` target configuration) should not be part of any static auth configuration as the same device can be configured for both udp/tcp.

In my humble opinion, transport should be actually part of `target`, for example in the form of a scheme. For example:
* `tcp://host:port`
* `udp://host:port`
* `host:port` (defaults to UDP as of today).

For example in Net SNMP ([manpage](http://www.net-snmp.org/docs/man/snmpcmd.html) - Agent Specification section), the syntax is `[<transport-specifier>:]<transport-address>`.

Or in Keepalived ([manpage](https://manpages.debian.org/unstable/keepalived/keepalived.conf.5.en.html) - `snmp_socket` keyword), the syntax is a similar `[transport:]host[:port]`.

Perhaps the SNMP Exporter should also use `[<transport-specifier>:]<transport-address>` ?
This would even make the SNMP Exporter future-proof for other transports such as Unix sockets.

**Comment by SuperQ** [comment]
The `host:port` is already set via the `target` param. We currently default the port to 161 in case there is no port specified in the target. See [collector.go](https://github.com/prometheus/snmp_exporter/blob/636f1fa98e04feb67990170ead602e02d6a570c6/collector/collector.go#L120-L121).

I would be in favor of URL handling here, since we can do simple operations like:
```
tcpTarget, tcpTargetFound := stings.CutPrefix("tcp://", target)
udpTarget, udpTargetFound := stings.CutPrefix("udp://", target)
```

Might be worth breaking out the `target` string parsing into a function that returns `(transport string, target string, port int)` or something like that.

**Comment by hhromic** [comment]
Yes, I'm aware of the `target` parsing on the `collector.go` file, that's why I later suggested using URL parsing.
Great that we are on the same page then with that part 👍.

This brings me another follow-up design question. Instead of hard-coding specific transports (udp/tcp), the gosnmp library can actually work with a wider range of transports than only udp/tcp. In fact, another very common transport are Unix sockets.

From: https://github.com/gosnmp/gosnmp/blob/33df32e33fbd043727a4a117a0ef6f2183607113/gosnmp.go#L285-L290
```
// https://golang.org/pkg/net/#Dial gives acceptable network values as:
//   "tcp", "tcp4" (IPv4-only), "tcp6" (IPv6-only), "udp", "udp4" (IPv4-only),"udp6" (IPv6-only), "ip",
//   "ip4" (IPv4-only), "ip6" (IPv6-only), "unix", "unixgram" and "unixpacket"
```

If we do proper [URL parsing](https://pkg.go.dev/net/url#ParseRequestURI), we can then pass _any_ scheme provided in `target` down and delegate transport validation to gosnmp. This would allow the SNMP exporter to support any transports that gosnmp supports transparently.

> Might be worth breaking out the `target` string parsing into a function that returns `(transport string, target string, port int)` or something like that.

I fully agree with that idea and considering the above, I suggest on a function like this:
```go
func parseTarget(target string) (*url.URL, error) {
    // The ugly part here is backwards compatibility.
    // If "target" does not have a scheme:// then we should add a default udp:// one to "target" before parsing.
    // This would require a regex prefix matching if we go the "generalized" route or
    // use simple rule-matching for all the supported schemes.
    return url.ParseRequestURI(target)
}
```

Then the collector can easily extract the parts or error out if target is invalid:
```go
u, err := parseTarget(target)

transport := u.Scheme
host := u.Host()
port := u:Port()
```

What do you think?

**Comment by SuperQ** [comment]
Yea, that kind of complexity is why I would prefer to have it be part of the config.

In our new config system we can do something like this:
```yaml
auths:
  tcp_public_v2:
    community: public
    version: 2
    transport: tcp
```

We can then pass in all of the transport options directly.

But, we could also go with `strings.SplitN(target, "://", 1)` and pass whatever prefix string to `Transport`.

**Comment by hhromic** [comment]
I _really_ don't think is a good idea to mix transport configuration with authentication.
The generator would have to provide combinations of udp/tcp configurations (and future ones) for every auth type.

> But, we could also go with `strings.SplitN(target, "://", 1)` and pass whatever prefix string to `Transport`.

Yeah maybe that is a good idea indeed, to not assume a "general URL" and avoid formal URL parsing which can get tricky.

Basically the contract for the `target` parameter would be `[transport://]host[:port]` and nothing else.
This would indeed simplify the parsing (no regex matchings) and is easy to validate.

If you are okay with that, I am happy to implement this.

**Comment by SuperQ** [comment]
Sounds like a good plan to me.
