### ISSUE TITLE
0.19.0 broke snmp.yml generation

### ISSUE THREAD

**Issue by nugored** [prometheus/snmp_exporter#560]
With the update(0.19.0) snmp-generator brokes snmp.yml sytnax
Check out enum_values positions (part of snmp.yml generated with 0.19.0):
```
    - labelname: tempSensorType
      type: gauge
      enum_values:
       	1: common
        2: housing
        3: rack
        4: cpu
    - labelname: tempSensorId
      type: gauge
    enum_values:
      1: common
      2: housing
      3: rack
      4: cpu
```

### Host operating system: output of `uname -a`
Linux prometheus_host 4.4.190-1.el7.elrepo.x86_64 #1 SMP Sun Aug 25 07:32:44 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: 
0.19.0

### What device/snmpwalk OID are you using?
Doesn't matter

### What did you do that produced an error?
Ran snmp-generator with the latest **docker** image.

### What did you expect to see?
```
prometheus snmp_exporter: level=info ts=2020-09-01T08:43:02.484Z caller=main.go:181 msg="Loaded config file"
```

### What did you see instead?
```
prometheus snmp_exporter: level=error ts=2020-09-01T08:14:48.823Z caller=main.go:156 msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 4277: field enum_values not found in type config.Index\n  line 4296: field enum_values not found in type config.Index\n
```

**Comment by brian-brazil** [comment]
You need to use snmp exporter 0.19.0, which is why it was released. In general if you have this sort of issue, make sure you're using the latest generator and exporter.

**Comment by nugored** [comment]
Sorry for long response. Yes, you are right. By mistake, I've got not the latest snmp_exporter version. Made some checks and found it out. Sorry for inconvenience. My apologies.
