### ISSUE TITLE
cant add APC Swtiched Rack PDU 

### ISSUE THREAD

**Issue by cb1234** [prometheus/snmp_exporter#577]
### What device/snmpwalk OID are you using?
modules:

  apcpdu:
    version: 1
    walk:
      - .1.3.6.1.4.1.318.1.1.26.2.1.3    # rPDU2IdentName
      - .1.3.6.1.4.1.318.1.1.26.2.1.4    # rPDU2IdentLocation
      - .1.3.6.1.4.1.318.1.1.26.2.1.8    # rPDU2IdentModelNumber
      - .1.3.6.1.4.1.318.1.1.26.2.1.9    # rPDU2IdentSerialNumber
      - .1.3.6.1.4.1.318.1.1.26.4.3.1.4  # rPDU2DeviceStatusLoadState
      - 1.3.6.1.4.1.318.1.1.26.4.3.1.5  # rPDU2DeviceStatusPower
      - 1.3.6.1.4.1.318.1.1.26.4.3.1.6  # rPDU2DeviceStatusPeakPower
      - 1.3.6.1.4.1.318.1.1.26.4.3.1.9  # rPDU2DeviceStatusEnergy
      - 1.3.6.1.4.1.318.1.1.26.4.3.1.12 # rPDU2DeviceStatusPowerSupplyAlarm
      - 1.3.6.1.4.1.318.1.1.26.4.3.1.13 # rPDU2DeviceStatusPowerSupply1Status
      - 1.3.6.1.4.1.318.1.1.26.4.3.1.14 # rPDU2DeviceStatusPowerSupply2Status
      - 1.3.6.1.4.1.318.1.1.26.4.3.1.16 # rPDU2DeviceStatusApparentPower### If this is a new device, please link to the MIB(s).

### What did you do that produced an error?
generate doesnt build the snmp.yml file. i am using this mibs. https://www.se.com/us/en/download/document/APC_POWERNETMIB_432/

a successful snmp.yml file
### What did you see instead? ./generator generate
level=info ts=2020-11-02T18:06:50.747Z caller=net_snmp.go:142 msg="Loading MIBs" from=../mibs/apc/powernet432.mib
level=info ts=2020-11-02T18:06:50.752Z caller=main.go:52 msg="Generating config for module" module=apcpdu
level=error ts=2020-11-02T18:06:50.752Z caller=main.go:130 msg="Error generating config netsnmp" err="cannot find oid '.1.3.6.1.4.1.318.1.1.26.2.1.3' to walk"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
