### ISSUE TITLE
SNMP generator - Checkpoint mibs

### ISSUE THREAD

**Issue by vmazyliukTW** [prometheus/snmp_exporter#581]
Hey!
I have an issue with checkpoint mibs taken from here: https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk90470

Trying to generate config from checkpoint mibs and receiving huge amount of errors:

`root@ubuntu:~/go/src/github.com/prometheus/snmp_exporter/generator# ./generator parse_errors | wc -l

level=info ts=2020-11-19T13:26:00.958Z caller=net_snmp.go:142 msg="Loading MIBs" from=mibs 
level=warn ts=2020-11-19T13:26:00.969Z caller=main.go:120 msg="NetSNMP reported parse error(s)" errors=4356 
4356 `

Errors look like this:
`
...
id not find 'fwLSConnOverallDesc' in module CHECKPOINT-MIB (mibs/chkpnt-trap.mib)
Did not find 'fwLocalLoggingDesc' in module CHECKPOINT-MIB (mibs/chkpnt-trap.mib)
Did not find 'fwLocalLoggingStat' in module CHECKPOINT-MIB (mibs/chkpnt-trap.mib)
Did not find 'fwLocalLoggingDesc' in module CHECKPOINT-MIB (mibs/chkpnt-trap.mib)
Did not find 'fwLocalLoggingStat' in module CHECKPOINT-MIB (mibs/chkpnt-trap.mib)
Did not find 'fwLocalLoggingDesc' in module CHECKPOINT-MIB (mibs/chkpnt-trap.mib)
Did not find 'fwLocalLoggingStat' in module CHECKPOINT-MIB (mibs/chkpnt-trap.mib)
Unlinked OID in CHECKPOINT-TRAP-MIB: checkpoint ::= { enterprises 2620 }
Undefined identifier: enterprises near line 67 of mibs/chkpnt-trap.mib
Cannot adopt OID in CHECKPOINT-MIB: memDiskTransfers64 ::= { svnMem64 7 }
Cannot adopt OID in CHECKPOINT-MIB: memSwapsSec64 ::= { svnMem64 6 }
Cannot adopt OID in CHECKPOINT-MIB: memFreeReal64 ::= { svnMem64 5 }
Cannot adopt OID in CHECKPOINT-MIB: memActiveReal64 ::= { svnMem64 4 }
...`

### Host operating system: 
Linux ubuntu 4.15.0-47-generic x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: 
don't use it

### What device/snmpwalk OID are you using?
checkpoint R80.40

### If this is a new device, please link to the MIB(s).
https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk90470

### What did you do that produced an error?
./generator generate

### What did you expect to see?
snmp.yml generated successfully

### What did you see instead?
errors

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by vmazyliukTW** [comment]
Ok sure
