### ISSUE TITLE
Feature Request: Way to tie ipAdEntAddr to interface metrics

### ISSUE THREAD

**Issue by loganmc10** [prometheus/snmp_exporter#583]
### Host operating system: output of `uname -a`

Docker container, latest

### snmp_exporter version: output of `snmp_exporter -version`

Docker container, latest

### What device/snmpwalk OID are you using?

ifHCOutOctets, trying to include ipAdEntAddr (1.3.6.1.2.1.4.20.1.1) as a label

### What did you see?

I don't think there is currently a way to link ipAdEntAddr as a label to interface stats like ifHCOutOctets. ipAdEntAddr is part of the table ipAddrTable. The index for this table is ipAdEntAddr itself. However the table has an entry called ipAdEntIfIndex, which ties/is equal to the ifIndex value of ifHCOutOctets. I don't currently see a way to link ipAdEntAddr with ifHCOutOctets

**Comment by loganmc10** [comment]
The reason the indexes work this way (it seems like they are backwards) is because there could be multiple IP addresses associated to each physical interface/ifIndex, but it would be nice to be able to add each IP address as a label to the interface statistics

**Comment by brian-brazil** [comment]
> it would be nice to be able to add each IP address as a label to the interface statistics

You're not going to be able to do that in the snmp exporter, as all the lookup stuff can't create more than one series per oid. This is a matter for PromQL's group_left.

**Comment by loganmc10** [comment]
I wouldn't want it to create multiple series per OID (I'm using Grafana Cloud and I pay by the series). Rather, I would want it to attach multiple labels to the series, something like "ipAdEntAddr_1", "ipAdEntAddr_2", etc..

Basically for it to be able to match up ipAdEntIfIndex and ifIndex, and then attach all valid ipAdEntAddr entries to the series as labels

**Comment by SuperQ** [comment]
FYI: `ipAddrTable` has been deprecated since 2006.

**Comment by loganmc10** [comment]
True, although many devices still support it, the same comment applies to the newer ipAddressTable (1.3.6.1.2.1.4.34), it is organized in the same fashion, where the index of that table is the IP address, and the table includes ipAddressIfIndex, which corresponds to the ifIndex of the interface.

So the general problem would still require the same solution.

**Comment by brian-brazil** [comment]
As I said, the solution for this is in PromQL not the snmp exporter. The snmp exporter only does 1:1 mappings.

**Comment by loganmc10** [comment]
I understand it doesn't do it today, that's why I labelled this as a feature request. You're saying it's not possible or not going to ever happen so this can be closed?

**Comment by brian-brazil** [comment]
Not going to happen, the lookup code is hairy enough as-is without adding in the risks and complexity associated with cardinality explosions from doing such expansion here - which PromQL won't let you do.

It's not reasonable for ifHCOutOctets to take a label from ipAdEntAddr, any lookups would have to be the other way around which you can already do.

**Comment by SuperQ** [comment]
I thought about this a bit, and I agree with Brian. I don't see an easy way to fix this on the exporter side. This is a one-to-many problem, that is more easily solved in PromQL.

One solution, is you could add a recording rule for the PromQL join, and configure your `remote_write` to drop the raw metrics from being sent to Grafana Cloud.

**Comment by loganmc10** [comment]
No worries, it's something I can probably just put into a SQL database and query. I'm using the Grafana Cloud Agent, so it doesn't support doing recording rules before they hit Grafana Cloud (and get billed)

**Comment by brian-brazil** [comment]
It'd be cheaper to do it all at query time then in any case, as you're not duplicating stored ifHCOutOctets series.
