### ISSUE TITLE
lldpRemPortId not being displayed correctly in some cases

### ISSUE THREAD

**Issue by loganmc10** [prometheus/snmp_exporter#584]
### Host operating system: output of `uname -a`

Latest docker container

### snmp_exporter version: output of `snmp_exporter -version`

Latest docker container

### What device/snmpwalk OID are you using?

1.0.8802.1.1.2.1.4.1 (lldpRemTable)
1.0.8802.1.1.2.1.4.1.1.7 (lldpRemPortId)

### What did you do that produced an error?
When doing:
```
  l2_info:
    walk:
      - lldpRemTable
```
The output for lldpRemPortId looks like this:
```
lldpRemPortId{lldpRemIndex="12582",lldpRemLocalPortNum="238",lldpRemPortId="Gi0",lldpRemTimeMark="0"} 1
```
The output correctly shows the lldpRemPortId as Gi0

But when doing:
```
  l2_info:
    walk:
      - lldpRemPortId
```
The output for lldpRemPortId looks like this:
```
lldpRemPortId{lldpRemIndex="12582",lldpRemLocalPortNum="238",lldpRemPortId="0x476930",lldpRemTimeMark="0"} 1
```
The output incorrectly shows the lldpRemPortId as 0x476930 (which is the hexadecimal version of Gi0 in utf8)

**Comment by brian-brazil** [comment]
There's not enough information here, can you share what an snmpwalk produces and what the snmp.yml is? Most likely the issue is that you've not included the SubType for walking, so we can't determine what is in lldpRemPortId.

**Comment by loganmc10** [comment]
Yes you are correct, I had to pull in ```lldpLocPortIdSubtype``` as a lookup for lldpRemPortId. Sorry, I wasn't aware that this Subtype system existed for some OIDs

**Comment by brian-brazil** [comment]
Yeah, that's how the lldpPortId syntax works. We do have code in the snmp exporter&generator to handle it, but in this case it should been extending the walk to include the subtype automatically. Feel free to send a PR fixing that.

**Comment by loganmc10** [comment]
Ok I may in the future, there are a few other things that would be nice as well, for instance, if you try to pull in another item in that table (lldpRemSysName for instance), and add lldpLocPortId and lldpLocPortIdSubtype as lookups, it won't properly resolve lldpLocPortId, it only works when lldpLocPortId is the metric

**Comment by brian-brazil** [comment]
That's meant to work, so that's likely a configuration error. In particular the subtype must always be right before the associated PortId.
