### ISSUE TITLE
Fortigate OIDs problem

### ISSUE THREAD

**Issue by UAnton** [prometheus/snmp_exporter#603]
### Host operating system: output of `uname -a`
Linux prometheus 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
last

### What device/snmpwalk OID are you using?
Fortigate
### If this is a new device, please link to the MIB(s).
https://help.fortinet.com/fmgr/50hlp/56/5-6-1/FMG-FAZ/2400_System_Settings/2400_Advanced/0220_SNMP%20MIBs.htm
### What did you do that produced an error?

Try to generate snmp.yaml

### What did you expect to see?
Generated snmp.yaml

### What did you see instead?
Error:
root@prometheus:~/go/src/github.com/prometheus/snmp_exporter/generator# ./generator generate
level=info ts=2021-01-22T13:26:32.893Z caller=net_snmp.go:144 msg="Loading MIBs" from=$HOME/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf
level=warn ts=2021-01-22T13:26:32.912Z caller=main.go:120 msg="NetSNMP reported parse error(s)" errors=3595
level=info ts=2021-01-22T13:26:32.912Z caller=main.go:52 msg="Generating config for module" module=FORTINET-FORTIGATE-MIB
level=error ts=2021-01-22T13:26:32.912Z caller=main.go:130 msg="Error generating config netsnmp" err="cannot find oid '1.3.6.1.4.1.12356.101' to walk"

I try 50+ OIDs but all = err="cannot find oid"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by amitkatti** [comment]
Was there a resolution to this?

**Comment by UAnton** [comment]
> Was there a resolution to this?

Wrong OIDs. Use OID Explorer for correct OID
