### ISSUE TITLE
invaild UTF-8 string cause the whole job fail

### ISSUE THREAD

**Issue by DadaHiT** [prometheus/snmp_exporter#637]
### Host operating system: output of `uname -a`

docker running on macOS

### snmp_exporter version: output of `snmp_exporter -version`

0.20.0

### What device/snmpwalk OID are you using?

1.3.6.1.4.1.14179.2.1.7.1.11    # bsnRogueAPSSID

### What did you do that produced an error?
When the SSID is something not UTF-8, the whole job will fail.

Below is the error message 

```
error collecting metric Desc{fqName: "snmp_error", help: "Error calling NewConstMetric", constLabels: {}, variableLabels: []}: error for metric bsnRogueAPSSID with labels [38:AD:8E:97:DD:83 LSAVSL��������] from indexOids [56 173 142 151 221 131]: label value "LSAVSL\xbf\xd8\xd6\xc6\xcd\xf8\xc2\xe7" is not valid UTF-8
```

### What did you expect to see?

Can we delete the invalid UTF-8 string or do something else instead of failing the whole job?

**Comment by SuperQ** [comment]
We could sanitize the strings like we did here: https://github.com/prometheus/node_exporter/pull/1984

But, there are still issues, there could be duplicate metrics if the squashed strings are identical.

**Comment by zhucan** [comment]
The same issue with me, like this:
![image](https://user-images.githubusercontent.com/13997135/118605302-b1e80280-b7e8-11eb-9ac6-f03a02d33c64.png)

**Comment by nathandiruggiero** [comment]
I have the same problem and I don’t know how to solve this UTF-8 :(

![image](https://user-images.githubusercontent.com/58921322/119109625-9fa4d900-ba21-11eb-9f81-b2a48255fc07.png)

**Comment by sford** [comment]
I ran into something similar:
```
error collecting metric Desc{fqName: "snmp_error", help: "Error calling NewConstMetric", constLabels: {}, variableLabels: []}: error for metric fgHwSensorEntName with labels [129 ?] from indexOids [129]: label value "\x89" is not valid UTF-8
```

When I run `snmpwalk` to get the raw data, it is pretty clear that something invalid is being returned from the device:
```
iso.3.6.1.4.1.12356.101.4.3.2.1.2.3 = STRING: "Ext_temp"
iso.3.6.1.4.1.12356.101.4.3.2.1.2.4 = STRING: "Fan_temp"
...
iso.3.6.1.4.1.12356.101.4.3.2.1.2.128 = ""
iso.3.6.1.4.1.12356.101.4.3.2.1.2.129 = Hex-STRING: 89 
iso.3.6.1.4.1.12356.101.4.3.2.1.2.130 = ""
```

Some `Hex-String` with invalid UTF-8 is present for whatever reason.

I am pretty certain this is a device bug.

I am working around this device bug by configuring `snmp_exporter` to ignore this data:
```
fgHwSensorEntName:
        ignore: true
```

It isn't optimal to ignore the entire metric, but it works. I don't know `snmp_exporter` well enough to know if there are other better ways to handle this.

**Comment by SuperQ** [comment]
This is now fixed.
