### ISSUE TITLE
SNMP Generator issue

### ISSUE THREAD

**Issue by pratik322** [prometheus/snmp_exporter#642]
Hi All,

Trying to monitor the HP Switch CPU Usage metric scrapping (OID and module mentioned below); We are not able to generate the snmp configuration file while giving the OIDs of 25506 group in prometheus server (where we installed the snmp exporter)

![unnamed](https://user-images.githubusercontent.com/29014771/114273934-d0185100-9a39-11eb-9df0-aefd01dc0ee7.jpg)

But, doing the snmp walk with same OIDs,switch is generating the response for these metrics.

Need help in understanding what we are missing while generating the snmp.yml file ?

OIDS trying to scrape.

1.3.6.1.4.1.25506.2.6.1.1.1.1.6.74
1.3.6.1.4.1.25506.2.6.1.1.1.1.6.81

 HP Network Switch Details:

 Switch Info : HP Comware Platform Software, Software Version 5.20.99 Release 5501P10-US HP A5500-48G-4SFP HI Switch with 2 interface Slots Copyright (c) 2010-2015 Hewlett-Packard Development Company, L.P

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
