### ISSUE TITLE
SNMP Query success sometime but Target shows the SNMP agent is down （Actually it is up all the time）

### ISSUE THREAD

**Issue by houchunzhong** [prometheus/snmp_exporter#643]
### Host operating system: output of `uname -a`
Linux prometheus.cloud.bbdops.com 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### What device/snmpwalk OID are you using?
huawei , cisco  snmp-finder, 

### If this is a new device, please link to the MIB(s).
HUAWEI-ENTITY-EXTENT-MIB.mib           HUAWEI-SECURITY-STAT-MIB.mib        OSPF-TRAP-MIB.mib
HUAWEI-ENTITY-TRAP-MIB.mib  
### What did you do that produced an error?
Query for the device SNMP OID information
### What did you expect to see?
can see the output for OID results

### What did you see instead?
![image](https://user-images.githubusercontent.com/22065653/114333432-d530e980-9b7a-11eb-8f10-63a41711543e.png)

**Comment by houchunzhong** [comment]
Currently can find the SNMP Expoter version via commands
![image](https://user-images.githubusercontent.com/22065653/114333938-1a095000-9b7c-11eb-92fc-e8e3702a9214.png)

**Comment by houchunzhong** [comment]
the SNMP agent devcies are compose of Huawei S6700 and S5700 switches and AR3200 routers. I upload them to the mibs, but when using SNMP generator to build, it seems the snmp.yml file doesn't consist Huawei OIDs infor.  Please elighten me to find a path the go through. 
![image](https://user-images.githubusercontent.com/22065653/114334309-e3800500-9b7c-11eb-83f0-8c7dbf174e61.png)

**Comment by houchunzhong** [comment]
When using  SNMP expoter ,huawei switch is able to reponse with OIDs query  results. 
![image](https://user-images.githubusercontent.com/22065653/114334699-b8e27c00-9b7d-11eb-80d8-fc8bb7f6a097.png)
![image](https://user-images.githubusercontent.com/22065653/114334752-d1eb2d00-9b7d-11eb-9f58-2fa2635fed73.png)

**Comment by houchunzhong** [comment]
The Major issue is Can Not get the SNMP target up.
the proemethemus.yml configured as below:

# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.28.119.205:9090']
      labels:
        instance: prometheus
  - job_name: 'snmp_exporter'
    scrape_interval: 10s
    static_configs:
    - targets: ['10.28.116.251']
      labels:
        instance: snmp_exporter
    metrics_path: /snmp
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 10.28.119.205:9116 # snmp_exporter server IP 
[root@prometheus config]#

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
