### ISSUE TITLE
Go port transition handling: Print warning and count errors up when using old URL scheme

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#65]
If some configs still use `/metrics?address` instead of `snmp?target`, the new version will silently discard the request, printing neither an error nor counting up error counters. Go metrics are returned and nothing else.

It would be better to make users aware of this other than through the docs.

**Comment by brian-brazil** [comment]
I'm not sure there's much we can do here, this endpoint is handled by the Prometheus client library now.

**Comment by RichiH** [comment]
You could parse the parameters by hand in parallel, but that sounds icky even typing it...

**Comment by brian-brazil** [comment]
Yeah, it will be fairly obvious when you aren't seeing the metrics you expect hopefully.
