### ISSUE TITLE
SNMP Exporter (prometheus) + dont print all OID

### ISSUE THREAD

**Issue by hunterfff** [prometheus/snmp_exporter#652]
I'm new on Prometheus and i'm trying to monitor some extend OID of BASTION-WALLIX I created with the snmp_exporter, but it doesn't work as expected.

I installed snmp v3 using the helm charts.
At the end I generated the snmp.ymal file.
![image](https://user-images.githubusercontent.com/43753186/116689545-91cadd80-a9b8-11eb-88a7-75312e9d3074.png)

then I copied the content of snmp.ymal into values.yaml 

![image](https://user-images.githubusercontent.com/43753186/116689261-284acf00-a9b8-11eb-9454-7e61bbc10565.png)

and i ran this command:
helm upgrade prometheus-snmp-exporter prometheus-community/prometheus-snmp-exporter -f values.yaml -n extmon-secops-prod.
I configured prometheus but I couldn't get the metrics back:
http://localhost:9116/snmp?target=10.10.160.10&module=WALLIX-BASTION-MIB

![image](https://user-images.githubusercontent.com/43753186/116689032-d86c0800-a9b7-11eb-8b74-199c316e5452.png)

any help please !

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
