### ISSUE TITLE
ipNetToPhysicalState not detecting proper indexes

### ISSUE THREAD

**Issue by loganmc10** [prometheus/snmp_exporter#655]
When using the generator to walk ipNetToPhysicalState, this is what gets put into snmp.yml:
```
  - name: ipNetToPhysicalState
    oid: 1.3.6.1.2.1.4.35.1.7
    type: gauge
    help: The Neighbor Unreachability Detection state for the interface when the address
      mapping in this entry is used - 1.3.6.1.2.1.4.35.1.7
    indexes:
    - labelname: ipNetToPhysicalIfIndex
      type: gauge
    - labelname: ipNetToPhysicalNetAddress
      type: InetAddress
    enum_values:
      1: reachable
      2: stale
      3: delay
      4: probe
      5: invalid
      6: unknown
      7: incomplete
```

However it's missing an index (ipNetToPhysicalNetAddressType):
```
INDEX { ipNetToPhysicalIfIndex,
ipNetToPhysicalNetAddressType,
ipNetToPhysicalNetAddress }
```

**Comment by loganmc10** [comment]
This happens for any entry in ipNetToPhysicalTable, as well as talking ipNetToPhysicalTable itself, it never includes ipNetToPhysicalNetAddressType as one of the indexes, so polling the OIDs doesn't work

**Comment by loganmc10** [comment]
hm I don't know what I did differently, but the query does seem to work:

```
ipNetToPhysicalState{ipNetToPhysicalIfIndex="144",ipNetToPhysicalNetAddress="1xx.4x.1xx.x2"} 1
```

However it is missing the ```ipNetToPhysicalNetAddressType``` index, so something is still not quite right

**Comment by SuperQ** [comment]
The exporter/generator automatically handle the `InetAddressType,InetAddress` combo as a single index. Since the Type is just a hint to what the next bytes will be.

**Comment by loganmc10** [comment]
Ok thanks I think I've got it now. That should maybe be documented somewhere, it makes it a bit confusing when you want to do a lookup and have to specify the source_indexes
