### ISSUE TITLE
Support return JSON format

### ISSUE THREAD

**Issue by tuanden0** [prometheus/snmp_exporter#663]
Hello Sir,

Could you guys support return json format in query_params such as ?json=true or ?format=json

THen people can use only SNMP_Exporter to get SNMP information without Prometheus.

Thank for your help.

**Comment by SuperQ** [comment]
Sorry, this is not possible with the metrics library we use. There are many options for parsing Prometheus format into whatever code you want. 

For example [in Python](https://github.com/prometheus/client_python#parser) and [in Go](https://pkg.go.dev/github.com/prometheus/common@v0.25.0/expfmt).
