### ISSUE TITLE
context deadline exceeded issue

### ISSUE THREAD

**Issue by tnrms007** [prometheus/snmp_exporter#668]
hi every one

The snmp exporter yml file normally, but a **context dead line error** occurs. Can you figure out why the error occurs..?
thank you..

<img width="932" alt="1" src="https://user-images.githubusercontent.com/80308035/122343581-d1598300-cf80-11eb-832c-e56d386b33f3.png">

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by tnrms007** [comment]
this ticket close plz
i solved..
snmp_exporter need to golang.. 
thank you

**Comment by Raymondmax** [comment]
@tnrms007 may I know what do you mean "need to golang"?
