### ISSUE TITLE
Port error

### ISSUE THREAD

**Issue by tnrms007** [prometheus/snmp_exporter#669]
hello everyone..

snmp_exporter error

A 400 Bad Request error occurs.. When I check the snmp_exporter log, the error caller=main.go:245 msg="Error starting HTTP server" err="listen tcp :9116: bind: address already in use" occurs. can you help??

thank you..

**Comment by RichiH** [comment]
Please ask support questions on our Discourse: https://discuss.prometheus.io/

That being said, you're running two instances of snmp_exporter and need to stop the other one, first.
