### ISSUE TITLE
Support HUP signal configuration reloading

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#68]
It would be nice to support configuration reload via SIGHUP.

**Comment by Colstuwjx** [comment]
Sorry, It seems that we don't have to support reload configuration since each request will [load the configuration](https://github.com/prometheus/snmp_exporter/blob/master/main.go#L53) by itself.

**Comment by SuperQ** [comment]
Ahh, I missed that.

**Comment by brian-brazil** [comment]
We should still support it to be in line with other components, but it's not urgent.

**Comment by brian-brazil** [comment]
#179
