### ISSUE TITLE
Snmp_exporter service is down

### ISSUE THREAD

**Issue by Musekhan** [prometheus/snmp_exporter#690]
Hi,

I have recently installed snmp_exporter generator, which is generating the snmp_exporter file.
But this service shows failed. I have tried to change the systemd file and give various paths. Also moved the snmp.yml file to different location but still service is failed Following is the output. Can any one help?

root@grafana:~# systemctl status snmp-exporter.service
● snmp-exporter.service - Prometheus SNMP Exporter Service
     Loaded: loaded (/etc/systemd/system/snmp-exporter.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-10-12 13:07:18 +04; 8s ago
    Process: 469550 ExecStart=/usr/local/bin/snmp_exporter --config.file=/usr/local/bin/snmp.yml (code=exited, status=203/EXEC)
   Main PID: 469550 (code=exited, status=203/EXEC)

Oct 12 13:07:18 grafana systemd[1]: Started Prometheus SNMP Exporter Service.
Oct 12 13:07:18 grafana systemd[469550]: snmp-exporter.service: Failed to execute command: Exec format error
Oct 12 13:07:18 grafana systemd[469550]: snmp-exporter.service: Failed at step EXEC spawning /usr/local/bin/snmp_exporter: Exec format error
Oct 12 13:07:18 grafana systemd[1]: snmp-exporter.service: Main process exited, code=exited, status=203/EXEC
Oct 12 13:07:18 grafana systemd[1]: snmp-exporter.service: Failed with result 'exit-code'.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
