### ISSUE TITLE
help: add label sysName

### ISSUE THREAD

**Issue by fthsnr** [prometheus/snmp_exporter#696]
I have a sysName label. I want to add this sysName label as a label of ifInOctets metric. I try to add the label but the label seems to be null. It is important for me because there is a lot of target. Can you help me?
![image](https://user-images.githubusercontent.com/93157472/138765308-dcdd4663-601e-4474-a7c1-828100206e7e.png)
![image](https://user-images.githubusercontent.com/93157472/138765365-98a6e5d1-5161-406c-8c76-620812e9586d.png)

**Comment by cassidy3** [comment]
Hey there! I see you marked this as completed. Could you please share your solution? I've been playing around with this exporter and trying to figure out why label lookups aren't working for me; I was able to get a temporary fix in place by using a _much_ older image after seeing #729, but I'm at a loss as to why I'm not able to complete lookups on the current version of the application.

If you could share any insight you've had into that, I'd greatly appreciate it!
