### ISSUE TITLE
Support equipment responding from different source address

### ISSUE THREAD

**Issue by tobbez** [prometheus/snmp_exporter#699]
Some equipment responds using a different source address than the address SNMP request was sent to.

Such equipment can currently not be monitored using snmp_exporter (which fails with `request timeout (after 3 retries)`).

The required functionality appears to already be present in gosnmp (controlled by the `UseUnconnectedUDPSocket` option), but is not used/exposed by snmp_exporter right now.

Could support for this be added, and if so, how? (per-scrape request parameter/command line flag/always enabled)

**Comment by SuperQ** [comment]
I think this would need to be a flag, since it changes the listening socket behavior.

**Comment by RichiH** [comment]
In your experience, is this per group of devices? Making this part of the configuration per module seems to be cleanest.

I am not against changing the default, but I think what would require a major version bump and some time for the new behavior to be tested. At the least, we should cut a new minor release for it.

**Comment by tobbez** [comment]
In my limited experience it is indeed only specific (groups of) devices, so adding this to the module configuration would make sense (so that's what the PR does).

It would of course be convenient if this behavior was eventually made default (no need for a custom snmp.yml; devices like these "just working" if they work with `snmpwalk`), but as you say that'd need further consideration (which can be left for the future for now).
