### ISSUE TITLE
`snmp_oids_walked` is missing in Go version

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#71]
The Python version used to expose `snmp_oids_walked`, the Go version does not. It's quite a useful metric to us, so we would love to have it back :)

**Comment by brian-brazil** [comment]
It's called snmp_scrape_pdus_returned now.

**Comment by RichiH** [comment]
Even better. Thanks! Can't close cause mobile.

Richard

Sent by mobile; excuse my brevity.
