### ISSUE TITLE
Generator skips metrics in snmp.yml

### ISSUE THREAD

**Issue by aleksandrbog** [prometheus/snmp_exporter#710]
Try to generate snmp.yml. Here is part of generator file -> 
generator.yml 
  cimc-memory:
    walk:
      - cucsMemoryUnitInstanceId
      - cucsMemoryUnitCapacity
      - cucsMemoryUnitSerial
      - cucsMemoryUnitRn
      - cucsMemoryUnitLocation
      - cucsMemoryUnitClock
      - cucsMemoryUnitLatency
      - cucsMemoryUnitSpeed
      - cucsMemoryUnitOperState
snmp.yml doesn't contain metric with name cucsMemoryUnitOperState. 
Other metrics present, Mib file contains all metrics.
Have any advice?

**Comment by aleksandrbog** [comment]
[](url)

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
