### ISSUE TITLE
snmp.yml with custom OID .

### ISSUE THREAD

**Issue by ishworkhanal900** [prometheus/snmp_exporter#712]
We have a some custom OID for a device which do not have MIB files.
How can I create snmp.yml to just walk only these OID ?

**Comment by xkilian** [comment]
Create your own mib file.. welcome to the 90's, lol. Joking aside, not overly complexe, google it.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
