### ISSUE TITLE
Juniper support missing

### ISSUE THREAD

**Issue by cmarasescu** [prometheus/snmp_exporter#719]
Hello,

Can you add support for Juniper devices also?

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by BeArchiTek** [comment]
Hello @cmarasescu ,

For juniper device, I would recommend you to check https://github.com/czerwonk/junos_exporter.

Regards,

**Comment by W-IT-is** [comment]
Hello @cmarasescu 

Juniper devices are supported - what are you looking for exactly?    
Junos_exporter by czerwonk is good - but extremely slowly (it basically runs "show....." commands and then "reads the screen")

If you have any questions -let me know.
