### ISSUE TITLE
No data is visible in grafana

### ISSUE THREAD

**Issue by tilenkosec** [prometheus/snmp_exporter#723]
Everything is setup i am getting results back from http://localhost:9116/snmp?module=if_mib&target=1.2.3.4

snmp_exporter is connected to Prometheus however there is "No data"

I have used the default snmp.yml as suggested.

When I run manual snmpwalk I see a lot of "Cannot" on the start of the file:
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (IP-MIB): At line 0 in (none)

### Host operating system: output of `uname -a`
Linux 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter-0.20.0.linux-amd64

### What device/snmpwalk OID are you using?
synology RS2418+

### What did you expect to see?
some data from prometheus 

### What did you see instead?
No Data

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
