### ISSUE TITLE
Downloading Error for UBNT-UniFi-MIB

### ISSUE THREAD

**Issue by prudentcircle** [prometheus/snmp_exporter#730]
### Host operating system: output of `uname -a`

Linux ubuntu 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

Not installed yet

### What device/snmpwalk OID are you using?
N/A

### If this is a new device, please link to the MIB(s).
N/A

### What did you do that produced an error?
Just following commands.
```
sudo apt-get install unzip build-essential libsnmp-dev p7zip-full
go get github.com/prometheus/snmp_exporter/generator
cd ${GOPATH-$HOME/go}/src/github.com/prometheus/snmp_exporter/generator
go build
make mibs
```

### What did you expect to see?
Complete without an error

### What did you see instead?

```
>> Downloading synology to /tmp/tmp.Pz0dQ2eUzT
Archive:  /tmp/tmp.Pz0dQ2eUzT
  inflating: mibs/SYNOLOGY-UPS-MIB.txt
  inflating: mibs/SYNOLOGY-SHA-MIB.txt
  inflating: mibs/SYNOLOGY-DISK-MIB.txt
  inflating: mibs/SYNOLOGY-GPUINFO-MIB.txt
  inflating: mibs/SYNOLOGY-PORT-MIB.txt
  inflating: mibs/SYNOLOGY-SYSTEM-MIB.txt
  inflating: mibs/SYNOLOGY-FLASHCACHE-MIB.txt
  inflating: mibs/SYNOLOGY-SPACEIO-MIB.txt
  inflating: mibs/SYNOLOGY-NFS-MIB.txt
  inflating: mibs/SYNOLOGY-ISCSILUN-MIB.txt
  inflating: mibs/SYNOLOGY-EBOX-MIB.txt
  inflating: mibs/SYNOLOGY-SMART-MIB.txt
  inflating: mibs/SYNOLOGY-RAID-MIB.txt
  inflating: mibs/SYNOLOGY-SERVICES-MIB.txt
  inflating: mibs/SYNOLOGY-ISCSITarget-MIB.txt
  inflating: mibs/SYNOLOGY-STORAGEIO-MIB.txt
removed '/tmp/tmp.Pz0dQ2eUzT'
  Successfully remade target file 'mibs/.synology'.
   File 'mibs/UBNT-UniFi-MIB' does not exist.
  Must remake target 'mibs/UBNT-UniFi-MIB'.
>> Downloading UBNT-UniFi-MIB
make: *** [Makefile:242: mibs/UBNT-UniFi-MIB] Error 22
```

**Comment by SuperQ** [comment]
This must be a local issue, as I can't reproduce it.

**Comment by prudentcircle** [comment]
> This must be a local issue, as I can't reproduce it.

Hmm. Interesting. Thank you for checking it out for me.
I will try to find in my environment what causes this issue.

**Comment by IgorShpirko** [comment]
the same error
>> Downloading UBNT-UniFi-MIB
make: *** [Makefile:252: mibs/UBNT-UniFi-MIB] Error 22

**Comment by cv-jaeha** [comment]
the same issues.
Has anyone solved it?

> curl: (22) The requested URL returned error: 403 
> make: *** [Makefile:270: mibs/UBNT-UniFi-MIB] Error 22

**Comment by SuperQ** [comment]
This is a local issue, as you can see by our CI pipeline, this works normally.
