### ISSUE TITLE
snmp walk "row-by-row" or "column-by-column"

### ISSUE THREAD

**Issue by Andy1616** [prometheus/snmp_exporter#732]
if-mib as an example:

COLUMN-BY-COLUMN:
interfaces.ifTable.ifEntry.ifInOctets.1
interfaces.ifTable.ifEntry.ifInOctets.2
interfaces.ifTable.ifEntry.ifInOctets.3
interfaces.ifTable.ifEntry.ifInOctets.4
interfaces.ifTable.ifEntry.ifInOctets.5
...
interfaces.ifTable.ifEntry.ifOutOctets.1
interfaces.ifTable.ifEntry.ifOutOctets.2
interfaces.ifTable.ifEntry.ifOutOctets.3
interfaces.ifTable.ifEntry.ifOutOctets.4
interfaces.ifTable.ifEntry.ifOutOctets.5
....

ROW-BY-ROW:
interfaces.ifTable.ifEntry.ifInOctets.1
interfaces.ifTable.ifEntry.ifOutOctets.1
...
interfaces.ifTable.ifEntry.ifInOctets.2
interfaces.ifTable.ifEntry.ifOutOctets.2
...
interfaces.ifTable.ifEntry.ifInOctets.3
interfaces.ifTable.ifEntry.ifOutOctets.3

============================================

Question A: What is currently implemented? How does snmp_exporter walk a table?

Question B: some devices are faster in ROW-BY-ROW (or at least boiling the CPU less).
Could it be made configurable? like walk-r vs walk-c?

**Comment by SuperQ** [comment]
It depends on the SNMP version, but assuming v2c/v3, the walks are performed with "Bulk Walk", which IIRC leaves it more up to the device to paginate.

This is mostly implemented in the [gosnmp library](https://github.com/gosnmp/gosnmp) and implements the [RFC 3416 GetBulkRequest](https://datatracker.ietf.org/doc/html/rfc3416#section-4.2.3).

**Comment by SuperQ** [comment]
I dug around a bit, and talked to another SNMP expert.

I don't think there's an efficient way that this could be implemented. There's nothing in the SNMP spec that does row-by-row. It would have to be manually implemented by first scanning the index. Then it would have to fire off a series of single PDU Get requests to fetch each entry separately. In theory, this could be implemented as a helper method in the upstream gosnmp library. But it's not something I have time or interest in working on.

If you had example implementations of whatever "walk-r" and "walk-c" are, that could be useful as a guide for the Go implementation. Some cursory searches don't turn up anything obvious.

**Comment by Andy1616** [comment]
Hi
walk-r and walk-c only was for walk-by-row and walk-by-column, not more than that :-)
The wholt thing came up as a vendor was recommendning to walk row-by-row as it should be less CPU intensice for the target decice...

**Comment by SuperQ** [comment]
Sorry, that vendor doesn't seem to understand how SNMP works. What they're recommending is not a thing in SNMP.

**Comment by Andy1616** [comment]
I fully agree :-)
but need to find a way to support those "buggy devices" in best possible way...

**Comment by SuperQ** [comment]
The only way to do this is to manually expand the walk into a series of get requests.
