### ISSUE TITLE
Windows releases should probably be in .zip not tar.gz (Like other release from the Prometheus ecosystem)

### ISSUE THREAD

**Issue by JDA88** [prometheus/snmp_exporter#733]
### What did you expect to see?
Windows release binaries in .zip files, like prometheus, alertmanager, blackbox_exporter etc.

### What did you see instead?
Windows release binaries in .tar.gz wich is not a windows native format (event hough recent versions of Windows have a partial command line support for it)

**Comment by SuperQ** [comment]
I think this is fixed the latest version of promu. The next release should fix this.

**Comment by JDA88** [comment]
Ho great! Thank for the information

**Comment by SuperQ** [comment]
This is now fixed.
