### ISSUE TITLE
SNMP Exporter connect: connection timed out

### ISSUE THREAD

**Issue by VanessaKom** [prometheus/snmp_exporter#735]
Hi,
i am try to monitor a fortigate firewall 100F with snmp-exporter over prometheus

in browser **http://127.0.0.1:9116/snmp?module=if_mib&target=172.16.10.1** give me all the metrics

![grafik](https://user-images.githubusercontent.com/56280690/157432393-80af9067-82b1-4e98-917c-d11bcd5134b4.png)

But targets monitored by prometheus are up but not the firewall. I saw the error bellow in Prometheus GUI
**Get "http://127.0.0.1:9116/snmp?module=if_mib&target=172.16.10.1": dial tcp 127.0.0.1:9116: connect: connection timed out**

I set  scrape_interval: 8m  scrape_timeout: 5m 

in  my generator.yml  i set timeout  to 2s before generated snmp.yml. Here is how the configs looks like

 version: 2
  max_repetitions: 25
  retries: 3
  timeout: 2s
  auth:
    community: prometheus

snmp curl and snmpwalk work properly

what am i doing wrong? Please need a help

**Comment by mm3906078** [comment]
Hi
same issue here
