### ISSUE TITLE
Enable Sentry automatic trace report

### ISSUE THREAD

**Issue by mirceaulinic** [prometheus/snmp_exporter#736]
I'm personally a big fan of [Sentry](https://sentry.io/) as it significantly simplifies my life when it comes to detecting the root cause of a bug, or when trying to figure what's the (use-specific) cause of a failure.

I would therefore like to file a feature request in order to add native support in this exporter. Enabling is quite straight forward (see https://docs.sentry.io/platforms/go/). Of course, the usage would be completely optional (i.e., typically only attempt to send traces when the `SENTRY_DSN` environment variable is configured). I'm happy to work on adding this myself, just wanted to discuss it here beforehand.

**Comment by mirceaulinic** [comment]
Opened #946 to address this proposal.

**Comment by SuperQ** [comment]
Sentry is a proprietary form of logging/tracing. We don't intend to support this.
