### ISSUE TITLE
use snmp-exporter not monitor fortiadc

### ISSUE THREAD

**Issue by ziansong** [prometheus/snmp_exporter#739]
### What device/snmpwalk OID are you using?
1.3.6.1.4.1.12356.112.1.4
### If this is a new device, please link to the MIB(s).
FORTINET-FORTIADC-MIB.mib
### What did you do that produced an error?
fortiadc not success
### What did you see instead?
forti_adc:
    walk:
    - 1.3.6.1.2.1.1.3.0
    - 1.3.6.1.4.1.12356.112.1
    metrics:
    - name: fadcSysUpTime
      oid: 1.3.6.1.2.1.1.3.0
      type: counter
      help: The 64bit time (in hundredths of a second) since the network management
        portion of the system was last re-initialized. - 1.3.6.1.2.1.1.3.0
    - name: fadcSysCpuUsage
      oid: 1.3.6.1.4.1.12356.112.1.4
      type: gauge
      help: Instantaneous CPU usage. - 1.3.6.1.4.1.12356.112.1.4
    - name: fadcSysMemUsage
      oid: 1.3.6.1.4.1.12356.112.1.5
      type: gauge
      help: Instantaneous memory utilization. - 1.3.6.1.4.1.12356.112.1.5
    - name: fadcSysLogDiskUsage
      oid: 1.3.6.1.4.1.12356.112.1.6
      type: gauge
      help: Instantaneous log disk usage. - 1.3.6.1.4.1.12356.112.1.6
    version: 2
    auth:
      community: adfrdf

if not 1.3.6.1.4.1.12356.112.1 and fadcSysCpuUsage/fadcSysMemUsage/fadcSysLogDiskUsage OK

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
