### ISSUE TITLE
OIDs for Arista Networks

### ISSUE THREAD

**Issue by inetman28** [prometheus/snmp_exporter#745]
hi, maybe I ask your about bizarre question but I have one. 
I ran snmp generator where I was going to see metrics for BGP, different kind of sensors, temperatures, etc, but I got only ifmib ;). I am about result file called snmp.yml.
as I understood I must manually create list of OID under "walk:" variable in generator.yml file and then run it. Is there real only one way to generate big snmp.yml file with different deep metrics where I have to find hundreeds OID manually ? 

I am sorry for stupid question, but right now I try to find ten hundreeds OID manually for my **Arista Networks** switches because I dont see another ways

**Comment by RichiH** [comment]
https://www.arista.com/en/support/product-documentation/arista-snmp-mibs is what you're looking for, I believe.

**Comment by inetman28** [comment]
Hi, I'm happy of your quick answer. 

Yes, they are. But when I copied them under mibs/ directory and ran generator - nothing happened (I meant nothing happened in snmp.yml file - new metrics like bgp weren't there)

Do I have to make a list of oid under walk variable in generator.yml ? for example of mine generator.yml file:
```  arista_sw:
    walk:
      - sysUpTime
      - interfaces
      - ifXTable
      - 1.3.6.1.2.1.25.3.3.1.2 # hrProcessorLoad
      - 1.3.6.1.2.1.25.2.3.1.6 # hrStorageUsed
      - 1.3.6.1.4.1.30065.3.1.1 # aristaSwFwdIp
      # my own oid list
      - 1.3.6.1.2.1.25 # CPU and Memory Monitoring
      - system # system
      - 1.3.6.1.4.1.30065.4.1	# aristaBgp4V2
      - 1.3.6.1.4.1.30065.3.12 # aristaEntSensorMIB
 ```
or not ? Because if I don't make walk list - nothing happened in new snmp.yml.
