### ISSUE TITLE
SNMP walk timeout on empty table

### ISSUE THREAD

**Issue by chris-esterlein** [prometheus/snmp_exporter#756]
I desperately need help. This hangup is going to kill a very important product. I would really appreciate some guidance here. 

### Host operating system: output of `uname -a`
I'm using [the snmp-exporter docker image ](https://hub.docker.com/r/prom/snmp-exporter)

```
uname -a
Linux docker-desktop 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 GNU/Linux

```

### snmp_exporter version: output of `snmp_exporter -version`
Using [the latest snmp-exporter docker image](https://hub.docker.com/r/prom/snmp-exporter) 
It seems `-version` flag does not work.

```
kubectl exec prometheus-snmp-era-exporter-deployment -- snmp_exporter --version
snmp_exporter: error: unknown short flag '-v', try --help
command terminated with exit code 1
```

### What device/snmpwalk OID are you using?
Niche device. Does it matter? It works fine with net-snmp snmpwalk. 

Commscope ERA,  alarm table - .1.3.6.1.4.1.331.1.2.1.1.2.6

```
snmpwalk -c public -v 2c x.x.x.x .1.3.6.1.4.1.331.1.2.1.1.2.6
```

### If this is a new device, please link to the MIB(s).
The device is a commscope [ERA](https://www.commscope.com/product-type/in-building-cellular-systems/distributed-antenna-systems-das/era/) 

[Mib](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiix6Dm-dP3AhUNCs0KHRrpCB4QFnoECAkQAQ&url=https%3A%2F%2Fwww.netxms.org%2Fforum%2Fgeneral-support%2Fcompiled-mib-not-in-browser%2F%3Faction%3Ddlattach%3Battach%3D5287&usg=AOvVaw1hx9lpv1fpPyMNw9iHgm-n) 
```
oid=1.3.6.1.4.1.331.1.2.1.1.2.6
```

### What did you do that produced an error?
Simply walk the table with snmp-exporter. There is nothing in the table at the moment. It works as expected with net-snmp and it works on other ERA devices with fewer connected devices. 

### What did you expect to see?
I expected to see the walk return quickly since there is nothing in the table. 
When I do `snmpwalk -c public -v 2c x.x.x.x .1.3.6.1.4.1.331.1.2.1.1.2.6`, I see - 
```
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6 = No Such Object available on this agent at this OID
```
This works on other ERA devices with no alarms. But here is an example with a device that has active alarms 

```
snmpwalk -c public -v 2c x.x.x.x 1.3.6.1.4.1.331.1.2.1.1.2.6
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.2.1 = INTEGER: 8063
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.2.2 = INTEGER: 8063
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.3.1 = Gauge32: 60063
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.3.2 = Gauge32: 60063
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.4.1 = INTEGER: 4
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.4.2 = INTEGER: 4
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.5.1 = Hex-STRING: 07 E6 05 0A 00 3B 29 00 2B 00 00
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.5.2 = Hex-STRING: 07 E6 05 0A 00 3B 2F 00 2B 00 00
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.6.1 = INTEGER: 4
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.6.2 = INTEGER: 4
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.7.1 = INTEGER: 7
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.7.2 = INTEGER: 7
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.8.1 = STRING: "RFD Carrier Aged Out"
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.8.2 = STRING: "RFD Carrier Aged Out"
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.9.1 = STRING: "1.0.RFD.R2.3"
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.9.2 = STRING: "1.0.RFD.R6.3"
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.10.1 = INTEGER: 1
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.10.2 = INTEGER: 1
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.11.1 = OID: SNMPv2-SMI::enterprises.331.1.2.1.6.4
SNMPv2-SMI::enterprises.331.1.2.1.1.2.6.1.11.2 = OID: SNMPv2-SMI::enterprises.331.1.2.1.6.4
```

### What did you see instead?
I see a timeout. "msg="Error scraping target" err="scrape canceled (possible timeout) walking target x.x.x.x"

```
level=debug ts=2022-05-10T02:31:06.164Z caller=collector.go:164 module=era target=x.x.x.x msg="Walking subtree" oid=1.3.6.1.4.1.331.1.2.1.1.2.6
level=info ts=2022-05-10T02:31:26.131Z caller=collector.go:224 module=era target=x.x.x.x msg="Error scraping target" err="scrape canceled (possible timeout) walking target x.x.x.x"
````

This should be relatively simple. It works correctly on other ERA devices with fewer connected devices. I am using snmp-exporter to check a device for active alarms. Since there are none in the table, the poll should quickly return nothing. Instead, it times out. When I use net-snmp, it behaves as I would expect -- it returns nothing quickly. 

Thanks in advance for any help. I've been struggling with this for awhile and could use some help.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by SuperQ** [comment]
Last I tested this, the exporter respects empty PDU responses just fine. Unless the device is sending a malformed response, I don't think it's a bug.

If you really do think it's a bug, it would be useful to gather some tcpdump packet captures with timestamps to compare against the debug logs of the exporter.

This exporter is overdue for a release, plus that would fix the `--version` bug you ran into in the current container image. :-(

**Comment by SuperQ** [comment]
It seems like there is a `GetResponse` from `snmpbulkget`. What is the dump for

**Comment by SuperQ** [comment]
The only difference I can see is that the snmp_exporter `max_repetitions` is 25, where as `snmpbulkget` defaults to 10. Maybe try making that setting match?

Only other question, is there any kind of IP filter in the non-working device that may be affecting the response?

**Comment by chris-esterlein** [comment]
OMG @SuperQ You are my hero! Setting `max_repetitions` to 10 seems to have fixed it!  I'm not totally clear on why that fixed it, but it no longer times out. 

I can't thank you enough. I really appreciate your help!

**Comment by SuperQ** [comment]
Weird device bugs are weird.
