### ISSUE TITLE
Change community string from public to something else

### ISSUE THREAD

**Issue by Kybeer** [prometheus/snmp_exporter#758]
How can I change the snmp community string to poll with this exporter? I cannot find anything in the README file. 

If I keep all my devices to public, the scraing is works. But if I change to something else the scraping stops. 

This is with v0.20.0 running in container.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
