### ISSUE TITLE
Build failed because url APC_URL https://download.schneider-electric.com/files?p_File_Name=powernet441.mib return a 404

### ISSUE THREAD

**Issue by jliebert** [prometheus/snmp_exporter#766]
Build failed because url APC_URL https://download.schneider-electric.com/files?p_File_Name=powernet441.mib return a 404.

I don't find any new url to download this mib, maybe it should be removed to permit build of project.

**Comment by jliebert** [comment]
APC_URL https://download.schneider-electric.com/files?p_File_Name=powernet441.mib work again, I close the issue.

**Comment by jliebert** [comment]
URL work with a normal navigator but retourn a 404 with curl, they are a filter on curl request.
This request failed with a 404:
curl -s --retry-delay 3 --fail -o mibs/apc-powernet-mib 'https://download.schneider-electric.com/files?p_File_Name=powernet432.mib'

**Comment by SuperQ** [comment]
Are you sure this is not a local / transient issue? Our CI pipeline runs this command regularly without issue.

**Comment by SuperQ** [comment]
I just merged a PR to main, CI build works fine. This appears to be a local issue.
