### ISSUE TITLE
snmp exporter error generator  GOOS=windows

### ISSUE THREAD

**Issue by jmanriquecruz** [prometheus/snmp_exporter#776]
Good morning, I am trying to compile the generator for the windows platform but when doing so it generates an error, is it possible to do this with the generator?

![image](https://user-images.githubusercontent.com/61441532/177575941-b4e47864-4d8b-42ed-b528-00b4d2c914f8.png)

enviroment
![image](https://user-images.githubusercontent.com/61441532/177575987-cde417c8-357b-40d8-9abc-a147df4ade8d.png)

Error 
![image](https://user-images.githubusercontent.com/61441532/177576307-09925a12-0cd2-4c0a-9ce3-a612f2a66114.png)

![image](https://user-images.githubusercontent.com/61441532/177576514-881e4d64-00b3-4006-ac6b-49fb17e477d1.png)

when I compile it with the snmp_exporter it generates the .exe
![image](https://user-images.githubusercontent.com/61441532/177582123-e5659f38-7d41-4ccd-8c94-014a2719cc81.png)

I appreciate any help or comment that allows me to compile

**Comment by nelsonjchen** [comment]
This is a cop-out but any thoughts on WSL?

**Comment by SuperQ** [comment]
The problem is the generator requires the net-snmp C code to compile, which I don't think would work on Windows.

**Comment by jmanriquecruz** [comment]
Hello again, my question would be, is it feasible to compile the generator for windows? o is definitely not an option, because of the dependency on net-snmp C

**Comment by SuperQ** [comment]
You need to install the net-snmp source code in order to compile the generator. I don't know how to do this on Windows. Sorry.
