### ISSUE TITLE
snmp configuration file can not poll  my switch 

### ISSUE THREAD

**Issue by shadialsalamat** [prometheus/snmp_exporter#78]
hallo i iam new in this  sector 
i downlload it and aplly all steps 
nodes is okey 
my problem  is 
whenn i add snmp device , it can not show anything from him and it can not even pollen 
but with snmpwalk from same machine works good i do not know where the problem 
please look at the photos and tell me what muss i change 
thank you 

![1](https://cloud.githubusercontent.com/assets/22962140/19565926/e95600ee-96e8-11e6-9958-aff60fef0ce0.PNG)
![2](https://cloud.githubusercontent.com/assets/22962140/19565925/e95452c6-96e8-11e6-8eff-79e9901157a3.PNG)
![3](https://cloud.githubusercontent.com/assets/22962140/19565929/e96695a8-96e8-11e6-8c0d-bfeaa689a0e1.PNG)
![4](https://cloud.githubusercontent.com/assets/22962140/19565928/e95bdf6e-96e8-11e6-8de7-1b6b14c284c8.PNG)
![snmp](https://cloud.githubusercontent.com/assets/22962140/19565927/e9589cd2-96e8-11e6-9311-3a169eab5aa7.PNG)

**Comment by SuperQ** [comment]
This is likely due to timeouts.  SNMP devices can be very slow.  Have you tested using a utility like `curl` against the SNMP exporter URL to see if it times out?

The SNMP exporter has a hard-coded timeout of 60 seconds.  How long does it take to SNMP walk the device?

**Comment by RichiH** [comment]
A full walk will (almost) always take longer than the few snmpbulkgets snmp_exporter does by default. That being said, you still want to look at the error it gives you via http.

In general, please never ever make screen shots of text. Past the text in here, instead. Everything else makes it very hard to read, and help you...

**Comment by shadialsalamat** [comment]
SuperQ  how can i make that  curl against the SNMP exporter URL to see if it times out?

**Comment by shadialsalamat** [comment]
whenn i browser http 
http://172.21.10.117:9116/snmp?module=default&target=172.16.10.1
give me the this  error 
An error has occurred during metrics gathering:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error walking target 172.16.10.1: Request timeout (after 3 retries)

**Comment by SuperQ** [comment]
Yes, it seems like your SNMP device is very slow to respond.  The timeouts are currently hard-coded, and you'll have to edit them yourself and re-build the snmp_exporter.

See: https://github.com/prometheus/snmp_exporter/blob/master/collector.go#L42

**Comment by shadialsalamat** [comment]
i test 6  switches and the same result .....always the status is down

**Comment by SuperQ** [comment]
changing the scrape_interval will not affect the internal timeouts in the exporter.  The problem is the snmp_exporter is unable to communicate with your switches, or they take too long to respond.

**Comment by shadialsalamat** [comment]
SuperQ thank you ....how can i rebuld the file where can i find collector.go 
i am beginner can you help me and say how can i build it agein or where i find the correct information _

**Comment by shadialsalamat** [comment]
i rebuld  it still did not work

**Comment by shadialsalamat** [comment]
now the switch all up but did not show information . 
![up switch](https://cloud.githubusercontent.com/assets/22962140/19725553/62969148-9b86-11e6-8ae1-85252a2f2a82.PNG)

**Comment by 0x000flo** [comment]
Hi, this is a problem with your procurve switch. The IP (VLAN) of the request is another one than the reply address.
The following command will solve your problem:
snmp-server response-source <yourIP>

**Comment by iliomad** [comment]
I got the same error message from the snmp exporter when talking to a switch and ended up here after a little searching. Figured I'd add my findings in case somebody else ends up here. 

I played about with snmpwalk in the command line, stepping up through the protocol levels (I'm new to SNMP). Note the similarity of the timeout error message to that of the Prometheus snmp_exporter. 

I ended up with snmp v3 with the security level and user name taken from the switch management interface info. Then I applied the same parameters to the snmp.yml file, started up the snmp_exporter and it's working ok now. 

snmpwalk -v1 -c public 172.ip.add.ress
Timeout: No Response from 172.ip.add.ress

snmpwalk -v2c -c public 172.ip.add.ress
Timeout: No Response from 172.ip.add.ress

snmpwalk -v3 -lnoAuthNoPriv -u guest 172.ip.add.ress
SNMPv2-MIB::sysDescr.0 = STRING: M4300-8X8F ProSAFE 8-port 10GBASE-T and 8-port 10G SFP+, 12.0.2.10, 1.0.0.8
....

Added the following to the snmp.yml file:
default:
  version: 3
  auth:
    username: guest
    security_level: noAuthNoPriv
  walk:
  -....

Exporter working ok now.

**Comment by cjdhakal** [comment]
Hi, I am using snmp_exporter in localhost having snmp version 1, Though Its scrapping the data using snmpwalk but using prometheus, it is not showing any data:

The output as:
# HELP snmp_scrape_duration_seconds Total SNMP time scrape took (walk and processing).
# TYPE snmp_scrape_duration_seconds gauge
snmp_scrape_duration_seconds 0.002006983
# HELP snmp_scrape_pdus_returned PDUs returned from walk.
# TYPE snmp_scrape_pdus_returned gauge
snmp_scrape_pdus_returned 7
# HELP snmp_scrape_walk_duration_seconds Time SNMP walk/bulkwalk took.
# TYPE snmp_scrape_walk_duration_seconds gauge
snmp_scrape_walk_duration_seconds 0.0019137310000000001

I used the snmp.yml as:

# my global config
global:
  scrape_interval:     5m 
scrape_configs:
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.126.88 # SNMP device.
    metrics_path: /snmp
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter.

lease suggest some way. @brian-brazil
