### ISSUE TITLE
APC_URL 404

### ISSUE THREAD

**Issue by burnsba** [prometheus/snmp_exporter#783]
In the generator MakeFile, the APC_URL link to schneider-electric gives a 404 or a redirect to a login.

https://download.schneider-electric.com/files?p_File_Name=powernet441.mib

I found another powernet 441 mib from schneider electric at

https://download.schneider-electric.com/files?p_Doc_Ref=APC_POWERNETMIB_441_EN&p_enDocType=Firmware&p_File_Name=powernet441.mib

**Comment by RichiH** [comment]
Thanks! See linked PR to fix it.
