### ISSUE TITLE
How to handle strings and map them to boolean.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/snmp_exporter#79]
First of all, thanks for this exporter. It's really done wonders for us. However, I often find myself at a loss when I'm faced with strings that could be translated to a boolean value. For example, I've mapped several VMware servers, and one of the oid's describe if the VM is in a runnable state or turned off. Is it possible to map for example s/running/1/g?

**Comment by brian-brazil** [comment]
Strings aren't currently supported, though I'd take a PR to add them.

Mapping to a number is likely to have to be done over in Prometheus.

**Comment by brian-brazil** [comment]
This will be added soon.
