### ISSUE TITLE
Is there a metric like prometheus_build_info that exposes the version of snmp exporter? 

### ISSUE THREAD

**Issue by chavalikesavanand** [prometheus/snmp_exporter#806]
snmp_exporter -version gives the details but we need as a metric so that we can fetch and report centrally

**Comment by RichiH** [comment]
We might want to put a `build_info` into exporter toolkit. @SuperQ thoughts?

**Comment by SuperQ** [comment]
There already is an `snmp_exporter_build_info` metric.

**Comment by chavalikesavanand** [comment]
Thanks for the response. Which end point to scrape to get this metric and can this be documented

Thanks and Regards,
Kesav
... Sent from mobile, excuse typos...
________________________________

**Comment by chavalikesavanand** [comment]
got it: http://localhost:9116/metrics

# HELP snmp_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which snmp_exporter was built.
# TYPE snmp_exporter_build_info gauge
snmp_exporter_build_info{branch="HEAD",goversion="go1.15.8",revision="c33572b6c8c8e43a479fde0f9fa8ac86e15598bc",version="0.20.0"} 1
