### ISSUE TITLE
Need steps in setting up generator, as its getting failed at make mibs command with the error make: *** [Makefile:148 mib/.cisco_v2] Error 56

### ISSUE THREAD

**Issue by saikrthk1322** [prometheus/snmp_exporter#809]
### Host operating system: output of `uname -a`
Linux testserver 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter-0.20.0
### What did you do that produced an error?
make mibs

**Comment by hoangtrucit** [comment]
I has same issue

**Comment by DaAwesomeP** [comment]
I am also able to reproduce this.

**Comment by SuperQ** [comment]
Looks like the Cisco FTP server is offline. I found a mirror of the Cisco MIB files on github, should be more reliable.
