### ISSUE TITLE
Cisco migrated from FTP MIB hosting to Git based hosting

### ISSUE THREAD

**Issue by RiveransRafting** [prometheus/snmp_exporter#813]
Since the 15 of october Cisco has moved from FTP hosting of their MIBS to Github based hosting. 
Are there any plans on moving the generator Makefile over to use the new MIBS repository?

https://github.com/cisco/cisco-mibs
***On 10/15/2022 ftp.cisco.com has been officially decomissioned making this the new source for Cisco MIB files. Cisco Developers will continue maintain MIB files in this location as they did on ftp.cisco.com***

Also, the APC link, in the same Makefile, seems to be deprecated as well.

**Comment by SuperQ** [comment]
Fixed in https://github.com/prometheus/snmp_exporter/pull/811
