### ISSUE TITLE
No prefix on all metrics?

### ISSUE THREAD

**Issue by ibrasho** [prometheus/snmp_exporter#82]
I'm wondering why the metric names in `snmp.yml` are not prefixed with the exporter name?
Is there a specific rationale for that decision?

**Comment by brian-brazil** [comment]
We're using the standard SNMP names for these metrics and following those conventions.

**Comment by RichiH** [comment]
This issue is older than https://github.com/prometheus/snmp_exporter/issues/104 but has more context, so I chose to re-open the other one for discussion.
