### ISSUE TITLE
pulling from network device issue

### ISSUE THREAD

**Issue by idanedry** [prometheus/snmp_exporter#83]
Hi,

I'm trying to setup prometheus with snmp_exporter to get snmp info from one of my network devices(DDOS protection), when I sample the DDOS protector device with SNMP through the browser I get the following:
http://172.31.15.222:9116/snmp?target=172.31.15.165
# TYPE ifHCInBroadcastPkts untyped
ifHCInBroadcastPkts{ifDescr="Gigabit Ethernet-25"} 5.117052e+06
ifHCInBroadcastPkts{ifDescr="Gigabit Ethernet-26"} 0

Now I just want to configure prometheus to monitor it, but I don't understand what is needed to fill in the prometheus.yml file.

Please help me!

**Comment by brian-brazil** [comment]
The README has an example: https://github.com/prometheus/snmp_exporter#prometheus-configuration
