### ISSUE TITLE
docker deployment

### ISSUE THREAD

**Issue by glensc** [prometheus/snmp_exporter#84]
i see `Dockerfile` in the project, please document docker deployment in README.md, preferrably with docker-compose example.

**Comment by amirgohar-AG** [comment]
@brian-brazil will this help ?
#### How to build snmp-exporter from the [prometheus/snmp-exporter](https://github.com/prometheus/snmp_exporter)

1. ```git clone https://github.com/prometheus/snmp_exporter```
2. ```cd snmp_exporter```
3. ```CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' .```
4. First copy desired snmp.yml to snmp_exporter folder
```
