### ISSUE TITLE
Web Application Potentially Vulnerable to Clickjacking

### ISSUE THREAD

**Issue by AlinS23** [prometheus/snmp_exporter#849]
Hi Team,

We've got Nessuss vulnerability scan and it highlighted the following finding:

> **Web Application Potentially Vulnerable to Clickjacking** 
>The remote web server does not set an X-Frame-Options response header or a Content-Security-Policy 'frame-ancestors' response header in all content responses. This could potentially expose the site to a clickjacking or UI redress attack, in which an attacker can trick a user into clicking an area of the vulnerable page that is different from what the user perceives the page to be. This can result in a user performing fraudulent or malicious transactions.
> X-Frame-Options has been proposed by Microsoft as a way to mitigate clickjacking attacks and is currently supported by all major browser vendors.
> Content-Security-Policy (CSP) has been proposed by the W3C Web Application Security Working Group, with increasing support among all major browser vendors, as a way to mitigate clickjacking and other attacks. The 'frame-ancestors' policy directive restricts which sources can embed the protected resource. 
> 
> Return the X-Frame-Options or Content-Security-Policy (with the 'frame-ancestors' directive) HTTP header with the page's response. 

It was found on the following web-interface (IP address just for sample):

```
Output: 
The following pages do not use a clickjacking mitigation response header and contain a clickable event :
http://192.168.1.12:9116/
```

More explanation of Clickjacking is here - [link](https://www.synopsys.com/glossary/what-is-clickjacking.html#:~:text=Clickjacking%20is%20an%20attack%20that,describes%20what%20is%20going%20on).

Could you please help how we could fix it or fix in the the futire releases? Thank you.

### Host operating system: output of `uname -a`
Ubuntu Linux 20.04.5

### snmp_exporter version: output of `snmp_exporter -version`

![image](https://user-images.githubusercontent.com/126081146/220635049-05dcc925-8659-4e5e-ac05-1e0c2c28b43c.png)
v0.21.0

### What did you do that produced an error?
Run a vulnerability scan to the servers with VM installed.

**Comment by SuperQ** [comment]
This is a false positive. There are no frames used in the exporter.
