### ISSUE TITLE
configuration: multiple configs

### ISSUE THREAD

**Issue by glensc** [prometheus/snmp_exporter#85]
please add support for multiple configuration files

so i could use unmodified [snmp.yml](https://github.com/prometheus/snmp_exporter/blob/master/snmp.yml) for the oid/metrics configuration

and have secondary file for configuring authentication:
https://github.com/prometheus/snmp_exporter#snmpv2

or perhaps allow authentication configured from commandline like haproxy exporter does?

**Comment by brian-brazil** [comment]
You can put multiple modules inside the one config file.

**Comment by RichiH** [comment]
Supporting different auth tokens would be appreciated from our side as well.

As this is stored in our CMDB and available via SD, this should align with Prometheus patterns. I don't care if the actual community is stored in snmp_exporter and accessed via a group parameter sent from Prometheus or stored in Prometheus config. Having a default that's used when nothing special is requested would also be useful but not essential.

**Comment by brian-brazil** [comment]
The Prometheus pattern for auth is one per scrape_config, so the snmp_exporter way of working aligns with that (indeed the snmp_exporter is a little more flexible).

**Comment by glensc** [comment]
@brian-brazil your suggestion is counter suggestion. i wanted to put my config to separate file so that i can update the snmp.yml from this repo without manually merging changes.

**Comment by brian-brazil** [comment]
That's not something that we'll be supporting. Merging multiple configs would likely only cause confusion.

**Comment by glensc** [comment]
perhaps move the `walk` and `metrics` themselves as separate files? or add `@include` directive?

```
default:
  version: 2
  auth:
    community: public
  walk:
    - 1.3.6.1.2.1.1.3
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
  metrics:
    - @include: linux-ifdescr.xml

```

**Comment by RichiH** [comment]
If you really think you need multiple configs, you can run multiple
exporters.

Richard

Sent by mobile; excuse my brevity.

**Comment by glensc** [comment]
@RichiH please read the issue initial description **WHY**. i wish to avoid merging configs manually in the future when i plan to update the software. currently i had to modify the snmp.xml to add auth credentials, there may come more options that need to configure. and `walk` and `metrics` definitions are complex, could easily break them, which can be avoided if i just define my customizations in other place than stock provided snmp.xml file.

**Comment by RichiH** [comment]
Then you need to generate your configuration.

Richard

Sent by mobile; excuse my brevity.

**Comment by glensc** [comment]
closing, seems upstream does not want any improvements and better maintainability of complex config.

**Comment by RichiH** [comment]
@glensc https://docs.google.com/document/d/1McJJIiJfHgoecVrVNXx4ABJmI5M21e-6O9IgMNbVnvw might be of interest to you

**Comment by RichiH** [comment]
One consideration: Should we make the order deterministic, follow the order on CLI, or not do anything special at all?

I think deterministic makes sense. While we hard fail on day 1, that might not always be the case (however unlikely). The other reason is that when we expose this in the UI and if we expose this as `_info` metrics, it's easier to compare long-term and between installations when it's sorted.
