### ISSUE TITLE
Problem with MakeFile

### ISSUE THREAD

**Issue by Wolfiens92** [prometheus/snmp_exporter#851]
### Host operating system: output of `uname -a`
Linux snmp 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter@v0.21.0

### What device/snmpwalk OID are you using?
I don't know, I am new at this :D
### If this is a new device, please link to the MIB(s).
https://raw.githubusercontent.com/libvirt/libvirt-snmp/master/src/LIBVIRT-MIB.txt

### What did you do that produced an error?
a step: make mibs and ./generator generate
### What did you expect to see?
no errors? :D
### What did you see instead?
ts=2023-02-25T16:09:05.303Z caller=net_snmp.go:161 level=info msg="Loading MIBs" from=$HOME/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf
ts=2023-02-25T16:09:05.947Z caller=main.go:51 level=info msg="Generating config for module" module=ddwrt
ts=2023-02-25T16:09:06.010Z caller=main.go:66 level=info msg="Generated metrics" module=ddwrt metrics=112
ts=2023-02-25T16:09:06.010Z caller=main.go:51 level=info msg="Generating config for module" module=kemp_loadmaster
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSAddrtype
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSL7persist
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSName
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSSchedulingMethod
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=patchVersion
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=rSIp
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSProtocol
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=haState
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=rSForwardingMethod
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=rSState
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSAdaptiveMethod
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSCheckerType
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSIp
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSL7cookieId
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=vSState
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=daemonState
ts=2023-02-25T16:09:06.060Z caller=tree.go:268 level=warn msg="Could not find node to override type" node=rSAddrType
ts=2023-02-25T16:09:06.060Z caller=main.go:129 level=error msg="Error generating config netsnmp" err="cannot find oid '1.3.6.1.4.1.12196.13.0' to walk"

THere is an error with downloading several MIBS, APC_URL is not correct and EATON_* aswell.

**Comment by Wolfiens92** [comment]
I also have commented problematic URLs, and added mine, but generator still does not work as intended.

Probably, it is a "go" error, with its path (which I also don't know what is correct path), any "go" version I run does not work.
This with go is used on Ubuntu 20.

Can anybody give me detailed instructions how to do configuring with this link I provided? and how to succesfully compile this?

**Comment by SuperQ** [comment]
```
from=$HOME/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf
```

You need to `export MIBDIRS=mibs` to use the Makefile MIBs.

**Comment by SuperQ** [comment]
Ugh, APC broke their download again.

**Comment by Wolfiens92** [comment]
Yes, APC is the problem, and Eaton as well. Yes, you were right, I needed ```export MIBDIRS=mibs```. Thank you. What do I write in generator.yml for it to be able to get values (if there is any) from https://raw.githubusercontent.com/libvirt/libvirt-snmp/master/src/LIBVIRT-MIB.txt ?

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
