### ISSUE TITLE
Docker Hub repo empty

### ISSUE THREAD

**Issue by jangrewe** [prometheus/snmp_exporter#87]
When trying to run the Docker image from your repo at https://hub.docker.com/r/prom/snmp_exporter/
i get the error:
```
docker: Tag latest not found in repository docker.io/prom/snmp_exporter.
```
Could you please link Docker Hub to this repo so that the image gets built?
Thanks!

**Comment by kkirsche** [comment]
https://hub.docker.com/r/prom/snmp-exporter/

shows last pushed a day ago

**Comment by jangrewe** [comment]
@kkirsche interesting, because now, 29 minutes after your comment, it says "a month ago". But then again i opened this issue nearly 4 months ago ;-)

**Comment by brian-brazil** [comment]
This all appears to be correct.
