### ISSUE TITLE
Upgrade to 0.1.0 (from previous python release) broke string data

### ISSUE THREAD

**Issue by HyperDevil** [prometheus/snmp_exporter#88]
Hi!

I just upgraded to the Go version 0.1.0.
I use this to monitor my NTP server, and after i installed the Go version some data stopped arriving into Prometheus.

This is the data that was previously working:
snmpwalk -c public -v 1 10.0.1.8 .1.3.6.1.4.1.5597.30.0.2.4.0
iso.3.6.1.4.1.5597.30.0.2.4.0 = STRING: "-0.000419"

Now with the new Go 0.1.0 version i get this output:
curl 'localhost:9116/snmp?target=10.0.1.8&module=meinberglantime'
HELP NTPRefclockOffset 
TYPE NTPRefclockOffset untyped
NTPRefclockOffset 0

So something broke in the Go version that worked previously.

**Comment by brian-brazil** [comment]
No version of this exporter has ever supported string values.

**Comment by HyperDevil** [comment]
I can guarantee that it worked before the upgrade to the Go version.
I installed the Go version 8:26 PM November 23rd 2016.

Here is the output of prometheus:
https://postimg.org/image/oeuj18pyb/

**Comment by HyperDevil** [comment]
Template:

meinberglantime:
  walk:
   - 1.3.6.1.2.1.1
   - 1.3.6.1.4.1.5597
   - 1.3.6.1.4.1.14988.1.1.14.1.1
   - 1.3.6.1.2.1.7
  metrics:
   - name: SystemUptime
     oid: 1.3.6.1.2.1.1.3
   - name: NTPRefclockOffset
     oid: 1.3.6.1.4.1.5597.30.0.2.4.0
   - name: NTPStratum
     oid: 1.3.6.1.4.1.5597.30.0.2.2
   - name: SystempCelcius
     oid: 1.3.6.1.4.1.5597.30.0.5.2.1
   - name: SatsInView
     oid: 1.3.6.1.4.1.5597.30.0.1.2.1.6
   - name: InUDPdatagrams
     oid: 1.3.6.1.2.1.7.1
   - name: OutUDPdatagrams
     oid: 1.3.6.1.2.1.7.4

**Comment by brian-brazil** [comment]
That must have been by accident due to a quirk of the Python language and netsnmp python bindings. Even with string support, we're unlikely to support PDUs like this that are using an inappropriate type.

**Comment by HyperDevil** [comment]
I presume this will fix my issue? 

https://github.com/prometheus/snmp_exporter/issues/79

**Comment by brian-brazil** [comment]
No, there's no plans to allow conversion of strings to floats. That way lies madness.
