### ISSUE TITLE
How to set the label with EnumAsInfo-Name in metrics?

### ISSUE THREAD

**Issue by coolshun** [prometheus/snmp_exporter#894]
the generator.yml:
<img width="311" alt="image" src="https://github.com/prometheus/snmp_exporter/assets/20296262/6c0f783d-e058-4109-8ae3-a36b45df82bf">
the snmp.yml:
<img width="521" alt="image" src="https://github.com/prometheus/snmp_exporter/assets/20296262/8eebc02e-e6a3-4220-8753-653a2499c843">
the metrics:
![image](https://github.com/prometheus/snmp_exporter/assets/20296262/24d2dec0-e36a-458b-8f08-e22a51475ddc)
but I want the metric lik the bellow:
![image](https://github.com/prometheus/snmp_exporter/assets/20296262/368cee63-39a0-476f-9c36-221d58412951)

How can I do ?

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
