### ISSUE TITLE
snmp exporter scrape_interval questions

### ISSUE THREAD

**Issue by ZoldanYao** [prometheus/snmp_exporter#899]
why prometheus can not scrape  every 30s ? 
snmpwalk and snmp exporter can get value fast . But prometheus only cat get value every minnte

![image](https://github.com/prometheus/snmp_exporter/assets/81861598/eddb0f9f-1a5d-4e68-97e7-95772c98cb7b)
![image](https://github.com/prometheus/snmp_exporter/assets/81861598/07e219e2-1904-41fa-8fe6-b5804a427adc)
![image](https://github.com/prometheus/snmp_exporter/assets/81861598/fc00af79-cbaf-4074-bf0b-dc85233571fa)
![image](https://github.com/prometheus/snmp_exporter/assets/81861598/cb24073b-4a6a-4113-9512-5e3eca3044db)

**Comment by SuperQ** [comment]
Prometheus is getting values every 30 seconds, but your device is caching them. This is a device issue.

Your screenshots only include 2 iterations, this isn't enough to prove your claim.

Try `while sleep 30 ; do snmpwalk ... ; done`.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
