### ISSUE TITLE
Generator fails to run with vanilla generator.yml

### ISSUE THREAD

**Issue by silke-99** [prometheus/snmp_exporter#916]
I'm a newbie to prometheus & snmp_exporter and am just starting out with a newly installed setup on Linux.

I'm trying to follow the instructions using a fresh git clone  and unchanged generator.yml. I just added some MIBs to my mibs dir in addition to the standard ones and then I'm already crashing against this wall:

```
sudo docker run --rm -ti   -v "${PWD}:/opt/"   snmp-generator generate

ts=2023-07-14T07:35:18.264Z caller=net_snmp.go:162 level=info msg="Loading MIBs" from=mibs
ts=2023-07-14T07:35:18.370Z caller=main.go:130 level=error msg="Error generating config netsnmp" err="error parsing yml config: yaml: unmarshal errors:\n  line 3: field version not found in type main.Config\n  line 5: field auths not found in type main.Config"
```

Can you give me a hint on what I'm doing wrong? I understand there were some changes in this area recently, but shouldn't this work?

Thanks so much!

**Comment by SuperQ** [comment]
You likely have a missmatch between the generator version and the config version. There is a new release candidate configuration that refactors the config.

See: https://github.com/prometheus/snmp_exporter/releases/tag/v0.23.0-rc.0

**Comment by silke-99** [comment]
Hi, yep I tried with the rc0 but somehow still failed with the docker approach. It's probably due to still poor understanding on my end,

I gave up on using docker for now and am running successfully with the raw binary in the meantime. 

Thanks a lot for the hint!
