### ISSUE TITLE
metrics are not coming in exporter  

### ISSUE THREAD

**Issue by abhirajverm** [prometheus/snmp_exporter#917]
### Host operating system: output of `uname -a`
Linux exporter 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.22.0 (branch: HEAD, revision: 7b0657fd99862a47f2f9f780f08a794ca7040ae7)
  build user:       root@cfac3556bd96
  build date:       20230615-13:29:47
  go version:       go1.20.5
  platform:         linux/amd64
  tags:             netgo

### What device/snmpwalk OID are you using?
if_mib

### What did you expect to see?
metrics for cisco switch 

### What did you see instead?

An error has occurred while serving metrics:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: error getting target 192.168.20.6: request timeout (after 3 retries)

 - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.20.6  # SNMP device.
         # SNMP device.
    metrics_path: /snmp
    params:
      auth: [innoviti_v2]
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.107:9116

**Comment by abhirajverm** [comment]
Jul 13 16:00:21 exporter systemd[1]: snmp-exporter.service: Main process exited, code=exited, status=217/USER
Jul 13 16:00:21 exporter systemd[1]: snmp-exporter.service: Failed with result 'exit-code'.
Jul 13 16:00:21 exporter systemd[1]: snmp-exporter.service: Scheduled restart job, restart counter is at 5.
Jul 13 16:00:21 exporter systemd[1]: Stopped Prometheus SNMP exporter service.
Jul 13 16:00:21 exporter systemd[1]: snmp-exporter.service: Start request repeated too quickly.
Jul 13 16:00:21 exporter systemd[1]: snmp-exporter.service: Failed with result 'exit-code'.
Jul 13 16:00:21 exporter systemd[1]: Failed to start Prometheus SNMP exporter service.
Jul 13 16:00:57 exporter systemd[1]: Started Prometheus SNMP exporter service.
Jul 13 16:00:57 exporter systemd[99618]: snmp-exporter.service: Failed to determine user credentials: No such process
Jul 13 16:00:57 exporter systemd[99618]: snmp-exporter.service: Failed at step USER spawning /usr/local/bin/snmp_exporter: No such process
Jul 13 16:00:57 exporter systemd[1]: snmp-exporter.service: Main process exited, code=exited, status=217/USER
Jul 13 16:00:57 exporter systemd[1]: snmp-exporter.service: Failed with result 'exit-code'.
Jul 13 16:00:58 exporter systemd[1]: snmp-exporter.service: Scheduled restart job, restart counter is at 1.
Jul 13 16:00:58 exporter systemd[1]: Stopped Prometheus SNMP exporter service.
Jul 13 16:00:58 exporter systemd[1]: Started Prometheus SNMP exporter service.
Jul 13 16:00:58 exporter systemd[99619]: snmp-exporter.service: Failed to determine user credentials: No such process
Jul 13 16:00:58 exporter systemd[99619]: snmp-exporter.service: Failed at step USER spawning /usr/local/bin/snmp_exporter: No such process
Jul 13 16:00:58 exporter systemd[1]: snmp-exporter.service: Main process exited, code=exited, status=217/USER
Jul 13 16:00:58 exporter systemd[1]: snmp-exporter.service: Failed with result 'exit-code'.
Jul 13 16:00:58 exporter systemd[1]: snmp-exporter.service: Scheduled restart job, restart counter is at 2.
Jul 13 16:00:58 exporter systemd[1]: Stopped Prometheus SNMP exporter service.
Jul 13 16:00:58 exporter systemd[1]: Started Prometheus SNMP exporter service.
Jul 13 16:00:58 exporter systemd[99620]: snmp-exporter.service: Failed to determine user credentials: No such process
Jul 13 16:00:58 exporter systemd[99620]: snmp-exporter.service: Failed at step USER spawning /usr/local/bin/snmp_exporter: No such process
Jul 13 16:00:58 exporter systemd[1]: snmp-exporter.service: Main process exited, code=exited, status=217/USER
Jul 13 16:00:58 exporter systemd[1]: snmp-exporter.service: Failed with result 'exit-code'.
Jul 13 16:00:58 exporter systemd[1]: snmp-exporter.service: Scheduled restart job, restart counter is at 3.
Jul 13 16:00:58 exporter systemd[1]: Stopped Prometheus SNMP exporter service.
Jul 13 16:00:58 exporter systemd[1]: Started Prometheus SNMP exporter service

**Comment by SuperQ** [comment]
This syntax requires the [v0.23.0 release candidate](https://github.com/prometheus/snmp_exporter/releases/tag/v0.23.0-rc.0).

**Comment by abhirajverm** [comment]
Thanks its working
