### ISSUE TITLE
Generated snmp.yml cannot be unmarshalled by snmp exporter

### ISSUE THREAD

**Issue by adminsend** [prometheus/snmp_exporter#922]
SNMP exporter has trouble parsing snmp.ymlö, generated by generator: snmp.yml is generated from the default generator.yml, without any modificaitons.

ts=2023-07-18T21:11:17.245Z caller=main.go:153 level=info build_context="(go=go1.18.1, user=team+pkg-go@tracker.debian.org, date=20230203-14:12:28)"
ts=2023-07-18T21:11:17.408Z caller=main.go:159 level=error msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 3: field public_v1 not found in type config.plain\n  line 9: field public_v2 not found in type config.plain\n  line 16: field apcups not found in type config.plain\n  line 2374: field arista_sw not found in type config.plain\n  line 2949: field cisco_wlc not found in type config.plain\n  line 3395: field cyberpower not found in type config.plain\n  line 6007: field ddwrt not found in type config.plain\n  line 6442: field if_mib not found in type config.plain\n  line 7699: field infrapower_pdu not found in type config.plain\n  line 7777: field keepalived not found in type config.plain\n  line 9633: field kemp_loadmaster not found in type config.plain\n  line 10396: field liebert_pdu not found in type config.plain\n  line 12902: field mikrotik not found in type config.plain\n  line 16180: field nec_ix not found in type config.plain\n  line 18459: field paloalto_fw not found in type config.plain\n  line 19548: field printer_mib not found in type config.plain\n  line 19751: field raritan not found in type config.plain\n  line 19878: field servertech_sentry3 not found in type config.plain\n  line 20407: field servertech_sentry4 not found in type config.plain\n  line 22740: field synology not found in type config.plain\n  line 24516: field ubiquiti_airfiber not found in type config.plain\n  line 25701: field ubiquiti_airmax not found in type config.plain\n  line 26345: field ubiquiti_unifi not found in type config.plain\n  line 26974: field wiener_mpod not found in type config.plain\n  line 49218: cannot unmarshal !!int `2` into config.plain"

### Host operating system: output of `uname -a`
Linux srv-adh-vm-0084 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter" version="(version=0.20.0, branch=debian/sid, revision=0.20.0-1ubuntu0.1)"

### What did you do that produced an error?
running snmp exporter

### What did you expect to see?
startup and correct parsing of exporter

### What did you see instead?
errormessage as shown above

**Comment by SuperQ** [comment]
You haven't included the config that caused the problem.

**Comment by calebarcher** [comment]
> You haven't included the config that caused the problem.

I have the same error. Here is my generator,yml and the snmp.yml generated
**generator.yml**
`---
# The generator config format version.
version: 2

auths:
  with_secret: 
    version: 3
    username: uname
    security_level: authNoPriv 
    password: pass
    auth_protocol: SHA  
    priv_protocol: AES256  
    priv_password: privpass 
    context_name: context


modules:
  # Default IF-MIB interfaces table with ifIndex.
  IF-MIB:
    walk: [sysUpTime, interfaces, ifXTable]
    retries: 3   # How many times to retry a failed request, defaults to 3.
    timeout: 10s  # Timeout for each individual SNMP request, defaults to 5s.
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo`

**snmp.yml**

`# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
auths:
  with_secret:
    community: public
    security_level: authNoPriv
    username: uname
    password: pass
    auth_protocol: SHA
    priv_protocol: AES256
    priv_password: privpass
    context_name: context
    version: 3
modules:
  IF-MIB:
    walk:
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
    get:
    - 1.3.6.1.2.1.1.3.0
    metrics:
    - name: sysUpTime
      oid: 1.3.6.1.2.1.1.3
      type: gauge
      help: The time (in hundredths of a second) since the network management portion
        of the system was last re-initialized. - 1.3.6.1.2.1.1.3
    - name: ifNumber
      oid: 1.3.6.1.2.1.2.1
      type: gauge
      help: The number of network interfaces (regardless of their current state) present
        on this system. - 1.3.6.1.2.1.2.1
    - name: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: gauge
      help: A unique value, greater than zero, for each interface - 1.3.6.1.2.1.2.2.1.1
      indexes:
      - labelname: ifIndex
        type: gauge
      lookups:
      - labels:
        - ifIndex
        labelname: ifAlias
        oid: 1.3.6.1.2.1.31.1.1.1.18
        type: DisplayString
      - labels:
        - ifIndex
        labelname: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: DisplayString
      - labels:
        - ifIndex
        labelname: ifName
        oid: 1.3.6.1.2.1.31.1.1.1.1
        type: DisplayString
    - name: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: EnumAsInfo
      help: The type of interface - 1.3.6.1.2.1.2.2.1.3
      indexes:
      - labelname: ifIndex
        type: gauge
      lookups:
      - labels:
        - ifIndex
        labelname: ifAlias
        oid: 1.3.6.1.2.1.31.1.1.1.18
        type: DisplayString
      - labels:
        - ifIndex
        labelname: ifDescr
        oid: 1.3.6.1.2.1.2.2.1.2
        type: DisplayString
      - labels:
        - ifIndex
        labelname: ifName
        oid: 1.3.6.1.2.1.31.1.1.1.1
        type: DisplayString
      enum_values:`

The generated file is over 1k lines so I've taken the first 77 here

**Comment by calebarcher** [comment]
I have the exact same problem. Here's my config
**generator.yml**
`---
version: 2

auths:
  with_secret: 
    version: 3
    username: uname
    security_level: authNoPriv 
    password: pass
    auth_protocol: SHA  
    priv_protocol: AES256  
    priv_password: privpass 
    context_name: context


modules:
  
  IF-MIB:
    walk: [sysUpTime, interfaces, ifXTable]
    retries: 3   
    timeout: 10s  
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        lookup: 1.3.6.1.2.1.31.1.1.1.1 
    overrides:
      ifAlias:
        ignore: true 
      ifDescr:
        ignore: true
      ifName:
        ignore: true
      ifType:
        type: EnumAsInfo`

I'm using version 0.22.0 of the snmp exporter. The generator generates the snmp.yml file without any errors but when I start the snmp exporter using the file, I get the the error

**Comment by calebarcher** [comment]
I just figured what my issue was, the version of snmp exporter was different from version of generator i was using. They have to be the same version

**Comment by adminsend** [comment]
Agreed, i came to the same conclusion. generator and snmp-exporter must have the same version. IMHO this should be mentioned somewhere. ;)
