### ISSUE TITLE
make: *** [Makefile:131：mibs/apc-powernet-mib] 错误 2

### ISSUE THREAD

**Issue by chaiguifeng007** [prometheus/snmp_exporter#926]
### Host operating system: output of `uname -a`
Linux compile 6.4.4-1.el8.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 19 17:37:44 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

./snmp_exporter --version
snmp_exporter, version 0.23.0-rc.1 (branch: main, revision: 982a1b30c57babcde566a529a51be7756e6bb66b)
  build user:       root@compile
  build date:       20230721-10:04:11
  go version:       go1.19.10
  platform:         linux/amd64
  tags:             netgo

### What device/snmpwalk OID are you using?
ups
### If this is a new device, please link to the MIB(s).
https://drive.google.com/file/d/1cnNlq1E498EMCYk-gZdHjkR5GAYqGDt-/view?usp=drive_link
### What did you do that produced an error?
make generator mibs

make: “generator”已是最新。
>> Downloading apc-powernet-mib
curl: option --no-progress-meter: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
make: *** [Makefile:131：mibs/apc-powernet-mib] 错误 2

### What did you expect to see?
generate a new snmp.yml
### What did you see instead?
make: *** [Makefile:131：mibs/apc-powernet-mib] 错误 2

**Comment by H2CO3Bearcard** [comment]
delete the "--no-progress-meter" option in line 17 of the file snmp_exporter/generator/Makefile or replace it with-s

```
  1 # Copyright 2018 The Prometheus Authors
  2 # Licensed under the Apache License, Version 2.0 (the "License");
  3 # you may not use this file except in compliance with the License.
  4 # You may obtain a copy of the License at
  5 #
  6 # http://www.apache.org/licenses/LICENSE-2.0
  7 #
  8 # Unless required by applicable law or agreed to in writing, software
  9 # distributed under the License is distributed on an "AS IS" BASIS,
 10 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 11 # See the License for the specific language governing permissions and
 12 # limitations under the License.
 13 
 14 MIBDIR   := mibs
 15 MIB_PATH := 'mibs'
 16 
 17 CURL_OPTS ?= -L -s --retry 3 --retry-delay 3 --fail
 18 
 19 DOCKER_IMAGE_NAME ?= snmp-generator
 20 DOCKER_IMAGE_TAG  ?= $(subst /,-,$(shell git rev-parse --abbrev-ref HEAD))
 21 DOCKER_REPO       ?= prom

```

**Comment by chaiguifeng007** [comment]
> delete the "--no-progress-meter" option in line 17 of the file snmp_exporter/generator/Makefile or replace it with-s
> 
> ```
>   1 # Copyright 2018 The Prometheus Authors
>   2 # Licensed under the Apache License, Version 2.0 (the "License");
>   3 # you may not use this file except in compliance with the License.
>   4 # You may obtain a copy of the License at
>   5 #
>   6 # http://www.apache.org/licenses/LICENSE-2.0
>   7 #
>   8 # Unless required by applicable law or agreed to in writing, software
>   9 # distributed under the License is distributed on an "AS IS" BASIS,
>  10 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
>  11 # See the License for the specific language governing permissions and
>  12 # limitations under the License.
>  13 
>  14 MIBDIR   := mibs
>  15 MIB_PATH := 'mibs'
>  16 
>  17 CURL_OPTS ?= -L -s --retry 3 --retry-delay 3 --fail
>  18 
>  19 DOCKER_IMAGE_NAME ?= snmp-generator
>  20 DOCKER_IMAGE_TAG  ?= $(subst /,-,$(shell git rev-parse --abbrev-ref HEAD))
>  21 DOCKER_REPO       ?= prom
> ```

thanks a lot,it's worked; was this a bug?

**Comment by chaiguifeng007** [comment]
> > delete the "--no-progress-meter" option in line 17 of the file snmp_exporter/generator/Makefile or replace it with-s
> > ```
> >   1 # Copyright 2018 The Prometheus Authors
> >   2 # Licensed under the Apache License, Version 2.0 (the "License");
> >   3 # you may not use this file except in compliance with the License.
> >   4 # You may obtain a copy of the License at
> >   5 #
> >   6 # http://www.apache.org/licenses/LICENSE-2.0
> >   7 #
> >   8 # Unless required by applicable law or agreed to in writing, software
> >   9 # distributed under the License is distributed on an "AS IS" BASIS,
> >  10 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> >  11 # See the License for the specific language governing permissions and
> >  12 # limitations under the License.
> >  13 
> >  14 MIBDIR   := mibs
> >  15 MIB_PATH := 'mibs'
> >  16 
> >  17 CURL_OPTS ?= -L -s --retry 3 --retry-delay 3 --fail
> >  18 
> >  19 DOCKER_IMAGE_NAME ?= snmp-generator
> >  20 DOCKER_IMAGE_TAG  ?= $(subst /,-,$(shell git rev-parse --abbrev-ref HEAD))
> >  21 DOCKER_REPO       ?= prom
> > ```
> 
> thanks a lot,it's worked; was this a bug?

根据这个回答，我删除了第17行，可以正常使用了。非常感谢。
