### ISSUE TITLE
SNMPv3 Credentials

### ISSUE THREAD

**Issue by alexandrempm** [prometheus/snmp_exporter#932]
Is possible to get the credentials by secret envs?
We have the situation where the credentials is stored on AWS Secret Manager, where we pull using App External Secrets that will provide a secret inside of Kubernetes, so we would is useful to pass this variables on snmp.yml to avoid expose this credentials on git repository, this way we will use just reference of the credentials and not expose the credentials on repository.

  auth:
    security_level: authPriv
    username: snmp-exporter
    password: $password
    auth_protocol: SHA
    priv_protocol: AES
    priv_password: $priv_password

**Comment by SuperQ** [comment]
No, this is not supported. Best practice is to compose your config with the secrets already baked in (say in CI) and push the whole config to your secrets provider. The the file is mapped as a kubernetes `Secret` object. This is safer than ENV vars.

**Comment by rosariofe** [comment]
@SuperQ , I'm facing the same problem here on my side, for me it would be very interesting, precisely because of the point that Alexandre mentioned having this possibility of using environment variables as well, I believe that there are more users facing the same problem, , of not exposing secure data in the git repository, I think it is not complicated to implement and would be of great value for the snmp exporter

**Comment by rosariofe** [comment]
![image](https://github.com/prometheus/snmp_exporter/assets/45441463/bf05617e-384c-4c15-94ce-2c2d81a8add3)
Another problem I also encounter is that due to the size of the snmp.yaml being very large, I cannot use it in Secret Manager and I end up getting this error.

**Comment by zanswerdev** [comment]
Count me too, right now we can't use snmp_exporter in kubernetes, because of inability to provide priv/auth values, as env variables from Vault.

**Comment by SuperQ** [comment]
We're planning to support multiple snmp.yml config files so `auths` can be separated from `modules`, as well as `modules` from multiple files.

**Comment by SuperQ** [comment]
We now support multiple config files. This should make it easier to manage the credentials separately from the module configuration.
