### ISSUE TITLE
Docker Hub snmp-generator outdated

### ISSUE THREAD

**Issue by llamafilm** [prometheus/snmp_exporter#944]
The last several versions of snmp-generator are missing from Docker Hub, as compared with snmp-exporter.  They should probably be kept in parity. Based on the release dates, I would guess that snmp-generator:latest refers to v0.21.0.

https://hub.docker.com/r/prom/snmp-generator/tags
https://hub.docker.com/r/prom/snmp-exporter/tags

**Comment by irctrakz** [comment]
Especially amusing that with v0.23.0 the old snmp.yml is no longer correct per https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md

**Comment by SuperQ** [comment]
Ok, I fixed at least the `main` tag publishing.

**Comment by SuperQ** [comment]
I tracked down the last few bugs in the publishing steps. This will now correctly publish and tag releases and the `latest` tag.
