### ISSUE TITLE
snmp_packet stats are all zeros

### ISSUE THREAD

**Issue by candlerb** [prometheus/snmp_exporter#950]
### Host operating system: output of `uname -a`

```
Linux prometheus 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### snmp_exporter version: output of `snmp_exporter -version`

```
snmp_exporter, version 0.23.0 (branch: HEAD, revision: 20657d2f486a1ac237238827beed97fa67eb8611)
  build user:       root@f2310b8dd92c
  build date:       20230816-09:56:45
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo
```

### What did you do that produced an error?

Simple scrape (do it multiple times)

### What did you expect to see?

The histogram snmp_packet_duration_seconds_bucket to increment; the counter snmp_packets_total to increment

(Note: these appear to be new. I tried with 0.21 and these metrics don't exist at all)

### What did you see instead?

All metrics are zero, even after repeated scrapes:

```
# HELP snmp_packet_duration_seconds A histogram of latencies for SNMP packets.
# TYPE snmp_packet_duration_seconds histogram
snmp_packet_duration_seconds_bucket{le="0.0001"} 0
snmp_packet_duration_seconds_bucket{le="0.0002"} 0
snmp_packet_duration_seconds_bucket{le="0.0004"} 0
snmp_packet_duration_seconds_bucket{le="0.0008"} 0
snmp_packet_duration_seconds_bucket{le="0.0016"} 0
snmp_packet_duration_seconds_bucket{le="0.0032"} 0
snmp_packet_duration_seconds_bucket{le="0.0064"} 0
snmp_packet_duration_seconds_bucket{le="0.0128"} 0
snmp_packet_duration_seconds_bucket{le="0.0256"} 0
snmp_packet_duration_seconds_bucket{le="0.0512"} 0
snmp_packet_duration_seconds_bucket{le="0.1024"} 0
snmp_packet_duration_seconds_bucket{le="0.2048"} 0
snmp_packet_duration_seconds_bucket{le="0.4096"} 0
snmp_packet_duration_seconds_bucket{le="0.8192"} 0
snmp_packet_duration_seconds_bucket{le="1.6384"} 0
snmp_packet_duration_seconds_bucket{le="+Inf"} 0
snmp_packet_duration_seconds_sum 0
snmp_packet_duration_seconds_count 0
# HELP snmp_packet_retries_total Number of SNMP packet retries.
# TYPE snmp_packet_retries_total counter
snmp_packet_retries_total 0
# HELP snmp_packets_total Number of SNMP packet sent, including retries.
# TYPE snmp_packets_total counter
snmp_packets_total 0
```

**Comment by candlerb** [comment]
I think the problem is that for every request, a brand new Registry is created and a brand new Collector put in it:
https://github.com/prometheus/snmp_exporter/blob/v0.23.0/main.go#L126-L128

I'm not entirely sure why it's done that way, but I'm guessing it's because `collector.Collect()` can't take parameters.

But this means that c.metrics needs to be shared between `collector.Collector` instances. At simplest, it could be made global.

**Comment by candlerb** [comment]
Also, I notice that [main.go](snmp_collection_duration_seconds) declares some more metrics: `snmpDuration` and `snmpRequestErrors`

AFAICS, these are intended to create metrics `snmp_collection_duration_seconds` and `snmp_request_errors_total`, but these don't appear in the output either. I think this is because they are created in the global registry, not in the per-request registry.

**Comment by candlerb** [comment]
The fix to the latter problem is pretty straightforward:

```
diff --git a/main.go b/main.go
index c28316f..69a1ce4 100644
--- a/main.go
+++ b/main.go
@@ -27,7 +27,6 @@ import (
        "github.com/go-kit/log"
        "github.com/go-kit/log/level"
        "github.com/prometheus/client_golang/prometheus"
-       "github.com/prometheus/client_golang/prometheus/promauto"
        "github.com/prometheus/client_golang/prometheus/promhttp"
        "github.com/prometheus/common/promlog"
        "github.com/prometheus/common/promlog/flag"
@@ -50,14 +49,14 @@ var (
        toolkitFlags = webflag.AddFlags(kingpin.CommandLine, ":9116")

        // Metrics about the SNMP exporter itself.
-       snmpDuration = promauto.NewSummaryVec(
+       snmpDuration = prometheus.NewSummaryVec(
                prometheus.SummaryOpts{
                        Name: "snmp_collection_duration_seconds",
                        Help: "Duration of collections by the SNMP exporter",
                },
                []string{"auth", "module"},
        )
-       snmpRequestErrors = promauto.NewCounter(
+       snmpRequestErrors = prometheus.NewCounter(
                prometheus.CounterOpts{
                        Name: "snmp_request_errors_total",
                        Help: "Errors in requests to the SNMP exporter",
@@ -124,6 +123,8 @@ func handler(w http.ResponseWriter, r *http.Request, logger log.Logger) {

        start := time.Now()
        registry := prometheus.NewRegistry()
+       registry.MustRegister(snmpDuration)
+       registry.MustRegister(snmpRequestErrors)
        c := collector.New(r.Context(), target, auth, module, logger, registry)
        registry.MustRegister(c)
        // Delegate http serving to Prometheus client library, which will call collector.Collect.
```

However, it generates an explosion of NxM metrics, for every possible combination of auths and metrics. In my case it's only 5 auths and 22 modules, which gives me 220 metrics (one sum and one count), and I don't think that will scale.

I think the snmp_collection_duration_seconds metric overlaps with the new per-module stats that #945 is introducing, so could probably be dropped, although it does measure the total time of both scraping and emitting metrics.

The snmp_request_errors_total is a single value, and refers to errors in the incoming HTTP request (missing or unknown target, auth, or module).  It's reasonable to keep.

**Comment by SuperQ** [comment]
@candlerb Let's open separate new issues for those items.
