### ISSUE TITLE
make docker-generate failed 

### ISSUE THREAD

**Issue by matjasm** [prometheus/snmp_exporter#951]
It's about the error message:

ts=2023-08-16T22:05:35.116Z caller=main.go:130 level=error msg="Error generating config netsnmp" err="error parsing yml config: yaml: unmarshal errors:\n  line 2: field auths not found in type main.Config"
Makefile:81: recipe for target 'docker-generate' failed
make: *** [docker-generate] Error 1

the head of the generator.yml file is: 

---
auths:
  public_v1:
    version: 1
  public_v2:
    version: 2

    auth_name: 
      version:3 
      auth_protocol: SHA
      username: admin
      password: admin_pass
      security_level: noAuthNoPriv

I want to configure a snmp.yml file with authentication content (i want to use snmp version 3). in the new source code the auths are separated. when generating the above error message comes the field auths not found in type main.config

Host operation system:
Linux  4.15.0-1160.80.1.vz7.191.4 #1 SMP Thu Dec 15 20:31:06 MSK 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SuperQ** [comment]
Probably related to https://github.com/prometheus/snmp_exporter/issues/944

**Comment by SuperQ** [comment]
Published the matching snmp-generator Docker image.

**Comment by matjasm** [comment]
thank you, now it works .👍
