### ISSUE TITLE
Generator Makefile make mibs fails APC_URL 404 again

### ISSUE THREAD

**Issue by fue36** [prometheus/snmp_exporter#996]
APC_URL 404

In the generator Makefile, the APC_URL link to schneider-electric gives a 404.

https://download.schneider-electric.com/files?p_Doc_Ref=APC_POWERNETMIB_441_EN&p_enDocType=Firmware&p_File_Name=powernet441.mib

I couldn't locate another link for the mib from schneider electric.  However I found one closer to home. ;-)

https://github.com/prometheus/snmp_exporter/files/11223248/powernet446.mib.txt

```
$ git describe --tags
v0.24.1-5-g7fa8c4d
```

**Comment by SuperQ** [comment]
Yes, it's now 4.4.6 or 4.4.9.

**Comment by SuperQ** [comment]
Or, ugh, all the downloads are broken.

**Comment by SirOch27** [comment]
hello

is there a workaound until the problem is solved ?

**Comment by robbyleh** [comment]
Same issue here...
git describe --tags
v0.24.1-5-g7fa8c4d

make mibs
>> Downloading apc-powernet-mib
curl: (22) The requested URL returned error: 404
make: *** [Makefile:138: mibs/apc-powernet-mib] Error 22

**Comment by SuperQ** [comment]
There is no workaround, APC has broken all MIB downloads. The only thing we could remove support for APC.

**Comment by RichiH** [comment]
We could keep the old config around and splice it into the generated config.

Sent by mobile; please excuse my brevity.

**Comment by gebn** [comment]
Frustratingly, it looks like only the newest download works: https://github.com/prometheus/snmp_exporter/pull/1003
