### ISSUE TITLE
Missing multiple versions from registry

### ISSUE THREAD

**Issue by bck01215** [prometheus/snmp_exporter#997]
### snmp_exporter version: output of `snmp_exporter -version`
0.21.0
0.22.0

The link https://quay.io/repository/prometheus/snmp-generator?tab=tags shows that multiple version are missing. We're using `use_unconnected_udp_socket` which isn't supported in 0.20.0, but we haven't migrated to the new auth configs yet. Please push images for the older tags so we can continue work while migrating.

**Comment by SuperQ** [comment]
Ok, I published v0.21.0 and v0.22.0 generators. Let me know if those work now.

**Comment by bck01215** [comment]
Those work. TY.
